🧴Mentions hygiene
status-im/status-react pull request #11454
Opened 2020-11-19 16:22 UTC by shivekkhurana

# Summary
- Remove redundant call to `users-fn` and pass `mentionable-users` directly
- Rename `get-suggestions` to `get-user-suggestions`, will be helpful when the `get-channel-suggestions` function is implemented
- Extract inline function props to text input as a namespaced function. Now they won't get redefined at every key-press and are slightly easier to read and reason for

These changes were made while working on # autocomplete feature for chat text-input (which is not completed yet).

### Testing notes
- Check if autocomplete mention works fine

#### Platforms
- Android
- iOS

#### Areas that maybe impacted
- All types of chat

##### Non-functional
- CPU performance / speed of the app

status: ready

2020-11-19 16:31 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | 87ca48c5 | [#1](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-11454/1/) | 2020-11-19 16:31:52 | ~8 min | `android` | [:page_facing_up:`log`](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-11454/1/consoleText) |

2020-11-20 09:19 UTC, rasom commented on src/status_im/ui/screens/chat/components/input.cljs
> +    ;; `on-change`, that's why mention/channel suggestions are calculated
we can just say "suggestions" instead of "mention/channel suggestions" here and in the rest of comments

2020-11-20 09:21 UTC, rasom requested changes
tests are broken

2020-11-20 11:39 UTC, rasom approved these changes

2020-11-20 13:19 UTC, status-im-auto commented
## 96% of end-end tests have passed
```
Total executed tests: 90
Failed tests: 4
Passed tests: 86
```
```
IDs of failed tests: 5403, 6316, 6226, 5332 
```
<h3>Failed tests (4)</h3><details><summary>Click to expand</summary><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1875406">test_start_chat_with_ens_mention_in_one_to_one</a>, id: 5403 </b></td></tr><tr><td><p><blockquote><div>Device 1: Wait for ConnectionStatusText</div><div>Device 1: Wait for ConnectionStatusText</div></blockquote></p><code> 'NoneType' object has no attribute 'click'; also Unexpected Alert is shown: 'function () { [bytecode] } is not ISeqable'</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/2c5c9617b45f4589aecd80d9496209ce?auth=2a7784579fcecb3b210725df3c713fe8">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/2c5c9617b45f4589aecd80d9496209ce/0025screenshot.png?auth=2a7784579fcecb3b210725df3c713fe8">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1875427">test_send_audio_message_with_push_notification_check</a>, id: 6316 </b></td></tr><tr><td><p><blockquote><div>Device 2: Tap on PlayPauseAudioMessageButton</div><div>Device 2: AudioMessageInChatTimer is 00:04</div></blockquote></p><code> Listened 5 seconds but timer shows different listened time in audio message</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/5bff2696d51340d8aee9744afd85bcdd?auth=d9ffe37b42b7cf7104d77ed48bdc96a1">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/5bff2696d51340d8aee9744afd85bcdd/0022screenshot.png?auth=d9ffe37b42b7cf7104d77ed48bdc96a1">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/2aa8e7b8647d4b0abfe9ebcb53194e9c?auth=4159d378d2be2254610cf4bb88154c26">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/2aa8e7b8647d4b0abfe9ebcb53194e9c/0018screenshot.png?auth=4159d378d2be2254610cf4bb88154c26">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1875415">test_ens_mentions_and_nickname_in_public_and_1_1_chats</a>, id: 6226 </b></td></tr><tr><td><p><blockquote><div>Device 2: Tap on SendMessageButton</div><div>Device 2: Looking for full text: '@statuse2e'</div></blockquote></p><code> Device 2: 'BaseButton' is not found on the screen; also Unexpected Alert is shown: 'function () { [bytecode] } is not ISeqable'</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/8b883a52b5764384b91239d8b319f1c4?auth=4edc5d80833b6a614916ddc2fdefc117">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/8b883a52b5764384b91239d8b319f1c4/0046screenshot.png?auth=4edc5d80833b6a614916ddc2fdefc117">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/9f12c7257e524efc8b306b207de4d753?auth=9bc8b36294983d5a19b4e6f3329aea4f">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/9f12c7257e524efc8b306b207de4d753/0018screenshot.png?auth=9bc8b36294983d5a19b4e6f3329aea4f">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1875396">test_add_and_remove_mention_contact_with_nickname_from_public_chat</a>, id: 5332 </b></td></tr><tr><td><code> Sauce could not start your job. For more information on what happened, please visit https://app.saucelabs.com/tests/b2d0624df59542a49326cc40b96c2d17</code><br/><br/></td></tr></tbody></table></details><h3>Passed tests (86)</h3><details><summary>Click to expand</summary><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1875461">test_mobile_data_usage_popup_stop_syncing</a>, id: 6228 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/acaa3480cd1d4687a006a8c968eb0b69?auth=3fde45e257fc01be54a2e5906c644b85">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1875393">test_back_forward_buttons_browsing_website</a>, id: 5321 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/30af11a66c8c4133a2802640c58d74d0?auth=fa521cac205ef218a8d33581f81fcf0f">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1875433">test_wallet_set_up</a>, id: 5335 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/26a1e34b08814c1c8d326e805ac6ffdc?auth=058027712ebb99fb265e32501e0d6406">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1875448">test_transaction_wrong_password_wallet</a>, id: 5408 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/20e30ebf446e491c9dcfcc8aeb50400d?auth=8d37b80f03b516080705a9a7729319ce">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1875465">test_add_and_delete_watch_only_account_to_multiaccount_instance</a>, id: 6244 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/e68c21efb0264c67a6902bd73720e2c6?auth=ac2ef4c3a4d10924b278d64a36bfad5a">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>6. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1875411">test_install_pack_and_send_sticker</a>, id: 5782 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/8299a2389e12445dab088e797915fd5a?auth=dab8ee9d561cb0922e568e7dd34cb5ef">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/6f575fa84e1b44edb5433ff13de3e61d?auth=a1dc61dfc3ecc1807a45747134732e0a">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>7. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1875430">test_user_can_switch_network</a>, id: 5299 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/d17294f4fde6416089f162732491d44f?auth=090961410a6a8afee299c21b71474cce">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>8. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1875539">test_keycard_send_eth_to_ens</a>, id: 6295 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/45893eb1b2ac45c58b7e609cf9ebbeb7?auth=d3d801a0c79ffcf0f0fe4cdc6fda1493">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>9. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1875468">test_decline_transactions_in_1_1_chat_push_notification_changing_state</a>, id: 6265 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/499e70c0f6e0499585413d82a252786e?auth=614f6354cb477e1cfdc7926fcb2e8dca">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/b1b47fc8eb6f4e9b9ddda67fa35173c0?auth=c7e32211097cbd078ee9212105729b11">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>10. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1875416">test_send_eth_in_1_1_chat</a>, id: 6253 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Devi [...]

2020-11-23 09:32 UTC, shivekkhurana commented
Tests related to mentions are failing although the feature works fine when I test manually. Checking the test source to see what causes the change. It's also possible that I missed refactoring some components.

2020-11-23 10:56 UTC, status-im-auto commented
## 100% of end-end tests have passed
```
Total executed tests: 91
Failed tests: 0
Passed tests: 91
```
<h3>Passed tests (91)</h3><details><summary>Click to expand</summary><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1886157">test_image_in_one_to_one_send_save_reply_timeline</a>, id: 6305 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/79ad2a1a8dc347d1b0ba96117b02c4f9?auth=6f15e48071f7235ffeafca9c75b71e6c">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/133e3e265e7e4676b4565381c7ddef86?auth=1ae40aa714184d0b917626425e61a8ce">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1886146">test_add_account_to_multiaccount_instance_generate_new</a>, id: 6224 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/8107b0b0efc443718b7a92415a798b14?auth=abb62d115ed77f43f0b2269d9fc98349">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1886116">test_send_eth_from_wallet_to_address</a>, id: 5308 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/5a5a2fb657c14ff69b153b9a36f69c8d?auth=c0892375fa9dc6d8ee89f0883b734f72">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1886183">test_onboarding_screen_when_requesting_tokens_for_recovered_account</a>, id: 5677 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/2b0d5635dd434b15a7510dcbba7b86b6?auth=1e07eb318ed509ecc1c4de7a4761d1bb">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1886155">test_keycard_can_see_all_transactions_in_history</a>, id: 6291 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/23633e02a84f4cd9a6316a787cc999cd?auth=7598f249de98c4d0e4240f2dee03f2a1">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>6. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1886115">test_text_message_1_1_chat</a>, id: 5305 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/9763b7773fe94e019743d26cd074c0c4?auth=52f959b00523d3632a87a456fd738124">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/102d31b728e14f7986b23fcc61dc0495?auth=dc491ade4adfedd536d83830fee60a2c">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>7. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1886201">test_push_notification_1_1_chat</a>, id: 6283 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/591085b5a3394c48aac41ae8a87bc1bf?auth=81bd138800227c57e3df96ca6a9c1e1d">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/8319c71b439b4d73994d5d0a8de12b25?auth=a099a1edb037db02789f11eebdcd498a">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>8. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1886174">test_delete_chats_via_delete_button</a>, id: 5387 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/f78a674349494fe694ac6a9a03626c68?auth=4ca298731d78d032c6130de6e715e6c8">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>9. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1886197">test_add_and_delete_watch_only_account_to_multiaccount_instance</a>, id: 6244 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/ff4427ebd5894f3a88ec1e0955f784ae?auth=08bc42a88b425c3b226666ff9f68faf2">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>10. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1886175">test_long_press_delete_clear_all_dapps</a>, id: 5390 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/38cd491db0c24e58b4c6d02b0366505c?auth=16e6d11026df41ff3d17f413db754a5f">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>11. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1886178">test_open_public_chat_using_deep_link</a>, id: 5396 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/05964686af1a4f00adbb9b3dfd4a0ea7?auth=236cf2fff1179698977710d4b142ea15">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>12. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1886161">test_offline_add_new_group_chat_member</a>, id: 3998 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/55052ebd0945460cbf7c91962041371d?auth=ca29747d4327866b0382a12a06a841c1">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/a310e017fdd74182986c75284c995f40?auth=edce56b23ef5b92a934790934bcf1cc1">Steps, video, logs</a></li></ul></p><p>Device 3:<ul><li><a href="https://saucelabs.com/jobs/c4b18617e946481fa3e3f2031c2849ae?auth=d6b9e14ffbe992798fd0054772bbd1a1">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>13. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1886169">test_copy_contact_code_and_wallet_address</a>, id: 5375 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/ff3189bd59704c95a090122bbc323990?auth=9d63416030a35f01b932e8ed32f6ec27">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>14. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1886151">test_add_account_to_multiaccount_instance_private_key</a>, id: 6272 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/0491e74c42a4449ca912ef402889e3e6?auth=a227a1e194343d367607dcb19d728121">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>15. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1886186">test_mobile_data_usage_popup_continue_syncing</a>, id: 5741 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/063e835aedab47f5a18b018d1292376a?auth=25f3f433766bc36a1a73f192f4f0b81e">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>16. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1886181">test_insufficient_funds_wallet_positive_balance</a>, id: 5412 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/b0bbf58a5e8f4f87bc8a4347d7a50f7d?auth=ac131c65416f2070e23f03bd34bfa77c">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>17. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1886160">test_create_new_group_chat</a>, id: 3994 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/b0ea1139f5194b33aecdf6a3a0bdbe11?auth=6758680b8e7bc709ba5d330f0c4ce0b0">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/03e78a024a454f0b824fd2aa9a7e9480?auth=cf669705ffe6111ea7b0b43224a02048">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>18. <a href="https://ethstatus.testrail.net/index.php?/tests/view/1886129">test_messaging_in_different_networks</a>, id: 5338 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href [...]

2020-11-23 11:03 UTC, merged