Update interceptors.cljs
status-im/status-react pull request #11921
Opened 2021-03-24 13:53 UTC by Samyoul

Quick patch to remove log macro call in an inaccessible place

Currently getting the following warning error.

```shell
------ WARNING #1 - :undeclared-var --------------------------------------------
 File: /Users/samuel/Documents/dev/status-im/status-react/src/status_im/anon_metrics/interceptors.cljs:17:33
--------------------------------------------------------------------------------
  14 |                                :value transformed-payload
  15 |                                :app_version build/version
  16 |                                :os platform/os}]]
  17 |                     :on-failure log/error})))
---------------------------------------^----------------------------------------
 Can't take value of macro taoensso.timbre/error
--------------------------------------------------------------------------------
  18 | 
  19 | (defn catch-events-before [context]
  20 |   (log/info "catch-events/interceptor fired")
  21 |   (transform-and-log context)
--------------------------------------------------------------------------------
```

2021-03-24 14:02 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 4c7f687e | [#1](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-11921/1/) | 2021-03-24 14:02:46 | ~9 min | `android` | [:package:`apk`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-210324-135333-4c7f68-pr-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-210324-135333-4c7f68-pr-universal.apk)|

2021-03-25 07:43 UTC, shivekkhurana approved these changes
<img src="https://user-images.githubusercontent.com/1925158/112436595-e3ee6280-8d6b-11eb-8c24-d060dd91618f.png" width="50" />
Tested

2021-03-25 07:48 UTC, shivekkhurana commented
@Samyoul The [og pr was reverted](https://github.com/status-im/status-react/commit/a8ae9336042acdbd9a0d1c8c67cc8dd0147da552). Can you please open that PR again with this fix?

2021-03-25 08:49 UTC, flexsurfer requested changes
could you please rebase and run tests, because tests in my PR failed with this change

2021-03-25 13:10 UTC, Samyoul commented
Hey, yes I'll close this PR and I'll open a re-revert PR including these changes

2021-03-25 13:10 UTC, closed without merging