Back / dismiss gestures on Android
status-im/status-react pull request #11970
Opened 2021-04-08 18:21 UTC by briansztamfater

fixes #11913 

### Summary

We need to enable navigation gestures on Android. In this PR i'm doing a refactor on the routing core functions where `gestureEnabled` is set to true by default on all screens on Android, which is enabling swipe gestures for navigating back and therefore that comes with animated transitions. Also we are applying different transition animations for modal presentations (default is an horizontal transition from left to right, and for modal presentation is a vertical transition from bottom to top). I set some arbitrary `gestureResponseDistance` values for enabling the swipe gesture, but can be adjusted. Finally, refactored `:presentation-ios` to `:presentation-modal` because we are enabling modal presentation for both OS.

![navigation-gestures-android](https://user-images.githubusercontent.com/18485527/114076288-e1682e80-987c-11eb-9f75-55ac0e343eff.gif)

### Testing notes

Be sure that no screen was broken.

#### Platforms

- Android
- iOS (changes impact on Android but doing some smoke testing on iOS is recommended)

#### Areas that maybe impacted
General navigation

##### Non-functional

- Navigation transitions and gestures

### Steps to test

- Open Status
- Navigate through screens
- Swipe horizontally to go back, or swipe vertically to dismiss a modal

status: ready

2021-04-08 18:32 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | e8cbfb14 | [#1](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-11970/1/) | 2021-04-08 18:32:18 | ~10 min | `android-e2e` | [:package:`apk`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-210408-182121-e8cbfb-pr-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-210408-182121-e8cbfb-pr-x86.apk)|

2021-04-09 05:32 UTC, flexsurfer approved these changes

2021-04-09 06:24 UTC, status-im-auto commented
## 95% of end-end tests have passed
```
Total executed tests: 80
Failed tests: 4
Passed tests: 76
```
```
IDs of failed tests: 6305,6210,5309,6249 
```
<h3>Failed tests (4)</h3><details><summary>Click to expand</summary><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2201214">test_image_in_one_to_one_send_save_reply_timeline</a>, id: 6305 </b></td></tr><tr><td><p><blockquote><div>Device 1: *Tap on found Button* </div><div>Device 1: *Find Button by accessibility id:* `open-gallery` </div></blockquote></p><code> Device 1: Button by accessibility id: `open-gallery` is not found on the screen</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/52bb797a7a35490086c4fb245c48ae23?auth=2e7f548f269c56cd172208a109fdda3e">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/52bb797a7a35490086c4fb245c48ae23/0032screenshot.png?auth=2e7f548f269c56cd172208a109fdda3e">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/2d76efbbf8e947f69213da74a1271cff?auth=5fcd4643b7b59279619cc437a31664bf">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/2d76efbbf8e947f69213da74a1271cff/0013screenshot.png?auth=5fcd4643b7b59279619cc437a31664bf">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2201192">test_open_blocked_secure_not_secure_inlalid_offline_urls</a>, id: 6210 </b></td></tr><tr><td><p><blockquote><div>Device 1: *Tap on found Button* </div><div>Device 1: *Find Button by xpath:* `//*[@text="Continue anyway"]` </div></blockquote></p><code> Device 1: Button by xpath: `//*[@text="Continue anyway"]` is not found on the screen</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/87c031e6501a4b308afff51ea7a5759d?auth=e6846a74b551a293f8850ee23f407e82">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/87c031e6501a4b308afff51ea7a5759d/0023screenshot.png?auth=e6846a74b551a293f8850ee23f407e82">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2201145">test_request_stt_from_daap</a>, id: 5309 </b></td></tr><tr><td><p><blockquote><div>Device 1: *Find WalletButton by accessibility id:* `wallet-tab-button` </div><div>Device 1: *Waiting 400s for STT updated balance* </div></blockquote></p><code> Device 1: Balance STT 4962000.0 is not changed during 400 seconds!</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/396e7d9a42b54f9196ff31502d3b75f9?auth=1a1e54a0d310ff01070023806190d61c">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/396e7d9a42b54f9196ff31502d3b75f9/0113screenshot.png?auth=1a1e54a0d310ff01070023806190d61c">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2201199">test_keycard_request_stt_from_daap</a>, id: 6249 </b></td></tr><tr><td><p><blockquote><div>Device 1: *Find WalletButton by accessibility id:* `wallet-tab-button` </div><div>Device 1: *Waiting 400s for STT updated balance* </div></blockquote></p><code> Device 1: Balance STT 4963000.0 is not changed during 400 seconds!</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/21cfc53ae0c84f3dbaf760d1c41e054f?auth=38b6cf85ed83e8daa6657536de103924">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/21cfc53ae0c84f3dbaf760d1c41e054f/0132screenshot.png?auth=38b6cf85ed83e8daa6657536de103924">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table></details><h3>Passed tests (76)</h3><details><summary>Click to expand</summary><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2201193">test_add_account_to_multiaccount_instance_generate_new</a>, id: 6224 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/2109d3930c5548f39201916721b3236b?auth=e8f2bbb24f1868a01a9071ca5a0f9bd6">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2201144">test_send_eth_from_wallet_to_address</a>, id: 5308 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/39b89c7cf7ce4e0bb42e3960c63b509a?auth=4d891153b7f053f803cd1be9f7712b0d">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2201180">test_onboarding_screen_when_requesting_tokens_for_recovered_account</a>, id: 5677 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/2d43b0f46cd94ea1be3f11ec6f23ff15?auth=048e02ed19edb0e9c3969c91667268d6">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2201211">test_keycard_can_see_all_transactions_in_history</a>, id: 6291 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/fa0e60f4c6b34b3eba6dbebfaa293b59?auth=914a243f97cdec6c8e0d9dd9120da390">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2201206">test_push_notification_1_1_chat</a>, id: 6283 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/9499e1e753a24624b6b762bdabbde2b4?auth=ff8233d4c74c3e841889c5afa479bda9">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/fcacf296a9da4d5092c0a77c3b816775?auth=3b8ccccb1439d4c52296471192c33556">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>6. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2201198">test_add_and_delete_watch_only_account_to_multiaccount_instance</a>, id: 6244 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/40a9bb6ba24140989678f6c7c9a12d8a?auth=9474aacf5efb5631f514e3de13a33304">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>7. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2201172">test_open_public_chat_using_deep_link</a>, id: 5396 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/2f6188c0b7ee4f568b8ce17f02fa8710?auth=0fbabaf28ec7f78dfc042034b370c0aa">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>8. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2201142">test_offline_add_new_group_chat_member</a>, id: 3998 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/515f39c3d33a4c55b55983afbd083b0c?auth=fba27dea738941877d97ad3f66af593b">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/0dbe7a47b9ad4625841dca3ea947cedd?auth=b4e94e43ac66a5f08ed88d6020851ddf">Steps, video, logs</a></li></ul></p><p>Device 3:<ul><li><a href="https://saucelabs.com/jobs/c891efe57993462fb70328cf43fa5c72?auth=76943799a5ee092ab924203ba2d33b81">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>9. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2201149">test_send_non_english_message_to_newly_added_contact_on_different_networks</a>, id: 5315 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/879ce165aef54e [...]

2021-04-09 06:48 UTC, shivekkhurana requested changes
This looks great 👏🏼

2021-04-09 06:48 UTC, shivekkhurana commented on src/status_im/ui/screens/routing/core.cljs
> +  (if (and platform/ios? (= transition :presentation-modal))
[`cond`](https://clojuredocs.org/clojure.core/cond) is more appropriate than `if`.

2021-04-10 07:49 UTC, errorists commented
Hey a question, is this push-pull navigation segue how Android supposed to work like these days? Because to me it easily takes the prize for the most non-Android shit I've seen yet 😅

2021-04-10 14:10 UTC, briansztamfater commented
> Hey a question, is this push-pull navigation segue how Android supposed to work like these days? Because to me it easily takes the prize for the most non-Android shit I've seen yet 😅

True, it is replicating iOS-style transitions, which may not be what an Android user is expecting. This is the Android Oreo-style transition alternative we have, what do you think?

![android-oreo-transition](https://user-images.githubusercontent.com/18485527/114272590-290dc800-99ed-11eb-86cf-7a8dc45e8dd6.gif)

2021-04-10 15:36 UTC, errorists commented
Why do we want our own transition in place if the [Android 10 system back gesture utilises a floating arrow indicator that maps to your drag gesture](https://cdn-vox--cdn-com.cdn.ampproject.org/i/s/cdn.vox-cdn.com/thumbor/rf9q5lnrGcvFtJ-gasqVAfegw3Q=/1400x0/filters:no_upscale()/cdn.vox-cdn.com/uploads/chorus_asset/file/16217483/nav.0.gif). Once registered we fire up a regular back event like we would with the hardware button. No need to have our transitions, let's use the one found on Android.

2021-04-10 16:17 UTC, briansztamfater commented
Yeah, I'm not an Android user so I'm not aware of the different transitions of different Android versions, but tried enabling the gestures from the OS settings and that already works in `develop` branch version, at least on my emulator. Example below 👇 

![android-back-default](https://user-images.githubusercontent.com/18485527/114276208-02a35900-99fc-11eb-93d2-8554342dd858.gif)

Another option is to keep the default transition but adding the gesture. Example below 👇 

![android-default-gesture](https://user-images.githubusercontent.com/18485527/114276509-4d71a080-99fd-11eb-8ccb-74ec65b9f5f2.gif)
 
So to sum up we could:

1. Keep the `develop` version (maybe the original feature request is not needed)
2. Keep the default transition _but_ add swipe / dragging gesture to go back

Any thoughts?

2021-04-10 17:23 UTC, errorists commented
Let's keep the develop 👍 It's a system-wide behavior that we don't want to customize. Likewise, I'm not an Android person, just know that porting iOS UI is the easiest way to piss those people off, when in doubt let's try not to :)

2021-04-11 12:22 UTC, shivekkhurana commented
Swipe from left to go back is a fairly common Android technique (iOs too). I think native routing libraries implement it by default. It's something that is enabled or disabled at system level in Android.

2021-04-12 08:46 UTC, status-im-auto commented
## 75% of end-end tests have passed
```
Total executed tests: 4
Failed tests: 1
Passed tests: 3
```
```
IDs of failed tests: 6305 
```
<h3>Failed tests (1)</h3><details><summary>Click to expand</summary><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2204459">test_image_in_one_to_one_send_save_reply_timeline</a>, id: 6305 </b></td></tr><tr><td><p><blockquote><div>Device 1: *Tap on found Button* </div><div>Device 1: *Find Button by accessibility id:* `open-gallery` </div></blockquote></p><code> Device 1: Button by accessibility id: `open-gallery` is not found on the screen</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/bd966a92220f4c1bb37b3de7c872dabb?auth=00181f0c52e60dc912083e9ef2000b89">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/bd966a92220f4c1bb37b3de7c872dabb/0032screenshot.png?auth=00181f0c52e60dc912083e9ef2000b89">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/1a5cdc5727c5488cb50ad708a9773dff?auth=67c3d82e9eeb6f43525a28b26277bd45">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/1a5cdc5727c5488cb50ad708a9773dff/0013screenshot.png?auth=67c3d82e9eeb6f43525a28b26277bd45">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table></details><h3>Passed tests (3)</h3><details><summary>Click to expand</summary><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2204456">test_request_stt_from_daap</a>, id: 5309 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/90c74c04ff734d76ad6a3450225f239a?auth=4c78e7d274dc355e8fd5caaf499b20d6">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2204458">test_keycard_request_stt_from_daap</a>, id: 6249 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/535af037e7ba44799a3ff6f6f1792164?auth=fdf2b6341bf19266db2596600858db86">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2204457">test_open_blocked_secure_not_secure_inlalid_offline_urls</a>, id: 6210 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/7957039601f3490d93b90f87ce3774ef?auth=881e533da0b151c999d1ccf11e466799">Steps, video, logs</a></li></ul></p></ul></p></td></tr></tbody></table></details>

2021-04-12 09:14 UTC, churik commented
So let's summarize.
I see several issues during onboarding when using swipe-to-back gesture on Android (null-pointer exception, possibility to create account without setting a password).
Original feature request came from user error-report https://github.com/status-im/status-react/issues/11913 and was reported by @qoqobolo 

In several chat apps (Telegram, Viber) swipe-to-back gesture works as back button, in other apps (Play Store, FB messenger) - it doesn't work.

As PR definitely contains some issues and as it comes from discussion between @errorists and @briansztamfater best solution IMO is to close PR and original feature request.

Objections?

2021-04-12 09:19 UTC, errorists commented
to add, my only objection was to add the iOS native transitions that were introduced first in the PR. As long as we implement the swipe back gestures using native Android behaviour, it's perfectly fine and a welcome improvement

2021-04-12 09:51 UTC, churik commented
@errorists tell me what do you think.
AFAIK there are 2 types of navigation on Android - "Full screen gestures" or "Buttons".

### so on current `develop`:
1) if system navigation is set to "Full screen gestures" (screenshot is attached) swipe-back is working inside app (when you logged in) but not working during onboarding on screens that instead of  <- contain "Cancel" 
<img width="190" alt="Monosnap 2021-04-12 11-49-14" src="https://user-images.githubusercontent.com/4557972/114375627-2645db00-9b85-11eb-8830-2ec76a81a6b4.png"><img width="183" alt="Monosnap 2021-04-12 11-38-22" src="https://user-images.githubusercontent.com/4557972/114374195-aa975e80-9b83-11eb-976b-0606c89481b9.png">

2)  if system navigation is set to "Buttons" swipe-back is not working inside app (I believe it is kind of additional feature and isn't related to native Android behavior and this is origin al issue https://github.com/status-im/status-react/issues/11913) 
As mentioned  in https://github.com/status-im/status-react/pull/11970#issuecomment-817637914 it is implemented selectively in some applications)

### on current PR build:
3) if system navigation is set to "Buttons" swipe-back gesture works on any screens and can cause new issues.

So we have several options here:
a) close this PR as it seems additional feature and it is not really required
b) fix all issues related to new navigation behavior (will report them if needed), as it changed a lot.

As for me better option is (a)

2021-04-12 13:03 UTC, briansztamfater commented
I think we can close this one. Feature request is not really required so spending more dev time in something that is not needed is not what we want. Thanks for your input guys!

2021-04-12 13:03 UTC, closed without merging