Community channel editing
status-im/status-react pull request #12173
Opened 2021-05-31 12:33 UTC by vkjr

fixes #12065

### Summary

- channel details page added
- channel description can be added on creation 
- channel name and description can be edited

[Related status-go PR](https://github.com/status-im/status-go/pull/2236)

#### Platforms
- Android
- iOS

##### Functional

Community channels editing

### Steps to test
- Open Status
- Create a community or open one where you are an admin
- Create a new channel and make sure you can enter description
- Open channel profile, select edit button (top right) and change name/description
- Make sure changes are seen in a channels list
- 
status: ready

2021-05-31 12:33 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | 1c88abc9 | [#1](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-12173/1/) | 2021-05-31 12:33:46 | ~19 sec | `ios` | [:page_facing_up:`log`](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-12173/1/consoleText) |

2021-06-01 10:16 UTC, status-im-auto commented
## 93% of end-end tests have passed
```
Total executed tests: 70
Failed tests: 5
Passed tests: 65
```
```
IDs of failed tests: 5350,6253,6279,6263,6293 
```
<h3>Failed tests (5)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/end-to-end-tests/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&APK_NAME=12173.apk&PR_ID=12173&TR_CASE_IDS=5350,6253,6279,6263,6293">Rerun tests</a></li><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2245171">test_send_token_with_7_decimals</a>, id: 5350 </b></td></tr><tr><td><p><blockquote><div>Device 1: *Find Button by xpath:* `//*[@text='OK' or @text='Ok']` </div><div>Device 1: *Tap on found Button* </div></blockquote></p><code> Expecting value: line 1 column 1 (char 0)</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/daa52bc031134a7f97ed5473a34dc9cd?auth=19bae535c5abf9753d8312301dc898a8">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/daa52bc031134a7f97ed5473a34dc9cd/0035screenshot.png?auth=19bae535c5abf9753d8312301dc898a8">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2245205">test_send_eth_in_1_1_chat_transaction_push</a>, id: 6253 </b></td></tr><tr><td><p><blockquote><div>Transaction #5, amount is 0.0031164515</div><div>{'blockNumber': '10347076', 'timeStamp': '1622479626', 'hash': '0xe4de46095a143f0a1c7d3a39fbdae902ae37be2999fb909cea3a234fb30348c8', 'nonce': '3246', 'blockHash': '0xf401a3626d20f40b4db927b60e7262f7c311cb3b4e2784fbef68b09cdedfb232', 'transactionIndex': '1', 'from': '0xefca4fd47b98b9f01c4eef4827e576a01459728a', 'to': '0xe9b267c196a5ca2d0e35faed75a415065babe68e', 'value': '3116451500000000', 'gas': '21000', 'gasPrice': '31000000000', 'isError': '0', 'txreceipt_status': '1', 'input': '0x', 'contractAddress': '', 'cumulativeGasUsed': '66959', 'gasUsed': '21000', 'confirmations': '4516'}</div></blockquote></p><code> Transaction with amount 0.00193835 is not found in list of ETH transactions, address is efca4fd47b98b9f01c4eef4827e576a01459728a during 600s</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/639e2a2d5cc84ce58c3a7345edbf9678?auth=0c7494b8c04b6c5338ef442ed22199c5">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/639e2a2d5cc84ce58c3a7345edbf9678/0042screenshot.png?auth=0c7494b8c04b6c5338ef442ed22199c5">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/bada3a04dc5f48afb96ac352a7c09b4f?auth=c62a2f671fe1e40c9efabf3bf1d9e36c">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/bada3a04dc5f48afb96ac352a7c09b4f/0024screenshot.png?auth=c62a2f671fe1e40c9efabf3bf1d9e36c">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2245209">test_send_eth_to_ens_in_chat</a>, id: 6279 </b></td></tr><tr><td><p><blockquote><div>Transaction #5, amount is 0.00165056</div><div>{'blockNumber': '10350895', 'timeStamp': '1622530291', 'hash': '0xa89d4fe1acd197e0aed0b9114f61250c06b32ebab995bb179e8e2861779ee7e3', 'nonce': '5601', 'blockHash': '0x4baa0f2544336e50e054f0e15cddaf4f123ac6679525227568c6d94bd60db7da', 'transactionIndex': '0', 'from': '0xf7cb60839c0de25e37be0391c33bb34a8f0f8414', 'to': '0x58d8c3d70ce4fa4b9fb10a665c8712238746f2ff', 'value': '1650560000000000', 'gas': '21000', 'gasPrice': '31000000000', 'isError': '0', 'txreceipt_status': '1', 'input': '0x', 'contractAddress': '', 'cumulativeGasUsed': '21000', 'gasUsed': '21000', 'confirmations': '695'}</div></blockquote></p><code> Transaction with amount 0.0019392 is not found in list of ETH transactions, address is f7cb60839c0de25e37be0391c33bb34a8f0f8414 during 600s</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/0e07c404451a4062b5faef54ad339d67?auth=3f3a48b1ee0ab4bfac72afa23e0a038e">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/0e07c404451a4062b5faef54ad339d67/0031screenshot.png?auth=3f3a48b1ee0ab4bfac72afa23e0a038e">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2245206">test_request_and_receive_stt_in_1_1_chat_offline</a>, id: 6263 </b></td></tr><tr><td><p><blockquote><div>Transaction #5, amount is 0.0031133817</div><div>{'blockNumber': '10346139', 'timeStamp': '1622468665', 'hash': '0xc2e643c2f9c82040475f7bc2ca2ba040fb7f9a3d8d73616f2c2df7ceb681ddfe', 'nonce': '5822', 'blockHash': '0x356bb292b7c7c8be41ce4e087db5424be72b56156f12fc62c6612f17e7d7602e', 'from': '0x549b9bcd069d720390a6819ff8b3d9dd252fa3be', 'contractAddress': '0xc55cf4b03948d7ebc8b9e8bad92643703811d162', 'to': '0x25d47cade2013a43eb07011bb88b8030118422d5', 'value': '3113381700000000', 'tokenName': 'Status Test Token', 'tokenSymbol': 'STT', 'tokenDecimal': '18', 'transactionIndex': '0', 'gas': '141028', 'gasPrice': '31000000000', 'gasUsed': '117524', 'cumulativeGasUsed': '117524', 'input': 'deprecated', 'confirmations': '5437'}</div></blockquote></p><code> Transaction with amount 0.0019286 is not found in list of token transactions, address is 549b9bcd069d720390a6819ff8b3d9dd252fa3be during 600s</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/eacda09afacf42aebbba3c201b8ac9b4?auth=b5fb30a0fd199339e5afb788db1d4888">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/eacda09afacf42aebbba3c201b8ac9b4/0029screenshot.png?auth=b5fb30a0fd199339e5afb788db1d4888">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/a5d41f32fce945e5b0ef87954a818282?auth=106bb08be298f28f5208e3029f8be833">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/a5d41f32fce945e5b0ef87954a818282/0044screenshot.png?auth=106bb08be298f28f5208e3029f8be833">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2245214">test_keycard_send_eth_in_1_1_chat</a>, id: 6293 </b></td></tr><tr><td><p><blockquote><div>Transaction #5, amount is 0.00165056</div><div>{'blockNumber': '10350895', 'timeStamp': '1622530291', 'hash': '0xa89d4fe1acd197e0aed0b9114f61250c06b32ebab995bb179e8e2861779ee7e3', 'nonce': '5601', 'blockHash': '0x4baa0f2544336e50e054f0e15cddaf4f123ac6679525227568c6d94bd60db7da', 'transactionIndex': '0', 'from': '0xf7cb60839c0de25e37be0391c33bb34a8f0f8414', 'to': '0x58d8c3d70ce4fa4b9fb10a665c8712238746f2ff', 'value': '1650560000000000', 'gas': '21000', 'gasPrice': '31000000000', 'isError': '0', 'txreceipt_status': '1', 'input': '0x', 'contractAddress': '', 'cumulativeGasUsed': '21000', 'gasUsed': '21000', 'confirmations': '739'}</div></blockquote></p><code> Transaction with amount 0.00194913 is not found in list of ETH transactions, address is f7cb60839c0de25e37be0391c33bb34a8f0f8414 during 600s</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/cf21f2f15aa44b238801ac45e13a8496?auth=d5c0963c50544763bd37b9e45670c1b4">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/cf21f2f15aa44b238801ac45e13a8496/0055screenshot.png?auth=d5c0963c50544763bd37b9e45670c1b4">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/3c70c8e0ed3d454f92700aeaed7d85d4?auth=79c66e5717243e0a064886ffbbf23b97">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/3c70c8e0ed3d454f92700aeaed7d85d4/0039screenshot.png?auth=79c66e5717243e0a064886ffbbf23b97">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table></details><h3>Passed tests (65)</h3><details><summa [...]

2021-06-01 10:26 UTC, churik commented
@vkjr 
### ISSUE 1: invited user has option to edit chat name / descritpion

**Steps:**
1) User A: Create community ("Require approval") with 1 public chat with description
2) User A: invite user B
3) User B: join community, try to edit community channel

**Expected result:**
edit option is not available
**Actual result:**
edit option is available, when trying to save nothing happened

**OS:** IOS, Android

### ISSUE 2: channel description changes are not saved

**Steps:**
1) User A: Create community ("Require approval") with 1 public chat with description
2) User A: invite user B
3) User B: join community
4) User A: change community description

**Expected result:**
User B: can see that community description is changed
**Actual result:**
User B: nothing changed

**OS:** IOS, Android

### ISSUE 3: long tap > open details from community screen leads to empty details

**Steps:**
1) User A: Create community ("Require approval") with 1 public chat with description
4) User A: open community view with channel list, long tap on created channel > View details
![IMAGE 2021-06-01 12:25:48](https://user-images.githubusercontent.com/4557972/120308543-7fec9b00-c2d4-11eb-83a5-35bbab0cfc03.jpg)

**OS:** IOS, Android

2021-06-03 11:18 UTC, vkjr commented
@churik, all issues were addressed (thanks for finding them)

2021-06-04 10:34 UTC, shivekkhurana requested changes
Looks good, pointed out some cosmetic issues.

2021-06-04 10:34 UTC, shivekkhurana commented on src/status_im/communities/core.cljs
> +  (log/info "")
Rogue log.

2021-06-04 10:34 UTC, shivekkhurana commented on src/status_im/communities/core.cljs
> +            {:db (assoc db :communities/create-channel {:name        chat-name
Can align map k/v pairs.

2021-06-04 10:34 UTC, shivekkhurana commented on src/status_im/ui/screens/chat/sheets.cljs
> +                  chat-id group-chat chat-name color]
Map kvs not aligned.

2021-06-04 10:34 UTC, shivekkhurana commented on src/status_im/ui/screens/communities/channel_details.cljs
> +      [:<>
Redundant fragment `[:<>`

2021-06-04 11:00 UTC, vkjr commented
@shivekkhurana, thanks for the notes, addressed them.

2021-06-04 12:48 UTC, shivekkhurana approved these changes

2021-06-04 15:31 UTC, qoqobolo commented
Checked the fixes for issues 1-5, everything works fine now. Thank you @vkjr!
PR can be merged.

2021-06-04 16:20 UTC, vkjr commented
@qoqobolo, thanks!

2021-06-04 16:22 UTC, merged