Pick community color
status-im/status-react pull request #12249
Opened 2021-06-24 14:55 UTC by sharmav9753

fixes [#12129](https://github.com/status-im/status-react/issues/12129)

[comment]: # Did implementation that allow user to pick community color

2021-06-24 14:56 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | f0bcca84 | [#1](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-12249/1/) | 2021-06-24 14:56:00 | ~18 sec | `android` | [:page_facing_up:`log`](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-12249/1/consoleText) |

2021-06-25 05:41 UTC, flexsurfer commented
hey @sharmav9753 great job, thanks for your contribution, one small thing, our own implementation of colour picker should be used, take a look at account color in wallet.

2021-06-25 05:47 UTC, flexsurfer commented
hey @sharmav9753 thanks for a great job. usually, we're trying to do not use external libraries if it possible, i've added a screen to the issue, it seems it could be done without external library

2021-06-25 05:58 UTC, flexsurfer commented
found this one https://github.com/naeemur/react-native-wheel-color-picker, looks similar to our design and Pure JS, lightweight, so we could use it

2021-06-25 07:02 UTC, errorists commented
heyo. one thing that should be addressed, the colour picked allows specifying any colour, and depending on what you end up picking it might be very bright/dark and not having enough contrast against the text used in front of it. We should adjust a matching text colour to either white or black depending on the colour you pick and store that value. 

to illustrate what I mean

<img width="731" alt="Screenshot 2021-06-25 at 09 01 17" src="https://user-images.githubusercontent.com/4932774/123383819-edb67a80-d593-11eb-89e4-6fd11a913c90.png">

2021-06-25 09:20 UTC, sharmav9753 commented
> found this one https://github.com/naeemur/react-native-wheel-color-picker, looks similar to our design and Pure JS, lightweight, so we could use it

Thanks for the feedback!
Sure, I will replace current library from above suggested. Although I chose lib based on stars and contributors.

2021-06-25 09:21 UTC, sharmav9753 commented
> heyo. one thing that should be addressed, the colour picked allows specifying any colour, and depending on what you end up picking it might be very bright/dark and not having enough contrast against the text used in front of it. We should adjust a matching text colour to either white or black depending on the colour you pick and store that value.
> 
> to illustrate what I mean
> 
> <img alt="Screenshot 2021-06-25 at 09 01 17" width="731" src="https://user-images.githubusercontent.com/4932774/123383819-edb67a80-d593-11eb-89e4-6fd11a913c90.png">

Thanks for the valuable feedback!
I will address the feedback soon.

2021-06-28 12:39 UTC, sharmav9753 commented
@errorists 
Added support for dynamically text colour generation. Please check

2021-06-28 15:12 UTC, cammellos commented
@sharmav9753 thanks for the update!
Have you looked into replacing the RN library with the one @flexsurfer suggested?
Also, could you please rebase?
Before pushing you can also run:

`make lint-fix`
and
`make lint` 
to make sure the code is linting fine.

Thanks!

2021-06-28 15:28 UTC, flexsurfer commented
im fine with react-native-color-picker , if @errorists and @shivekkhurana is fine

2021-06-29 13:01 UTC, shivekkhurana requested changes

2021-06-29 13:01 UTC, shivekkhurana commented on src/status_im/ui/screens/communities/create.cljs
> +    (fn [{:keys [name description]}]
Why did you add an extra `fn`?

2021-06-29 13:01 UTC, shivekkhurana commented on src/status_im/ui/screens/communities/create.cljs
> +      (let [on-close-color-picker    (fn [] (reset! visible false))
Although this is the better way, we tend to use inline functions directly. So instead of 
`:on-press on-close-color-picker`, using `:on-press #(reset! visible false)` is more coherent with the rest of the codebase.

2021-06-29 13:01 UTC, shivekkhurana commented on src/status_im/ui/screens/communities/create.cljs
> +            [rn/view {:style {:padding-bottom     16
Maybe extract this as a component? It adds complexity to this function. Not a big deal though.

2021-06-29 13:01 UTC, shivekkhurana commented on src/status_im/ui/screens/communities/create.cljs
> +         (when @visible
We need to use a native modal. 

To open a native modal, you need to define a screen in `screens.cljs` and then use `#(re-frame/dispatch [:open-modal :screen-id])` to open that screen as a modal. Here's an example: https://github.com/status-im/status-react/pull/12240/files#diff-eaf9764ab778d38605bc08f4a137ca29c144c02db7c250d8755ec0a067369369R164

2021-06-29 13:01 UTC, shivekkhurana commented on src/status_im/ui/screens/communities/create.cljs
> +                [color-picker {
I see there are two sliders in the component, where is the code responsible for that ?
<details>
  <summary>View Screenshot 📷 </summary>
  
![Simulator Screen Shot - iPhone 11 - 2021-06-29 at 18 10 41](https://user-images.githubusercontent.com/1925158/123800737-39a44f00-d907-11eb-8616-bc8ea3fa0e40.png)
</details>

Also as per the design, we need an input box to handle hex values: https://www.figma.com/file/aS1ct66VQ6V0cio7vSqS8UoG/Chat?node-id=17028%3A202

2021-06-29 13:01 UTC, shivekkhurana commented on src/status_im/utils/colors.cljs
> +            (fn [m r g b] (+ (+ (+ (+ (+ r r) g) g) b) b)))
What is this magic? Comments/ links will be helpful.

2021-06-29 13:01 UTC, shivekkhurana commented on src/status_im/utils/colors.cljs
> +(defn hexToRgb
Clojure conventionally follows `snake-case`, so its better if this is `hex-to-rgb`.

2021-06-29 13:01 UTC, shivekkhurana commented on src/status_im/utils/colors.cljs
> +        (if result [
1. What are you trying to achieve here?
2. The indentation is off. Calva for VS-Code might help.

2021-06-29 13:01 UTC, shivekkhurana commented on src/status_im/utils/colors.cljs
> +    let [[r g b] (hexToRgb color)]
These `def`s inside the code block are redundant. You can use `let` bindings:

```clojure
(let [[r g b] (hex-to-rgb ...)
      target-color (str "rgb(" r "," ...)
      colors (.match target-color #"...")]
  (.round ...)) ; last value is return value, no need to define it

2021-06-29 13:01 UTC, shivekkhurana commented on src/status_im/utils/colors.cljs
> +              (* (js/parseInt (aget colors 1)) 299)
Magic numbers should be documented.

2021-07-01 09:45 UTC, sharmav9753 commented
@shivekkhurana 
Thanks for the feedbacks. Will address soon.

2021-07-02 15:11 UTC, sharmav9753 commented on src/status_im/ui/screens/communities/create.cljs
> +      (let [on-close-color-picker    (fn [] (reset! visible false))
Done!

2021-07-02 15:13 UTC, sharmav9753 commented on src/status_im/ui/screens/communities/create.cljs
> +                [color-picker {
I used default 3rd party lib design as I didn't get the design. Now will adjust it accordingly.

2021-07-02 15:14 UTC, sharmav9753 commented on src/status_im/utils/colors.cljs
> +            (fn [m r g b] (+ (+ (+ (+ (+ r r) g) g) b) b)))
Updated the code and included links. please check.

2021-07-02 15:14 UTC, sharmav9753 commented on src/status_im/utils/colors.cljs
> +(defn hexToRgb
Done.

2021-07-02 15:15 UTC, sharmav9753 commented on src/status_im/utils/colors.cljs
> +        (if result [
Thanks for reference for the extension.
Updated the code.

2021-07-02 15:16 UTC, sharmav9753 commented on src/status_im/utils/colors.cljs
> +    let [[r g b] (hexToRgb color)]
Done.

2021-07-14 09:15 UTC, flexsurfer commented
@shivekkhurana is this still relevant ?

2021-07-14 09:26 UTC, shivekkhurana commented
@flexsurfer The candidate has been moved to the next stage and won't be completing this PR. Someone from our team has to work on this. It sets a good foundation to build upon.

2021-07-22 12:49 UTC, closed without merging