Fix show/hide password on Android
status-im/status-react pull request #12536
Opened 2021-09-02 08:38 UTC by bitgamma

Fixes #11955.

This PR actually has three parts

[x] Make the seed phrase entry "visibile-password" on Android, otherwise SwiftKey and similar would record the seed phrase
[x] Make the password hide/show button work in both directions.
[x] When the text is password/visibile-password make sure auto correct and autocomplete is disabled

As a side effect of point 2, when the password is shown, the "suggestions" from SwiftKey and probably other keyboard as activated. This is because I had to make a sort of workaround until https://github.com/facebook/react-native/issues/27946 is fixed. Point 3 seems to at least (from my limited testing) avoid that the password is stored by the keyboard.

2021-09-02 08:50 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | fa900bb5 | [#1](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-12536/1/) | 2021-09-02 08:50:12 | ~11 min | `android-e2e` | [:package:`apk`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-210902-083911-fa900b-pr12536-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-210902-083911-fa900b-pr12536-x86.apk)|

2021-09-02 14:11 UTC, status-im-auto commented
## 93% of end-end tests have passed
```
Total executed tests: 70
Failed tests: 5
Passed tests: 65
```
```
IDs of failed tests: 6645,6272,6228,6263,6293 
```
<h3>Failed tests (5)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/end-to-end-tests/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&APK_NAME=12536.apk&PR_ID=12536&TR_CASE_IDS=6645,6272,6228,6263,6293">Rerun tests</a></li><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2305289">test_restore_account_migrate_multiaccount_to_keycard</a>, id: 6645 </b></td></tr><tr><td><p><blockquote><div>Device 1: *Tap on found Button* </div><div>Device 1: **Enter default pin 111111** </div></blockquote></p><code> Device 1: 'AccountElementButton' by xpath:'//*[@content-desc='accountcardEthereum account']' not found on the screen</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/1c4a0eb5b01847dcb1b5262a8493588a?auth=65f4e8e304ddd03cda8d3475e576a62d">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/1c4a0eb5b01847dcb1b5262a8493588a/0085screenshot.png?auth=65f4e8e304ddd03cda8d3475e576a62d">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2305276">test_add_account_to_wallet_private_key_and_seed_phrase</a>, id: 6272 </b></td></tr><tr><td><p><blockquote><div>Device 1: *Scrolling up to AccountElementButton* </div><div>Device 1: *Find ReceiveTransactionButton by xpath:* `//*[@text="Receive"]` </div></blockquote></p><code> Device 1: ReceiveTransactionButton by xpath: `//*[@text="Receive"]` is not found on the screen</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/821e899e67b146adb93ff7e9edae7e94?auth=164b424c779fac423b484e6997b458ca">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/821e899e67b146adb93ff7e9edae7e94/0038screenshot.png?auth=164b424c779fac423b484e6997b458ca">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2305267">test_mobile_data_usage_complex_settings</a>, id: 6228 </b></td></tr><tr><td><p><blockquote><div>Device 1: *Find Button by xpath:* `//*[@text="Use mobile data"]/following-sibling::android.widget.Switch[1]` </div><div>Device 1: *Find Button by xpath:* `//*[@text="Ask me when on mobile network"]/following-sibling::android.widget.Switch[1]` </div></blockquote></p><code> Chat history was not fetched with mobile data fetching ON</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/5ce369d83cf845ba84742a2f5b6c1c07?auth=9c79cf900edc919639e5fc23ec867abf">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/5ce369d83cf845ba84742a2f5b6c1c07/0029screenshot.png?auth=9c79cf900edc919639e5fc23ec867abf">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/01eb70cd9c7b48abbed21caeed85451b?auth=5355335fd3024478375bc1d7182431a9">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/01eb70cd9c7b48abbed21caeed85451b/0028screenshot.png?auth=5355335fd3024478375bc1d7182431a9">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2305274">test_request_and_receive_stt_in_1_1_chat_offline</a>, id: 6263 </b></td></tr><tr><td><p><blockquote><div>Device 2: *Tap on found Button* </div><div>Device 2: *Wait for text element TransactionStatus to be equal to Pending* </div></blockquote></p><code> Device 2: 'Confirmed' is not equal to expected 'Pending' in 60 sec</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/96608196d0c244aca447d9efd31d165d?auth=0bbf72e69e30153fa980e78fa103f4c2">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/96608196d0c244aca447d9efd31d165d/0031screenshot.png?auth=0bbf72e69e30153fa980e78fa103f4c2">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/2eee2e6c11dd4cbb811575bdce905f3c?auth=b9e6aaf8004a2b06a27da3b487b3ac4f">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/2eee2e6c11dd4cbb811575bdce905f3c/0040screenshot.png?auth=b9e6aaf8004a2b06a27da3b487b3ac4f">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2305282">test_keycard_send_eth_in_1_1_chat</a>, id: 6293 </b></td></tr><tr><td><p><blockquote><div>Device 1: *Element TransactionStatus text is equal to Confirmed* </div><div>Device 2: *Wait for text element TransactionStatus to be equal to Confirmed* </div></blockquote></p><code> Device 2: 'Shared 'Ethereum account'' is not equal to expected 'Confirmed' in 60 sec</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/356f4b14a3144e1980ff13ea899174e2?auth=65f58768bfe9a62f4d40bc544157d65c">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/356f4b14a3144e1980ff13ea899174e2/0054screenshot.png?auth=65f58768bfe9a62f4d40bc544157d65c">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/c9e60bdc66b74edcb2a226b0a6804204?auth=e535820dee0f6af8669203f449e9323a">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/c9e60bdc66b74edcb2a226b0a6804204/0045screenshot.png?auth=e535820dee0f6af8669203f449e9323a">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table></details><h3>Passed tests (65)</h3><details><summary>Click to expand</summary><br/><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2305284">test_image_in_one_to_one_send_save_reply_timeline</a>, id: 6305 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/d987907e57d34115a05e965ba5cacca2?auth=c888369c66ffec0babf162b00c052452">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/835d7026c53e47a589bae5c1914bfe4c?auth=9d938b872c9f2cb50a88521c0080ed39">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2305265">test_add_account_to_multiaccount_instance_generate_new</a>, id: 6224 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/fa29642255984a8393426cec422c65d8?auth=0ee7605b3bb95c1876758b6a8d78be72">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2305281">test_keycard_can_see_all_transactions_in_history</a>, id: 6291 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/1966960854c84a6b8db76bb8d31b9394?auth=12945a39d786a214481798ce141e0471">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2305237">test_sign_message_and_2tx_in_batch_and_transactions_filters_from_daap</a>, id: 5342 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/b06e0dc786084fad9b04d1a31146262f?auth=6376114d9e22a66aa8d82936a8d21ab9">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2305270">test_add_and_delete_watch_only_account_to_multiaccount_instance</a>, id: 6244 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="h [...]

2021-09-02 14:17 UTC, briansztamfater approved these changes

2021-09-02 15:21 UTC, flexsurfer requested changes
pls do not merge, i'll make review tomorrow, thanks

2021-09-02 15:21 UTC, flexsurfer commented on src/status_im/ui/screens/multiaccounts/views.cljs
> +     :keyboard-type       "visible-password"
better to use keyword

2021-09-03 05:42 UTC, bitgamma commented on src/status_im/ui/screens/multiaccounts/views.cljs
> +     :keyboard-type       "visible-password"
"visibile-password" appears in the code in other places too as string so I kept it this way, but I can change it everywhere in the code

2021-09-03 07:59 UTC, flexsurfer approved these changes

2021-09-07 09:50 UTC, status-im-auto commented
## 60% of end-end tests have passed
```
Total executed tests: 5
Failed tests: 2
Passed tests: 3
```
```
IDs of failed tests: 6645,6293 
```
<h3>Failed tests (2)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/end-to-end-tests/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&APK_NAME=12536.apk&PR_ID=12536&TR_CASE_IDS=6645,6293">Rerun tests</a></li><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2307144">test_restore_account_migrate_multiaccount_to_keycard</a>, id: 6645 </b></td></tr><tr><td><p><blockquote><div>Device 1: *Tap on found Button* </div><div>Device 1: *Find Button by accessibility id:* `connect-card` </div></blockquote></p><code> Device 1: Button by accessibility id: `connect-card` is not found on the screen</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/5b201e4fa55e41c1ba8b24069965e5d0?auth=f9bc18386a55823def32976241392cad">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/5b201e4fa55e41c1ba8b24069965e5d0/0148screenshot.png?auth=f9bc18386a55823def32976241392cad">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2307143">test_keycard_send_eth_in_1_1_chat</a>, id: 6293 </b></td></tr><tr><td><p><blockquote><div>Expected amount of confirmations is 6, in fact 5</div><div>Finding tx in ETH transactions, attempt #1</div></blockquote></p><code> Expecting value: line 1 column 1 (char 0)</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/d683a94fa4e648e784dc202fcbfc3ef7?auth=63e11cf6f1579b1e7e03b4c2d0a358bd">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/d683a94fa4e648e784dc202fcbfc3ef7/0051screenshot.png?auth=63e11cf6f1579b1e7e03b4c2d0a358bd">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/418ed589965e465a8a3fe950e4c0bf15?auth=5149093d29d40e857b87c34613871236">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/418ed589965e465a8a3fe950e4c0bf15/0039screenshot.png?auth=5149093d29d40e857b87c34613871236">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table></details><h3>Passed tests (3)</h3><details><summary>Click to expand</summary><br/><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2307142">test_add_account_to_wallet_private_key_and_seed_phrase</a>, id: 6272 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/c0b411dad9754a02a0e5a3f00e035ff6?auth=7fe8b587aadf6e14d83b4790d7ebe2ef">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2307140">test_mobile_data_usage_complex_settings</a>, id: 6228 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/8fe7acc823234fe29d718aa8c9549771?auth=e1d5c9954f16ba66e85faf4616d8d72b">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/0099892b64a54ae08d9fa61f6a79b6a0?auth=385868215e949045a2e2d18bf7c61e86">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2307141">test_request_and_receive_stt_in_1_1_chat_offline</a>, id: 6263 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/3d3c81ab54cc48499fb5ea645909cfc1?auth=cf8bfbed8a9a30c4f92998632e67bc45">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/bef6b5062f3642db8f045cad52ed375f?auth=07f9c9eea96904e6a0ba14e969d5c416">Steps, video, logs</a></li></ul></p></ul></p></td></tr></tbody></table></details>

2021-09-07 10:30 UTC, Serhy commented
Tested with Android 11 and Android 9 and iOS 14, - seed phrase field does not have autosuggestions (and autocomplete panel) enabled, password fields hide/show also works. 
Failed tests were false failures (can not reproduce manually), - will fix them separately. 
Thanks a lot, @bitgamma !

2021-09-07 10:37 UTC, status-im-auto commented
## 100% of end-end tests have passed
```
Total executed tests: 2
Failed tests: 0
Passed tests: 2
```
<h3>Passed tests (2)</h3><details><summary>Click to expand</summary><br/><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2307163">test_restore_account_migrate_multiaccount_to_keycard</a>, id: 6645 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/c8733616c4114b548cbf650a4b933ba0?auth=195f4585b4e48af9a622d180f1863958">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2307162">test_keycard_send_eth_in_1_1_chat</a>, id: 6293 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/ebf686a66b33408bb43090c7dfc6c592?auth=fa31f6175e80036eb04c78eb6fa4a217">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/877de2b1f0b44633bdf66a35e3d86176?auth=bfdd84067e115a711d90df688304b8bb">Steps, video, logs</a></li></ul></p></ul></p></td></tr></tbody></table></details>

2021-09-07 11:05 UTC, merged

2021-09-08 11:01 UTC, Serhy commented
@bitgamma sorry, i've missed regression after this change, - https://github.com/status-im/status-react/issues/12560
(on iOS all one-line inputs behave like passwords now)