Added 'censorship' to society
status-im/status-react pull request #12653
Opened 2021-09-26 21:21 UTC by ducheng0

I've added #censorship to the list of public chats under Society because censorship is something that is frequently experienced and should be talked about and scrutinized.

2021-09-26 21:33 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 924b9e08 | [#1](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-12653/1/) | 2021-09-26 21:33:34 | ~11 min | `android` | [:package:`apk`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-210926-212200-924b9e-pr12653-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-210926-212200-924b9e-pr12653-universal.apk)|

2021-09-27 11:03 UTC, hesterbruikman requested changes
Thanks for the PR @ducheng0 There's an issue, with the list not showing in the PR build. I think it's because of a missing comma. Can you please take a look at that?

As a heads up: we'll likely remove this list of public chats at some point because they are vulnerable to spam. Also, ironically, the current approach of a list being maintained for which you have to submit a PR that needs to be approved is, in itself not censorship resistant. The `communities` feature is the way forward 💪 It'll come with a dapp for independent community curation; For ranking, communities are fully permissionless to create as are public chats currently.

2021-09-27 11:03 UTC, hesterbruikman commented on resources/chats.json
>        "privacy"
Looks like there's a comma missing. When testing the PR build I'm no longer seeing any public chats listed.

![Screenshot_20210927-124835_Status PR](https://user-images.githubusercontent.com/35233054/134895694-0c17e24a-3499-46ac-93cd-e6283f53e22e.jpg)

2021-09-27 14:56 UTC, ducheng0 commented
> Thanks for the PR @ducheng0 There's an issue, with the list not showing in the PR build. I think it's because of a missing comma. Can you please take a look at that?
> 
> As a heads up: we'll likely remove this list of public chats at some point because they are vulnerable to spam. Also, ironically, the current approach of a list being maintained for which you have to submit a PR that needs to be approved is, in itself not censorship resistant. The `communities` feature is the way forward  It'll come with a dapp for independent community curation; For ranking, communities are fully permissionless to create as are public chats currently.

I was talking with one of the devs about the new community curation feature, and I'm quite excited! Maybe offer options to rank them based on amount of users in them, how much is staked, and when they were added to the list. Making Dapps look more like WeChat's mini-programs would also be awesome (having a bottom nav bar, and fullscreen experience with options in the top right). I'll figure out how to use Figma and send over my ideas on a UI.

For some reason I can't update the pull request, so you can find the updated code here: https://github.com/ducheng0/status-react/commit/1606c0711ef344bbca62c0059153c7cbf5d699f2

Thanks

2021-09-29 01:24 UTC, ducheng0 commented
I'm going to close this pull request because I've never used Git to collaborate with others on code, and I don't know what I'm doing or how this works. Help would be much appreciated :)

2021-09-29 01:24 UTC, closed without merging