Online status indicator
status-im/status-react pull request #12716
Opened 2021-10-18 08:40 UTC by Parveshdhull

fixes #12547

### Summary
PR implements Online Status Indicator
<div align="center">
<img src="https://user-images.githubusercontent.com/17097240/137238899-27f531a4-f463-4029-b526-8c906cb7d02f.png" alt="Screenshot" height="400"/>
<img src="https://user-images.githubusercontent.com/17097240/137976829-6e2dde90-bbc4-424c-b52a-9fdbc86afcdc.gif" alt="Screenshot" height="400"/>
<img src="https://user-images.githubusercontent.com/17097240/137238905-4bca1567-61f6-40c0-9e2e-d6456f6c4e23.png" alt="Screenshot" height="400"/>
</div>

PR follows these design guidelines: Designs [[1st]](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=7253%3A27195) [[2nd]](https://www.figma.com/file/IPpvkpDWabBKJTeo6bFop0/Kuba%E2%8E%9CDesktop?node-id=77%3A19108)
#### status-go PR:
https://github.com/status-im/status-go/pull/2408

#### Code
There were some residue code in [styles.cljs](https://github.com/status-im/status-react/pull/12706/files#diff-f54bb761ef81cb3f9f1af35f7080f4edc667f1e88fb816755a5d14d7d442992d) file from 2016 implementation of online status indicator. Currently, it is not used anywhere, so removed to avoid confusion between styles.

#### Other features:
- Status updates syncing between devices
- Offline status updates
- Sort community members & contacts based on online status and name

#### Known Issues:
- Gap between each ping is 5 minutes. So it has its own side effects for ex. the user seems online a little longer, etc.
- Offline capability works great with the single device it will broadcast its current status whenever the device becomes online, even after app restart. 
But there is one rare case where it will not work:
i) User is using multiple devices
ii) Another device is online and broadcasting different status than saved by the main device during the offline state. (with larger clock value than saved clock)
iii) Once the main device gets online it receives broadcast from another device before broadcasting saved status. 

Thanks

2021-10-18 08:58 UTC, status-im-auto commented
### Jenkins Builds
<details>
<summary>Click to see older builds (57)</summary>

| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 6cc708a6 | [#1](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-12716/1/) | 2021-10-18 08:58:00 | ~17 min | `ios` | [:package:`ipa`](https://i.diawi.com/HFtQFs) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2FHFtQFs)|
| :heavy_check_mark: | 6cc708a6 | [#1](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-12716/1/) | 2021-10-18 08:58:19 | ~17 min | `android-e2e` | [:package:`apk`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-211018-084026-6cc708-pr12716-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-211018-084026-6cc708-pr12716-x86.apk)|
| :heavy_check_mark: | 6cc708a6 | [#1](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-12716/1/) | 2021-10-18 08:58:21 | ~17 min | `android` | [:package:`apk`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-211018-084026-6cc708-pr12716-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-211018-084026-6cc708-pr12716-universal.apk)|
| | | | | | | |
| :heavy_check_mark: | 95e0a1a9 | [#2](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-12716/2/) | 2021-10-18 12:47:00 | ~14 min | `android-e2e` | [:package:`apk`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-211018-123235-95e0a1-pr12716-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-211018-123235-95e0a1-pr12716-x86.apk)|
| :heavy_check_mark: | 95e0a1a9 | [#2](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-12716/2/) | 2021-10-18 12:47:12 | ~14 min | `android` | [:package:`apk`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-211018-123235-95e0a1-pr12716-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-211018-123235-95e0a1-pr12716-universal.apk)|
| :heavy_check_mark: | 95e0a1a9 | [#2](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-12716/2/) | 2021-10-18 12:49:24 | ~16 min | `ios` | [:package:`ipa`](https://i.diawi.com/Ri9E6k) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2FRi9E6k)|
| | | | | | | |
| :heavy_check_mark: | d7a2f899 | [#3](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-12716/3/) | 2021-10-18 17:00:37 | ~14 min | `android-e2e` | [:package:`apk`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-211018-164624-d7a2f8-pr12716-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-211018-164624-d7a2f8-pr12716-x86.apk)|
| :heavy_check_mark: | d7a2f899 | [#3](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-12716/3/) | 2021-10-18 17:00:38 | ~14 min | `android` | [:package:`apk`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-211018-164624-d7a2f8-pr12716-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-211018-164624-d7a2f8-pr12716-universal.apk)|
| :heavy_check_mark: | d7a2f899 | [#3](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-12716/3/) | 2021-10-18 17:02:30 | ~16 min | `ios` | [:package:`ipa`](https://i.diawi.com/yUj452) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2FyUj452)|
| | | | | | | |
| :heavy_check_mark: | 4d29a980 | [#4](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-12716/4/) | 2021-10-19 19:05:52 | ~14 min | `android` | [:package:`apk`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-211019-185053-4d29a9-pr12716-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-211019-185053-4d29a9-pr12716-universal.apk)|
| :heavy_check_mark: | 4d29a980 | [#4](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-12716/4/) | 2021-10-19 19:07:54 | ~17 min | `android-e2e` | [:package:`apk`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-211019-185053-4d29a9-pr12716-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-211019-185053-4d29a9-pr12716-x86.apk)|
| :heavy_check_mark: | 4d29a980 | [#4](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-12716/4/) | 2021-10-19 19:09:16 | ~18 min | `ios` | [:package:`ipa`](https://i.diawi.com/6SqYgp) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2F6SqYgp)|
| | | | | | | |
| :x: | 317a21dc | [#5](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-12716/5/) | 2021-10-21 02:45:33 | ~18 sec | `android-e2e` | [:page_facing_up:`log`](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-12716/5/consoleText) |
| :x: | 317a21dc | [#5](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-12716/5/) | 2021-10-21 02:45:33 | ~18 sec | `android` | [:page_facing_up:`log`](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-12716/5/consoleText) |
| :x: | 317a21dc | [#5](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-12716/5/) | 2021-10-21 02:45:33 | ~18 sec | `ios` | [:page_facing_up:`log`](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-12716/5/consoleText) |
| | | | | | | |
| :x: | 2d974659 | [#6](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-12716/6/) | 2021-10-21 02:49:33 | ~13 sec | `android-e2e` | [:page_facing_up:`log`](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-12716/6/consoleText) |
| :x: | 2d974659 | [#6](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-12716/6/) | 2021-10-21 02:49:34 | ~13 sec | `android` | [:page_facing_up:`log`](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-12716/6/consoleText) |
| :x: | 2d974659 | [#6](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-12716/6/) | 2021-10-21 02:49:34 | ~14 sec | `ios` | [:page_facing_up:`log`](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-12716/6/consoleText) |
| | | | | | | |
| :heavy_check_mark: | afcbd6f7 | [#7](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-12716/7/) | 2021-10-21 03:17:07 | ~15 min | `ios` | [:package:`ipa`](https://i.diawi.com/PY51wL) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2FPY51wL)|
| :heavy_check_mark: | afcbd6f7 | [#7](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-12716/7/) | 2021-10-21 03:18:35 | ~17 min | `android` | [:package:`apk`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-211021-030120-afcbd6-pr12716-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-211021-030120-afcbd6-pr12716-universal.apk)|
| :heavy_check_mark: | afcbd6f7 | [#7](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-12 [...]

2021-10-18 11:31 UTC, rasom commented on src/status_im/status_updates/core.cljs
> +           (if (nil? dispatch) {} {:dispatch dispatch}))))
could be just `(when dispatch {:dispatch dispatch})`. It is shorter although still dispatch dispatch dispatch :D

2021-10-18 11:31 UTC, rasom commented on src/status_im/status_updates/core.cljs
> +    (swap! events-to-dispatch-later conj {:ms 10 :dispatch [:status-updates/update-visibility-status status-type]})
When it is possible, please, keep lines' length shorter/equal 80 chars.

2021-10-18 11:31 UTC, rasom commented on src/status_im/utils/datetime.cljs
> +(defn to-mills [sec]
That's very subjective, but imo `to-ms` would look better.

2021-10-18 12:35 UTC, Parveshdhull commented on src/status_im/status_updates/core.cljs
> +    (swap! events-to-dispatch-later conj {:ms 10 :dispatch [:status-updates/update-visibility-status status-type]})
Great Tip 🙏, now I enabled Emacs auto highlight for longer lines. Thanks

2021-10-18 12:35 UTC, Parveshdhull commented on src/status_im/utils/datetime.cljs
> +(defn to-mills [sec]
Yes, this looks much better 😅

2021-10-18 16:36 UTC, rasom approved these changes

2021-10-18 18:04 UTC, status-im-auto commented
## 72% of end-end tests have passed
```
Total executed tests: 69
Failed tests: 19
Passed tests: 50
```
```
IDs of failed tests: 5502,5315,5390,5758,6645,5319,6253,5782,5356,5341,6633,5783,5394,6263,5346,6249,6240,5381,6283 
```
<h3>Failed tests (19)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/end-to-end-tests/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&APK_NAME=12716.apk&PR_ID=12716&TR_CASE_IDS=5502,5315,5390,5758,6645,5319,6253,5782,5356,5341,6633,5783,5394,6263,5346,6249,6240,5381,6283">Rerun tests</a></li><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2332309">test_can_add_existing_ens_on_mainnet</a>, id: 5502 </b></td></tr><tr><td><p><blockquote><div>Device 1: **Sign in** (password:qwerty, keycard:False) </div><div>Device 1: *Find EditBox by accessibility id:* `password-input` </div></blockquote></p><code> Device 1: EditBox by accessibility id: `password-input` is not found on the screen; also Unexpected Alert is shown: 'Please shake the phone to report this error and restart the app. multiaccount is currently empty, which means something went wrong when t</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/1b4df6361745415cba6ed1b9a95ff06c?auth=e68d69d1883d2a3efbca23742822633f">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/1b4df6361745415cba6ed1b9a95ff06c/0028screenshot.png?auth=e68d69d1883d2a3efbca23742822633f">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2332285">test_send_non_english_message_to_newly_added_contact_on_different_networks</a>, id: 5315 </b></td></tr><tr><td><p><blockquote><div>Device 1: **Sign in** (password:qwerty, keycard:False) </div><div>Device 1: *Find EditBox by accessibility id:* `password-input` </div></blockquote></p><code> Device 1: EditBox by accessibility id: `password-input` is not found on the screen; also Unexpected Alert is shown: 'Please shake the phone to report this error and restart the app. multiaccount is currently empty, which means something went wrong when t</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/75eab33fc870416b9f893a34391e706d?auth=d8d57d56c3fd353e5092d06c92e7d4d9">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/75eab33fc870416b9f893a34391e706d/0018screenshot.png?auth=d8d57d56c3fd353e5092d06c92e7d4d9">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/47078aad076f4c7080a66582b6bc2e33?auth=568f947b824e79f8a541913a1504794e">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/47078aad076f4c7080a66582b6bc2e33/0011screenshot.png?auth=568f947b824e79f8a541913a1504794e">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2332303">test_delete_close_all_tabs</a>, id: 5390 </b></td></tr><tr><td><p><blockquote><div>Device 1: **Sign in** (password:qwerty, keycard:False) </div><div>Device 1: *Find EditBox by accessibility id:* `password-input` </div></blockquote></p><code> Device 1: EditBox by accessibility id: `password-input` is not found on the screen; also Unexpected Alert is shown: 'Please shake the phone to report this error and restart the app. multiaccount is currently empty, which means something went wrong when t</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/61a4ca1d1ba844c58167c3c652dd6842?auth=fc32a2d6adb22fd75b3000230020eba0">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/61a4ca1d1ba844c58167c3c652dd6842/0031screenshot.png?auth=fc32a2d6adb22fd75b3000230020eba0">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2332313">test_keycard_can_recover_keycard_account_card_pairing</a>, id: 5758 </b></td></tr><tr><td><p><blockquote><div>Device 1: ========================================================================= </div><div>Device 1: **Sign in** (password:qwerty, keycard:True) </div></blockquote></p><code> Device 1: SilentButton by accessibility id:`numpad-button-1` is not found on the screen; also Unexpected Alert is shown: 'Please shake the phone to report this error and restart the app. multiaccount is currently empty, which means something went wrong w</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/94c8899a556f46d2b07c3e4b1c493636?auth=7ef09ee39143ea74185ecd91da3cd30c">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/94c8899a556f46d2b07c3e4b1c493636/0028screenshot.png?auth=7ef09ee39143ea74185ecd91da3cd30c">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2332343">test_restore_account_migrate_multiaccount_to_keycard</a>, id: 6645 </b></td></tr><tr><td><p><blockquote><div>Device 1: ========================================================================= </div><div>Device 1: *Find Button by accessibility id:* `back-button` </div></blockquote></p><code> Device 1: Button by accessibility id: `back-button` is not found on the screen; also Unexpected Alert is shown: 'You need to log out to access key management.'</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/53992ee75d5e4c92bae4ae0267b97770?auth=f750af56fcda187f2c9054c1c320e4ee">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/53992ee75d5e4c92bae4ae0267b97770/0021screenshot.png?auth=f750af56fcda187f2c9054c1c320e4ee">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>6. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2332287">test_long_press_to_delete_chat</a>, id: 5319 </b></td></tr><tr><td><p><blockquote><div>Device 1: **Sign in** (password:qwerty, keycard:False) </div><div>Device 1: *Find EditBox by accessibility id:* `password-input` </div></blockquote></p><code> Device 1: EditBox by accessibility id: `password-input` is not found on the screen; also Unexpected Alert is shown: 'Please shake the phone to report this error and restart the app. multiaccount is currently empty, which means something went wrong when t</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/e7dd45fd8b12417ebd8f7b77f38fb95d?auth=1a785797f47d15faec3206b1cb366443">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/e7dd45fd8b12417ebd8f7b77f38fb95d/0055screenshot.png?auth=1a785797f47d15faec3206b1cb366443">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>7. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2332328">test_send_eth_in_1_1_chat_transaction_push</a>, id: 6253 </b></td></tr><tr><td><p><blockquote><div>Device 1: *Find ProfileButton by xpath:* `//*[contains(@content-desc,'5 out of 5')]` </div><div>Device 1: *Find Button by accessibility id:* `notifications-settings-button` </div></blockquote></p><code> Device 1: Button by accessibility id: `notifications-settings-button` is not found on the screen</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/157119072624444984684e0ea22e0443?auth=d611e58ffb73aedb27a7028e705a1af7">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/157119072624444984684e0ea22e0443/0016screenshot.png?auth=d611e58ffb73aedb27a7028e705a1af7">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/bb0ad1295f9a4e8a96905b9ee61332c3?auth=e2f53a1e129b785f6d3cf1b7ae814f83">Steps, video, logs</a></li><li>< [...]

2021-10-19 11:39 UTC, status-im-auto commented
## 11% of end-end tests have passed
```
Total executed tests: 19
Failed tests: 17
Passed tests: 2
```
```
IDs of failed tests: 5782,6645,6283,5341,6633,5783,5315,6253,5390,6263,5381,6240,5394,5758,5502,5356,5346 
```
<h3>Failed tests (17)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/end-to-end-tests/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&APK_NAME=12716.apk&PR_ID=12716&TR_CASE_IDS=5782,6645,6283,5341,6633,5783,5315,6253,5390,6263,5381,6240,5394,5758,5502,5356,5346">Rerun tests</a></li><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2332672">test_install_pack_and_send_sticker</a>, id: 5782 </b></td></tr><tr><td><p><blockquote><div>Device 2: **Sign in** (password:qwerty, keycard:False) </div><div>Device 2: *Find EditBox by accessibility id:* `password-input` </div></blockquote></p><code> Device 2: EditBox by accessibility id: `password-input` is not found on the screen; also Unexpected Alert is shown: 'Please shake the phone to report this error and restart the app. multiaccount is currently empty, which means something went wrong when t</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/d1d35b1191b4468fb26bf6facecf1191?auth=cecd816db8ac3712c4af507a78b8a887">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/d1d35b1191b4468fb26bf6facecf1191/0018screenshot.png?auth=cecd816db8ac3712c4af507a78b8a887">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/efd985dfd6a04b39812f4158d3ba2bcc?auth=36bea4c01fefb89d4fe9fd741851de0f">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/efd985dfd6a04b39812f4158d3ba2bcc/0019screenshot.png?auth=36bea4c01fefb89d4fe9fd741851de0f">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2332680">test_restore_account_migrate_multiaccount_to_keycard</a>, id: 6645 </b></td></tr><tr><td><p><blockquote><div>Device 1: ========================================================================= </div><div>Device 1: *Find Button by accessibility id:* `back-button` </div></blockquote></p><code> Device 1: Button by accessibility id: `back-button` is not found on the screen; also Unexpected Alert is shown: 'Please shake the phone to report this error and restart the app. multiaccount is currently empty, which means something went wrong when tryin</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/54a685a1b9884b46b075d6db127f24b1?auth=0aa361ce570afd0e55721ce9c3271871">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/54a685a1b9884b46b075d6db127f24b1/0020screenshot.png?auth=0aa361ce570afd0e55721ce9c3271871">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2332678">test_push_notification_1_1_chat_no_pn_activity_center</a>, id: 6283 </b></td></tr><tr><td><p><blockquote><div>Device 1: *Text is Welldocumented Gaseous Zigzagsalamander* </div><div>Device 1: *Find Button by accessibility id:* `notifications-settings-button` </div></blockquote></p><code> Device 1: Button by accessibility id: `notifications-settings-button` is not found on the screen</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/188e503ecea2410bbc36f327fa07ba3b?auth=24d9092b9a0e5e472e4ca5bb36930028">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/188e503ecea2410bbc36f327fa07ba3b/0012screenshot.png?auth=24d9092b9a0e5e472e4ca5bb36930028">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/3d183720f1924e96b099555913b903dd?auth=6d4e1440d42cfaa1a6f1e0f90ab76499">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/3d183720f1924e96b099555913b903dd/0011screenshot.png?auth=6d4e1440d42cfaa1a6f1e0f90ab76499">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2332664">test_manage_assets</a>, id: 5341 </b></td></tr><tr><td><p><blockquote><div>Device 1: **Sign in** (password:qwerty, keycard:False) </div><div>Device 1: *Find EditBox by accessibility id:* `password-input` </div></blockquote></p><code> Device 1: EditBox by accessibility id: `password-input` is not found on the screen; also Unexpected Alert is shown: 'Please shake the phone to report this error and restart the app. multiaccount is currently empty, which means something went wrong when t</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/c581f217e21a448baf434f8e1ce3e9c5?auth=b72097eac313d0b404f4880b9a487434">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/c581f217e21a448baf434f8e1ce3e9c5/0021screenshot.png?auth=b72097eac313d0b404f4880b9a487434">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2332679">test_browser_managing_bookmarks</a>, id: 6633 </b></td></tr><tr><td><p><blockquote><div>Device 1: **Sign in** (password:qwerty, keycard:False) </div><div>Device 1: *Find EditBox by accessibility id:* `password-input` </div></blockquote></p><code> Device 1: EditBox by accessibility id: `password-input` is not found on the screen; also Unexpected Alert is shown: 'Please shake the phone to report this error and restart the app. multiaccount is currently empty, which means something went wrong when t</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/bd708392b07c409aaf09001e04c9a666?auth=28eab17ba668cdae829cceef0bc7ff03">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/bd708392b07c409aaf09001e04c9a666/0034screenshot.png?auth=28eab17ba668cdae829cceef0bc7ff03">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>6. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2332673">test_can_use_purchased_stickers_on_recovered_account</a>, id: 5783 </b></td></tr><tr><td><p><blockquote><div>Device 1: **Sign in** (password:qwerty, keycard:False) </div><div>Device 1: *Find EditBox by accessibility id:* `password-input` </div></blockquote></p><code> Device 1: EditBox by accessibility id: `password-input` is not found on the screen; also Unexpected Alert is shown: 'Please shake the phone to report this error and restart the app. multiaccount is currently empty, which means something went wrong when t</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/484a09fcbafd4f7aa6ae17bd8418f4fc?auth=c0aee4c24fdbc54ce19e9528709c7d2a">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/484a09fcbafd4f7aa6ae17bd8418f4fc/0022screenshot.png?auth=c0aee4c24fdbc54ce19e9528709c7d2a">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>7. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2332662">test_send_non_english_message_to_newly_added_contact_on_different_networks</a>, id: 5315 </b></td></tr><tr><td><p><blockquote><div>Device 1: **Sign in** (password:qwerty, keycard:False) </div><div>Device 1: *Find EditBox by accessibility id:* `password-input` </div></blockquote></p><code> Device 1: EditBox by accessibility id: `password-input` is not found on the screen; also Unexpected Alert is shown: 'Please shake the phone to report this error and restart the app. multiaccount is currently empty, which means something went wrong when t</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/c8be88f4a1be4f0a9e958c875c4ffa84?auth=169181f83219537ee404079ebed9df04">St [...]

2021-10-19 20:21 UTC, status-im-auto commented
## 90% of end-end tests have passed
```
Total executed tests: 69
Failed tests: 7
Passed tests: 62
```
```
IDs of failed tests: 6251,6272,6228,6253,6208,6249,6283 
```
<h3>Failed tests (7)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/end-to-end-tests/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&APK_NAME=12716.apk&PR_ID=12716&TR_CASE_IDS=6251,6272,6228,6253,6208,6249,6283">Rerun tests</a></li><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2332743">test_keycard_sign_message_and_transactions_from_daap</a>, id: 6251 </b></td></tr><tr><td><p><blockquote><div>Device 1: SilentButton element not found </div><div>Device 1: **Enter default pin 111111** </div></blockquote></p><code> Device 1: 'SilentButton' by accessibility id:'numpad-button-1' not found on the screen</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/b09b201a47c04d56bb3b368796fd4f62?auth=125c86b70b90961b92ddaacdffeba343">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/b09b201a47c04d56bb3b368796fd4f62/0050screenshot.png?auth=125c86b70b90961b92ddaacdffeba343">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2332747">test_add_account_to_wallet_private_key_and_seed_phrase</a>, id: 6272 </b></td></tr><tr><td><p><blockquote><div>Device 1: *Scrolling up to AccountElementButton* </div><div>Device 1: *Find ReceiveTransactionButton by xpath:* `//*[@text="Receive"]` </div></blockquote></p><code> Device 1: ReceiveTransactionButton by xpath: `//*[@text="Receive"]` is not found on the screen</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/1dd8645538da4f7691d09409ab56ad21?auth=a7f3f09093664849e442346634c74aab">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/1dd8645538da4f7691d09409ab56ad21/0058screenshot.png?auth=a7f3f09093664849e442346634c74aab">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2332738">test_mobile_data_usage_complex_settings</a>, id: 6228 </b></td></tr><tr><td><p><blockquote><div>Device 1: *Find Button by xpath:* `//*[@text="Use mobile data"]/following-sibling::android.widget.Switch[1]` </div><div>Device 1: *Find Button by xpath:* `//*[@text="Ask me when on mobile network"]/following-sibling::android.widget.Switch[1]` </div></blockquote></p><code> Chat history was not fetched with mobile data fetching ON</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/172258e5ea7f443da3369aa860a1ae66?auth=067037adaafce35754bc972fcf6b88ae">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/172258e5ea7f443da3369aa860a1ae66/0029screenshot.png?auth=067037adaafce35754bc972fcf6b88ae">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/2134abd50ddb459a902e5a3c113260ff?auth=e3c91fff05e0294727e1b1b9c589ae67">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/2134abd50ddb459a902e5a3c113260ff/0028screenshot.png?auth=e3c91fff05e0294727e1b1b9c589ae67">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2332744">test_send_eth_in_1_1_chat_transaction_push</a>, id: 6253 </b></td></tr><tr><td><p><blockquote><div>Device 1: *Find ProfileButton by xpath:* `//*[contains(@content-desc,'5 out of 5')]` </div><div>Device 1: *Find Button by accessibility id:* `notifications-settings-button` </div></blockquote></p><code> Device 1: Button by accessibility id: `notifications-settings-button` is not found on the screen</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/0b3710acb86543a094d0d9e960c84244?auth=bfb838daac627dc22a72fd1601abaa35">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/0b3710acb86543a094d0d9e960c84244/0016screenshot.png?auth=bfb838daac627dc22a72fd1601abaa35">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/443818e080fc439786cd628483244304?auth=8e2da3e1d2fdad57a086362c9c0b6dc6">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/443818e080fc439786cd628483244304/0011screenshot.png?auth=8e2da3e1d2fdad57a086362c9c0b6dc6">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2332734">test_send_transaction_with_custom_token</a>, id: 6208 </b></td></tr><tr><td><p><blockquote><div>Device 1: **Sending transaction** </div><div>Device 1: *Find SendTransactionButton by xpath:* `//*[@text="Send"]` </div></blockquote></p><code> Device 1: SendTransactionButton by xpath: `//*[@text="Send"]` is not found on the screen</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/4dc509a4d1114758a64d5b8561e12367?auth=49fd5d6105778d37eea246d9f2671a29">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/4dc509a4d1114758a64d5b8561e12367/0026screenshot.png?auth=49fd5d6105778d37eea246d9f2671a29">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>6. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2332742">test_keycard_request_stt_from_daap</a>, id: 6249 </b></td></tr><tr><td><p><blockquote><div>Device 1: *Find SignWithKeycardButton by xpath:* `//*[contains(@text,'Sign with')]` </div><div>Device 1: **Enter default pin 111111** </div></blockquote></p><code> Device 1: Transaction failed; also Unexpected Alert is shown: 'replacement transaction underpriced'</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/483d984e25044aaabc9e34680995b0e5?auth=4f32cb1f16c254b274864894b90bbda8">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/483d984e25044aaabc9e34680995b0e5/0045screenshot.png?auth=4f32cb1f16c254b274864894b90bbda8">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>7. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2332749">test_push_notification_1_1_chat_no_pn_activity_center</a>, id: 6283 </b></td></tr><tr><td><p><blockquote><div>Device 1: *Text is Khaki Helpful Galago* </div><div>Device 1: *Find Button by accessibility id:* `notifications-settings-button` </div></blockquote></p><code> Device 1: Button by accessibility id: `notifications-settings-button` is not found on the screen</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/ab8422a44be042869a9497514d653a02?auth=7e594e4a508c0b52d70ab7a4f3a7b05e">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/ab8422a44be042869a9497514d653a02/0012screenshot.png?auth=7e594e4a508c0b52d70ab7a4f3a7b05e">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/92267099b5bc4b5d9fdbae0bb5901d39?auth=e53ddbc5dbfe7477aa6cc8a01c7c5218">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/92267099b5bc4b5d9fdbae0bb5901d39/0011screenshot.png?auth=e53ddbc5dbfe7477aa6cc8a01c7c5218">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table></details><h3>Passed tests (62)</h3><details><summary>Click to expand</summary><br/><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2332754">test_image_in_one_to_one_send_save_reply_timeline</a>, id: 6305 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs [...]

2021-10-20 08:58 UTC, flexsurfer commented on src/status_im/constants.cljs
> +(def ^:const visibility-status-inactive 4)
what about invisible ?

2021-10-20 08:58 UTC, flexsurfer commented on src/status_im/data_store/settings.cljs
> +      (update :current-user-status status-updates/<-rpc)))
we have status tab. so probably we should use something like `user-online-status` or smth

2021-10-20 08:58 UTC, flexsurfer commented on src/status_im/db.cljs
> +             :status-updates                     {}
this might be confused with statuses (timeline)

2021-10-20 08:58 UTC, flexsurfer commented on src/status_im/visibility_status_popover/core.cljs
> +(ns status-im.visibility-status-popover.core
I'm not sure if it is worth it to use a separate overlay for this, probably better to just use absolute layout

2021-10-20 10:35 UTC, Parveshdhull commented on src/status_im/constants.cljs
> +(def ^:const visibility-status-inactive 4)
Hi @flexsurfer, [originally](https://github.com/status-im/status-react/pull/12706), I had invisible. But that created conflicts with the desktop's [designs](https://www.figma.com/file/IPpvkpDWabBKJTeo6bFop0/Kuba%E2%8E%9CDesktop?node-id=77%3A19108).

2021-10-20 10:36 UTC, Parveshdhull commented on src/status_im/data_store/settings.cljs
> +      (update :current-user-status status-updates/<-rpc)))
`user-online-status` will also create some confusion because there is also a status type as online. I will use `visibility-status-updates` instead of plain `status-updates` 👍

2021-10-20 10:36 UTC, Parveshdhull commented on src/status_im/visibility_status_popover/core.cljs
> +(ns status-im.visibility-status-popover.core
I tried with the absolute layout too, but I was unable to make it the same as [designs](https://www.figma.com/file/TNCyHKtR3sx5EL6YznFWUa4O/Profile?node-id=7253%3A27195). The design requires a full overlay which also closes this on touch.

2021-10-20 10:38 UTC, flexsurfer commented on src/status_im/visibility_status_popover/core.cljs
> +(ns status-im.visibility-status-popover.core
ok, thanks

2021-10-20 10:39 UTC, flexsurfer commented on src/status_im/constants.cljs
> +(def ^:const visibility-status-inactive 4)
I'm more interested in the UX, by default I would expect that my status is not propagated, is that the case ?

2021-10-20 12:53 UTC, du82 commented on src/status_im/data_store/settings.cljs
> +      (update :current-user-status status-updates/<-rpc)))
> we have status tab. so probably we should use something like `user-online-status` or smth

I think we should rename the Status tab to "Moments" because it's more in line with WeChat, and it's less confusing to have a Status tab in the Status app.

2021-10-21 21:47 UTC, Parveshdhull commented
New Changes:
- Added syncing functionality - [Code](https://github.com/status-im/status-react/pull/12716/files#diff-44579badd82775c385690432066be20672d359b6c15a9b305ccbc42794506dfe) - L157
- Offline Status Updates - [Code](https://github.com/status-im/status-react/pull/12716/files#diff-44579badd82775c385690432066be20672d359b6c15a9b305ccbc42794506dfe) - L138
- `status-update(s)` changed to `visibility-status-update(s)` except for some 3-4 occurrence related to status-go calls. They are currently also used by desktop
- Fixed minor design bugs

2021-10-22 10:06 UTC, qoqobolo commented
@Parveshdhull thanks for your work!


### ISSUE 1: The screen shifts down when pressing the `Online status` button on iOS

https://user-images.githubusercontent.com/67952253/138434694-6a289b92-dbaf-4339-88f6-9c3ecb42b133.mp4

### ISSUE 2: According to the [feature request description](https://github.com/status-im/status-react/issues/12547) the default status should be `Invisible` (`Inactive`)

The current default status is `Automatic`. 
Please, let me know if this requirement has been changed.

2021-10-22 10:14 UTC, Parveshdhull commented
Hi @qoqobolo, I will check why ios behaving like this, but yes default settings is changed, you can find more details in this [conversation](https://discord.com/channels/624205794384281629/697843216048717905/898490235040710677)

2021-10-22 10:30 UTC, status-im-auto commented
## 59% of end-end tests have passed
```
Total executed tests: 69
Failed tests: 28
Passed tests: 41
```
```
IDs of failed tests: 6305,5502,5315,5390,5387,6328,5758,6645,6226,5689,5403,6253,5782,5356,5341,6633,5309,5783,5394,6279,5419,6263,5346,5332,6249,6240,5381,6283 
```
<h3>Failed tests (28)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/end-to-end-tests/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&APK_NAME=12716.apk&PR_ID=12716&TR_CASE_IDS=6305,5502,5315,5390,5387,6328,5758,6645,6226,5689,5403,6253,5782,5356,5341,6633,5309,5783,5394,6279,5419,6263,5346,5332,6249,6240,5381,6283">Rerun tests</a></li><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2334685">test_image_in_one_to_one_send_save_reply_timeline</a>, id: 6305 </b></td></tr><tr><td><p><blockquote><div>Device 2: Button element not found </div><div>Device 2: *Find ViewProfileButton by xpath:* `//*[@text="View profile"]` </div></blockquote></p><code> Device 2: ViewProfileButton by xpath: `//*[@text="View profile"]` is not found on the screen</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/c6df357eadd94ec5b3c90ed761c0035c?auth=f49f731bf972e097f7295970f53c831e">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/c6df357eadd94ec5b3c90ed761c0035c/0035screenshot.png?auth=f49f731bf972e097f7295970f53c831e">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/dda2c3cc54d043a0bb321eb521471f1a?auth=339a0ebbd0f43e6c4fa9371eeebde202">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/dda2c3cc54d043a0bb321eb521471f1a/0024screenshot.png?auth=339a0ebbd0f43e6c4fa9371eeebde202">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2334656">test_can_add_existing_ens_on_mainnet</a>, id: 5502 </b></td></tr><tr><td><p><blockquote><div>Device 1: **Sign in** (password:qwerty, keycard:False) </div><div>Device 1: *Find EditBox by accessibility id:* `password-input` </div></blockquote></p><code> Device 1: EditBox by accessibility id: `password-input` is not found on the screen; also Unexpected Alert is shown: 'Please shake the phone to report this error and restart the app. multiaccount is currently empty, which means something went wrong when t</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/a50dd82e46a149cb9794c0fbe568e1df?auth=2afbc92eb2dc27f19340e23e1f231cb4">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/a50dd82e46a149cb9794c0fbe568e1df/0022screenshot.png?auth=2afbc92eb2dc27f19340e23e1f231cb4">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2334632">test_send_non_english_message_to_newly_added_contact_on_different_networks</a>, id: 5315 </b></td></tr><tr><td><p><blockquote><div>Device 1: **Sign in** (password:qwerty, keycard:False) </div><div>Device 1: *Find EditBox by accessibility id:* `password-input` </div></blockquote></p><code> Device 1: EditBox by accessibility id: `password-input` is not found on the screen; also Unexpected Alert is shown: 'Please shake the phone to report this error and restart the app. multiaccount is currently empty, which means something went wrong when t</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/1001e605cdc84221b249373bf038c41a?auth=42031d29f65c9b18075f2739785ff4d0">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/1001e605cdc84221b249373bf038c41a/0018screenshot.png?auth=42031d29f65c9b18075f2739785ff4d0">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/64a66b4747c846149212e776f0796dfd?auth=eaddbd2e8c0e7a60f87466845e3c4afe">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/64a66b4747c846149212e776f0796dfd/0011screenshot.png?auth=eaddbd2e8c0e7a60f87466845e3c4afe">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2334650">test_delete_close_all_tabs</a>, id: 5390 </b></td></tr><tr><td><p><blockquote><div>Device 1: **Sign in** (password:qwerty, keycard:False) </div><div>Device 1: *Find EditBox by accessibility id:* `password-input` </div></blockquote></p><code> Device 1: EditBox by accessibility id: `password-input` is not found on the screen; also Unexpected Alert is shown: 'Please shake the phone to report this error and restart the app. multiaccount is currently empty, which means something went wrong when t</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/de2d9bd3dde94a44a758d29786807538?auth=0aace4c5451000498cf56c0aa01d531e">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/de2d9bd3dde94a44a758d29786807538/0031screenshot.png?auth=0aace4c5451000498cf56c0aa01d531e">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2334649">test_delete_chats_via_delete_button_rejoin</a>, id: 5387 </b></td></tr><tr><td><p><blockquote><div>Device 1: Button element not found </div><div>Device 1: *Find Button by xpath:* `//*[@text="Delete chat"]` </div></blockquote></p><code> Device 1: Button by xpath: `//*[@text="Delete chat"]` is not found on the screen</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/5750eef8ea4a46c8b5b502ee9a7602e5?auth=62ef3404bdd1af20cdcb3063e4dcc5be">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/5750eef8ea4a46c8b5b502ee9a7602e5/0042screenshot.png?auth=62ef3404bdd1af20cdcb3063e4dcc5be">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>6. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2334688">test_send_transaction_set_recipient_options</a>, id: 6328 </b></td></tr><tr><td><p><blockquote><div>Device 1: **Setting nickname:my_some_nickname** </div><div>Device 1: *Find Button by accessibility id:* `profile-nickname-item` </div></blockquote></p><code> Device 1: Button by accessibility id: `profile-nickname-item` is not found on the screen</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/19f407937ea640e8820f59ea88b20f41?auth=acfe071053aa2b7f694169adf97fed51">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/19f407937ea640e8820f59ea88b20f41/0025screenshot.png?auth=acfe071053aa2b7f694169adf97fed51">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>7. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2334660">test_keycard_can_recover_keycard_account_card_pairing</a>, id: 5758 </b></td></tr><tr><td><p><blockquote><div>Device 1: ========================================================================= </div><div>Device 1: **Sign in** (password:qwerty, keycard:True) </div></blockquote></p><code> Device 1: SilentButton by accessibility id:`numpad-button-1` is not found on the screen; also Unexpected Alert is shown: 'Please shake the phone to report this error and restart the app. multiaccount is currently empty, which means something went wrong w</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/0d2eb22e450644d6a7ae51efeb8c13a5?auth=ad3ad236451503588fab61c5c45c3ae4">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/0d2eb22e450644d6a7ae51efeb8c13a5/0027screenshot.png?auth=ad3ad236451503588fab61c5c45c3ae4">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>8. <a href="https://ethstatus.testrail.net/index.php [...]

2021-10-22 11:04 UTC, qoqobolo commented
@Parveshdhull 

### ISSUE 3: Error when switching to Mainnet 
**Steps:**
1. Create multiaccount
2. Advanced > Network > Mainnet > Confirm

**OS**: Android, iOS

Caught by autotests. Take a look, please.

<img width="305" alt="Screenshot 2021-10-22 at 13 02 24" src="https://user-images.githubusercontent.com/67952253/138443395-80dd862f-8912-4138-bd65-ee78c4d6b9b5.png">

2021-10-22 11:18 UTC, flexsurfer requested changes

2021-10-22 11:18 UTC, flexsurfer commented on src/status_im/data_store/settings.cljs
> +      (update :current-user-status visibility-status-updates/<-rpc)))
:current-user-**visibility**-status ?

2021-10-22 11:18 UTC, flexsurfer commented on src/status_im/ui/screens/profile/visibility_status/styles.cljs
> +(def color-error "#FA6565")
should we move this to color ns ?

2021-10-22 11:18 UTC, flexsurfer commented on src/status_im/ui/screens/profile/visibility_status/styles.cljs
> +   :align-self             "flex-start"
better to use keywords :flex-start

2021-10-22 11:18 UTC, flexsurfer commented on src/status_im/ui/screens/profile/visibility_status/styles.cljs
> +   :border-color     "#FFFFFF"})
colors/white

2021-10-22 11:18 UTC, flexsurfer commented on src/status_im/visibility_status_updates/core.cljs
> +                {:visibility-status-updates {}}
why dont just have {} here ? why do you need `:visibility-status-updates` key ?

2021-10-22 11:18 UTC, flexsurfer commented on src/status_im/visibility_status_updates/core.cljs
> +        (reduce (fn [prev-map visibility-status-update-loaded]
usually prev-map named as `acc` - accumulator

2021-10-22 11:18 UTC, flexsurfer commented on src/status_im/visibility_status_updates/core.cljs
> +    (when (or
dont you need to return prev-map for else case ?

2021-10-22 11:18 UTC, flexsurfer commented on src/status_im/visibility_status_updates/core.cljs
> +  (visibility-status-updates-store/fetch-visibility-status-updates-rpc
why not call this method directly ?

2021-10-22 11:18 UTC, flexsurfer commented on src/status_im/visibility_status_updates/core.cljs
> +        events-to-dispatch-later (atom [])]
this doesn't look clojure idiomatic, whats the point of using atom here ?

2021-10-22 11:18 UTC, flexsurfer commented on src/status_im/visibility_status_updates/core.cljs
> +  {:dispatch-later
what is the point of having dispach-later inside dispatch?

2021-10-22 11:18 UTC, flexsurfer commented on src/status_im/visibility_status_updates/core.cljs
> +       [{:ms 100
why dispatch-later and magic numbers 100 and 1000 ?

2021-10-22 11:34 UTC, Parveshdhull commented on src/status_im/ui/screens/profile/visibility_status/styles.cljs
> +   :border-color     "#FFFFFF"})
Hi, can you please take a look at colors.cljs. It has the same value for white and white-persist and there is no pure white. That's why I hard-coded this value.

2021-10-22 11:40 UTC, Parveshdhull commented on src/status_im/visibility_status_updates/core.cljs
> +  (visibility-status-updates-store/fetch-visibility-status-updates-rpc
I was trying to keep `login/core.cljs` clean and use the same pattern used earlier, for ex.  `(contact/initialize-contacts)`

2021-10-22 11:49 UTC, flexsurfer commented on src/status_im/ui/screens/profile/visibility_status/styles.cljs
> +   :border-color     "#FFFFFF"})
what do you mean pure white ?

2021-10-22 11:53 UTC, Parveshdhull commented on src/status_im/ui/screens/profile/visibility_status/styles.cljs
> +   :border-color     "#FFFFFF"})
Pure White - #FFFFFF
current white is not actually white, it is changing based on theme

2021-10-22 11:58 UTC, Parveshdhull commented on src/status_im/visibility_status_updates/core.cljs
> +       [{:ms 100
I think the first dispatch-later can be changed into dispatch but the second one is stopping broadcasts once the current status is broadcast-ed. 1000 was just a safety net, can be changed into 100 or something I guess 🤔

2021-10-22 12:02 UTC, flexsurfer commented on src/status_im/ui/screens/profile/visibility_status/styles.cljs
> +   :border-color     "#FFFFFF"})
if you want white for both dark and light use white-persist  then

2021-10-22 12:07 UTC, Parveshdhull commented on src/status_im/ui/screens/profile/visibility_status/styles.cljs
> +   :border-color     "#FFFFFF"})
Oh sorry, I was confused between theme and light theme. I will user colors/white, instead of hard coding 👍

2021-10-22 12:08 UTC, Parveshdhull commented on src/status_im/ui/screens/profile/visibility_status/styles.cljs
> +   :border-color     "#FFFFFF"})
still it is little weird that white and white-persist are exactly same

2021-10-22 12:36 UTC, Parveshdhull commented on src/status_im/visibility_status_updates/core.cljs
> +  (visibility-status-updates-store/fetch-visibility-status-updates-rpc
Now as I think, accessing directly also looks great 🤔, will change this too 👍 Thanks

2021-10-25 00:51 UTC, Parveshdhull commented
Hi @qoqobolo , Thank you very much for testing PR 🙏.
I fixed the above issues and also added another functionality.
`Sort community members & contacts based on online status and name`
Please let me know if I can improve anything else. Thanks

2021-10-25 01:04 UTC, status-im-auto commented
## 94% of end-end tests have passed
```
Total executed tests: 69
Failed tests: 4
Passed tests: 65
```
```
IDs of failed tests: 6226,5762,6253,6283 
```
<h3>Failed tests (4)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/end-to-end-tests/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&APK_NAME=12716.apk&PR_ID=12716&TR_CASE_IDS=6226,5762,6253,6283">Rerun tests</a></li><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2335343">test_ens_mentions_pn_and_nickname_in_public_and_1_1_chats</a>, id: 6226 </b></td></tr><tr><td><p><blockquote><div>Device 1: **Recover access(password:qwerty, keycard:False)** </div><div>Device 1: Find 'Button' by 'xpath': `//android.widget.CheckBox[@content-desc='checkbox']` </div></blockquote></p><code> Device 1: Button by xpath: `//android.widget.CheckBox[@content-desc='checkbox']` is not found on the screen</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/fd5d64a563b347ad8ef5d907c3e2d2fe?auth=8404d800ee6d1a299237b58563ab93cb">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/fd5d64a563b347ad8ef5d907c3e2d2fe/0001screenshot.png?auth=8404d800ee6d1a299237b58563ab93cb">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/00c3c4fb4bac47828aea1db5d26e0a07?auth=575d7c1aca0587c581693b3f9bf3a8a6">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/00c3c4fb4bac47828aea1db5d26e0a07/0001screenshot.png?auth=575d7c1aca0587c581693b3f9bf3a8a6">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2335336">test_pair_devices_sync_one_to_one_contacts_nicknames_public_chat</a>, id: 5762 </b></td></tr><tr><td><p><blockquote><div>Device 1: ## Looking for chat: 'after-pairing' </div><div>Device 1: Wait for element 'Button' for max 30s and click when it is available </div></blockquote></p><code> Device 1: Button by accessibility id:`notifications-unread-badge` is not found on the screen</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/b49ee7457f024f86bc153fd4d0a6fcad?auth=f99e354f3e2de4ef4853f2ae949802f5">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/b49ee7457f024f86bc153fd4d0a6fcad/0107screenshot.png?auth=f99e354f3e2de4ef4853f2ae949802f5">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/050542fe42654eeb89e10decb9180c26?auth=7a62359ff3b003cb798034efd2204620">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/050542fe42654eeb89e10decb9180c26/0042screenshot.png?auth=7a62359ff3b003cb798034efd2204620">Failure screenshot</a></li></ul></p><p>Device 3:<ul><li><a href="https://saucelabs.com/jobs/44bcd1978711435b958e1b2076c4afb8?auth=fc3b629696e9148b78fc93933cf43307">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/44bcd1978711435b958e1b2076c4afb8/0017screenshot.png?auth=fc3b629696e9148b78fc93933cf43307">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2335350">test_send_eth_in_1_1_chat_transaction_push</a>, id: 6253 </b></td></tr><tr><td><p><blockquote><div>Device 1: Find 'ProfileButton' by 'xpath': `//*[contains(@content-desc,'5 out of 5')]` </div><div>Device 1: Find 'Button' by 'accessibility id': `notifications-settings-button` </div></blockquote></p><code> Device 1: Button by accessibility id: `notifications-settings-button` is not found on the screen</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/1f3e16805b1c4f3baea5e1b5c54d0c9a?auth=5bd00a53eacfb20a5b0c292637e40bdc">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/1f3e16805b1c4f3baea5e1b5c54d0c9a/0016screenshot.png?auth=5bd00a53eacfb20a5b0c292637e40bdc">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/362d3e843da54e61b27c744e6f84aa92?auth=510abddee91a73da9fc66cf28022d68c">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/362d3e843da54e61b27c744e6f84aa92/0011screenshot.png?auth=510abddee91a73da9fc66cf28022d68c">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2335355">test_push_notification_1_1_chat_no_pn_activity_center</a>, id: 6283 </b></td></tr><tr><td><p><blockquote><div>Device 1: 'Text' is 'Back Careful Zigzagsalamander' </div><div>Device 1: Find 'Button' by 'accessibility id': `notifications-settings-button` </div></blockquote></p><code> Device 1: Button by accessibility id: `notifications-settings-button` is not found on the screen</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/8fb89e5db4ed4687b170d38c11fd2c81?auth=59e5fac50e1ecd70fd1b23644b1dcc71">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/8fb89e5db4ed4687b170d38c11fd2c81/0012screenshot.png?auth=59e5fac50e1ecd70fd1b23644b1dcc71">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/eb60a291ef9a45b688f35efd9686e420?auth=42a1aaa1ff23c8513f8c9e206272d180">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/eb60a291ef9a45b688f35efd9686e420/0011screenshot.png?auth=42a1aaa1ff23c8513f8c9e206272d180">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table></details><h3>Passed tests (65)</h3><details><summary>Click to expand</summary><br/><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2335360">test_image_in_one_to_one_send_save_reply_timeline</a>, id: 6305 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/b6da07136a9a4911a176dd90770b7695?auth=71d6fda7e4072cf74a01bd359a6126fa">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/d3c62c1448b649d184c4e924424cde67?auth=52e92d2befc07cf65d769b27a412c51a">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2335342">test_add_account_to_multiaccount_instance_generate_new</a>, id: 6224 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/4185875f87fe47eeb50d3242472187d7?auth=69523ecd2456f9f3462cc61ed06d95f9">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2335331">test_can_add_existing_ens_on_mainnet</a>, id: 5502 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/2a4e3c5caadc4566b848dcf458531330?auth=e0c80da2b607d9ffffce492f23af1937">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2335357">test_keycard_can_see_all_transactions_in_history</a>, id: 6291 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/713d23b971e64d1eae5038bd8d25141f?auth=7c4d70d73f607c4fcd68a12824dbf5fd">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2335314">test_sign_message_and_2tx_in_batch_and_transactions_filters_from_daap</a>, id: 5342 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/575efe8d2af5475a8cc9ea33a83da95c?auth=8c3fc9afb8ca2ccc252488376b7633be"> [...]

2021-10-25 01:31 UTC, status-im-auto commented
## 25% of end-end tests have passed
```
Total executed tests: 4
Failed tests: 3
Passed tests: 1
```
```
IDs of failed tests: 6283,6253,5762 
```
<h3>Failed tests (3)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/end-to-end-tests/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&APK_NAME=12716.apk&PR_ID=12716&TR_CASE_IDS=6283,6253,5762">Rerun tests</a></li><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2335429">test_push_notification_1_1_chat_no_pn_activity_center</a>, id: 6283 </b></td></tr><tr><td><p><blockquote><div>Device 1: 'Text' is 'Ethical Ample Narwhale' </div><div>Device 1: Find 'Button' by 'accessibility id': `notifications-settings-button` </div></blockquote></p><code> Device 1: Button by accessibility id: `notifications-settings-button` is not found on the screen</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/676b97a2f5224140b417a680f7be0e16?auth=3f0b84e2e2a514f76ec89614fc860c38">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/676b97a2f5224140b417a680f7be0e16/0012screenshot.png?auth=3f0b84e2e2a514f76ec89614fc860c38">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/9ab84cc148bf43f195172f27f7299424?auth=c3f0394967c938638a13decbc1632e8c">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/9ab84cc148bf43f195172f27f7299424/0011screenshot.png?auth=c3f0394967c938638a13decbc1632e8c">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2335428">test_send_eth_in_1_1_chat_transaction_push</a>, id: 6253 </b></td></tr><tr><td><p><blockquote><div>Device 1: Find 'ProfileButton' by 'xpath': `//*[contains(@content-desc,'5 out of 5')]` </div><div>Device 1: Find 'Button' by 'accessibility id': `notifications-settings-button` </div></blockquote></p><code> Device 1: Button by accessibility id: `notifications-settings-button` is not found on the screen</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/443c356d780d4c35b2b8f4f89eabe27e?auth=a14215eaac396624fb4cf5f6b083d7b4">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/443c356d780d4c35b2b8f4f89eabe27e/0016screenshot.png?auth=a14215eaac396624fb4cf5f6b083d7b4">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/c2b74125e6b1419185b856adc9e36026?auth=b443e0d35de897f5dade293a5a9e472d">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/c2b74125e6b1419185b856adc9e36026/0011screenshot.png?auth=b443e0d35de897f5dade293a5a9e472d">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2335426">test_pair_devices_sync_one_to_one_contacts_nicknames_public_chat</a>, id: 5762 </b></td></tr><tr><td><p><blockquote><div>Device 1: ## Looking for chat: 'after-pairing' </div><div>Device 1: Wait for element 'Button' for max 30s and click when it is available </div></blockquote></p><code> Device 1: Button by accessibility id:`notifications-unread-badge` is not found on the screen</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/17ff1979c5b74709a545aed479b18ca9?auth=9c6ec82bfda3e7a3c2346725c53bfac6">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/17ff1979c5b74709a545aed479b18ca9/0107screenshot.png?auth=9c6ec82bfda3e7a3c2346725c53bfac6">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/b32a1f242708461883ac570a3c69af80?auth=a36c50ce178af409e2d635e0da4d1aea">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/b32a1f242708461883ac570a3c69af80/0042screenshot.png?auth=a36c50ce178af409e2d635e0da4d1aea">Failure screenshot</a></li></ul></p><p>Device 3:<ul><li><a href="https://saucelabs.com/jobs/f7f33541e9d94d0dafacec2392bcd975?auth=650b11748b9d6b48fedf7df636de6e35">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/f7f33541e9d94d0dafacec2392bcd975/0017screenshot.png?auth=650b11748b9d6b48fedf7df636de6e35">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table></details><h3>Passed tests (1)</h3><details><summary>Click to expand</summary><br/><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2335427">test_ens_mentions_pn_and_nickname_in_public_and_1_1_chats</a>, id: 6226 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/418070e7b202486c9fb569b2ebe63d24?auth=f9a7e4f7d9576245b8bfe39f483ae56f">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/c9f76da50b7f4ac18813e998e2ace9bd?auth=aabb3890e1aa83aef9921ca7c2a4557b">Steps, video, logs</a></li></ul></p></ul></p></td></tr></tbody></table></details>

2021-10-25 11:32 UTC, flexsurfer commented on src/status_im/data_store/settings.cljs
> +      (visibility-status-updates/<-rpc-settings)))
why is it different from others ? i mean why not `update`

2021-10-25 11:32 UTC, flexsurfer commented on src/status_im/ui/screens/contacts_list/views.cljs
> +(defn sorted-contacts-list [contacts]
its better to create a new subscription, views must be dumb

2021-10-25 11:32 UTC, flexsurfer commented on src/status_im/ui/screens/communities/members.cljs
> +(defn sorted-members-list [members]
better to move to subscriptions

2021-10-25 11:32 UTC, flexsurfer commented on src/status_im/ui/screens/communities/members.cljs
> +  (<sub [:contacts/contact-name-by-identity (get member 0)]))
this looks not correct, better to have one subscription

2021-10-25 11:32 UTC, flexsurfer commented on src/status_im/visibility_status_updates/core.cljs
> +      (assoc :dispatch-later
why not update ?

2021-10-25 11:32 UTC, flexsurfer commented on src/status_im/visibility_status_updates/core.cljs
> +      (assoc :dispatch-later
and still not sure why dispatch-later is used here ?

2021-10-25 11:32 UTC, flexsurfer commented on src/status_im/visibility_status_updates/core.cljs
> +      {:dispatch [:visibility-status-updates/update-visibility-status status-type]
can't we use update-visibility-status handler here instead of dispatch?

2021-10-25 11:56 UTC, Parveshdhull commented on src/status_im/data_store/settings.cljs
> +      (visibility-status-updates/<-rpc-settings)))
Hi, data from go is returned as

``` 
-current-user-status
	- statusType
	- clock
```

I can use update as `(update :current-user-status visibility-status-updates/<-rpc)`, but that will only change `statusType` into `status-type`
I also want to change key `current-user-status` into `current-user-visibility-status` and `<-rpc-settings` does both those things in one call

2021-10-25 11:57 UTC, Parveshdhull commented on src/status_im/visibility_status_updates/core.cljs
> +      (assoc :dispatch-later
1. assoc is used because dispatch-later is initially nil and update will through error
2. User is online for 5 minutes, dispatch-later is used to make him/her offline after 5 minutes

2021-10-25 12:02 UTC, flexsurfer commented on src/status_im/visibility_status_updates/core.cljs
> +      (assoc :dispatch-later
1. clojure doesn't through errors ;) it will work fine even if dispatch-later  is nil
2. hm now its even more confusing, could you please elaborate

2021-10-25 12:08 UTC, Parveshdhull commented on src/status_im/visibility_status_updates/core.cljs
> +      (assoc :dispatch-later
I also tried just checking if the online status is 5 minutes old directly on view, that works great, but the view doesn't re-render after 5 minutes, So I need to use dispatch-later to expire that status.

2021-10-25 12:18 UTC, Parveshdhull commented on src/status_im/visibility_status_updates/core.cljs
> +      (assoc :dispatch-later
Sure,
There are 3 status types
1. **Inactive** - User will always displayed as offline, and no ping is received - _Anonymous_
2. **Always Online** - User will always displayed as online, and online ping is received every 5 minutes (when sender is online) - _Pseudo Anonymous_
3. **Automatic** - User will only be shown online if there is a online ping in last 5 minutes, otherwise offline

So for `automatic`, to make sure the user is online or not, I have to make sure if ping received with the clock is in last 5 minutes, and I have to convert that status into offline, after whatever time is left between `now` and `received clock`

2021-10-25 12:31 UTC, Parveshdhull commented on src/status_im/visibility_status_updates/core.cljs
> +      (assoc :dispatch-later
Yes it is confusing :D, you can find more details in [specs](https://github.com/status-im/status-go/pull/2408)

2021-10-25 13:29 UTC, flexsurfer commented on src/status_im/visibility_status_updates/core.cljs
> +      (assoc :dispatch-later
does that mean that for every process-visibility-status-update you 'll create a new dispatch later ? but you probably need to remove old dispatches ?

2021-10-25 13:39 UTC, Parveshdhull commented on src/status_im/visibility_status_updates/core.cljs
> +      (assoc :dispatch-later
Actually, another user is broadcasting at the rate of 5 minutes and this is dispatch-later for 5.05 minutes. So there will not be much issue of having many pending dispatch-laters because this one will expire whenever new will receive.

And also this dispatch checks clock of current status update before converting it into offline. If a new status is received, then it will not do anything.

So in a way there is only one dispatch-later per user, that keeps getting renewed every 5 minutes if another user is online and destroys after one run if he/she is not

Also dispatch-later will not be registered for inactive users, always online, and expired automatic. So it will only be registered for a fraction of user's, who are online at that moment.

2021-10-26 06:47 UTC, flexsurfer commented on src/status_im/subs.cljs
> +                   @(re-frame/subscribe
unfortunately, this won't work properly, we have to create a new subscription :contacts/contact-names-by-identitis

2021-10-26 08:54 UTC, status-im-auto commented
## 100% of end-end tests have passed
```
Total executed tests: 2
Failed tests: 0
Passed tests: 2
```
<h3>Passed tests (2)</h3><details><summary>Click to expand</summary><br/><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2338607">test_push_notification_1_1_chat_no_pn_activity_center</a>, id: 6283 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/e7033e70f8214880b0cbbe3eacc13a73?auth=83d55382de1463d9e47fe2d2b86e2d80">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/74db93dd46754b128283516ad2b0a69e?auth=97efef0fb1273a92636311ef16a9b507">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2338606">test_send_eth_in_1_1_chat_transaction_push</a>, id: 6253 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/0c93bfc4bd854e2f867c712e765f90d0?auth=b3ae0e83bade2ae49861ce13b58f2d5c">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/57509cf8102f4b58872fad359e7ec1c7?auth=c5b0d03dc646fe6283f45257c83148bc">Steps, video, logs</a></li></ul></p></ul></p></td></tr></tbody></table></details>

2021-10-27 05:36 UTC, flexsurfer commented on src/status_im/subs.cljs
> +                  [:contacts/contact-names-by-identities (keys @members)])]
:communities/community-members should be inside contact-names-by-identities

2021-10-27 05:37 UTC, flexsurfer commented on src/status_im/subs.cljs
> +                  [:contacts/contact-names-by-identities (keys @members)])]
or you don't need contact-names-by-identities then you could move its code here

2021-10-27 09:12 UTC, Parveshdhull commented on src/status_im/subs.cljs
> +                  [:contacts/contact-names-by-identities (keys @members)])]
Yes, better to remove `contact-names-by-identities`, because this function also requires members

2021-10-28 14:15 UTC, flexsurfer commented on src/status_im/subs.cljs
> +         names        (atom
why this reduce here with atom but not in the subscription function?

2021-10-28 14:38 UTC, flexsurfer approved these changes

2021-10-28 14:38 UTC, flexsurfer commented
Great job!

2021-10-29 09:34 UTC, status-im-auto commented
## 99% of end-end tests have passed
```
Total executed tests: 69
Failed tests: 1
Passed tests: 68
```
```
IDs of failed tests: 6251 
```
<h3>Failed tests (1)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/end-to-end-tests/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&APK_NAME=12716.apk&PR_ID=12716&TR_CASE_IDS=6251">Rerun tests</a></li><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2340738">test_keycard_sign_message_and_transactions_from_daap</a>, id: 6251 </b></td></tr><tr><td><p><blockquote><div>Device 1: SilentButton element not found </div><div>Device 1: Enter default pin 111111 </div></blockquote></p><code> Device 1: 'SilentButton' by accessibility id:'numpad-button-1' not found on the screen</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/7982427db5864cf99811c7397679a169?auth=a94b57a2d3032fccf3f1e94571929089">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/7982427db5864cf99811c7397679a169/0050screenshot.png?auth=a94b57a2d3032fccf3f1e94571929089">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table></details><h3>Passed tests (68)</h3><details><summary>Click to expand</summary><br/><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2340749">test_image_in_one_to_one_send_save_reply_timeline</a>, id: 6305 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/b914b088bfa54d4fa4ff79466377e88e?auth=fa0aff4b5554cab824c6609890c76daa">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/acdb99578c32439eb57e34e79c429da6?auth=68d64fd66c1003a0bae330879d275103">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2340731">test_add_account_to_multiaccount_instance_generate_new</a>, id: 6224 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/e0ffa5b2f532436d8ea7d26fd77c6354?auth=176f53d213dbfdad573de93e88fdfb33">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2340720">test_can_add_existing_ens_on_mainnet</a>, id: 5502 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/d9529b9ed96842cb9b2689bc89ab98dd?auth=fdac5fb24679424343c7c6011aa27157">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2340746">test_keycard_can_see_all_transactions_in_history</a>, id: 6291 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/e5415c305c494948a55fc270147abff6?auth=eda561bed36d8d57fccbf35b14b73678">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2340703">test_sign_message_and_2tx_in_batch_and_transactions_filters_from_daap</a>, id: 5342 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/acce85623ccf498dabd8880e21622fa9?auth=200dcc9f18dcdf6a8f2a4e92c28c72f5">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>6. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2340736">test_add_and_delete_watch_only_account_to_multiaccount_instance</a>, id: 6244 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/c4d3e94d9c464755af3c3496986cff9d?auth=83efcf2a6a31d9d0ded38937c79064a0">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>7. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2340730">test_open_blocked_secure_not_secure_inlalid_offline_urls</a>, id: 6210 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/01bb4e19498b4c7ca5f091ba21727c93?auth=03c16698a54eed9f7f4672b074e25e18">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>8. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2340716">test_open_public_chat_using_deep_link</a>, id: 5396 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/113e7f0ae2b84e369bb43667d4ec9989?auth=60882e11ad6362cc96522ddce0395549">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>9. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2340689">test_offline_add_new_group_chat_member</a>, id: 3998 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/df156bc48084439898e2d6810029efc7?auth=d1de2bcf07d0526c41a5f724230a6608">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/a43ca116651c493987cce5b0f26b5880?auth=3fc3ef0e590158d1393b4ccee7ba62df">Steps, video, logs</a></li></ul></p><p>Device 3:<ul><li><a href="https://saucelabs.com/jobs/db7add082f8043f8814b377a2d66de4b?auth=388e4e5f13116ebd369cade93d466879">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>10. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2340696">test_send_non_english_message_to_newly_added_contact_on_different_networks</a>, id: 5315 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/0844afa166284ec4bfea893bd01050e5?auth=a06b0363cf30211bdb54d712d707d0d2">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/31534b6c9dd245a38f447a24a39c1f63?auth=eb67ef61a97ddd090c3e58fca51b3402">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>11. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2340695">test_can_see_balance_and_all_transactions_history_on_cellular</a>, id: 5314 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/93cf6c7838a7432a82a69ac80a049e8a?auth=64800b304ae5314678742d83fe089055">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>12. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2340718">test_insufficient_funds_wallet_positive_balance</a>, id: 5412 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/4928846384e344878820a9d4c32c6df0?auth=cd1be3a037b54a5f0e472c9d19614bef">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>13. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2340714">test_delete_close_all_tabs</a>, id: 5390 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/4cb007b0d2ce47deb3a39d420b7139d0?auth=9bc1d941e2b57a92e236b3612f301be3">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>14. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2340688">test_create_new_group_chat_messaging_pn_delivered</a>, id: 3994 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/45a2a3f9aa0b4536a94d807fa96964f9?auth=29cb567a58f8d55a6660521e81501873">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/092d3634070f4550aed0bfc9ca7e60e0?auth=cb5e440ce718ac33995dbba777ad2829">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>15. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2340705">test_send_token_with_7_decimals</a>, id: 5350 </b></td></tr><tr><td><ins>Device sessions</ [...]

2021-10-29 10:18 UTC, qoqobolo commented
@Parveshdhull Thank you for this awesome work!

There are two small design issues left

### ISSUE 4: Online indicator is duplicated when opened on Android
Can we have this drop-down menu in the way as on iOS? 
<img width="470" alt="Screenshot 2021-10-29 at 12 06 48" src="https://user-images.githubusercontent.com/67952253/139416972-fa17d43e-fa82-4c10-8c6c-5cef6a584fa1.png">

### ISSUE 5: The background of the drop-down menu blends in with the background of the screen in dark mode on iOS
It would be better to make the drop-down menu background a dark gray if possible

UPD: skipped, since the issue is only reproducible on 1 device (Google Pixel 2) out of 5.
<img width="470" alt="Screenshot 2021-10-29 at 12 07 08" src="https://user-images.githubusercontent.com/67952253/139417024-8a45b2b8-8d6f-4a84-8a79-67e41881086c.png">

2021-10-29 14:22 UTC, qoqobolo commented
@Parveshdhull another unexpected behavior found

### ISSUE 6: When a new message is received in 1-1 chat from a non-contacts user, the sender's online status remains `offline` until the recipient adds the sender to contacts or re-logs in

Sometimes, both users need to re-login in order for the sender's status to change to `Online`.


**Steps:**

UserA and UserB have default the `Automatic` status state
_UserA (sender)_:
- Start 1-1 chat with UserB
- Send a message

_UserB (receiver)_:
- Open the Activity center
- Open the 1-1 chat
- Send a message

**Expected behavior:** the online status of UserB is displayed as `Online` once the 1-1 chat is opened/some message is sent by UserB
**Actual behavior:** UserB's status remains `Offline`

https://user-images.githubusercontent.com/67952253/139449454-003e9b9f-6d4f-4631-af8a-646cf3892d07.mp4

**Logs:**
[geth.log](https://github.com/status-im/status-react/files/7442614/geth.log)
[Status.log](https://github.com/status-im/status-react/files/7442615/Status.log)

2021-10-29 16:20 UTC, qoqobolo commented
Update on ISSUE 6: the described behavior was found to be expected

Tested:
- on iOS and Android devices
- all the states
- offline status updates (with ~5 minutes delay, as expected)
- syncing between devices
- sort community members & contacts based on online status and name
- displaying status on different screens (1-1 chat, home screen, community members, contacts, user profile, activity center, blocked users)
- with PN background service enabled
- send messages with different options (while `Automatic`, `Always online`, `Inactive`)
- offline/cellular network
- dark mode

@Parveshdhull let's merge!

2021-10-29 16:25 UTC, merged