Add status-go tests
status-im/status-react pull request #13376
Opened 2022-05-19 15:56 UTC by cammellos

[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

If you submit PR for issue with bounty then write here Fixes #NN where NN is issue number

*otherwise*

fixes #...

### Summary

[comment]: # (Summarise the problem and how the pull request solves it)
...

Documentation change PR (review please): https://github.com/status-im/status.im/pull/xxx

### Review notes

### Testing notes

#### Platforms

- Android
- iOS
- macOS
- Linux
- Windows

#### Areas that maybe impacted

##### Functional

- 1-1 chats
- public chats
- group chats
- wallet / transactions
- dapps / app browsing
- account recovery
- new account
- user profile updates
- networks
- mailservers
- fleet
- bootnodes

##### Non-functional

- battery performance
- CPU performance / speed of the app
- network consumption

### Steps to test

- Open Status
- ...
- Step 3, etc.

status: ready

2022-05-19 16:05 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | 65be73f8 | [#1](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-13376/1/) | 2022-05-19 16:05:38 | ~8 min | `android-e2e` | [:page_facing_up:`log`](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-13376/1/consoleText) |

2022-05-20 09:13 UTC, jakubgs requested changes
Good stuff man.

2022-05-20 09:13 UTC, jakubgs commented on Makefile
> +	nix/scripts/build.sh targets.status-go.library
Why do this if you can just make this target depend on the library target?
```suggestion
test: status-go-library ##@test Run tests once in NodeJS
	nix/scripts/build.sh targets.status-go.library
```

2022-05-20 09:13 UTC, jakubgs commented on nix/status-go/library/default.nix
> +, goBuildFlags ? [ ]
You are receiving and passing `goBuildFlags` but not using them, is that intentional or did you remove too much?

2022-05-20 09:13 UTC, jakubgs commented on nix/status-go/library/default.nix
> +    export GO111MODULE=off
I don't think we need this setting here. Actually, I don't think we need this whole `preBuild` phase.

2022-05-20 09:13 UTC, jakubgs commented on nix/status-go/library/default.nix
> +    runHook renameImports
What is `renameImports`? I don't see it anywhere.

2022-05-20 09:13 UTC, jakubgs commented on nix/status-go/library/default.nix
> +  fixupPhase = ''
It doesn't seem like `fixupPhase` is necessary, as there is no references to Go path in the library:
```
post-installation fixup
find: 'remove-references-to': No such file or directory
```
We can check that manually:
```
 > strings /nix/store/d4ys954p76y5cxy7nqii4g4rifl8icd4-status-go-develop-a244d77/libstatus.a | grep '/nix/store/[a-z0-9]+-go'

```

2022-05-20 09:13 UTC, jakubgs commented on nix/status-go/library/default.nix
> +    ls $out/
Why is this here?

2022-05-20 09:13 UTC, jakubgs commented on nix/status-go/library/default.nix
> +    rm $out/main.go
Completely unnecessary. Nix builds in a sandbox, once build is over the sandbox is gone.

2022-05-20 09:13 UTC, jakubgs commented on nix/status-go/library/default.nix
> +    cd ${source.src} && go run ${source.src}/cmd/library/*.go > $out/main.go
Why are you putting `main.go` into `$out`? We don't need it there. If it's part of the build it should be under `/build`.

2022-05-20 09:13 UTC, jakubgs commented on nix/status-go/library/default.nix
> +    CGO_LDFLAGS = concatStringsSep " " ldFlags;
This has no effect. Variables set in a `let` block of a phase(or anything really) are available in the following block to be used, but __are not an env variables in the build__. To have that take effect you have to either:

* Define `CGO_LDFLAGS` in the main argument set for `buildGo116Package`.
* Use `export CGO_LDFLAGS=${CGO_LDFLAGS}` in the `buildPhase` or some other phase.

2022-05-20 09:13 UTC, jakubgs commented on nix/status-go/library/default.nix
> +  hardeningDisable = [ "fortify" ];
Pretty sure this is also unnecessary.

2022-05-20 09:13 UTC, jakubgs commented on nix/status-go/library/default.nix
> +in buildGo116Package {
We should probably switch to using `buildGo117Package`.

2022-05-20 09:13 UTC, jakubgs commented on nix/status-go/library/default.nix
> +  removeExpr = refs: ''remove-references-to ${concatMapStrings (ref: " -t ${ref}") refs}'';
If we don't run `fixupPhase` we don't need this either.

2022-05-20 09:20 UTC, jakubgs commented on nix/status-go/library/default.nix
> +    CGO_LDFLAGS = concatStringsSep " " ldFlags;
A proper way would look something like this:
```nix
{
  buildPhase = let
    ldFlags = [ "-extldflags=-Wl,--allow-multiple-definition" ]
      ++ lib.optionals (secretsFile != "") ["-X node.OpenseaKeyFromEnv=$OPENSEA_API_KEY"]
      ++ goBuildLdFlags;
  in ''
    runHook preBuild
    go build \
      -buildmode=c-archive \
      -ldflags="${concatStringsSep " " ldFlags}" \
      -o libstatus.a main.go
  '';
}
```

2022-05-21 10:39 UTC, jakubgs commented on nix/status-go/library/default.nix
> +    cd ${source.src} && go run ${source.src}/cmd/library/*.go > $out/main.go
Athough the more proper way is to use `NIX_BUILD_TOP` variable, as in :` > $NIX_BUILD_TOP/main.go`

2022-05-21 10:47 UTC, jakubgs commented on nix/status-go/library/default.nix
> +    cd ${source.src} && go run ${source.src}/cmd/library/*.go > $out/main.go
Also, this part should probably be moved to a `preBuild` hook:
```nix
{
  preBuild = ''
    pushd go/src/$goPackagePath
    go run cmd/library/*.go > $NIX_BUILD_TOP/main.go
    popd
  '';
}
```

2022-05-25 14:03 UTC, cammellos commented on nix/status-go/library/default.nix
> +, goBuildFlags ? [ ]
Not using them, removing

2022-05-25 15:38 UTC, jakubgs commented
I verified on a CI host that `make status-go-library` builds fine on MacOS without `nativeBuildInputs` and `preConfigure`.

2022-05-25 15:50 UTC, jakubgs approved these changes
Cool stuff.

2022-05-25 16:59 UTC, merged