Base chat dedesign
status-im/status-react pull request #13640
Opened 2022-07-07 16:12 UTC by briansztamfater

Context: Reverted #13184 on #13638.

Now resubmitting chat redesign changes to track and fix some issues before merging

Issues: https://github.com/status-im/status-react/pull/13184#issuecomment-1177340711

status: ready

2022-07-07 16:22 UTC, status-im-auto commented
### Jenkins Builds
<details>
<summary>Click to see older builds (22)</summary>

| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 538410ea | [#1](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-13640/1/) | 2022-07-07 16:22:13 | ~9 min | `android-e2e` | [:package:`apk`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-220707-161244-538410-pr13640-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-220707-161244-538410-pr13640-x86.apk)|
| :heavy_check_mark: | 538410ea | [#1](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-13640/1/) | 2022-07-07 16:22:22 | ~9 min | `android` | [:package:`apk`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-220707-161244-538410-pr13640-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-220707-161244-538410-pr13640-universal.apk)|
| :heavy_check_mark: | 538410ea | [#1](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-13640/1/) | 2022-07-07 16:27:25 | ~14 min | `ios` | [:package:`ipa`](https://i.diawi.com/HzJP4q) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2FHzJP4q)|
| | | | | | | |
| :heavy_check_mark: | e174adcc | [#2](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-13640/2/) | 2022-07-07 16:48:21 | ~9 min | `ios` | [:package:`ipa`](https://i.diawi.com/GyF3cd) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2FGyF3cd)|
| :heavy_check_mark: | e174adcc | [#2](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-13640/2/) | 2022-07-07 16:50:19 | ~11 min | `android-e2e` | [:package:`apk`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-220707-163824-e174ad-pr13640-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-220707-163824-e174ad-pr13640-x86.apk)|
| | | | | | | |
| :heavy_check_mark: | 96969533 | [#3](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-13640/3/) | 2022-07-07 16:55:34 | ~9 min | `android` | [:package:`apk`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-220707-164624-969695-pr13640-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-220707-164624-969695-pr13640-universal.apk)|
| :heavy_check_mark: | 96969533 | [#3](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-13640/3/) | 2022-07-07 16:56:47 | ~10 min | `ios` | [:package:`ipa`](https://i.diawi.com/Tk4LLd) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2FTk4LLd)|
| :heavy_check_mark: | 96969533 | [#3](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-13640/3/) | 2022-07-07 16:56:56 | ~10 min | `android-e2e` | [:package:`apk`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-220707-164624-969695-pr13640-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-220707-164624-969695-pr13640-x86.apk)|
| | | | | | | |
| :heavy_check_mark: | c4f34418 | [#4](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-13640/4/) | 2022-07-11 20:32:26 | ~10 min | `ios` | [:package:`ipa`](https://i.diawi.com/v7JgPs) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2Fv7JgPs)|
| :heavy_check_mark: | c4f34418 | [#4](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-13640/4/) | 2022-07-11 20:34:05 | ~11 min | `android-e2e` | [:package:`apk`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-220711-202222-c4f344-pr13640-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-220711-202222-c4f344-pr13640-x86.apk)|
| | | | | | | |
| :heavy_check_mark: | bf02622f | [#5](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-13640/5/) | 2022-07-11 20:56:12 | ~9 min | `android` | [:package:`apk`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-220711-204702-bf0262-pr13640-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-220711-204702-bf0262-pr13640-universal.apk)|
| :heavy_check_mark: | bf02622f | [#5](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-13640/5/) | 2022-07-11 20:56:20 | ~9 min | `android-e2e` | [:package:`apk`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-220711-204702-bf0262-pr13640-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-220711-204702-bf0262-pr13640-x86.apk)|
| :heavy_check_mark: | bf02622f | [#5](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-13640/5/) | 2022-07-11 20:57:00 | ~9 min | `ios` | [:package:`ipa`](https://i.diawi.com/1xeTJi) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2F1xeTJi)|
| | | | | | | |
| :x: | 06d2512f | [#6](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-13640/6/) | 2022-07-13 19:06:35 | ~14 sec | `ios` | [:page_facing_up:`log`](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-13640/6/consoleText) |
| :x: | 06d2512f | [#6](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-13640/6/) | 2022-07-13 19:06:37 | ~16 sec | `android` | [:page_facing_up:`log`](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-13640/6/consoleText) |
| :x: | 06d2512f | [#6](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-13640/6/) | 2022-07-13 19:06:45 | ~24 sec | `android-e2e` | [:page_facing_up:`log`](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-13640/6/consoleText) |
| | | | | | | |
| :x: | 6a4d561c | [#7](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-13640/7/) | 2022-07-13 19:27:56 | ~2 min | `ios` | [:page_facing_up:`log`](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-13640/7/consoleText) |
| :heavy_multiplication_x: | 6a4d561c | [#7](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-13640/7/) | 2022-07-13 19:34:16 | ~9 min | `android-e2e` | [:package:`apk`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-220713-192506-6a4d56-pr13640-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-220713-192506-6a4d56-pr13640-x86.apk)|
| :heavy_multiplication_x: | 6a4d561c | [#7](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-13640/7/) | 2022-07-13 19:36:34 | ~11 min | `android` | [:package:`apk`](https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-220713-192506-6a4d56-pr13640-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-220713-192506-6a4d56-pr13640-universal.apk)|
| | | | | | | |
| :heavy_check_mark: | 8f1140b6 | [#8](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-13640/8/) | 2022-07-13 [...]

2022-07-07 21:30 UTC, status-im-auto commented
## 90% of end-end tests have passed
```
Total executed tests: 183
Failed tests: 18
Passed tests: 165
Not executed tests: 3
```
```
IDs of not executed tests: 702266,702288,702133 
```
```
IDs of failed tests: 5453,702176,702287,702286,702360,702296,5358,702175,702196,702295,702281,702186,702164,702294,702194,702177,5766,702188 
```
<h3>Not executed tests (3)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-react/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&APK_NAME=https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-220707-164624-969695-pr13640-x86.apk&PR_ID=13640&TR_CASE_IDS=702266,702288,702133">Rerun not executed tests</a></li></details><h3>Failed tests (18)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-react/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&APK_NAME=https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-220707-164624-969695-pr13640-x86.apk&PR_ID=13640&TR_CASE_IDS=5453,702176,702287,702286,702360,702296,5358,702175,702196,702295,702281,702186,702164,702294,702194,702177,5766,702188">Rerun failed tests</a></li><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2912358">test_profile_privacy_policy_terms_of_use_node_version_need_help</a>, id: 5453 </b></td></tr><tr><td><p><blockquote><div>Device 1: Double tap on: ProfileButton </div><div>Device 1: Find `ProfileButton` by `xpath`: `//*[contains(@content-desc,'5 out of 5')]` </div></blockquote></p><code> Device 1: ProfileButton by xpath: `//*[contains(@content-desc,'5 out of 5')]` is not found on the screen</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/de8e6ff7b507471da29ade30bac1a771?auth=9cba20c830262efa0d9f9c8f8ed0b852">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/de8e6ff7b507471da29ade30bac1a771/0027screenshot.png?auth=9cba20c830262efa0d9f9c8f8ed0b852">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2912451">test_contact_block_unblock_public_chat_offline</a>, id: 702176 </b></td></tr><tr><td><code>Test setup failed:  An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up</code><br/><br/><p><b>Class: TestContactBlockMigrateKeycardMultipleSharedDevices</b></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2912498">test_profile_can_not_connect_to_custom_history_node_add_delete</a>, id: 702287 </b></td></tr><tr><td><p><blockquote><div>Device 1: Double tap on: ProfileButton </div><div>Device 1: Find `ProfileButton` by `xpath`: `//*[contains(@content-desc,'5 out of 5')]` </div></blockquote></p><code> Device 1: ProfileButton by xpath: `//*[contains(@content-desc,'5 out of 5')]` is not found on the screen </code><b>[[may be failed due to #13333]]</b><br/><br/><p><b>Class: TestTimelineHistoryNodesBootnodesMultipleDeviceMergedMedium</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/5eb5e0d200d34584b0f36b06e1e42755?auth=56ea9391384bc36787361dc07b424644#411">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/5eb5e0d200d34584b0f36b06e1e42755/0105screenshot.png?auth=56ea9391384bc36787361dc07b424644">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/35102b9808b94fa4b9568a90582c4c38?auth=f25248d3fffa39462ba01b6eb188d18c#252">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/35102b9808b94fa4b9568a90582c4c38/0056screenshot.png?auth=f25248d3fffa39462ba01b6eb188d18c">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2912497">test_profile_use_history_node_disable_enable</a>, id: 702286 </b></td></tr><tr><td><p><blockquote><div>Device 1: EditBox element not found </div><div>Device 1: Looking for a message by text: message from offline </div></blockquote></p><code> History was not fetched after enabling use_history_node</code><br/><br/><p><b>Class: TestTimelineHistoryNodesBootnodesMultipleDeviceMergedMedium</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/5eb5e0d200d34584b0f36b06e1e42755?auth=56ea9391384bc36787361dc07b424644#283">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/5eb5e0d200d34584b0f36b06e1e42755/0105screenshot.png?auth=56ea9391384bc36787361dc07b424644">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/35102b9808b94fa4b9568a90582c4c38?auth=f25248d3fffa39462ba01b6eb188d18c#232">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/35102b9808b94fa4b9568a90582c4c38/0056screenshot.png?auth=f25248d3fffa39462ba01b6eb188d18c">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2912523">test_collectibles_rinkeby_set_as_profile_image</a>, id: 702360 </b></td></tr><tr><td><p><blockquote><div>Device 1: Find `ProfileButton` by `xpath`: `//*[contains(@content-desc,'5 out of 5')]` </div><div>Device 1: Find `ProfilePictureElement` by `accessibility id`: `chat-icon` </div></blockquote></p><code> Collectible image is not set as profile image </code><b>[[flaky; on e2e builds when switching on rinkeby sometimes no collectibles]]</b><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/36f8e96186114df690ab811114449f9d?auth=b159d81e2aa70307d440ac7810c92294">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/36f8e96186114df690ab811114449f9d/0044screenshot.png?auth=b159d81e2aa70307d440ac7810c92294">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>6. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2912507">test_block_user_from_1_1_chat_header_check_mentions_and_push_notification_service</a>, id: 702296 </b></td></tr><tr><td><code>Test setup failed: E   http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:
 ('Connection aborted.', RemoteDisconnected('Remote end closed connection without res</code><br/><br/><p><b>Class: TestChatKeycardMentionsMediumMultipleDevice</b></p></td></tr><tr><td><b>7. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2912352">test_wallet_backup_recovery_phrase_warning_from_wallet</a>, id: 5358 </b></td></tr><tr><td><p><blockquote><div>Device 1: Tap on found: Button </div><div>Device 1: Find `RecoveryPhraseWordNumberText` by `xpath`: `//*[contains(@text,'#')]` </div></blockquote></p><code> Device 1: RecoveryPhraseWordNumberText by xpath: `//*[contains(@text,'#')]` is not found on the screen</code><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/0314393dfc6a48fd9b5319a51474135d?auth=2021bf44a648b416aaa7d5f712cc163f">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/0314393dfc6a48fd9b5319a51474135d/0024screenshot.png?auth=2021bf44a648b416aaa7d5f712cc163f">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>8. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2912450">test_contact_add_remove_mention_default_username_nickname_public_chat</a>, id: 702175 </b></td></tr><tr><td><code>Test setup failed:  An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up</code><br/><br/><p><b>Class: TestContactBlockMigrateKeycardMultipleSharedDevices</b>< [...]

2022-07-08 09:47 UTC, status-im-auto commented
## 67% of end-end tests have passed
```
Total executed tests: 18
Failed tests: 6
Passed tests: 12
```
```
IDs of failed tests: 702360,702196,702295,702281,702164,702194 
```
<h3>Failed tests (6)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-react/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&APK_NAME=https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-220707-164624-969695-pr13640-x86.apk&PR_ID=13640&TR_CASE_IDS=702360,702196,702295,702281,702164,702194">Rerun failed tests</a></li><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2914004">test_collectibles_rinkeby_set_as_profile_image</a>, id: 702360 </b></td></tr><tr><td><p><blockquote><div>Device 1: Find `ProfileButton` by `xpath`: `//*[contains(@content-desc,'5 out of 5')]` </div><div>Device 1: Find `ProfilePictureElement` by `accessibility id`: `chat-icon` </div></blockquote></p><code> Collectible image is not set as profile image </code><b>[[flaky; on e2e builds when switching on rinkeby sometimes no collectibles]]</b><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/ded39c7f94aa4ff4a530faf5149d7fdd?auth=e5bba8de8436014eccc48d3a0ecf11e9">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/ded39c7f94aa4ff4a530faf5149d7fdd/0044screenshot.png?auth=e5bba8de8436014eccc48d3a0ecf11e9">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2913997">test_pairing_sync_contacts_block_unblock</a>, id: 702196 </b></td></tr><tr><td><p><blockquote><div>Device 2: Tap on found: Button </div><div>Device 2: Find `Button` by `accessibility id`: `blocked-users-list-button` </div></blockquote></p><code> Device 2: Button by accessibility id: `blocked-users-list-button` is not found on the screen</code><br/><br/><p><b>Class: TestPairingSyncMultipleDevicesMerged</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/d85f4992c36e45fb9effae523af2282f?auth=11396372bbdec7ee8be6f1821bd1fa28#280">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/d85f4992c36e45fb9effae523af2282f/0087screenshot.png?auth=11396372bbdec7ee8be6f1821bd1fa28">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/12346789c5244d5990a42c3840197b71?auth=c439bfa6a028b5397480aaee5c08cad4#87">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/12346789c5244d5990a42c3840197b71/0029screenshot.png?auth=c439bfa6a028b5397480aaee5c08cad4">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2914002">test_keycard_1_1_chat_command_request_and_send_tx_stt_in_1_1_chat_offline_opened_from_push</a>, id: 702295 </b></td></tr><tr><td><p><blockquote><div>Device 1: Tap on found: Button </div><div>Device 1: Waiting 400s for STT updated balance </div></blockquote></p><code> Device 1: Balance STT 0 is not changed during 400 seconds! </code><b>[[mysterious issue when PNs are not fetched from offline, can not reproduce on real devices; needs investigation]]</b><br/><br/><p><b>Class: TestChatKeycardMentionsMediumMultipleDevice</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/bd6e277a2be04dcfaed3596916c8f580?auth=56d91c5abec249ef009eb3dfc5bbd0d5#249">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/bd6e277a2be04dcfaed3596916c8f580/0165screenshot.png?auth=56d91c5abec249ef009eb3dfc5bbd0d5">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/7c4171961a114daf9b2a60ea6a4e540b?auth=f7717cb93f23a0bc417f9d273a5baf25#122">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/7c4171961a114daf9b2a60ea6a4e540b/0092screenshot.png?auth=f7717cb93f23a0bc417f9d273a5baf25">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2913998">test_profile_show_profile_picture_and_online_indicator_settings</a>, id: 702281 </b></td></tr><tr><td><p><blockquote><div>Device 2: Looking for chat: 'Knotty Itchy Herald' </div><div>Device 2: Find `ChatImage` by `xpath`: `//*[@content-desc='chat-icon']` </div></blockquote></p><code> Profile picture was not updated on user Profile view</code><br/><br/><p><b>Class: TestProfileGapsCommunityMediumMultipleDevicesMerged</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/d787c6c22ed74af0befc3cd928298d34?auth=97709622dd0c323f694d9045f6d31b4c#124">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/d787c6c22ed74af0befc3cd928298d34/0076screenshot.png?auth=97709622dd0c323f694d9045f6d31b4c">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/7546425b17804c59811a849c1e2c20ff?auth=89d523005242fca8a7956514411fef75#120">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/7546425b17804c59811a849c1e2c20ff/0073screenshot.png?auth=89d523005242fca8a7956514411fef75">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2913990">test_profile_backup_of_contacts</a>, id: 702164 </b></td></tr><tr><td><p><blockquote><div>Device 1: Find `Button` by `accessibility id`: `contacts-button` </div><div>Device 1: Tap on found: Button </div></blockquote></p><code> Device `1`: `Button` by` xpath`: `//*[starts-with(@text,'Blocked users')]` is not found on the screen after wait_for_element</code><br/><br/><p><b>Class: TestBrowserProfileOneDevice</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/31b22d4a9ed54eba88ba2e7e0d9c48d4?auth=bdf5fce7cad1d1e7cc1254c91994d8de#37">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/31b22d4a9ed54eba88ba2e7e0d9c48d4/0073screenshot.png?auth=bdf5fce7cad1d1e7cc1254c91994d8de">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>6. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2913996">test_pairing_sync_initial_contacts_blocked_users</a>, id: 702194 </b></td></tr><tr><td><p><blockquote><div>Device 2: Tap on found: Button </div><div>Device 2: Find `Button` by `accessibility id`: `blocked-users-list-button` </div></blockquote></p><code> Device 2: Button by accessibility id: `blocked-users-list-button` is not found on the screen</code><br/><br/><p><b>Class: TestPairingSyncMultipleDevicesMerged</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/d85f4992c36e45fb9effae523af2282f?auth=11396372bbdec7ee8be6f1821bd1fa28#277">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/d85f4992c36e45fb9effae523af2282f/0087screenshot.png?auth=11396372bbdec7ee8be6f1821bd1fa28">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/12346789c5244d5990a42c3840197b71?auth=c439bfa6a028b5397480aaee5c08cad4#69">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/12346789c5244d5990a42c3840197b71/0029screenshot.png?auth=c439bfa6a028b5397480aaee5c08cad4">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table></details><h3>Passed tests (12)</h3><details><summary>Click to expand</summary><br/><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2913988">test_profile_privacy_policy_terms_of_use_node_version_need_help</a>, id: 5453 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https [...]

2022-07-08 10:26 UTC, status-im-auto commented
## 17% of end-end tests have passed
```
Total executed tests: 6
Failed tests: 5
Passed tests: 1
```
```
IDs of failed tests: 702360,702196,702281,702164,702194 
```
<h3>Failed tests (5)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-react/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&APK_NAME=https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-220707-164624-969695-pr13640-x86.apk&PR_ID=13640&TR_CASE_IDS=702360,702196,702281,702164,702194">Rerun failed tests</a></li><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2914179">test_collectibles_rinkeby_set_as_profile_image</a>, id: 702360 </b></td></tr><tr><td><p><blockquote><div>Device 1: Find `ProfileButton` by `xpath`: `//*[contains(@content-desc,'5 out of 5')]` </div><div>Device 1: Find `ProfilePictureElement` by `accessibility id`: `chat-icon` </div></blockquote></p><code> Collectible image is not set as profile image </code><b>[[flaky; on e2e builds when switching on rinkeby sometimes no collectibles]]</b><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/cdf53bb364cc4d5ca3555f3aa09bd028?auth=2a1f87e3603d86851f9f7f911858a564">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/cdf53bb364cc4d5ca3555f3aa09bd028/0044screenshot.png?auth=2a1f87e3603d86851f9f7f911858a564">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2914176">test_pairing_sync_contacts_block_unblock</a>, id: 702196 </b></td></tr><tr><td><p><blockquote><div>Device 2: Tap on found: Button </div><div>Device 2: Find `Button` by `accessibility id`: `blocked-users-list-button` </div></blockquote></p><code> Device 2: Button by accessibility id: `blocked-users-list-button` is not found on the screen</code><br/><br/><p><b>Class: TestPairingSyncMultipleDevicesMerged</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/a31f1f809b7a4ad8a8da77442cf0effe?auth=a445d2faed1e0157a10b28dcc76051f3#280">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/a31f1f809b7a4ad8a8da77442cf0effe/0087screenshot.png?auth=a445d2faed1e0157a10b28dcc76051f3">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/fce751643cd54003a57ef79d80077083?auth=9b31fa47aa31e2af76c0a6b6f8489e8b#88">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/fce751643cd54003a57ef79d80077083/0029screenshot.png?auth=9b31fa47aa31e2af76c0a6b6f8489e8b">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2914177">test_profile_show_profile_picture_and_online_indicator_settings</a>, id: 702281 </b></td></tr><tr><td><p><blockquote><div>Device 2: Looking for chat: 'Yellowgreen Yellow Tarantula' </div><div>Device 2: Find `ChatImage` by `xpath`: `//*[@content-desc='chat-icon']` </div></blockquote></p><code> Profile picture was not updated on user Profile view</code><br/><br/><p><b>Class: TestProfileGapsCommunityMediumMultipleDevicesMerged</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/5676f03c3b16481e8a34a8f226040ec9?auth=769a3f24c16ea2a4ed617a90cf4a0a09#124">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/5676f03c3b16481e8a34a8f226040ec9/0076screenshot.png?auth=769a3f24c16ea2a4ed617a90cf4a0a09">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/30aebfe1545347c1bc36e1c37940018f?auth=6da8ecc8172cbc5e234c510fa92d744f#120">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/30aebfe1545347c1bc36e1c37940018f/0074screenshot.png?auth=6da8ecc8172cbc5e234c510fa92d744f">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2914174">test_profile_backup_of_contacts</a>, id: 702164 </b></td></tr><tr><td><p><blockquote><div>Device 1: Find `Button` by `accessibility id`: `contacts-button` </div><div>Device 1: Tap on found: Button </div></blockquote></p><code> Device `1`: `Button` by` xpath`: `//*[starts-with(@text,'Blocked users')]` is not found on the screen after wait_for_element</code><br/><br/><p><b>Class: TestBrowserProfileOneDevice</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/b105cbbf898b4e688b049f60d94b19b4?auth=8d27cef42656a74e694aa62eedaf7aa7#37">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/b105cbbf898b4e688b049f60d94b19b4/0073screenshot.png?auth=8d27cef42656a74e694aa62eedaf7aa7">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2914175">test_pairing_sync_initial_contacts_blocked_users</a>, id: 702194 </b></td></tr><tr><td><p><blockquote><div>Device 2: Tap on found: Button </div><div>Device 2: Find `Button` by `accessibility id`: `blocked-users-list-button` </div></blockquote></p><code> Device 2: Button by accessibility id: `blocked-users-list-button` is not found on the screen</code><br/><br/><p><b>Class: TestPairingSyncMultipleDevicesMerged</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/a31f1f809b7a4ad8a8da77442cf0effe?auth=a445d2faed1e0157a10b28dcc76051f3#277">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/a31f1f809b7a4ad8a8da77442cf0effe/0087screenshot.png?auth=a445d2faed1e0157a10b28dcc76051f3">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/fce751643cd54003a57ef79d80077083?auth=9b31fa47aa31e2af76c0a6b6f8489e8b#69">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/fce751643cd54003a57ef79d80077083/0029screenshot.png?auth=9b31fa47aa31e2af76c0a6b6f8489e8b">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table></details><h3>Passed tests (1)</h3><details><summary>Click to expand</summary><br/><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2914178">test_keycard_1_1_chat_command_request_and_send_tx_stt_in_1_1_chat_offline_opened_from_push</a>, id: 702295 </b></td></tr><tr><td><p><b>Class: TestChatKeycardMentionsMediumMultipleDevice</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/1e7ca0aa52a04e319c9325daf24c0905?auth=12fdf4665da2842223ae80fa11c8f57f#175">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/dae4ec5d76bb47d19da41e7516c967e4?auth=98167e838293907c1391c623a73ef13e#109">Steps, video, logs</a></li></ul></p></ul></p></td></tr></tbody></table></details>

2022-07-08 11:48 UTC, pavloburykh commented
@briansztamfater thank you for the fixes. 
I have found a few minor affections of old UI. Would appreciate if you fix them

### ISSUE 1 White border around "pencil" element became wider than it used to be in original old UI

**expected result:** 
![photo_2022-07-08 14 45 17](https://user-images.githubusercontent.com/97245802/177986071-316197db-365d-42f3-ab92-f6c61be676b6.jpeg)


**actual result:**
![photo_2022-07-08 14 44 52](https://user-images.githubusercontent.com/97245802/177986015-9856a064-a4cc-470b-b87c-9897859a5915.jpeg)

### ISSUE 2 Color of online indicator changed its color 
**expected result:** 
![photo_2022-07-08 14 43 58](https://user-images.githubusercontent.com/97245802/177986211-c0d69466-3bdb-4d28-af7f-2a1fa03c229c.jpeg)

**actual result:**
![photo_2022-07-08 14 47 05](https://user-images.githubusercontent.com/97245802/177986294-cc772b8b-ec5e-483e-9949-1f6b4030c615.jpeg)

2022-07-08 13:49 UTC, du64 commented
ENS names do not show up in the new "Discord style" design. The user Dearest Powerful Sloth should show up as @bridge like it used to.

![Screenshot_20220708-084611_Status](https://user-images.githubusercontent.com/65834069/178004665-c12d9a55-0867-4744-b5fa-147a9c9167d7.png)
![Screenshot_20220708-084706_Status PR](https://user-images.githubusercontent.com/65834069/178004672-9d036135-a848-4007-9553-67b4083c0ba7.png)

2022-07-08 18:58 UTC, du82 commented
Sometimes the notification bar turns black when reopening a chat

![Screenshot_20220708-135713_Status PR](https://user-images.githubusercontent.com/65834069/178054014-48c56c73-d59b-4591-9d11-7acabcde04e1.png)

2022-07-08 20:00 UTC, Parveshdhull commented
> Sometimes the notification bar turns black when reopening a chat

Hi @du64, Thank you for finding this issue.
Actually root cause behing this issue and https://github.com/status-im/status-react/issues/13612 is same and will be fixed in https://github.com/status-im/status-react/pull/13641

2022-07-11 11:05 UTC, Parveshdhull requested changes

2022-07-11 11:05 UTC, Parveshdhull commented on src/status_im/ui/components/chat_icon/screen.cljs
> +(defn profile-photo-plus-dot-view-old
Hi @briansztamfater, Did you meant to use `profile-photo-plus-dot-view-new` or use this name for old function

2022-07-11 11:05 UTC, Parveshdhull commented on src/status_im/ui/components/chat_icon/screen.cljs
> +(defn emoji-chat-icon-view-old
same here, `emoji-chat-icon-view-new`

2022-07-11 11:05 UTC, Parveshdhull commented on src/status_im/ui/components/chat_icon/styles.cljs
> +   :width            2
width 2?, wouldn't this will also affect old UI.

2022-07-11 11:05 UTC, Parveshdhull commented on src/status_im/ui/screens/home/views.cljs
> +(defn render-fn-old [{:keys [chat-id] :as home-item}]
same here, naming looks wrong

2022-07-11 11:05 UTC, Parveshdhull commented on src/status_im/ui/screens/home/views.cljs
> +(views/defview communities-and-chats-old []
here too

2022-07-11 19:44 UTC, briansztamfater commented on src/status_im/ui/components/chat_icon/screen.cljs
> +(defn profile-photo-plus-dot-view-old
So I am using `-old` suffix to differenciate functions from the old (current) design, and keep the original name for the new design as @flexsurfer suggested for the topbar

2022-07-11 19:46 UTC, Parveshdhull commented on src/status_im/ui/components/chat_icon/screen.cljs
> +(defn profile-photo-plus-dot-view-old
Yes, that's what is confusing. You are using old for new code
![image](https://user-images.githubusercontent.com/17097240/178345959-a25270da-bc73-4935-b5c2-b64685cf6571.png)

2022-07-11 19:49 UTC, Parveshdhull commented on src/status_im/ui/components/chat_icon/screen.cljs
> +(defn profile-photo-plus-dot-view-old
ok, I get it now

2022-07-11 19:51 UTC, Parveshdhull commented on src/status_im/ui/components/chat_icon/screen.cljs
> +(defn profile-photo-plus-dot-view-old
It is new code, but internally it points to `icon-visiblity-status-dot-old`. This was little confusing, we are writing new code for old UI 😅

2022-07-11 19:56 UTC, Parveshdhull commented on src/status_im/ui/components/chat_icon/styles.cljs
> +   :width            2
ok, we are overwriting this value later
![image](https://user-images.githubusercontent.com/17097240/178347334-099fd162-0aea-4920-9b51-524288033d34.png)
but still, why 2?

2022-07-11 20:22 UTC, briansztamfater commented on src/status_im/ui/components/chat_icon/styles.cljs
> +   :width            2
Nice catch, fixed

2022-07-11 20:26 UTC, briansztamfater commented
> ENS names do not show up in the new "Discord style" design. The user Dearest Powerful Sloth should show up as @bridge like it used to.
> 
> ![Screenshot_20220708-084611_Status](https://user-images.githubusercontent.com/65834069/178004665-c12d9a55-0867-4744-b5fa-147a9c9167d7.png) ![Screenshot_20220708-084706_Status PR](https://user-images.githubusercontent.com/65834069/178004672-9d036135-a848-4007-9553-67b4083c0ba7.png)

Hey @du64 thanks for the issue, I couldn't reproduce it unfortunately, but if you can create an issue to track this separately would be better, as this PR is only modifying styling / UI and the issue may be related to something else.

<img width="448" alt="Captura de Pantalla 2022-07-11 a la(s) 17 21 09" src="https://user-images.githubusercontent.com/18485527/178351878-7f98ef84-28de-43ee-9280-1b48be0ad8d0.png">

2022-07-11 20:27 UTC, briansztamfater commented
@pavloburykh UI fixes you pointed out should be fixed, could you verify please?

2022-07-12 09:58 UTC, status-im-auto commented
## 100% of end-end tests have passed
```
Total executed tests: 2
Failed tests: 0
Passed tests: 2
```
<h3>Passed tests (2)</h3><details><summary>Click to expand</summary><br/><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2916647">test_collectibles_rinkeby_set_as_profile_image</a>, id: 702360 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/96d4754aef2840b398913b29d8737d12?auth=8e8e90f1e3d1452921af3456c701b697">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2916646">test_profile_show_profile_picture_and_online_indicator_settings</a>, id: 702281 </b></td></tr><tr><td><p><b>Class: TestProfileGapsCommunityMediumMultipleDevicesMerged</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/5e981da6b638443299a3ec768f4ded14?auth=18c8704cd6df89f8c77ef22cf2794314#124">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/fe15eb3c8d4f45f5b05b4da2dcfa7e47?auth=f2df5b2b75c5303b8312f762ea9e0b9a#120">Steps, video, logs</a></li></ul></p></ul></p></td></tr></tbody></table></details>

2022-07-12 10:21 UTC, pavloburykh commented
> @pavloburykh UI fixes you pointed out should be fixed, could you verify please?

@briansztamfater thank you for the fixes. Those issues are fixed. Now we will need to perform regression testing and run all critical and medium e2e before merging into develop. We will do it as soon as all final changes will be done and approved. Please, let me know when PR will be ready for final testing (you can just move it to E2E column when PR will pass the developers review). Thanx!

2022-07-12 11:53 UTC, Parveshdhull commented on src/status_im/ui/screens/chat/message/datemark.cljs
> -     (string/capitalize value)]]])
Hi, shouldn't we use quo2/text component which already has these text-styles defined
![image](https://user-images.githubusercontent.com/17097240/178483874-46f71a20-1ad3-472f-b64f-66f08693b354.png)

2022-07-12 12:00 UTC, Parveshdhull approved these changes
Other than the above comment, looks good to me. Thank you for great work.

2022-07-12 17:06 UTC, status-im-auto commented
## 95% of end-end tests have passed
```
Total executed tests: 84
Failed tests: 4
Passed tests: 80
```
```
IDs of failed tests: 702196,700757,702194,700759 
```
<h3>Failed tests (4)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-react/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&APK_NAME=13640.apk&PR_ID=13640&TR_CASE_IDS=702196,700757,702194,700759">Rerun failed tests</a></li><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2917366">test_pairing_sync_contacts_block_unblock</a>, id: 702196 </b></td></tr><tr><td><p><blockquote><div>Device 2: Tap on found: Button </div><div>Device 2: Find `Button` by `accessibility id`: `blocked-users-list-button` </div></blockquote></p><code> Device 2: Button by accessibility id: `blocked-users-list-button` is not found on the screen</code><br/><br/><p><b>Class: TestPairingSyncMultipleDevicesMerged</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/9cd65e95d11743749ca2e94f4355eec5?auth=2ab2dc5cc4a193f65185743bcdeaaa87#287">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/9cd65e95d11743749ca2e94f4355eec5/0127screenshot.png?auth=2ab2dc5cc4a193f65185743bcdeaaa87">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/fee72a7070214248845246f22ffd478d?auth=3a26dc2895bbc911bc5d7ff26ec7e3af#96">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/fee72a7070214248845246f22ffd478d/0041screenshot.png?auth=3a26dc2895bbc911bc5d7ff26ec7e3af">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2917331">test_send_tx_set_recipient_options</a>, id: 700757 </b></td></tr><tr><td><p><blockquote><div>Device 1: Set `hen mango since lottery laundry flag report whisper cycle rate festival carry` value for `EditBox` </div><div>Device 1: Find `Button` by `xpath`: `//*[@text="Next"]` </div></blockquote></p><code>E   http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:
 ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))</code><br/><br/><p><b>Class: TestSendTxDeviceMerged</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/0e0a6a92d5294e68b3344146bcbbbb4f?auth=a2c5f09ca7bd0c98ac23d818689312f2#563">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/0e0a6a92d5294e68b3344146bcbbbb4f/0137screenshot.png?auth=a2c5f09ca7bd0c98ac23d818689312f2">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2917364">test_pairing_sync_initial_contacts_blocked_users</a>, id: 702194 </b></td></tr><tr><td><p><blockquote><div>Device 2: Tap on found: Button </div><div>Device 2: Find `Button` by `accessibility id`: `blocked-users-list-button` </div></blockquote></p><code> Device 2: Button by accessibility id: `blocked-users-list-button` is not found on the screen</code><br/><br/><p><b>Class: TestPairingSyncMultipleDevicesMerged</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/9cd65e95d11743749ca2e94f4355eec5?auth=2ab2dc5cc4a193f65185743bcdeaaa87#277">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/9cd65e95d11743749ca2e94f4355eec5/0127screenshot.png?auth=2ab2dc5cc4a193f65185743bcdeaaa87">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/fee72a7070214248845246f22ffd478d?auth=3a26dc2895bbc911bc5d7ff26ec7e3af#69">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/fee72a7070214248845246f22ffd478d/0041screenshot.png?auth=3a26dc2895bbc911bc5d7ff26ec7e3af">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2917333">test_wallet_add_account_generate_new</a>, id: 700759 </b></td></tr><tr><td><p><blockquote><div>Device 1: Find `Button` by `accessibility id`: `add-new-account` </div><div>Device 1: Find `Button` by `accessibility id`: `add-account-sheet-generate` </div></blockquote></p><code> Device 1: Button by accessibility id: `add-account-sheet-generate` is not found on the screen</code><br/><br/><p><b>Class: TestWalletManagementDeviceMerged</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/39029f179f6b4921959f49f81cb26767?auth=f80c2a827f3c640e268221ee1c2ddee6#205">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/39029f179f6b4921959f49f81cb26767/0162screenshot.png?auth=f80c2a827f3c640e268221ee1c2ddee6">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table></details><h3>Passed tests (80)</h3><details><summary>Click to expand</summary><br/><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2917332">test_wallet_manage_assets</a>, id: 700758 </b></td></tr><tr><td><p><b>Class: TestWalletManagementDeviceMerged</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/39029f179f6b4921959f49f81cb26767?auth=f80c2a827f3c640e268221ee1c2ddee6#218">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2917315">test_public_chat_message_edit</a>, id: 700734 </b></td></tr><tr><td><p><b>Class: TestPublicChatMultipleDeviceMerged</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/7ad2a3db02a44770baafaee9410ffe64?auth=74b585c0cd93df49335a78d70c3b9dd3#119">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/160bfad3cebe47c788891fe7dc33f0fa?auth=167292a6ea79902331b0650f9caa1b55#77">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2917359">test_contact_block_unblock_public_chat_offline</a>, id: 702176 </b></td></tr><tr><td><p><b>Class: TestContactBlockMigrateKeycardMultipleSharedDevices</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/d946ee93660949598be8e34880254fa8?auth=e0030fc1e0ab6e7b4fcfdea171db5719#351">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/e512eff1324e41008d018ce9da4e32d6?auth=3ef1be5effc7f78f0c6d4d55ca0c8d27#240">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2917310">test_1_1_chat_text_message_edit_delete_push_disappear</a>, id: 695843 </b></td></tr><tr><td><p><b>Class: TestOneToOneChatMultipleSharedDevices</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/fe975c63eecf4117ab8bce4b7ab2fb59?auth=bc56c802b5869b0a64f9395952b25e1f#148">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/363a0520c0e04c92a28e660dd3ac93ce?auth=df4c8d7701236fa2b3aa7ac8bb1bd4bc#136">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2917342">test_keycard_relogin_after_restore</a>, id: 700768 </b></td></tr><tr><td><p><b>Class: TestKeycardTxOneDeviceMerged</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/d286b779b4344c5aa5c9cfa0f3785bad?auth=d978f693e7259d2886682a0f93de0942#243">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>6. <a href="https://ethstatus.testrail.net/inde [...]

2022-07-12 20:41 UTC, status-im-auto commented
## 50% of end-end tests have passed
```
Total executed tests: 4
Failed tests: 2
Passed tests: 2
```
```
IDs of failed tests: 702196,702194 
```
<h3>Failed tests (2)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-react/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&APK_NAME=https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-220711-204702-bf0262-pr13640-x86.apk&PR_ID=13640&TR_CASE_IDS=702196,702194">Rerun failed tests</a></li><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2917416">test_pairing_sync_contacts_block_unblock</a>, id: 702196 </b></td></tr><tr><td><p><blockquote><div>Device 2: Tap on found: Button </div><div>Device 2: Find `Button` by `accessibility id`: `blocked-users-list-button` </div></blockquote></p><code>critical/test_pairing_devices_sync.py:193: in test_pairing_sync_contacts_block_unblock
    self.profile_2.blocked_users_button.click()
../views/base_element.py:90: in click
    self.find_element().click()
../views/base_element.py:79: in find_element
    r</code><br/><br/><p><b>Class: TestPairingSyncMultipleDevicesMerged</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/0f016fd8ba7047ee8888c313ba906709?auth=1d08b1ba2208092120cb663ddb9350ef#283">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/0f016fd8ba7047ee8888c313ba906709/0087screenshot.png?auth=1d08b1ba2208092120cb663ddb9350ef">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/42c4b67bfeac4d828eae71662c938dba?auth=ed2b2f03293d88dc236523cae430196c#90">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/42c4b67bfeac4d828eae71662c938dba/0029screenshot.png?auth=ed2b2f03293d88dc236523cae430196c">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2917415">test_pairing_sync_initial_contacts_blocked_users</a>, id: 702194 </b></td></tr><tr><td><p><blockquote><div>Device 2: Tap on found: Button </div><div>Device 2: Find `Button` by `accessibility id`: `blocked-users-list-button` </div></blockquote></p><code>critical/test_pairing_devices_sync.py:159: in test_pairing_sync_initial_contacts_blocked_users
    self.profile_2.blocked_users_button.click()
../views/base_element.py:90: in click
    self.find_element().click()
../views/base_element.py:79: in find_eleme</code><br/><br/><p><b>Class: TestPairingSyncMultipleDevicesMerged</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/0f016fd8ba7047ee8888c313ba906709?auth=1d08b1ba2208092120cb663ddb9350ef#280">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/0f016fd8ba7047ee8888c313ba906709/0087screenshot.png?auth=1d08b1ba2208092120cb663ddb9350ef">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/42c4b67bfeac4d828eae71662c938dba?auth=ed2b2f03293d88dc236523cae430196c#72">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/42c4b67bfeac4d828eae71662c938dba/0029screenshot.png?auth=ed2b2f03293d88dc236523cae430196c">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table></details><h3>Passed tests (2)</h3><details><summary>Click to expand</summary><br/><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2917413">test_send_tx_set_recipient_options</a>, id: 700757 </b></td></tr><tr><td><p><b>Class: TestSendTxDeviceMerged</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/79f41f389de34f15a8e34eb999994cbe?auth=15f420f156b35e4b4d589a1c8b505894#222">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2917414">test_wallet_add_account_generate_new</a>, id: 700759 </b></td></tr><tr><td><p><b>Class: TestWalletManagementDeviceMerged</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/7f2a0344d0e345abad0dfa51e2b9d1ac?auth=0a06c8dea66748b153796ac7bfd46572#116">Steps, video, logs</a></li></ul></p></ul></p></td></tr></tbody></table></details>

2022-07-13 08:12 UTC, status-im-auto commented
## 99% of end-end tests have passed
```
Total executed tests: 99
Failed tests: 1
Passed tests: 98
Not executed tests: 87
```
```
IDs of not executed tests: 6253,6265,6263,6315,6316,5373,695843,5315,6283,6305,5310,5387,5313,700734,700735,700719,5360,700718,5319,700736,700737,6270,5675,5396,5317,700738,700739,3994,700731,700732,3998,5756,3997,702152,702153,702155,702156,702157,702158,700742,700743,700744,700745,700746,700747,700748,700749,702189,700750,700756,700758,700759,700760,700761,700762,700766,700763,700764,700765,700757,5342,700767,700768,700769,700770,5689,702072,702073,702074,702075,702076,702077,702078,702186,702175,702176,702188,702177,702194,702195,702196,702197,702198,702199,702266,702288,702133 
```
```
IDs of failed tests: 702164 
```
<h3>Not executed tests (87)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-react/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&APK_NAME=https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-220711-204702-bf0262-pr13640-x86.apk&PR_ID=13640&TR_CASE_IDS=6253,6265,6263,6315,6316,5373,695843,5315,6283,6305,5310,5387,5313,700734,700735,700719,5360,700718,5319,700736,700737,6270,5675,5396,5317,700738,700739,3994,700731,700732,3998,5756,3997,702152,702153,702155,702156,702157,702158,700742,700743,700744,700745,700746,700747,700748,700749,702189,700750,700756,700758,700759,700760,700761,700762,700766,700763,700764,700765,700757,5342,700767,700768,700769,700770,5689,702072,702073,702074,702075,702076,702077,702078,702186,702175,702176,702188,702177,702194,702195,702196,702197,702198,702199,702266,702288,702133">Rerun not executed tests</a></li></details><h3>Failed tests (1)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-react/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&APK_NAME=https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-220711-204702-bf0262-pr13640-x86.apk&PR_ID=13640&TR_CASE_IDS=702164">Rerun failed tests</a></li><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2917778">test_profile_backup_of_contacts</a>, id: 702164 </b></td></tr><tr><td><p><blockquote><div>Device 1: Find `Button` by `accessibility id`: `contacts-button` </div><div>Device 1: Tap on found: Button </div></blockquote></p><code> Device `1`: `Button` by` xpath`: `//*[starts-with(@text,'Blocked users')]` is not found on the screen after wait_for_element</code><br/><br/><p><b>Class: TestBrowserProfileOneDevice</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/344ab7860fdd47fd9094366a0a15ffd2?auth=91e167f254da8d1a80ccd113d5bc4407#720">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/344ab7860fdd47fd9094366a0a15ffd2/0288screenshot.png?auth=91e167f254da8d1a80ccd113d5bc4407">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table></details><h3>Passed tests (98)</h3><details><summary>Click to expand</summary><br/><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2917860">test_mutual_cr_decline_contact_request</a>, id: 702377 </b></td></tr><tr><td><p><b>Class: TestMutualContactRequests</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/ac5358da9f254d63aa8bdef027f83b0a?auth=8a0bbca2bb65b1bce08e25596cdc40c6#164">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/492c74f9d24e4b3c9d956d2ad402b8b2?auth=a9b94a28fa35c7d8801927782cf6e6b2#110">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2917776">test_profile_add_remove_contact_via_contacts_view</a>, id: 702160 </b></td></tr><tr><td><p><b>Class: TestBrowserProfileOneDevice</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/344ab7860fdd47fd9094366a0a15ffd2?auth=91e167f254da8d1a80ccd113d5bc4407#480">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2917775">test_profile_invite_friends</a>, id: 702159 </b></td></tr><tr><td><p><b>Class: TestBrowserProfileOneDevice</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/344ab7860fdd47fd9094366a0a15ffd2?auth=91e167f254da8d1a80ccd113d5bc4407#421">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2917690">test_profile_privacy_policy_terms_of_use_node_version_need_help</a>, id: 5453 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/f8e6b70bdce7446eaf5cee7eee99c4d9?auth=4f91ae3c017fd22124879fc9e1d6ee28">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2917707">test_keycard_send_funds_between_accounts_set_max_in_multiaccount_instance</a>, id: 6292 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/49cec46287764f918dc4b83db3e93c9f?auth=bf20f553a480231ac54eb60e3792b3ae">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>6. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2917781">test_ens_dapp_purchase</a>, id: 702167 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/e3ad585297f342bdb469f4678fcffeaf?auth=64ae66307f11d7f2509a180b8215e4a3">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>7. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2917786">test_browser_refresh_page</a>, id: 702179 </b></td></tr><tr><td><p><b>Class: TestBrowserProfileOneDevice</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/344ab7860fdd47fd9094366a0a15ffd2?auth=91e167f254da8d1a80ccd113d5bc4407#203">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>8. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2917830">test_profile_can_not_connect_to_custom_history_node_add_delete</a>, id: 702287 </b></td></tr><tr><td><p><b>Class: TestTimelineHistoryNodesBootnodesMultipleDeviceMergedMedium</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/6c86ba4a64984896b0a320e6ab5849d5?auth=50dd7e70487e632d8e94bf3c623fd8da#396">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/30cf2e6445c04b4fa6b97b3fa998c770?auth=98962c35a24972243b7489fbf6710b6a#252">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>9. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2917829">test_profile_use_history_node_disable_enable</a>, id: 702286 </b></td></tr><tr><td><p><b>Class: TestTimelineHistoryNodesBootnodesMultipleDeviceMergedMedium</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/6c86ba4a64984896b0a320e6ab5849d5?auth=50dd7e70487e632d8e94bf3c623fd8da#283">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://saucelabs.com/jobs/30cf2e6445c04b4fa6b97b3fa998c770?auth=98962c35a24972243b7489fbf6710b6a#232">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>10. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2917855">test_collectibles_rinkeby_set_as_profile_image</a>, id: 702360 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/8a300d86763143dbbcadd4253baa6555?auth=e50c282e0aadd7e84c8c2c581bbc0248">Steps,  [...]

2022-07-13 14:31 UTC, pavloburykh commented
@briansztamfater please, take a look at following issue: 

### ISSUE 3 Old UI Add (+) element on status screen has new UI style and is dislocated

**Actual result:** 
![photo_2022-07-13 17 30 49](https://user-images.githubusercontent.com/97245802/178759054-8f697a28-a739-46df-a317-2a2abf66a888.jpeg)

**Expected result:**
![photo_2022-07-13 17 30 30](https://user-images.githubusercontent.com/97245802/178759122-223f2a2c-9f49-4369-8b20-1c061d7fa510.jpeg)

2022-07-13 14:32 UTC, pavloburykh commented
@briansztamfater also, could you please resolve existing conflicts here src/status_im/ui/screens/home/views.cljs ? Thanx!

2022-07-13 19:42 UTC, briansztamfater commented
@pavloburykh thanks for pointing out the issue, just rebased and pushed out the fix. Let me know if you find something else.

2022-07-13 22:45 UTC, status-im-auto commented
## 92% of end-end tests have passed
```
Total executed tests: 186
Failed tests: 14
Passed tests: 172
```
```
IDs of failed tests: 702160,702159,702179,702181,702196,702180,702161,702166,702178,702182,702165,702164,702194,702151 
```
<h3>Failed tests (14)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-react/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&APK_NAME=https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-220713-194241-8f1140-pr13640-x86.apk&PR_ID=13640&TR_CASE_IDS=702160,702159,702179,702181,702196,702180,702161,702166,702178,702182,702165,702164,702194,702151">Rerun failed tests</a></li><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2921251">test_profile_add_remove_contact_via_contacts_view</a>, id: 702160 </b></td></tr><tr><td><p><blockquote><div># STEP: Check empty contacts view</div><div>Device 1: Click until `Button` by `accessibility id`: `privacy-and-security-settings-button` will be presented </div></blockquote></p><code>medium/test_browser_profile.py:210: in test_profile_add_remove_contact_via_contacts_view
    profile = self.home.profile_button.click()
../views/base_view.py:129: in click
    self.click_until_presence_of_element(ProfileView(self.driver).privacy_and_secur</code><br/><br/><p><b>Class: TestBrowserProfileOneDevice</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/90d47a078ad94069b40b1605cbc0a30f?auth=150a5eb26deb56c9e8aee071572e04c4#250">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/90d47a078ad94069b40b1605cbc0a30f/0060screenshot.png?auth=150a5eb26deb56c9e8aee071572e04c4">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2921250">test_profile_invite_friends</a>, id: 702159 </b></td></tr><tr><td><p><blockquote><div>Device 1: Find `HomeButton` by `xpath`: `//*[contains(@content-desc,'tab, 1 out of 5')]` </div><div>Device 1: Find `HomeButton` by `xpath`: `//*[contains(@content-desc,'tab, 1 out of 5')]` </div></blockquote></p><code>medium/test_browser_profile.py:190: in test_profile_invite_friends
    self.home.home_button.double_click()
../views/base_element.py:110: in double_click
    [self.find_element().click() for _ in range(2)]
../views/base_element.py:110: in <listcomp>
    [</code><br/><br/><p><b>Class: TestBrowserProfileOneDevice</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/90d47a078ad94069b40b1605cbc0a30f?auth=150a5eb26deb56c9e8aee071572e04c4#245">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/90d47a078ad94069b40b1605cbc0a30f/0060screenshot.png?auth=150a5eb26deb56c9e8aee071572e04c4">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2921261">test_browser_refresh_page</a>, id: 702179 </b></td></tr><tr><td><p><blockquote><div>Device 1: Find `Button` by `xpath`: `//*[@text="Select a token"]` </div><div>Device 1: Find `Button` by `xpath`: `//*[@text="Select a token"]` </div></blockquote></p><code>medium/test_browser_profile.py:96: in test_browser_refresh_page
    element_on_start_page.scroll_and_click()
../views/base_element.py:179: in scroll_and_click
    self.click()
../views/base_element.py:90: in click
    self.find_element().click()
/home/jen</code><br/><br/><p><b>Class: TestBrowserProfileOneDevice</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/90d47a078ad94069b40b1605cbc0a30f?auth=150a5eb26deb56c9e8aee071572e04c4#208">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/90d47a078ad94069b40b1605cbc0a30f/0060screenshot.png?auth=150a5eb26deb56c9e8aee071572e04c4">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2921263">test_browser_open_chat_options</a>, id: 702181 </b></td></tr><tr><td><p><blockquote><div>Device 1: Find `DappTabButton` by `xpath`: `//*[contains(@content-desc,'tab, 2 out of 5')]` </div><div>Device 1: Find `DappTabButton` by `xpath`: `//*[contains(@content-desc,'tab, 2 out of 5')]` </div></blockquote></p><code>medium/test_browser_profile.py:155: in test_browser_open_chat_options
    dapp = self.home.dapp_tab_button.click()
../views/base_view.py:95: in click
    super().click()
../views/base_element.py:90: in click
    self.find_element().click()
 'NoneType' obj</code><br/><br/><p><b>Class: TestBrowserProfileOneDevice</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/90d47a078ad94069b40b1605cbc0a30f?auth=150a5eb26deb56c9e8aee071572e04c4#235">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/90d47a078ad94069b40b1605cbc0a30f/0060screenshot.png?auth=150a5eb26deb56c9e8aee071572e04c4">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2921274">test_pairing_sync_contacts_block_unblock</a>, id: 702196 </b></td></tr><tr><td><code>Test is not run, e2e blocker  </code><b>[[reason: [NOTRUN] failing due to issue #13635. Skipping until fix]]</b><br/><br/><p><b>Class: TestPairingSyncMultipleDevicesMerged</b></p></td></tr><tr><td><b>6. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2921262">test_browser_connect_revoke_wallet</a>, id: 702180 </b></td></tr><tr><td><p><blockquote><div>Device 1: Find `DappTabButton` by `xpath`: `//*[contains(@content-desc,'tab, 2 out of 5')]` </div><div>Device 1: Find `DappTabButton` by `xpath`: `//*[contains(@content-desc,'tab, 2 out of 5')]` </div></blockquote></p><code>medium/test_browser_profile.py:122: in test_browser_connect_revoke_wallet
    dapp = self.home.dapp_tab_button.click()
../views/base_view.py:95: in click
    super().click()
../views/base_element.py:90: in click
    self.find_element().click()
 'NoneType'</code><br/><br/><p><b>Class: TestBrowserProfileOneDevice</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/90d47a078ad94069b40b1605cbc0a30f?auth=150a5eb26deb56c9e8aee071572e04c4#230">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/90d47a078ad94069b40b1605cbc0a30f/0060screenshot.png?auth=150a5eb26deb56c9e8aee071572e04c4">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>7. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2921252">test_profile_can_reset_password</a>, id: 702161 </b></td></tr><tr><td><code>medium/test_browser_profile.py:431: in test_profile_can_reset_password
    self.home.get_back_to_home_view()
../views/base_view.py:542: in get_back_to_home_view
    while BackButton(self.driver).is_element_displayed(2) or self.close_button.is_element_disp</code><br/><br/><p><b>Class: TestBrowserProfileOneDevice</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/90d47a078ad94069b40b1605cbc0a30f?auth=150a5eb26deb56c9e8aee071572e04c4#263">Steps, video, logs</a></li><li><a href="https://assets.saucelabs.com/jobs/90d47a078ad94069b40b1605cbc0a30f/0060screenshot.png?auth=150a5eb26deb56c9e8aee071572e04c4">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>8. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2921255">test_profile_add_custom_network</a>, id: 702166 </b></td></tr><tr><td><code>medium/test_browser_profile.py:282: in test_profile_add_custom_network
    self.home.get_back_to_home_view()
../views/base_view.py:542: in get_back_to_home_view
    while BackButton(self.driver).is_element_displayed(2) or self.close_button.is_element_disp</code><br/><br/><p><b>Class: TestBrowserProfileOneDevice</b></p><ins>Device sessions</ins><p><ul><p> [...]

2022-07-14 07:27 UTC, status-im-auto commented
## 79% of end-end tests have passed
```
Total executed tests: 14
Failed tests: 3
Passed tests: 11
```
```
IDs of failed tests: 702196,702164,702194 
```
<h3>Failed tests (3)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-react/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&APK_NAME=https://status-im-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-220713-194241-8f1140-pr13640-x86.apk&PR_ID=13640&TR_CASE_IDS=702196,702164,702194">Rerun failed tests</a></li><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2921927">test_pairing_sync_contacts_block_unblock</a>, id: 702196 </b></td></tr><tr><td><code>Test is not run, e2e blocker  </code><b>[[reason: [NOTRUN] failing due to issue #13635. Skipping until fix]]</b><br/><br/><p><b>Class: TestPairingSyncMultipleDevicesMerged</b></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2921918">test_profile_backup_of_contacts</a>, id: 702164 </b></td></tr><tr><td><code>Test is not run, e2e blocker  </code><b>[[reason: [NOTRUN] failing due to issue #13635. Skipping until fix]]</b><br/><br/><p><b>Class: TestBrowserProfileOneDevice</b></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2921926">test_pairing_sync_initial_contacts_blocked_users</a>, id: 702194 </b></td></tr><tr><td><code>Test is not run, e2e blocker  </code><b>[[reason: [NOTRUN] failing due to issue #13635. Skipping until fix]]</b><br/><br/><p><b>Class: TestPairingSyncMultipleDevicesMerged</b></p></td></tr></tbody></table></details><h3>Passed tests (11)</h3><details><summary>Click to expand</summary><br/><br/><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2921916">test_profile_add_remove_contact_via_contacts_view</a>, id: 702160 </b></td></tr><tr><td><p><b>Class: TestBrowserProfileOneDevice</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/f77a331dc4ec45a28448bfb7e6769d83?auth=7e0a25d7ddfbc99b6778fa1db124ee5b#321">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2921915">test_profile_invite_friends</a>, id: 702159 </b></td></tr><tr><td><p><b>Class: TestBrowserProfileOneDevice</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/f77a331dc4ec45a28448bfb7e6769d83?auth=7e0a25d7ddfbc99b6778fa1db124ee5b#260">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2921922">test_browser_refresh_page</a>, id: 702179 </b></td></tr><tr><td><p><b>Class: TestBrowserProfileOneDevice</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/f77a331dc4ec45a28448bfb7e6769d83?auth=7e0a25d7ddfbc99b6778fa1db124ee5b#37">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2921924">test_browser_open_chat_options</a>, id: 702181 </b></td></tr><tr><td><p><b>Class: TestBrowserProfileOneDevice</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/f77a331dc4ec45a28448bfb7e6769d83?auth=7e0a25d7ddfbc99b6778fa1db124ee5b#178">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2921923">test_browser_connect_revoke_wallet</a>, id: 702180 </b></td></tr><tr><td><p><b>Class: TestBrowserProfileOneDevice</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/f77a331dc4ec45a28448bfb7e6769d83?auth=7e0a25d7ddfbc99b6778fa1db124ee5b#94">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>6. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2921917">test_profile_can_reset_password</a>, id: 702161 </b></td></tr><tr><td><p><b>Class: TestBrowserProfileOneDevice</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/f77a331dc4ec45a28448bfb7e6769d83?auth=7e0a25d7ddfbc99b6778fa1db124ee5b#680">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>7. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2921920">test_profile_add_custom_network</a>, id: 702166 </b></td></tr><tr><td><p><b>Class: TestBrowserProfileOneDevice</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/f77a331dc4ec45a28448bfb7e6769d83?auth=7e0a25d7ddfbc99b6778fa1db124ee5b#446">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>8. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2921921">test_profile_change_fleet</a>, id: 702178 </b></td></tr><tr><td><p><b>Class: TestBrowserProfileOneDevice</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/f77a331dc4ec45a28448bfb7e6769d83?auth=7e0a25d7ddfbc99b6778fa1db124ee5b#630">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>9. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2921925">test_browser_new_tab_open</a>, id: 702182 </b></td></tr><tr><td><p><b>Class: TestBrowserProfileOneDevice</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/f77a331dc4ec45a28448bfb7e6769d83?auth=7e0a25d7ddfbc99b6778fa1db124ee5b#231">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>10. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2921919">test_profile_change_log_level</a>, id: 702165 </b></td></tr><tr><td><p><b>Class: TestBrowserProfileOneDevice</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/f77a331dc4ec45a28448bfb7e6769d83?auth=7e0a25d7ddfbc99b6778fa1db124ee5b#569">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>11. <a href="https://ethstatus.testrail.net/index.php?/tests/view/2921914">test_browser_open_url_with_non_english_text</a>, id: 702151 </b></td></tr><tr><td><p><b>Class: TestBrowserProfileOneDevice</b></p><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://saucelabs.com/jobs/f77a331dc4ec45a28448bfb7e6769d83?auth=7e0a25d7ddfbc99b6778fa1db124ee5b#61">Steps, video, logs</a></li></ul></p></ul></p></td></tr></tbody></table></details>

2022-07-14 10:19 UTC, pavloburykh commented
@briansztamfater thank you for the fixes, PR is ready for merge.

2022-07-14 10:21 UTC, Parveshdhull commented
Hi @briansztamfater, Please also look into https://github.com/status-im/status-react/issues/13666#issuecomment-1183862725

2022-07-14 11:54 UTC, Parveshdhull reviewed
These are a few small changes, Please feel free to address them later in separate PR.

2022-07-14 11:54 UTC, Parveshdhull commented on src/status_im/ui/screens/home/views.cljs
> +    [quo2.text/text {:size :heading-1 :weight :semi-bold} "Messages"]
Hard coding string will cause problems while supporting multiple languages

2022-07-14 11:54 UTC, Parveshdhull commented on src/status_im/ui/screens/home/views/inner_item.cljs
> +          "Public"]
Same here, better to add in translations

2022-07-14 11:54 UTC, Parveshdhull commented on src/status_im/ui/screens/home/views/inner_item.cljs
> +                                                                                                                                                                                               (utils.u
When it is possible, please, keep lines' length shorter/equal 80 chars.

2022-07-14 11:55 UTC, Parveshdhull commented
This [comment](https://github.com/status-im/status-react/pull/13640#discussion_r918878805), also needs to be addressed.

2022-07-14 12:23 UTC, briansztamfater commented
> This [comment](https://github.com/status-im/status-react/pull/13640#discussion_r918878805), also needs to be addressed.

Done! Let me know if we can merge

2022-07-14 12:42 UTC, Parveshdhull commented
> > This [comment](https://github.com/status-im/status-react/pull/13640#discussion_r918878805), also needs to be addressed.
> 
> Done! Let me know if we can merge

Thank you, PR is ready to be merge

2022-07-14 12:45 UTC, merged