implemented ui for community-link card
status-im/status-react pull request #14368
Opened 2022-11-15 06:57 UTC by izuchukwu-eric

fixes #14123 

### Summary

[comment]: # (Summarise the problem and how the pull)
created a reusable component for community-link card

### Testing notes

#### Platforms

- Android
- iOS
- macOS
- Linux
- Windows

### Steps to test

- Open Status
- Open community
- Should see a community card for decentraland

status: ready

2022-11-15 06:57 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | 6762f54a | [#1](https://ci.status.im/job/status-mobile/job/prs/job/android/job/PR-14368/1/) | 2022-11-15 06:57:51 | ~27 sec | `android` | [:page_facing_up:`log`](https://ci.status.im/job/status-mobile/job/prs/job/android/job/PR-14368/1/consoleText) |

2022-11-15 10:31 UTC, jo-mut commented on src/quo2/components/community/community_card.cljs
> +   [rn/view
@izuchukwu-eric align your clojure maps properly

 you can have a look at this doc to see more on how to format your code
https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md

2022-11-15 10:31 UTC, jo-mut commented on translations/en.json
> +    "likes-count": "112.1k",
active-members instead of likes-count
mutual-contacts instead of dislike-count

2022-11-15 10:31 UTC, jo-mut commented on src/quo2/components/community/community_card.cljs
> +              :background-color "#EC4D57"
use the `quo2.foundations.colors` component for colors

2022-11-15 10:31 UTC, jo-mut commented on src/quo2/components/community/community_card.cljs
> +      "View Community"
use `i18n/label`

2022-11-15 10:31 UTC, jo-mut commented on src/status_im/ui2/screens/communities/communities_home.cljs
> +     [community-card]
Add your component for preview to `status-im.ui2.screens.quo2-preview.` It should not be here.
See examples of how other components in for instance: 
`status-im.ui2.screens.quo2-preview.community.community-card-view` are added to quo2_preview.

2022-11-15 10:31 UTC, jo-mut commented on src/status_im/ui2/screens/communities/communities_home.cljs
> +(defn community-card []
`active-members` instead of `likes-count`
`mutual-contacts` instead of ` dislike-count`

2022-11-15 10:31 UTC, jo-mut commented on src/quo2/components/community/community_card.cljs
> +(defn community-stats [member_count likes_count dislike_count]
better to use a keyword argument here
`community-stats [{:keys [member_count likes_count dislike_count]}]`

2022-11-15 11:44 UTC, jo-mut requested changes
have a look at these guideline https://github.com/status-im/status-mobile/blob/develop/doc/new-guidelines.md and format your code appropriately

2022-11-15 12:02 UTC, izuchukwu-eric commented
Alright I'll make the due changes...thanks

2022-11-15 18:35 UTC, izuchukwu-eric commented
I changed the component name from community-card to community-link-card, just to be specific.

2022-11-15 19:48 UTC, jo-mut commented on src/status_im/ui2/screens/quo2_preview/community/community_link_card.cljs
> +    [rn/view
I dont think the parent `rn/view` is necessary. is it?

2022-11-15 19:48 UTC, jo-mut commented on src/quo2/foundations/colors.cljs
> +
are the comments needed here?

2022-11-15 20:50 UTC, izuchukwu-eric commented
okay I'll remove the unnecessary code and comment

2022-11-15 20:59 UTC, J-Son89 commented on src/quo2/components/community/community_link_card.cljs
> +(defn community-link-card [{:keys [title description image member_count active_members mutual_contacts]}]
we don't use `_` for variable names. Can you change these to `member-count`, `active-members` etc

2022-11-15 21:00 UTC, ibrkhalil requested changes

2022-11-15 21:00 UTC, ibrkhalil commented on src/quo2/components/community/community_link_card.cljs
> +                 :weight       :semi-bold}
Why is there two font-weight attributes ?

2022-11-15 21:00 UTC, ibrkhalil commented on src/quo2/components/community/community_link_card.cljs
> +                :weight          :regular}
Two weights again
And for font-size 13 we use this attribute
`:size` `:paragraph-2`

2022-11-15 21:00 UTC, ibrkhalil commented on src/quo2/components/community/community_link_card.cljs
> +(defn community-stats [{:keys [member_count active_members mutual_contacts]}]
Clojure naming convention is kebab case
`member-count` `active-members` etc

2022-11-15 21:00 UTC, ibrkhalil commented on src/quo2/components/community/community_link_card.cljs
> +     mutual_contacts]]])
Kebab case

2022-11-15 21:00 UTC, ibrkhalil commented on src/quo2/components/community/community_link_card.cljs
> +     active_members]]
kebab

2022-11-15 21:00 UTC, ibrkhalil commented on src/quo2/components/community/community_link_card.cljs
> +                :font-style   :normal}
This can be `{:weight` `:regular` `:size` `:paragraph-2}`

2022-11-15 21:00 UTC, ibrkhalil commented on src/quo2/components/community/community_link_card.cljs
> +(defn community-link-card [{:keys [title description image member_count active_members mutual_contacts]}]
Kebab case

2022-11-15 21:00 UTC, ibrkhalil commented on src/quo2/components/community/community_link_card.cljs
> +                   :padding-top      12
Can be `padding-vertical`

2022-11-15 21:00 UTC, ibrkhalil commented on src/quo2/components/community/community_link_card.cljs
> +             :padding-left       12
Can be padding vertical and padding horizontal

2022-11-15 21:00 UTC, ibrkhalil commented on src/quo2/components/community/community_link_card.cljs
> +      (i18n/label :t/community-link-card-button-text)]]])
Kindly use text component from `quo2.text`

2022-11-15 21:00 UTC, ibrkhalil commented on src/status_im/ui2/screens/communities/communities_home.cljs
> +
Unneeded change

2022-11-15 21:00 UTC, ibrkhalil commented on src/status_im/ui2/screens/quo2_preview/community/community_link_card.cljs
> +                      :key-fn                    str}]])
Kindly add a new line at EOF

2022-11-15 21:00 UTC, ibrkhalil commented on src/quo2/components/community/community_link_card.cljs
> +       :left   10}]]
Kindly make sure that `rn/view` is needed .. As too many redundant `rn/view` usages are bad for performance

2022-11-15 21:00 UTC, Parveshdhull commented on src/quo2/components/community/community_link_card.cljs
> +              :height 16}}]
1. first `[rn/view` can be replaced with `[:<>`
2. Please remove unnecessary empty lines

2022-11-15 21:00 UTC, Parveshdhull commented on src/quo2/components/community/community_link_card.cljs
> +                :weight          :regular}
we don't need to pass font-size, style, spacing etc. Please checkout available values for size in [text.cljs](https://github.com/status-im/status-mobile/blob/433f9185c8e89dffac95a0c3a188bf1ceef2b292/src/quo2/components/markdown/text.cljs#L17)

2022-11-15 21:05 UTC, J-Son89 commented on src/quo2/components/community/community_link_card.cljs
> +                 :font-weight  600
hmm, perhaps you should be using
```
[text/text {:size  :paragraph-1 
:weight :semi-bold
}]
```
see the file: "src/quo2/foundations/typography.cljs"

for a the different sizes.

Unless there's a specific reason you need these exact props

2022-11-15 21:06 UTC, J-Son89 commented on src/quo2/components/community/community_link_card.cljs
> +    [text/text {:font-size       13
same here, could this be:

```
[text/text {:size  :paragraph-2
}]
```
`:weight :regular` is the default as far as I know. Best to double check that

2022-11-15 21:06 UTC, J-Son89 commented on src/quo2/components/community/community_link_card.cljs
> +(defn community-stats [{:keys [member_count active_members mutual_contacts]}]
same here, update variable names to use `-` instead of `_` for consistency

2022-11-15 21:10 UTC, J-Son89 commented
If possible it would be great if you can add a screen shot or two of the implementation.

and when attaching them to github comments you can use 
<img src="..." height="400" /> or any other combination of width/height 
where src is the url github displays when you upload. (This helps avoid the image being huge and taking over the p.r feed)

2022-11-15 21:56 UTC, izuchukwu-eric commented
thanks for the review everyone, will send an updated commit

2022-11-16 10:37 UTC, jo-mut commented
@izuchukwu-eric could you run `make lint-fix` to format the code and confirm that the code is well formatted by running `make lint` as some of the tests are not going past linting. Also it would be nice to add a screenshot of the community-link-card component

2022-11-16 11:51 UTC, izuchukwu-eric commented
Alright will do that
I added `:i/group` and `:i/lightning`  icons, but for some reason they aren't showing...any tip?
I tried taking a screenshot but due to the privacy policy it doesn't work

2022-11-16 12:24 UTC, jo-mut commented
looks 

> Alright will do that I added `:i/group` and `:i/lightning` icons, but for some reason they aren't showing...any tip? I tried taking a screenshot but due to the privacy policy it doesn't work

Enable your security settings to allow for screen shot. `Profile -> Privacy and security -> Block screenshots`

2022-11-16 12:25 UTC, jo-mut commented
You can restart `make run-clojure` to see new added icons

2022-11-16 12:37 UTC, izuchukwu-eric commented
Alright...thanks

2022-11-16 17:52 UTC, izuchukwu-eric commented
> You can restart `make run-clojure` to see new added icons

restarting `make run-clojure` doesn't seem to fix it

2022-11-16 23:19 UTC, izuchukwu-eric commented
![Screenshot_20221117-000432_Status Debug](https://user-images.githubusercontent.com/57435925/202315517-8db13926-6d99-46af-938e-c6487ccc6778.jpg)
This is how it looks

2022-11-16 23:20 UTC, izuchukwu-eric commented
![Screenshot_20221117-000432_Status Debug](https://user-images.githubusercontent.com/57435925/202315741-3e4d21e4-3961-46f1-a954-fd3db989cd94.jpg)
This is how it looks

2022-11-17 09:45 UTC, jo-mut commented
looks good to me but your tests need to pass. ran `make lint-fix` & `make-lint`

2022-11-17 09:53 UTC, churik commented
Also please rebase and make sure that `make test` is passed. Thanks

2022-11-17 18:21 UTC, izuchukwu-eric commented
> looks good to me but your tests need to pass. ran `make lint-fix` & `make-lint`

running `make lint` says the files are indented correctly

2022-11-17 18:30 UTC, jo-mut commented
> > looks good to me but your tests need to pass. ran `make lint-fix` & `make-lint`
> 
> running `make lint` says the files are indented correctly

make sure you commit and push your changes

2022-11-17 19:43 UTC, izuchukwu-eric commented
> > > looks good to me but your tests need to pass. ran `make lint-fix` & `make-lint`
> > 
> > 
> > running `make lint` says the files are indented correctly
> 
> make sure you commit and push your changes

I already made a commit that fixes the lint issues. could there be any other reasons why the commits aren't passing the jenkins test?

2022-11-17 20:23 UTC, churik commented
@izuchukwu-eric yes, there is a conflict on rebase stage:
```
18:25:40  Rebasing (1/7)
CONFLICT (modify/delete): src/status_im/ui2/screens/communities/communities_home.cljs deleted in HEAD and modified in b082f7782 (ui-component community-link-card).  Version b082f7782 (ui-component community-link-card) of src/status_im/ui2/screens/communities/communities_home.cljs left in tree.
18:25:40  Auto-merging translations/en.json
18:25:40  error: could not apply b082f7782... ui-component community-link-card
18:25:40  hint: Resolve all conflicts manually, mark them as resolved with
18:25:40  hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
18:25:40  hint: You can instead skip this commit: run "git rebase --skip".
18:25:40  hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
18:25:40  Could not apply b082f7782... ui-component community-link-card
```

2022-11-18 07:54 UTC, izuchukwu-eric commented
> @izuchukwu-eric yes, there is a conflict on rebase stage:
> 
> ```
> 18:25:40  Rebasing (1/7)
> CONFLICT (modify/delete): src/status_im/ui2/screens/communities/communities_home.cljs deleted in HEAD and modified in b082f7782 (ui-component community-link-card).  Version b082f7782 (ui-component community-link-card) of src/status_im/ui2/screens/communities/communities_home.cljs left in tree.
> 18:25:40  Auto-merging translations/en.json
> 18:25:40  error: could not apply b082f7782... ui-component community-link-card
> 18:25:40  hint: Resolve all conflicts manually, mark them as resolved with
> 18:25:40  hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
> 18:25:40  hint: You can instead skip this commit: run "git rebase --skip".
> 18:25:40  hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
> 18:25:40  Could not apply b082f7782... ui-component community-link-card
> ```

Thanks for pointing this out, I think its resolved now

2022-11-18 08:51 UTC, jo-mut approved these changes

2022-11-18 14:26 UTC, churik commented
@izuchukwu-eric 
```
[2022-11-18T10:56:55.155Z] + git rebase develop

[2022-11-18T10:56:55.155Z] Rebasing (1/14)
CONFLICT (modify/delete): src/status_im/ui2/screens/communities/communities_home.cljs deleted in HEAD and modified in b082f7782 (ui-component community-link-card).  Version b082f7782 (ui-component community-link-card) of src/status_im/ui2/screens/communities/communities_home.cljs left in tree.

[2022-11-18T10:56:55.155Z] Auto-merging translations/en.json

[2022-11-18T10:56:55.155Z] error: could not apply b082f7782... ui-component community-link-card

[2022-11-18T10:56:55.155Z] hint: Resolve all conflicts manually, mark them as resolved with

[2022-11-18T10:56:55.155Z] hint: "git add/rm <conflicted_files>", then run "git rebase --continue".

[2022-11-18T10:56:55.155Z] hint: You can instead skip this commit: run "git rebase --skip".

[2022-11-18T10:56:55.155Z] hint: To abort and get back to the state before "git rebase", run "git rebase --abort".

[2022-11-18T10:56:55.155Z] Could not apply b082f7782... ui-component community-link-card

script returned exit code 1
```

2022-11-18 17:21 UTC, izuchukwu-eric commented
> @izuchukwu-eric
> 
> ```
> [2022-11-18T10:56:55.155Z] + git rebase develop
> 
> [2022-11-18T10:56:55.155Z] Rebasing (1/14)
> CONFLICT (modify/delete): src/status_im/ui2/screens/communities/communities_home.cljs deleted in HEAD and modified in b082f7782 (ui-component community-link-card).  Version b082f7782 (ui-component community-link-card) of src/status_im/ui2/screens/communities/communities_home.cljs left in tree.
> 
> [2022-11-18T10:56:55.155Z] Auto-merging translations/en.json
> 
> [2022-11-18T10:56:55.155Z] error: could not apply b082f7782... ui-component community-link-card
> 
> [2022-11-18T10:56:55.155Z] hint: Resolve all conflicts manually, mark them as resolved with
> 
> [2022-11-18T10:56:55.155Z] hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
> 
> [2022-11-18T10:56:55.155Z] hint: You can instead skip this commit: run "git rebase --skip".
> 
> [2022-11-18T10:56:55.155Z] hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
> 
> [2022-11-18T10:56:55.155Z] Could not apply b082f7782... ui-component community-link-card
> 
> script returned exit code 1
> ```

I'm getting a rebase successfully message after fixing the conflicts, not why it keeps showing these conflicts even after rebasing. are there any other solutions?

2022-11-29 10:40 UTC, closed without merging