Update translation
status-im/status-react pull request #14483
Opened 2022-12-02 16:38 UTC by jinhojang6

Updated languages

- Spanish (Latin America) : es_419.json
- Persian : fa.json
- Frech : fr.json
- Hindi : hi.json
- Japanese : ja.json
- Brazilian Portuguese : pt_BR.json
- Russian: ru.json
- Traditional Chinese : zh_TW.json
- Simplified Chinese : zh.json

2022-12-02 16:42 UTC, status-im-auto commented
### Jenkins Builds
<details>
<summary>Click to see older builds (4)</summary>

| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 5b95eb1e | [#1](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-14483/1/) | 2022-12-02 16:42:02 | ~3 min | `tests` | [:page_facing_up:`log`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-221202-163842-5b95eb-pr14483-tests.log) |
| :heavy_check_mark: | 5b95eb1e | [#1](https://ci.status.im/job/status-mobile/job/prs/job/android/job/PR-14483/1/) | 2022-12-02 16:46:15 | ~7 min | `android` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-221202-163837-5b95eb-pr14483-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-221202-163837-5b95eb-pr14483-universal.apk)|
| :heavy_check_mark: | 5b95eb1e | [#1](https://ci.status.im/job/status-mobile/job/prs/job/android-e2e/job/PR-14483/1/) | 2022-12-02 16:46:41 | ~8 min | `android-e2e` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-221202-163837-5b95eb-pr14483-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-221202-163837-5b95eb-pr14483-x86.apk)|
| :heavy_check_mark: | 5b95eb1e | [#1](https://ci.status.im/job/status-mobile/job/prs/job/ios/job/PR-14483/1/) | 2022-12-02 16:51:15 | ~12 min | `ios` | [:iphone:`ipa`](https://i.diawi.com/yH7cRa) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2FyH7cRa)|
</details>

| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 57e0ba53 | [#2](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-14483/2/) | 2022-12-16 18:13:44 | ~2 min | `tests` | [:page_facing_up:`log`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-221216-181104-57e0ba-pr14483-tests.log) |
| :heavy_check_mark: | 57e0ba53 | [#2](https://ci.status.im/job/status-mobile/job/prs/job/android/job/PR-14483/2/) | 2022-12-16 18:18:43 | ~7 min | `android` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-221216-181104-57e0ba-pr14483-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-221216-181104-57e0ba-pr14483-universal.apk)|
| :heavy_check_mark: | 57e0ba53 | [#2](https://ci.status.im/job/status-mobile/job/prs/job/android-e2e/job/PR-14483/2/) | 2022-12-16 18:18:58 | ~7 min | `android-e2e` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-221216-181104-57e0ba-pr14483-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-221216-181104-57e0ba-pr14483-x86.apk)|
| :heavy_check_mark: | 57e0ba53 | [#2](https://ci.status.im/job/status-mobile/job/prs/job/ios/job/PR-14483/2/) | 2022-12-16 18:26:42 | ~15 min | `ios` | [:iphone:`ipa`](https://i.diawi.com/nnV3Yi) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2FnnV3Yi)|
| | | | | | | |
| :heavy_check_mark: | bac3abf7 | [#3](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-14483/3/) | 2023-01-04 10:43:52 | ~2 min | `tests` | [:page_facing_up:`log`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230104-104139-bac3ab-pr14483-tests.log) |
| :heavy_check_mark: | bac3abf7 | [#3](https://ci.status.im/job/status-mobile/job/prs/job/android-e2e/job/PR-14483/3/) | 2023-01-04 10:50:33 | ~8 min | `android-e2e` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230104-104139-bac3ab-pr14483-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-230104-104139-bac3ab-pr14483-x86.apk)|
| :heavy_check_mark: | bac3abf7 | [#3](https://ci.status.im/job/status-mobile/job/prs/job/android/job/PR-14483/3/) | 2023-01-04 10:50:41 | ~9 min | `android` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230104-104139-bac3ab-pr14483-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-230104-104139-bac3ab-pr14483-universal.apk)|
| :heavy_check_mark: | bac3abf7 | [#3](https://ci.status.im/job/status-mobile/job/prs/job/ios/job/PR-14483/3/) | 2023-01-04 10:58:23 | ~16 min | `ios` | [:iphone:`ipa`](https://i.diawi.com/ATC4yH) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2FATC4yH)|

2022-12-16 18:24 UTC, flexsurfer requested changes
i think Keycard shouldn't be translated?

2023-01-04 09:39 UTC, flexsurfer commented
ping @jinhojang6 , i found that "Keycard" word is translated to russian , but it should stay untranslated because its a name

2023-01-04 10:06 UTC, jinhojang6 commented
Thanks for letting me know @flexsurfer . Let me remove the Russian update from this pull request.

2023-01-04 11:18 UTC, flexsurfer approved these changes

2023-01-04 11:18 UTC, merged