[Update][#14555] Channel name update in Context Tag
status-im/status-react pull request #14578
Opened 2022-12-19 18:13 UTC by smohamedjavid

fixes #14555

### Summary

A minor UI update on the `Context Tag` component to support channel name as this component is extensively used on Activity Center.

#### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Navigate to `Quo2 Preview`
- Open `Context-Tag` under the `tags` section

status: ready

2022-12-19 18:14 UTC, jo-mut approved these changes

2022-12-19 18:15 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 255714e7 | [#1](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-14578/1/) | 2022-12-19 18:15:44 | ~2 min | `tests` | [:page_facing_up:`log`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-221219-181326-255714-pr14578-tests.log) |

2022-12-19 18:18 UTC, ibrkhalil approved these changes
Non blocking comments

2022-12-19 18:18 UTC, ibrkhalil commented on src/quo2/components/tags/context_tags.cljs
> +         [text/text text-params (str "#" " " channel-name)]])]]))
Can we change `(str "#" " " channel-name)` to `(str "# " channel-name)` for better readability please ?

2022-12-19 18:18 UTC, ibrkhalil commented on src/quo2/components/tags/context_tags.cljs
> +      [text/text text-params (str " " name)]
Do we need a `(when name ...` to check if name is `nil`, Like we did for `channel-name`?

2022-12-19 18:18 UTC, ibrkhalil commented on src/quo2/components/tags/context_tags.cljs
> +                           {:style (merge text-style {:justify-content :center})})
We can use `assoc` instead of `merge` here

2022-12-19 18:21 UTC, flexsurfer requested changes

2022-12-19 18:21 UTC, flexsurfer commented on src/quo2/components/tags/context_tags.cljs
> +  (let [text-style (params :text-style)
it's always better to have a keyword as a function

2022-12-19 18:21 UTC, flexsurfer commented on src/quo2/components/tags/context_tags.cljs
> +        text-params (merge {:weight :medium
what's the point of merge here?

2022-12-19 18:21 UTC, flexsurfer commented on src/quo2/components/tags/context_tags.cljs
> +          :main-icons/chevron-right
:i/chevron-right

2022-12-19 18:21 UTC, flexsurfer commented on src/quo2/components/tags/context_tags.cljs
> +           :width  16
there are no width and height, only one prop :size

2022-12-19 18:38 UTC, smohamedjavid commented on src/quo2/components/tags/context_tags.cljs
> +         [text/text text-params (str "#" " " channel-name)]])]]))
done.

2022-12-19 18:39 UTC, smohamedjavid commented on src/quo2/components/tags/context_tags.cljs
> +      [text/text text-params (str " " name)]
I believe it's not required for this component.

2022-12-19 19:14 UTC, flexsurfer commented on src/quo2/components/tags/context_tags.cljs
> +    (let [text-style (params :text-style)
`(:text-style params )`

2022-12-20 08:10 UTC, flexsurfer commented on src/quo2/components/tags/context_tags.cljs
> +  (fn [params photo name channel-name]
sorry for the late comment, but it's better to have only one parameter and destructure it, also `params ` is a strange name, what do we have params inside params ? could we give it some meaningful name

2022-12-20 11:50 UTC, smohamedjavid commented on src/quo2/components/tags/context_tags.cljs
> +  (fn [params photo name channel-name]
No worries @flexsurfer. The issue intends to add support for displaying the channel name in the existing `Context Tag` component (additional args in the component). There are no `params` inside `params`, it's a prop for the tag component. Based on my observation from the existing codebase, the name is separated from the prop/map to make use of passing common props.

![Screenshot 2022-12-20 at 5 17 14 PM](https://user-images.githubusercontent.com/19339952/208659818-2bd35bbb-f3a9-4cfa-a1f2-365dc90f4755.png)

I agree to have one parameter and de-structure it.
We changed it, I have to make changes across the code. Let me know your thoughts.

2022-12-20 13:08 UTC, flexsurfer approved these changes

2022-12-20 13:08 UTC, flexsurfer commented on src/quo2/components/tags/context_tags.cljs
> +  (fn [params photo name channel-name]
not in this PR :)

2022-12-21 12:03 UTC, merged