navigate to community home screen
status-im/status-react pull request #15498
Opened 2023-03-27 13:55 UTC by jo-mut

fixes #15491

### Summary
This PR directs user to communities home screen after enable notifications.

2023-03-27 14:00 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | 927805b3 | [#1](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-15498/1/) | 2023-03-27 14:00:00 | ~3 min | `tests` | [:page_facing_up:`log`](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-15498/1/consoleText) |

2023-03-28 09:51 UTC, flexsurfer commented on src/status_im2/contexts/onboarding/enable_notifications/view.cljs
> +
extra line

2023-03-28 09:53 UTC, Parveshdhull requested changes

2023-03-28 09:53 UTC, Parveshdhull commented on src/status_im2/contexts/shell/view.cljs
> +           show-shell?   (reagent/atom false)]
Hi, we already have functionality to set default selected tab.
Its added to create-only-event, but not sure why that event didn't got called in mentioned issue.
If it follows some other flow or even, please add this change there too
https://github.com/status-im/status-mobile/blob/ac2d10bc5d2001df8a45be1834dc81d3dcbe2ceb/src/status_im/multiaccounts/login/core.cljs#L522

2023-03-29 12:45 UTC, Parveshdhull approved these changes
Thank you for fixing it

2023-03-29 13:36 UTC, briansztamfater approved these changes
LGTM! Please run `make lint-fix` to get rid of linting issues

2023-03-30 08:27 UTC, status-im-auto commented
## 93% of end-end tests have passed
```
Total executed tests: 29
Failed tests: 2
Passed tests: 27
```
```
IDs of failed tests: 702958,702838 
```
<h3>Failed tests (2)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&PR_ID=15498&TR_CASE_IDS=702958,702838">Rerun failed tests</a></li><br/><h4>Class TestCommunityMultipleDeviceMerged:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3124823">test_community_message_send_check_timestamps_sender_username</a>, id: 702838 </b></td></tr><tr><td><p><blockquote><div>Device 2: Verifying that 'hello' is under today </div><div>Device 2: Looking for a message by text: hello </div></blockquote></p>

```
critical/test_public_chat_browsing.py:418: in test_community_message_send_check_timestamps_sender_username
    channel.verify_message_is_under_today_text(message, self.errors)
../views/chat_view.py:923: in verify_message_is_under_today_text
    message_element.wait_for_visibility_of_element()
../views/base_element.py:135: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 2: ChatElementByText by xpath:`//*[starts-with(@text,'hello')]/ancestor::android.view.ViewGroup[@content-desc='chat-item']` is not found on the screen after wait_for_visibility_of_element 
```

<b>[[blocked by 14797]]</b><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/789b1993f79947fab1775e85a7232a98?auth=338476afef9f28cadefc5219e70c1986#158">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/a824bda2a0704375b00e92da5ee3dd12?auth=c5e9312656108730663a821256cac207#103">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestActivityMultipleDevicePR:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3124838">test_activity_center_admin_notification_accept_swipe</a>, id: 702958 </b></td></tr><tr><td><p><blockquote><div>Device 2: ChatMessageInput element not found </div><div>Device 2: Find `Button` by `xpath`: `//*[contains(@text, "View")]` </div></blockquote></p>

```
medium/test_activity_center.py:386: in test_activity_center_admin_notification_accept_swipe
    self.chat_2.element_by_text_part('View').click()
../views/base_element.py:91: in click
    self.find_element().click()
../views/base_element.py:80: in find_element
    raise NoSuchElementException(
 Device 2: Button by xpath: `//*[contains(@text, "View")]` is not found on the screen
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/284146b80b58414183f4978517927dd4?auth=6e998fe9cb95ff808beff0dd6e59c742#319">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/1622f4356f0245bb82c68bdfb3ffe0d6?auth=a093da522cd4df43302548ffd385d2f5#142">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table></details><h3>Passed tests (27)</h3><details><summary>Click to expand</summary><br/><br/><h4>Class TestCommunityOneDeviceMerged:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3124830">test_community_navigate_to_channel_when_relaunch</a>, id: 702846 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/9ee2dfcabce04d8ba90daddfac0cf414?auth=fbf5ebd382dd11d7c27f90799065152c#70">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3124814">test_community_copy_and_paste_message_in_chat_input</a>, id: 702742 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/9ee2dfcabce04d8ba90daddfac0cf414?auth=fbf5ebd382dd11d7c27f90799065152c#88">Steps, video, logs</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestActivityMultipleDevicePR:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3124836">test_activity_center_reply_read_unread_delete_filter_swipe</a>, id: 702947 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/284146b80b58414183f4978517927dd4?auth=6e998fe9cb95ff808beff0dd6e59c742#179">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/1622f4356f0245bb82c68bdfb3ffe0d6?auth=a093da522cd4df43302548ffd385d2f5#106">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3124835">test_navigation_jump_to</a>, id: 702936 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/284146b80b58414183f4978517927dd4?auth=6e998fe9cb95ff808beff0dd6e59c742#158">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/1622f4356f0245bb82c68bdfb3ffe0d6?auth=a093da522cd4df43302548ffd385d2f5#103">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3124837">test_activity_center_mentions</a>, id: 702957 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/284146b80b58414183f4978517927dd4?auth=6e998fe9cb95ff808beff0dd6e59c742#285">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/1622f4356f0245bb82c68bdfb3ffe0d6?auth=a093da522cd4df43302548ffd385d2f5#122">Steps, video, logs</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestActivityCenterContactRequestMultipleDevicePR:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3124831">test_activity_center_contact_request_decline</a>, id: 702850 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/d221d908aacc4275ae97f1b91e36160e?auth=f0f0a98de0112669cdb35560bf3a4d12#47">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/58e2ce89ec7b4601bd0f8b4b8f546416?auth=9237e9bd144b6c1ee5f26b96e58f6bde#47">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3124832">test_activity_center_contact_request_accept_swipe_mark_all_as_read</a>, id: 702851 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/d221d908aacc4275ae97f1b91e36160e?auth=f0f0a98de0112669cdb35560bf3a4d12#80">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/58e2ce89ec7b4 [...]

2023-03-30 09:09 UTC, VolodLytvynenko commented
Hi @jo-mut thank you for PR. One issue is found:

## ISSUE 1:  The user is not navigated to the communities home page after 'Sign in' flow is passed
#### Steps to reproduce:
1. User_A: Go to profile page -> syncing ->Tap 'Sync a new device' -> tap 'Setup Syncing' button -> Enter user's password -> Tap 'Generate scan' button
2. User_A: Leave the generated code on the screen
3. User_B: Open 'Status' app
4. User_B: Tap 'Sign in'
5. User_B: Enable camera -> point the camera at the generated QR code
6. Pass next onboarding pages


#### Actual result:
The 'jump to'  page is opened after onboarding is passed

https://user-images.githubusercontent.com/52490791/228780361-71c8921e-a278-4674-8ed7-7966c92e68e2.mp4

#### Expected result:
The user is redirected to the communities home page

2023-03-30 12:14 UTC, VladimrLitvinenko commented
Hi, @jo-mut I see some new commits were pushed. Let me know if this PR is ready for tests

2023-03-30 12:19 UTC, jo-mut commented
@VladimrLitvinenko  I will let you know once i am okay with this

2023-03-30 13:36 UTC, jo-mut commented
@VladimrLitvinenko its good now to proceed. I had not resolved this before in the case of scan to login flow but now should be fine in both `scan to login` and `I am new to status`

2023-04-07 14:15 UTC, status-im-auto commented
## 93% of end-end tests have passed
```
Total executed tests: 29
Failed tests: 2
Passed tests: 27
```
```
IDs of failed tests: 702850,702838 
```
<h3>Failed tests (2)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&PR_ID=15498&TR_CASE_IDS=702850,702838">Rerun failed tests</a></li><br/><h4>Class TestCommunityMultipleDeviceMerged:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3126985">test_community_message_send_check_timestamps_sender_username</a>, id: 702838 </b></td></tr><tr><td><p><blockquote><div>Device 2: Verifying that 'hello' is under today </div><div>Device 2: Looking for a message by text: hello </div></blockquote></p>

```
critical/test_public_chat_browsing.py:418: in test_community_message_send_check_timestamps_sender_username
    channel.verify_message_is_under_today_text(message, self.errors)
../views/chat_view.py:923: in verify_message_is_under_today_text
    message_element.wait_for_visibility_of_element()
../views/base_element.py:135: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 2: ChatElementByText by xpath:`//*[starts-with(@text,'hello')]/ancestor::android.view.ViewGroup[@content-desc='chat-item']` is not found on the screen after wait_for_visibility_of_element 
```

<b>[[blocked by 14797]]</b><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/768c0fa45b654dd69f1de57fa9fac202?auth=14654ecaa31a5cd57a5b9010a75ca0bd#171">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/5458d3dbad9948ed83825689a49395cf?auth=5bc82da4f3872b327ad9f4584ab74e37#114">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestActivityCenterContactRequestMultipleDevicePR:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3126993">test_activity_center_contact_request_decline</a>, id: 702850 </b></td></tr><tr><td><p><blockquote><div>Device 2: Find `Button` by `accessibility id`: `tab-recent` </div><div>Device 2: Tap on found: Button </div></blockquote></p>

```
medium/test_activity_center.py:142: in test_activity_center_contact_request_decline
    self.errors.verify_no_errors()
base_test_case.py:184: in verify_no_errors
    pytest.fail('\n '.join([self.errors.pop(0) for _ in range(len(self.errors))]))
 Username is not shown on 'Add contact' page after entering valid public key 
```

<b>[[Blocked by 15500]]</b><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/de4749579d4641deb1bf9b14b76a7861?auth=da815bafbcff9979bf20ad9ff572222c#57">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/6c8c18f51600472f91d3acc3f3610367?auth=c49dfaa6cd5956c9f3089dcee0dfd514#57">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table></details><h3>Passed tests (27)</h3><details><summary>Click to expand</summary><br/><br/><h4>Class TestCommunityMultipleDeviceMerged:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3126987">test_community_emoji_send_copy_paste_reply</a>, id: 702840 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/768c0fa45b654dd69f1de57fa9fac202?auth=14654ecaa31a5cd57a5b9010a75ca0bd#224">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/5458d3dbad9948ed83825689a49395cf?auth=5bc82da4f3872b327ad9f4584ab74e37#153">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3126990">test_community_links_with_previews_github_youtube_twitter_gif_send_enable</a>, id: 702844 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/768c0fa45b654dd69f1de57fa9fac202?auth=14654ecaa31a5cd57a5b9010a75ca0bd#250">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/5458d3dbad9948ed83825689a49395cf?auth=5bc82da4f3872b327ad9f4584ab74e37#168">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3126981">test_community_mentions_push_notification</a>, id: 702786 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/768c0fa45b654dd69f1de57fa9fac202?auth=14654ecaa31a5cd57a5b9010a75ca0bd#417">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/5458d3dbad9948ed83825689a49395cf?auth=5bc82da4f3872b327ad9f4584ab74e37#269">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3126996">test_community_contact_block_unblock_offline</a>, id: 702894 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/768c0fa45b654dd69f1de57fa9fac202?auth=14654ecaa31a5cd57a5b9010a75ca0bd#312">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/5458d3dbad9948ed83825689a49395cf?auth=5bc82da4f3872b327ad9f4584ab74e37#239">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3126991">test_community_leave</a>, id: 702845 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/768c0fa45b654dd69f1de57fa9fac202?auth=14654ecaa31a5cd57a5b9010a75ca0bd#434">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/5458d3dbad9948ed83825689a49395cf?auth=5bc82da4f3872b327ad9f4584ab74e37#292">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>6. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3126988">test_community_unread_messages_badge</a>, id: 702841 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/768c0fa45b654dd69f1de57fa9fac202?auth=14654ecaa31a5cd57a5b9010a75ca0bd#288">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/5458d3dbad9948ed83825689a49395cf?auth=5bc82da4f3872b327ad9f4584ab74e37#231">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>7. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3126986">test_community_message_delete</a>, id: 702839 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/768c0fa45b654dd69f1de57fa9fac202?auth=14654ecaa31a5cd57a5b9010a75ca0bd#206">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/5458d3dbad9948ed83825689a49395cf?auth=5bc82da4f3872b327ad9f4584ab74e37#124">Steps, video, logs</a></li></ul></p></ul></p [...]

2023-04-07 14:21 UTC, VladimrLitvinenko commented
Hi @jo-mut. Thank you for your work. Issue 1 is fixed. No issues from my side. PR is ready to be merged

2023-04-07 14:58 UTC, status-im-auto commented
## 93% of end-end tests have passed
```
Total executed tests: 29
Failed tests: 2
Passed tests: 27
```
```
IDs of failed tests: 702850,702838 
```
<h3>Failed tests (2)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&PR_ID=15498&TR_CASE_IDS=702850,702838">Rerun failed tests</a></li><br/><h4>Class TestCommunityMultipleDeviceMerged:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3127016">test_community_message_send_check_timestamps_sender_username</a>, id: 702838 </b></td></tr><tr><td><p><blockquote><div>Device 2: Verifying that 'hello' is under today </div><div>Device 2: Looking for a message by text: hello </div></blockquote></p>

```
critical/test_public_chat_browsing.py:418: in test_community_message_send_check_timestamps_sender_username
    channel.verify_message_is_under_today_text(message, self.errors)
../views/chat_view.py:923: in verify_message_is_under_today_text
    message_element.wait_for_visibility_of_element()
../views/base_element.py:135: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 2: ChatElementByText by xpath:`//*[starts-with(@text,'hello')]/ancestor::android.view.ViewGroup[@content-desc='chat-item']` is not found on the screen after wait_for_visibility_of_element 
```

<b>[[blocked by 14797]]</b><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/be5fbecc304d4f96a405002d2a250c5b?auth=280ecbdf43e00636ac93332e7119b3af#171">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/d8554d1a49064aa8871a8b79c854099c?auth=5dc213d42a2c686d4e135148c2d9fc81#114">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestActivityCenterContactRequestMultipleDevicePR:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3127024">test_activity_center_contact_request_decline</a>, id: 702850 </b></td></tr><tr><td><p><blockquote><div>Device 2: Find `Button` by `accessibility id`: `tab-recent` </div><div>Device 2: Tap on found: Button </div></blockquote></p>

```
medium/test_activity_center.py:142: in test_activity_center_contact_request_decline
    self.errors.verify_no_errors()
base_test_case.py:184: in verify_no_errors
    pytest.fail('\n '.join([self.errors.pop(0) for _ in range(len(self.errors))]))
 Username is not shown on 'Add contact' page after entering valid public key 
```

<b>[[Blocked by 15500]]</b><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/d5637e0e94e24322b9bd6f85932ac684?auth=76aa178fa901c20d46d251fb8c9d9478#57">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/9992c95d13594e6c9573df6572080bae?auth=78f3862be5c36111238c613ce7c712d4#57">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table></details><h3>Passed tests (27)</h3><details><summary>Click to expand</summary><br/><br/><h4>Class TestCommunityOneDeviceMerged:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3127023">test_community_navigate_to_channel_when_relaunch</a>, id: 702846 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/7268a0db6e4147b792a036a1591a9900?auth=f9c76053bbc118e7ef135117f874564a#81">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3127007">test_community_copy_and_paste_message_in_chat_input</a>, id: 702742 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/7268a0db6e4147b792a036a1591a9900?auth=f9c76053bbc118e7ef135117f874564a#99">Steps, video, logs</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestGroupChatMultipleDeviceMergedNewUI:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3127005">test_group_chat_pin_messages</a>, id: 702732 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/aeafe496b036438fb204f878adcc0b75?auth=267ecf98e5556fbad2fee63c5c3f5589#182">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/a404eef4e5d749e4b0754ad6c3e3082e?auth=884691485e3ca5714b0a66e85e1797c9#114">Steps, video, logs</a></li></ul></p><p>Device 3:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/9216937cfc324602b7ac522d73d4f1f7?auth=a3dd32c84508ebf7c1fdb8403a230d8b#93">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3127013">test_group_chat_join_send_text_messages_push</a>, id: 702807 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/aeafe496b036438fb204f878adcc0b75?auth=267ecf98e5556fbad2fee63c5c3f5589#123">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/a404eef4e5d749e4b0754ad6c3e3082e?auth=884691485e3ca5714b0a66e85e1797c9#69">Steps, video, logs</a></li></ul></p><p>Device 3:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/9216937cfc324602b7ac522d73d4f1f7?auth=a3dd32c84508ebf7c1fdb8403a230d8b#69">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3127014">test_group_chat_offline_pn</a>, id: 702808 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/aeafe496b036438fb204f878adcc0b75?auth=267ecf98e5556fbad2fee63c5c3f5589#137">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/a404eef4e5d749e4b0754ad6c3e3082e?auth=884691485e3ca5714b0a66e85e1797c9#94">Steps, video, logs</a></li></ul></p><p>Device 3:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/9216937cfc324602b7ac522d73d4f1f7?auth=a3dd32c84508ebf7c1fdb8403a230d8b#74">Steps, video, logs</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestCommunityMultipleDeviceMerged:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3127018">test_community_emoji_send_copy_paste_reply</a>, id: 702840 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/be5fbecc304d4f96a405002d2a250c5b?auth=280ecbdf43e00636ac93332e7119b3af#224">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/d8554d1a49064aa8871a8b79c854099c?auth=5dc213d42a2c686d4e135148c2d9fc81#153">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr>< [...]

2023-04-07 23:45 UTC, merged