[Fix] QR scanner scanning QR when user moved to next screen
status-im/status-react pull request #16012
Opened 2023-05-24 14:56 UTC by smohamedjavid

fixes #15970

### Summary

This PR fixes the QR scanner that scans the QR code when the user is moved to the next screen (`:syncing-progress`). 

The bug was caused when due to the navigational stack. The "QR scanner" screen will be behind the "Syncing devices" screen, and the QR scanner reset after 3 seconds to scan/process any QR code. The fix was to ensure the scanner scan/process the data only when the user is on the "QR scanner" screen.

### Platforms

- Android
- iOS

### Steps to test

- Open Status
- Navigate to `Sign in`
- Enable access to the camera
- Point the camera at an invalid QR code. (for instance, a QR code that has been used before)
- Check if the user gets redirected again to the `Something went wrong` screen more than once.

status: ready

2023-05-24 15:03 UTC, status-im-auto commented
### Jenkins Builds
<details>
<summary>Click to see older builds (12)</summary>

| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | e248993f | [#1](https://ci.status.im/job/status-mobile/job/prs/job/android-e2e/job/PR-16012/1/) | 2023-05-24 15:03:47 | ~6 min | `android-e2e` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230524-145709-e24899-pr16012-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-230524-145709-e24899-pr16012-x86.apk)|
| :heavy_check_mark: | e248993f | [#1](https://ci.status.im/job/status-mobile/job/prs/job/android/job/PR-16012/1/) | 2023-05-24 15:03:50 | ~6 min | `android` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230524-145709-e24899-pr16012-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-230524-145709-e24899-pr16012-universal.apk)|
| :heavy_check_mark: | e248993f | [#1](https://ci.status.im/job/status-mobile/job/prs/job/ios/job/PR-16012/1/) | 2023-05-24 15:04:18 | ~7 min | `ios` | [:iphone:`ipa`](https://i.diawi.com/GwvHJc) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2FGwvHJc)|
| :heavy_check_mark: | e248993f | [#1](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-16012/1/) | 2023-05-24 15:05:09 | ~7 min | `tests` | [:page_facing_up:`log`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230524-145714-e24899-pr16012-tests.log) |
| | | | | | | |
| :heavy_check_mark: | fa5d3a22 | [#2](https://ci.status.im/job/status-mobile/job/prs/job/android/job/PR-16012/2/) | 2023-05-25 14:45:39 | ~5 min | `android` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230525-143954-fa5d3a-pr16012-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-230525-143954-fa5d3a-pr16012-universal.apk)|
| :heavy_check_mark: | fa5d3a22 | [#2](https://ci.status.im/job/status-mobile/job/prs/job/android-e2e/job/PR-16012/2/) | 2023-05-25 14:45:59 | ~6 min | `android-e2e` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230525-143954-fa5d3a-pr16012-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-230525-143954-fa5d3a-pr16012-x86.apk)|
| :heavy_check_mark: | fa5d3a22 | [#2](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-16012/2/) | 2023-05-25 14:48:15 | ~8 min | `tests` | [:page_facing_up:`log`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230525-143954-fa5d3a-pr16012-tests.log) |
| :heavy_check_mark: | fa5d3a22 | [#2](https://ci.status.im/job/status-mobile/job/prs/job/ios/job/PR-16012/2/) | 2023-05-25 15:29:12 | ~49 min | `ios` | [:iphone:`ipa`](https://i.diawi.com/suYir6) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2FsuYir6)|
| | | | | | | |
| :heavy_check_mark: | 1197087e | [#3](https://ci.status.im/job/status-mobile/job/prs/job/ios/job/PR-16012/3/) | 2023-05-29 08:32:20 | ~6 min | `ios` | [:iphone:`ipa`](https://i.diawi.com/Lkz8EH) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2FLkz8EH)|
| :heavy_check_mark: | 1197087e | [#3](https://ci.status.im/job/status-mobile/job/prs/job/android/job/PR-16012/3/) | 2023-05-29 08:32:36 | ~6 min | `android` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230529-082610-119708-pr16012-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-230529-082610-119708-pr16012-universal.apk)|
| :heavy_check_mark: | 1197087e | [#3](https://ci.status.im/job/status-mobile/job/prs/job/android-e2e/job/PR-16012/3/) | 2023-05-29 08:32:39 | ~6 min | `android-e2e` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230529-082610-119708-pr16012-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-230529-082610-119708-pr16012-x86.apk)|
| :heavy_check_mark: | 1197087e | [#3](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-16012/3/) | 2023-05-29 08:34:51 | ~8 min | `tests` | [:page_facing_up:`log`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230529-082610-119708-pr16012-tests.log) |
</details>

| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | ec7a57a2 | [#5](https://ci.status.im/job/status-mobile/job/prs/job/ios/job/PR-16012/5/) | 2023-05-30 11:01:11 | ~5 min | `ios` | [:iphone:`ipa`](https://i.diawi.com/6K76x7) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2F6K76x7)|
| :heavy_check_mark: | ec7a57a2 | [#5](https://ci.status.im/job/status-mobile/job/prs/job/android/job/PR-16012/5/) | 2023-05-30 11:02:27 | ~7 min | `android` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230530-105512-ec7a57-pr16012-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-230530-105512-ec7a57-pr16012-universal.apk)|
| :heavy_check_mark: | ec7a57a2 | [#5](https://ci.status.im/job/status-mobile/job/prs/job/android-e2e/job/PR-16012/5/) | 2023-05-30 11:07:16 | ~12 min | `android-e2e` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230530-105512-ec7a57-pr16012-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-230530-105512-ec7a57-pr16012-x86.apk)|
| :heavy_check_mark: | ec7a57a2 | [#5](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-16012/5/) | 2023-05-30 11:08:01 | ~12 min | `tests` | [:page_facing_up:`log`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230530-105512-ec7a57-pr16012-tests.log) |
| | | | | | | |
| :heavy_check_mark: | 8af64025 | [#6](https://ci.status.im/job/status-mobile/job/prs/job/android/job/PR-16012/6/) | 2023-05-30 15:54:18 | ~5 min | `android` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230530-154858-8af640-pr16012-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-230530-154858-8af640-pr16012-universal.apk)|
| :heavy_check_mark: | 8af64025 | [#6](https://ci.status.im/job/status-mobile/job/prs/job/android-e2e/job/PR-16012/6/) | 2023-05-30 15:54:54 | ~5 min | `android-e2e` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230530-154858-8af640-pr16012-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-230530-154858-8af640-pr16012-x86.apk)|
| :heavy_check_mark: | 8af64025 | [#6](https://ci.status.im/job/status-mobile/job/prs/job/ios/j [...]

2023-05-24 15:10 UTC, jo-mut approved these changes

2023-05-25 04:54 UTC, flexsurfer requested changes

2023-05-25 04:54 UTC, flexsurfer commented on src/status_im2/contexts/syncing/scan_sync_code/view.cljs
> +            user-in-syncing-progress-screen? (= view-id :syncing-progress)
i believe is the proper solution to close qr screen. why is it active?

2023-05-25 14:38 UTC, smohamedjavid commented
> i believe is the proper solution to close qr screen. why is it active?

@flexsurfer 

This is due to the navigational structure of the stack navigation.

Let's say we have screens A, B, C,...etc.

On stack navigation, when the user moves from `A -> B`, the screen `B` is added to the top of the stack (which is visible to the user). When the user navigates back, the screen B is popped from the stack. The previous screen (`A`) is visible to the user.

That's why the camera on the previous screen is active. Once the syncing is completed successfully, we reset the whole stack with `:init-root`. That's where the screen so far the user has been destroyed.

When the QR scans any sync code, it moves to `:syncing-progress` screen. Here, the syncing can be successful or not. In case of not successful, we should allow the user to go back.

To prevent the QR scanner to process any further data. I believe checking the `view-id` would be the best solution.

2023-05-26 11:31 UTC, flexsurfer approved these changes

2023-05-26 13:58 UTC, status-im-auto commented
## 82% of end-end tests have passed
```
Total executed tests: 33
Failed tests: 6
Passed tests: 27
```
```
IDs of failed tests: 702840,702851,702947,702731,702838,702783 
```
<h3>Failed tests (6)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&PR_ID=16012&TR_CASE_IDS=702840,702851,702947,702731,702838,702783">Rerun failed tests</a></li><br/><h4>Class TestOneToOneChatMultipleSharedDevicesNewUi:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3155213">test_1_1_chat_pin_messages</a>, id: 702731 </b></td></tr><tr><td><p><blockquote><div>Device 1: Find `Text` by `xpath`: `//*[starts-with(@text,'Message 3')]/ancestor::android.view.ViewGroup[@content-desc='chat-item']` </div><div>Device 1: Tap on found: Text </div></blockquote></p>

```
critical/chats/test_1_1_public_chats.py:979: in test_1_1_chat_pin_messages
    self.chat_1.chat_element_by_text(message).wait_for_status_to_be("Delivered")
../views/chat_view.py:227: in wait_for_status_to_be
    raise TimeoutException("Message status was not changed to %s" % expected_status)
 Message status was not changed to Delivered
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/bfd6eb7cdf3d4c5593508240b5c19507?auth=da8c77699914888c9372ab8e3ec02b19#151">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/cf79b7bf06354342a1f34ac34d15a275?auth=268daa25dbfe340c82812e10fe2f2823#116">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3155219">test_1_1_chat_is_shown_message_sent_delivered_from_offline</a>, id: 702783 </b></td></tr><tr><td><p><blockquote><div># STEP: Device1 goes back online and checks that 1-1 chat will be fetched</div><div>Device 1: Looking for a message by text: test message </div></blockquote></p>

```
critical/chats/test_1_1_public_chats.py:1230: in test_1_1_chat_is_shown_message_sent_delivered_from_offline
    self.errors.verify_no_errors()
base_test_case.py:184: in verify_no_errors
    pytest.fail('\n '.join([self.errors.pop(0) for _ in range(len(self.errors))]))
 Message status was not delivered after back up online, it is "Sending"!
E    Message was not delivered after resending from offline
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/bfd6eb7cdf3d4c5593508240b5c19507?auth=da8c77699914888c9372ab8e3ec02b19#439">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/cf79b7bf06354342a1f34ac34d15a275?auth=268daa25dbfe340c82812e10fe2f2823#330">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestCommunityMultipleDeviceMerged:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3155227">test_community_emoji_send_copy_paste_reply</a>, id: 702840 </b></td></tr><tr><td><p><blockquote><div>Device 2: Quoting '♻' message </div><div>Device 2: Find `Button` by `xpath`: `//*[contains(@text, "♻")]` </div></blockquote></p>

```
critical/test_public_chat_browsing.py:584: in test_community_emoji_send_copy_paste_reply
    self.channel_2.quote_message(emoji_unicode)
../views/chat_view.py:994: in quote_message
    self.element_by_text_part(message).long_press_until_element_is_shown(self.reply_message_button)
../views/base_element.py:298: in long_press_until_element_is_shown
    element = self.find_element()
../views/base_element.py:80: in find_element
    raise NoSuchElementException(
 Device 2: Button by xpath: `//*[contains(@text, "♻")]` is not found on the screen
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/ad258d6be7bc474e861b12f7aca6c11f?auth=9f6cd4c3951d0c9a82d06b407d0be3e3#246">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/27c8d5c5ba584469aa0efd08481deed8?auth=9ac151a32543dca4716e74f8a381cbe2#190">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3155225">test_community_message_send_check_timestamps_sender_username</a>, id: 702838 </b></td></tr><tr><td><p><blockquote><div>Device 2: Verifying that 'hello' is under today </div><div>Device 2: Looking for a message by text: hello </div></blockquote></p>

```
critical/test_public_chat_browsing.py:456: in test_community_message_send_check_timestamps_sender_username
    channel.verify_message_is_under_today_text(message, self.errors)
../views/chat_view.py:944: in verify_message_is_under_today_text
    message_element.wait_for_visibility_of_element()
../views/base_element.py:135: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 2: ChatElementByText by xpath:`//*[starts-with(@text,'hello')]/ancestor::android.view.ViewGroup[@content-desc='chat-item']` is not found on the screen after wait_for_visibility_of_element 
```

<b>[[blocked by 14797]]</b><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/ad258d6be7bc474e861b12f7aca6c11f?auth=9f6cd4c3951d0c9a82d06b407d0be3e3#143">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/27c8d5c5ba584469aa0efd08481deed8?auth=9ac151a32543dca4716e74f8a381cbe2#103">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestActivityMultipleDevicePR:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3155239">test_activity_center_reply_read_unread_delete_filter_swipe</a>, id: 702947 </b></td></tr><tr><td><p><blockquote><div>Device 2: Tap on found: SendMessageButton </div><div># STEP: Checking unread indicators</div></blockquote></p>

```
medium/test_activity_center.py:188: in test_activity_center_reply_read_unread_delete_filter_swipe
    self.home_1.notifications_unread_badge.wait_for_visibility_of_element(120)
../views/base_element.py:135: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 1: BaseElement by accessibility id:`activity-center-unread-count` is not found on the screen after wait_for_visibility_of_element
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/0041b4fab3f94b90a72153267c04e1fd?auth=db34b169ad67b847b5c963d8101c48f6#162">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/6b6498a179ff49fe8ebd170841 [...]

2023-05-29 15:03 UTC, status-im-auto commented
## 100% of end-end tests have passed
```
Total executed tests: 2
Failed tests: 0
Passed tests: 2
```
<h3>Passed tests (2)</h3><details><summary>Click to expand</summary><br/><br/><h4>Class TestActivityCenterContactRequestMultipleDevicePR:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3155812">test_activity_center_contact_request_accept_swipe_mark_all_as_read</a>, id: 702851 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/4a737469eef74fe99018eef39a5d7fe7?auth=f52d59563226bc4f108b2c99207e5b90#55">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/f10a884115884e3db799e8479a34aeba?auth=7e3d1d0a93970cfa463127d845c4202e#55">Steps, video, logs</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestActivityMultipleDevicePR:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3155813">test_activity_center_reply_read_unread_delete_filter_swipe</a>, id: 702947 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/9a331090ed274088a02caef5e381477b?auth=8d556688767d3cc64a6b72c0ca63d2fe#141">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/157b4eb05524466c817c7ede0c49c12c?auth=216f21d1abff6cf910c7c03f4bf3c376#102">Steps, video, logs</a></li></ul></p></ul></p></td></tr></tbody></table></details>

2023-05-29 15:17 UTC, VladimrLitvinenko commented
Hi @smohamedjavid . Thank you for PR. 
The issue is still reproducible
## ISSUE 1: Continuous QR code scanning even after "Oops something wrong" page is displayed

### Steps to reproduce:
1. Point the camera at an invalid QR code. (In this case, use the sync code that has been used before)
2. Do not tap the "Try again" button and keep the camera pointed at the QR code when the "Oops something wrong" page is displayed.

### Actual result:
The IOS device continues to scan the QR code.

(I don't tap 'try again' button on the record)

https://github.com/status-im/status-mobile/assets/52490791/b179f802-503e-4467-8b15-d27fcc571b7d



### Expected result:
The IOS device should stop scanning the QR code until the "Try again" button is tapped.

### Device:
- iPhone 11 Pro Max, iOS 16

2023-05-30 11:28 UTC, smohamedjavid commented
@VladimrLitvinenko - Kindly retest.

2023-05-30 13:47 UTC, status-im-auto commented
## 67% of end-end tests have passed
```
Total executed tests: 33
Failed tests: 11
Passed tests: 22
```
```
IDs of failed tests: 703133,702732,702894,702782,703086,702731,702807,702784,702838,702958,702745 
```
<h3>Failed tests (11)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&PR_ID=16012&TR_CASE_IDS=703133,702732,702894,702782,703086,702731,702807,702784,702838,702958,702745">Rerun failed tests</a></li><br/><h4>Class TestGroupChatMultipleDeviceMergedNewUI:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3156106">test_group_chat_pin_messages</a>, id: 702732 </b></td></tr><tr><td><p><blockquote><div>Device 2: Find `Text` by `xpath`: `//*[@content-desc='pinned-messages-menu']//*[starts-with(@text,'Message 4')]/../../*[@content-desc='pinned-by']/android.widget.TextView` </div><div>Device 2: `Text` is `user admin` </div></blockquote></p>

```
critical/chats/test_group_chat.py:337: in test_group_chat_pin_messages
    self.errors.verify_no_errors()
base_test_case.py:184: in verify_no_errors
    pytest.fail('\n '.join([self.errors.pop(0) for _ in range(len(self.errors))]))
 Message 2 is not pinned in group chat!
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/5ff71d0684834e469fe1ae88fb633ef9?auth=11fec78fdb891afabc07060bfa94a515#178">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/6dbfd67cc9414c509fb99c9749b029cd?auth=72dd115f3b0b0640db6159f5bcc01716#203">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 3:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/cdecf600981844a38cae1618335e2c94?auth=773ba397a739fea6edf85ca3092a397d#91">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3156114">test_group_chat_join_send_text_messages_push</a>, id: 702807 </b></td></tr><tr><td><p><blockquote><div>Device 2: Find `Text` by `xpath`: `//*[starts-with(@text,'Hey, admin!')]/ancestor::android.view.ViewGroup[@content-desc='chat-item']//*[@content-desc='message-status']/android.widget.TextView` </div><div>Device 2: `Text` is `Sent` </div></blockquote></p>

```
critical/chats/test_group_chat.py:224: in test_group_chat_join_send_text_messages_push
    self.chats[1].chat_element_by_text(message_to_admin).wait_for_status_to_be('Delivered', timeout=120)
../views/chat_view.py:227: in wait_for_status_to_be
    raise TimeoutException("Message status was not changed to %s" % expected_status)
 Message status was not changed to Delivered
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/5ff71d0684834e469fe1ae88fb633ef9?auth=11fec78fdb891afabc07060bfa94a515#121">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/6dbfd67cc9414c509fb99c9749b029cd?auth=72dd115f3b0b0640db6159f5bcc01716#68">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 3:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/cdecf600981844a38cae1618335e2c94?auth=773ba397a739fea6edf85ca3092a397d#67">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestActivityMultipleDevicePR:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3156133">test_activity_center_admin_notification_accept_swipe</a>, id: 702958 </b></td></tr><tr><td><p><blockquote><div>Device 2: Tap on found: Button </div><div>Device 2: Click until `Button` by `accessibility id`: `jump-to` will be presented </div></blockquote></p>

```
medium/test_activity_center.py:292: in test_activity_center_admin_notification_accept_swipe
    [home.jump_to_communities_home() for home in (self.home_1, self.home_2)]
medium/test_activity_center.py:292: in <listcomp>
    [home.jump_to_communities_home() for home in (self.home_1, self.home_2)]
../views/base_view.py:606: in jump_to_communities_home
    self.communities_tab.click_until_presence_of_element(self.jump_to_button)
../views/base_element.py:99: in click_until_presence_of_element
    while not desired_element.is_element_displayed(1) and counter <= attempts:
../views/base_element.py:193: in is_element_displayed
    return self.wait_for_visibility_of_element(sec, ignored_exceptions=ignored_exceptions)
../views/base_element.py:133: in wait_for_visibility_of_element
    .until(expected_conditions.visibility_of_element_located((self.by, self.locator)))
/home/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/support/wait.py:71: in until
    value = method(self._driver)
/home/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/support/expected_conditions.py:128: in __call__
    return _element_if_visible(_find_element(driver, self.locator))
/home/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/support/expected_conditions.py:148: in _element_if_visible
    return element if element.is_displayed() == visibility else False
 'dict' object has no attribute 'is_displayed'
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/71ed3e9ee2c24a9dbef8e8c21533f673?auth=91063f74eb67ebe60b1339e6e1cc3ca0#306">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/adc91a9cebc5488c8755766ad69432e1?auth=f769c633207ddfd8236f8a230bae5b0b#144">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestCommunityMultipleDeviceMerged:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3156129">test_community_contact_block_unblock_offline</a>, id: 702894 </b></td></tr><tr><td><p><blockquote><div>Device 1: Tap on found: ProfileSendMessageButton </div><div>Device 1: Sending message 'piy' </div></blockquote></p>

```
critical/test_public_chat_browsing.py:741: in test_community_contact_block_unblock_offline
    self.chat_1.send_message("piy")
../views/chat_view.py:954: in send_message
    self.chat_message_input.wait_for_element(wait_chat_input_sec)
../views/base_element.py:117: in wait_for_element
    raise TimeoutException(
 Device `1`: `ChatMessageInput` by` accessibility id`: `chat-message-input` is not found on the screen after wait_for_element
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/be9e3d2e4bb345c18e505f9aad05e773?auth=713b3ac5c674947d8a79649a797fcf34#319">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/b766e908 [...]

2023-05-30 15:27 UTC, status-im-auto commented
## 85% of end-end tests have passed
```
Total executed tests: 33
Failed tests: 5
Passed tests: 28
```
```
IDs of failed tests: 703133,702732,702807,702838,702808 
```
<h3>Failed tests (5)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&PR_ID=16012&TR_CASE_IDS=703133,702732,702807,702838,702808">Rerun failed tests</a></li><br/><h4>Class TestCommunityOneDeviceMerged:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3156261">test_restore_multiaccount_with_waku_backup_remove_switch</a>, id: 703133 </b></td></tr><tr><td><p><blockquote><div>Device 1: Wait for element `Button` for max 30s and click when it is available </div><div>Device 1: Find `Button` by `accessibility id`: `skip-identifiers` </div></blockquote></p>

```
critical/test_public_chat_browsing.py:354: in test_restore_multiaccount_with_waku_backup_remove_switch
    self.sign_in.recover_access(passphrase=waku_user.seed, second_user=True)
../views/sign_in_view.py:265: in recover_access
    self.identifiers_button.wait_and_click(30)
../views/base_element.py:404: in wait_and_click
    self.click()
../views/base_element.py:91: in click
    self.find_element().click()
../views/base_element.py:80: in find_element
    raise NoSuchElementException(
 Device 1: Button by accessibility id: `skip-identifiers` is not found on the screen
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/f159f1be0a83485b8d23afa68699a2ef?auth=6c2831f4394fc80a1336f208fff91cf6#117">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestCommunityMultipleDeviceMerged:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3156243">test_community_message_send_check_timestamps_sender_username</a>, id: 702838 </b></td></tr><tr><td><p><blockquote><div>Device 2: Verifying that 'hello' is under today </div><div>Device 2: Looking for a message by text: hello </div></blockquote></p>

```
critical/test_public_chat_browsing.py:456: in test_community_message_send_check_timestamps_sender_username
    channel.verify_message_is_under_today_text(message, self.errors)
../views/chat_view.py:944: in verify_message_is_under_today_text
    message_element.wait_for_visibility_of_element()
../views/base_element.py:135: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 2: ChatElementByText by xpath:`//*[starts-with(@text,'hello')]/ancestor::android.view.ViewGroup[@content-desc='chat-item']` is not found on the screen after wait_for_visibility_of_element 
```

<b>[[blocked by 14797]]</b><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/99fb0d92b3854f3ca802fbf5cdffa55d?auth=6461a1d3433182caa8c0e85c0d322481#144">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/be0352deafa94e5596db1abc926f087a?auth=8599f86ec164635628299e1d62e09435#103">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestGroupChatMultipleDeviceMergedNewUI:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3156232">test_group_chat_pin_messages</a>, id: 702732 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_group_chat.py:154: in prepare_devices
    self.loop.run_until_complete(
/usr/lib/python3.10/asyncio/base_events.py:646: in run_until_complete
    return future.result()
__init__.py:36: in run_in_parallel
    returns.append(await k)
/usr/lib/python3.10/concurrent/futures/thread.py:58: in run
    result = self.fn(*self.args, **self.kwargs)
../views/sign_in_view.py:224: in create_user
    self.i_m_new_in_status_button.click_until_presence_of_element(self.generate_keys_button)
../views/base_element.py:99: in click_until_presence_of_element
    while not desired_element.is_element_displayed(1) and counter <= attempts:
../views/base_element.py:193: in is_element_displayed
    return self.wait_for_visibility_of_element(sec, ignored_exceptions=ignored_exceptions)
../views/base_element.py:133: in wait_for_visibility_of_element
    .until(expected_conditions.visibility_of_element_located((self.by, self.locator)))
/home/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/support/wait.py:71: in until
    value = method(self._driver)
/home/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/support/expected_conditions.py:128: in __call__
    return _element_if_visible(_find_element(driver, self.locator))
/home/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/support/expected_conditions.py:415: in _find_element
    raise e
/home/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/support/expected_conditions.py:411: in _find_element
    return driver.find_element(*by)
/home/jenkins/.local/lib/python3.10/site-packages/appium/webdriver/webdriver.py:414: in find_element
    return self.execute(RemoteCommand.FIND_ELEMENT, {'using': by, 'value': value})['value']
/home/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:321: in execute
    self.error_handler.check_response(response)
/home/jenkins/.local/lib/python3.10/site-packages/appium/webdriver/errorhandler.py:31: in check_response
    raise wde
/home/jenkins/.local/lib/python3.10/site-packages/appium/webdriver/errorhandler.py:26: in check_response
    super().check_response(response)
/home/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py:242: in check_response
    raise exception_class(message, screen, stacktrace)
 session backend not connected
```

<br/><br/></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3156240">test_group_chat_join_send_text_messages_push</a>, id: 702807 </b></td></tr><tr><td><p><blockquote><div>## Creating new multiaccount (password:'qwerty1234', keycard:'False', enable_notification: 'True')</div><div>Device 3: Click until `Button` by `xpath`: `//*[@text="Generate keys"]` will be presented </div></blockquote></p>

```
Test setup failed: critical/chats/test_group_chat.py:154: in prepare_devices
    self.loop.run_until_complete(
/usr/lib/python3.10/asyncio/base_events.py:646: in run_until_complete
    return future.result()
__init__.py:36: in run_in_parallel
    returns.append(await k)
/usr/lib/python3.10/concurrent/futures/thread.py:58: in run
    result = self.fn(*self.args, **self.kwargs)
../views/sign_in_view.py:224: in create_user
    self.i_m_new_in_status_button.click_until_presence_of_element(self.generate_keys_button)
../views/base_element.py:99: in click_until_presence_of_element
    while not desired_element.is_element_displayed(1) and counter <= attempts:
../views/base_element.py:193: in is_element_displayed
    return self.wait_for_visibility_of_element(sec, ignored_exceptions=ignored_exceptions)
../views/base_element.py:133: in wait_for_visibility_of_element
    .until(expected_conditions.visibility_of_element_located((self.by, self.locator)))
/home/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/support/wait.py:71: in until
    value = method(self._driver)
/home/jenkins/.local/lib/python3. [...]

2023-05-30 15:37 UTC, VladimrLitvinenko commented
hi @smohamedjavid Thank you for the fixes. PR is ready to be merged

2023-05-30 15:58 UTC, merged