[Fix] Nav bar overlap in "Syncing" screen
status-im/status-react pull request #16014
Opened 2023-05-24 15:40 UTC by smohamedjavid

fixes #16011

### Summary

This PR fixes the overlap of the Navigation bar with the status bar in the "Syncing" screen.

### Steps to test

- Open Status
- Navigate to Profile > Syncing
- Check if the Navigation bar overlaps with the status bar

status: ready

2023-05-24 15:41 UTC, jo-mut approved these changes

2023-05-24 15:47 UTC, status-im-auto commented
### Jenkins Builds
<details>
<summary>Click to see older builds (8)</summary>

| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | e6fbc024 | [#1](https://ci.status.im/job/status-mobile/job/prs/job/ios/job/PR-16014/1/) | 2023-05-24 15:47:22 | ~6 min | `ios` | [:iphone:`ipa`](https://i.diawi.com/JbBCtm) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2FJbBCtm)|
| :heavy_check_mark: | e6fbc024 | [#1](https://ci.status.im/job/status-mobile/job/prs/job/android-e2e/job/PR-16014/1/) | 2023-05-24 15:47:27 | ~6 min | `android-e2e` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230524-154049-e6fbc0-pr16014-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-230524-154049-e6fbc0-pr16014-x86.apk)|
| :heavy_check_mark: | e6fbc024 | [#1](https://ci.status.im/job/status-mobile/job/prs/job/android/job/PR-16014/1/) | 2023-05-24 15:48:13 | ~7 min | `android` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230524-154049-e6fbc0-pr16014-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-230524-154049-e6fbc0-pr16014-universal.apk)|
| :heavy_check_mark: | e6fbc024 | [#1](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-16014/1/) | 2023-05-24 15:50:19 | ~9 min | `tests` | [:page_facing_up:`log`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230524-154049-e6fbc0-pr16014-tests.log) |
| | | | | | | |
| :heavy_check_mark: | d6bdd27e | [#2](https://ci.status.im/job/status-mobile/job/prs/job/android-e2e/job/PR-16014/2/) | 2023-05-25 09:50:57 | ~6 min | `android-e2e` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230525-094402-d6bdd2-pr16014-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-230525-094402-d6bdd2-pr16014-x86.apk)|
| :heavy_check_mark: | d6bdd27e | [#2](https://ci.status.im/job/status-mobile/job/prs/job/ios/job/PR-16014/2/) | 2023-05-25 09:52:02 | ~7 min | `ios` | [:iphone:`ipa`](https://i.diawi.com/EwNfKF) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2FEwNfKF)|
| :heavy_check_mark: | d6bdd27e | [#2](https://ci.status.im/job/status-mobile/job/prs/job/android/job/PR-16014/2/) | 2023-05-25 09:53:00 | ~8 min | `android` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230525-094406-d6bdd2-pr16014-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-230525-094406-d6bdd2-pr16014-universal.apk)|
| :heavy_check_mark: | d6bdd27e | [#2](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-16014/2/) | 2023-05-25 09:59:29 | ~15 min | `tests` | [:page_facing_up:`log`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230525-094406-d6bdd2-pr16014-tests.log) |
</details>

| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 4fd3da55 | [#3](https://ci.status.im/job/status-mobile/job/prs/job/android-e2e/job/PR-16014/3/) | 2023-05-25 12:44:52 | ~6 min | `android-e2e` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230525-123813-4fd3da-pr16014-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-230525-123813-4fd3da-pr16014-x86.apk)|
| :heavy_check_mark: | 4fd3da55 | [#3](https://ci.status.im/job/status-mobile/job/prs/job/ios/job/PR-16014/3/) | 2023-05-25 12:45:07 | ~6 min | `ios` | [:iphone:`ipa`](https://i.diawi.com/p7AgFJ) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2Fp7AgFJ)|
| :heavy_check_mark: | 4fd3da55 | [#3](https://ci.status.im/job/status-mobile/job/prs/job/android/job/PR-16014/3/) | 2023-05-25 12:48:37 | ~10 min | `android` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230525-123813-4fd3da-pr16014-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-230525-123813-4fd3da-pr16014-universal.apk)|
| :heavy_check_mark: | 4fd3da55 | [#3](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-16014/3/) | 2023-05-25 12:51:26 | ~13 min | `tests` | [:page_facing_up:`log`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230525-123818-4fd3da-pr16014-tests.log) |
| | | | | | | |
| :heavy_check_mark: | 4345ee20 | [#4](https://ci.status.im/job/status-mobile/job/prs/job/android/job/PR-16014/4/) | 2023-05-26 15:30:00 | ~5 min | `android` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230526-152422-4345ee-pr16014-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-230526-152422-4345ee-pr16014-universal.apk)|
| :heavy_check_mark: | 4345ee20 | [#4](https://ci.status.im/job/status-mobile/job/prs/job/android-e2e/job/PR-16014/4/) | 2023-05-26 15:30:09 | ~5 min | `android-e2e` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230526-152422-4345ee-pr16014-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-230526-152422-4345ee-pr16014-x86.apk)|
| :heavy_check_mark: | 4345ee20 | [#4](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-16014/4/) | 2023-05-26 15:33:57 | ~9 min | `tests` | [:page_facing_up:`log`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230526-152426-4345ee-pr16014-tests.log) |
| :heavy_check_mark: | 4345ee20 | [#4](https://ci.status.im/job/status-mobile/job/prs/job/ios/job/PR-16014/4/) | 2023-05-26 15:50:02 | ~25 min | `ios` | [:iphone:`ipa`](https://i.diawi.com/8ebvUH) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2F8ebvUH)|

2023-05-24 17:36 UTC, status-im-auto commented
## 82% of end-end tests have passed
```
Total executed tests: 33
Failed tests: 6
Passed tests: 27
```
```
IDs of failed tests: 702840,702844,702894,702841,703086,702838 
```
<h3>Failed tests (6)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&PR_ID=16014&TR_CASE_IDS=702840,702844,702894,702841,703086,702838">Rerun failed tests</a></li><br/><h4>Class TestCommunityMultipleDeviceMerged:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3153841">test_community_emoji_send_copy_paste_reply</a>, id: 702840 </b></td></tr><tr><td><p><blockquote><div>Device 1: Long press on `Button` </div><div>Device 1: Find `Button` by `xpath`: `//*[@text="Copy text"]` </div></blockquote></p>

```
critical/test_public_chat_browsing.py:578: in test_community_emoji_send_copy_paste_reply
    self.channel_1.copy_message_text(emoji_unicode)
../views/chat_view.py:990: in copy_message_text
    self.element_by_translation_id("copy-text").click()
../views/base_element.py:91: in click
    self.find_element().click()
../views/base_element.py:80: in find_element
    raise NoSuchElementException(
 Device 1: Button by xpath: `//*[@text="Copy text"]` is not found on the screen
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/4c3f41da33824bf08f37ebee75ef6793?auth=58c09b7887ba81a756a2b0e8dac19bd2#241">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/b70c63b159b24f52b085f9240de90027?auth=4010a161918056a6e673034ab2628918#189">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3153844">test_community_links_with_previews_github_youtube_twitter_gif_send_enable</a>, id: 702844 </b></td></tr><tr><td><p><blockquote><div>Device 2: Tap on found: SendMessageButton </div><div>Device 1: Getting preview message for link: https://github.com/status-im/status-mobile/pull/11707 </div></blockquote></p>

```
critical/test_public_chat_browsing.py:644: in test_community_links_with_previews_github_youtube_twitter_gif_send_enable
    self.channel_1.get_preview_message_by_text(url).wait_for_element(60)
../views/base_element.py:117: in wait_for_element
    raise TimeoutException(
 Device `1`: `PreviewMessage` by` xpath`: `//*[starts-with(@text,'https://github.com/status-im/status-mobile/pull/11707')]/ancestor::android.view.ViewGroup[@content-desc='chat-item']` is not found on the screen after wait_for_element
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/4c3f41da33824bf08f37ebee75ef6793?auth=58c09b7887ba81a756a2b0e8dac19bd2#255">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/b70c63b159b24f52b085f9240de90027?auth=4010a161918056a6e673034ab2628918#194">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3153851">test_community_contact_block_unblock_offline</a>, id: 702894 </b></td></tr><tr><td><p><blockquote><div>Device 1: Find `Button` by `accessibility id`: `jump-to` </div></blockquote></p>

```
critical/test_public_chat_browsing.py:681: in test_community_contact_block_unblock_offline
    [home.jump_to_card_by_text('# %s' % self.channel_name) for home in self.homes]
critical/test_public_chat_browsing.py:681: in <listcomp>
    [home.jump_to_card_by_text('# %s' % self.channel_name) for home in self.homes]
../views/base_view.py:609: in jump_to_card_by_text
    self.jump_to_button.click()
../views/base_element.py:91: in click
    self.find_element().click()
../views/base_element.py:80: in find_element
    raise NoSuchElementException(
 Device 1: Button by accessibility id: `jump-to` is not found on the screen
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/4c3f41da33824bf08f37ebee75ef6793?auth=58c09b7887ba81a756a2b0e8dac19bd2#273">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/b70c63b159b24f52b085f9240de90027?auth=4010a161918056a6e673034ab2628918#208">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3153842">test_community_unread_messages_badge</a>, id: 702841 </b></td></tr><tr><td><p><blockquote><div>Device 1: Find `Button` by `accessibility id`: `jump-to` </div></blockquote></p>

```
critical/test_public_chat_browsing.py:662: in test_community_unread_messages_badge
    self.channel_1.jump_to_communities_home()
../views/base_view.py:605: in jump_to_communities_home
    self.jump_to_button.click()
../views/base_element.py:91: in click
    self.find_element().click()
../views/base_element.py:80: in find_element
    raise NoSuchElementException(
 Device 1: Button by accessibility id: `jump-to` is not found on the screen
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/4c3f41da33824bf08f37ebee75ef6793?auth=58c09b7887ba81a756a2b0e8dac19bd2#269">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/b70c63b159b24f52b085f9240de90027?auth=4010a161918056a6e673034ab2628918#205">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3153856">test_community_mark_all_messages_as_read</a>, id: 703086 </b></td></tr><tr><td><p><blockquote><div>Device 1: Find `Button` by `accessibility id`: `jump-to` </div></blockquote></p>

```
critical/test_public_chat_browsing.py:752: in test_community_mark_all_messages_as_read
    self.channel_1.jump_to_communities_home()
../views/base_view.py:605: in jump_to_communities_home
    self.jump_to_button.click()
../views/base_element.py:91: in click
    self.find_element().click()
../views/base_element.py:80: in find_element
    raise NoSuchElementException(
 Device 1: Button by accessibility id: `jump-to` is not found on the screen
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/4c3f41da33824bf08f37ebee75ef6793?auth=58c09b7887ba81a756a2b0e8dac19bd2#277">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/b70c63b159b24f52b085f9240de90027?auth=4010a161918056a6e673034ab2628918#211">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>6. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3153839">test_community_message_send_check_timestamps_sender_username</a>, id: 702838 </b></td></tr><tr><td><p><blockquot [...]

2023-05-25 04:53 UTC, flexsurfer requested changes
`:options   {:insets {:top? true}}` just needs to be added to the screen

2023-05-25 08:28 UTC, smohamedjavid commented
> `:options {:insets {:top? true}}` just needs to be added to the screen

@flexsurfer - `:options {:insets {:top? true}}` pushes the whole screen to render below the status bar.

<img src="https://github.com/status-im/status-mobile/assets/19339952/3330715d-82ea-4853-b0d2-57b7b8340053" width="300" />

2023-05-25 09:45 UTC, flexsurfer approved these changes
nice! thanks

2023-05-26 11:37 UTC, status-im-auto commented
## 94% of end-end tests have passed
```
Total executed tests: 33
Failed tests: 2
Passed tests: 31
```
```
IDs of failed tests: 702732,702838 
```
<h3>Failed tests (2)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&PR_ID=16014&TR_CASE_IDS=702732,702838">Rerun failed tests</a></li><br/><h4>Class TestCommunityMultipleDeviceMerged:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3155036">test_community_message_send_check_timestamps_sender_username</a>, id: 702838 </b></td></tr><tr><td><p><blockquote><div>Device 2: Verifying that 'hello' is under today </div><div>Device 2: Looking for a message by text: hello </div></blockquote></p>

```
critical/test_public_chat_browsing.py:456: in test_community_message_send_check_timestamps_sender_username
    channel.verify_message_is_under_today_text(message, self.errors)
../views/chat_view.py:944: in verify_message_is_under_today_text
    message_element.wait_for_visibility_of_element()
../views/base_element.py:135: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 2: ChatElementByText by xpath:`//*[starts-with(@text,'hello')]/ancestor::android.view.ViewGroup[@content-desc='chat-item']` is not found on the screen after wait_for_visibility_of_element 
```

<b>[[blocked by 14797]]</b><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/06c8a7f9fcce4f7a80347c2114bab7b3?auth=9182da3b26ff3b34b9435d91af673a3d#144">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/d5f11010da004c52ade4c5da421490c5?auth=5144800ed2f5f3da5d07b1d712db083b#103">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestGroupChatMultipleDeviceMergedNewUI:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3155025">test_group_chat_pin_messages</a>, id: 702732 </b></td></tr><tr><td><p><blockquote><div>Device 2: `Text` is `user admin` </div><div>Device 2: Looking for a pinned by message with text: Message 4 </div></blockquote></p>

```
critical/chats/test_group_chat.py:337: in test_group_chat_pin_messages
    self.errors.verify_no_errors()
base_test_case.py:184: in verify_no_errors
    pytest.fail('\n '.join([self.errors.pop(0) for _ in range(len(self.errors))]))
 Message 4 is not pinned in group chat after unpinning previous one
E    Pinned messages count 2 doesn't match expected 3 for user 2
E    Message 'Message 4' is missed on Pinned messages list for user 2
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/1c52dbd0b8d74b10afee45ebfc6860ae?auth=21b6f15581424c82a51dc8449c0c73dd#181">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/c815b7a9308546e1b71be41e4891f6fe?auth=da3bf2aa9339048ac4b5c4c6500c3fae#112">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 3:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/a62df1ec85844e71b12c93842caf7ea5?auth=1d6a40180e7921d8418a0d3ba94314a9#91">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table></details><h3>Passed tests (31)</h3><details><summary>Click to expand</summary><br/><br/><h4>Class TestActivityMultipleDevicePR:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3155052">test_activity_center_admin_notification_accept_swipe</a>, id: 702958 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/eaadb67044ee45458648d72a0981ad03?auth=637200f8c214bd543d5628a97d185d28#307">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/a215505aa62441f6829de6be4f32c262?auth=772fd93a83867007dda83246b76219f9#141">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3155051">test_activity_center_mentions</a>, id: 702957 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/eaadb67044ee45458648d72a0981ad03?auth=637200f8c214bd543d5628a97d185d28#272">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/a215505aa62441f6829de6be4f32c262?auth=772fd93a83867007dda83246b76219f9#121">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3155049">test_navigation_jump_to</a>, id: 702936 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/eaadb67044ee45458648d72a0981ad03?auth=637200f8c214bd543d5628a97d185d28#142">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/a215505aa62441f6829de6be4f32c262?auth=772fd93a83867007dda83246b76219f9#102">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3155050">test_activity_center_reply_read_unread_delete_filter_swipe</a>, id: 702947 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/eaadb67044ee45458648d72a0981ad03?auth=637200f8c214bd543d5628a97d185d28#163">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/a215505aa62441f6829de6be4f32c262?auth=772fd93a83867007dda83246b76219f9#105">Steps, video, logs</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestActivityCenterContactRequestMultipleDevicePR:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3155045">test_activity_center_contact_request_accept_swipe_mark_all_as_read</a>, id: 702851 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/f3cea22545df4565b83807e8634a3180?auth=bc7005d4c16003a2134879a1b8da1314#89">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/3851c2f3b9194863bcdfe1fbf6ce1953?auth=b970e862ecb5944efb0aade12c2236a8#90">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3155044">test_activity_center_contact_request_decline</a>, id: 702850 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/f3cea22545df4565b83807e8634a3180?auth=bc7005d4c16003a2134879a1b8da1314#56">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/3851c2f3b9194863bcdfe1fbf6ce1953?auth=b970e862ecb5944efb0aade12c2236a8#55">Steps, video, logs</a></li></ul></p></ul></p>< [...]

2023-05-26 14:40 UTC, pavloburykh commented
@smohamedjavid thanx for the fix! Ready to be merged.

2023-05-26 16:28 UTC, merged