[16137] Disable text description in lightbox for now
status-im/status-react pull request #16169
Opened 2023-06-03 11:08 UTC by ibrkhalil

fixes #16137

### Summary

Need to disable text preview in lightbox when opening an image/album for better UX

status: ready

2023-06-03 11:12 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | 6558c4ae | [#1](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-16169/1/) | 2023-06-03 11:12:01 | ~3 min | `tests` | [:page_facing_up:`log`](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-16169/1/consoleText) |

2023-06-04 16:47 UTC, J-Son89 commented on src/status_im2/contexts/chat/lightbox/bottom_view.cljs
> +     #_[rn/text {:style style/text-style} text]
there should also be an issue to reenable this feature. 

Can you leave a TODO with that issue? If the issue does not exist you can go ahead and create it 👍

2023-06-05 05:26 UTC, OmarBasem commented
I don't think this is needed. I am currently working on this feature anyways.

2023-06-05 05:57 UTC, ibrkhalil commented
> I don't think this is needed. I am currently working on this feature anyways.

Alright, Closing as it'll be fixed by you Omar.
Thank you

2023-06-05 08:01 UTC, J-Son89 commented
@ibrkhalil, @OmarBasem as part of current descoping process removing this feature was requested so we can focus on other priorities without halfway baked UX implementations. Afaik You should reopen this pr @ibrkhalil and @OmarBasem you should park working on that feature and focus on other decided priorities. 
Maybe confirm with @cammellos or @qoqobolo

2023-06-05 08:39 UTC, ibrkhalil commented
> @ibrkhalil, @OmarBasem as part of current descoping process removing this feature was requested so we can focus on other priorities without halfway baked UX implementations. Afaik You should reopen this pr @ibrkhalil and @OmarBasem you should park working on that feature and focus on other decided priorities. Maybe confirm with @cammellos or @qoqobolo

Reopening it just in case we needed to hide it for next release.

2023-06-05 09:05 UTC, qoqobolo commented
@ibrkhalil @OmarBasem confirming that we should disable text description in lightbox for now

2023-06-05 10:02 UTC, OmarBasem approved these changes

2023-06-05 14:10 UTC, ilmotta requested changes

2023-06-05 14:10 UTC, ilmotta commented on src/status_im2/contexts/chat/lightbox/bottom_view.cljs
> +     #_[rn/text {:style style/text-style} text]
I think we should not disable code like this. We should at least define a boolean var and use it to switch on/off the feature. Even if we're just temporarily disabling it, the var approach is just as easy as using `#_` and much clearer for other devs.

2023-06-06 05:19 UTC, OmarBasem commented
@J-Son89 @qoqobolo just wondering why are we parking development on the images lightbox. Isn't it part of the one-to-one chat?

2023-06-06 05:52 UTC, ibrkhalil commented
@ilmotta I actually felt code smell when doing it :)
Thanks for correcting me Icaro 🚀

2023-06-06 09:33 UTC, ilmotta approved these changes

2023-06-06 09:36 UTC, J-Son89 commented on src/status_im2/contexts/chat/lightbox/bottom_view.cljs
> +     #_[rn/text {:style style/text-style} text]
It would be nice to have a common variable for this, like `disabled-features`. We can reuse this across similar places in the app so that we can easily find them 👍

2023-06-06 09:37 UTC, J-Son89 commented
> @J-Son89 @qoqobolo just wondering why are we parking development on the images lightbox. Isn't it part of the one-to-one chats?

@OmarBasem as I understand it, we are not parking development on the lightbox, only the text preview on lightbox images.

2023-06-09 10:09 UTC, qoqobolo commented
Hey @ibrkhalil, could you rebase this PR, please?
Thanks

2023-06-09 14:27 UTC, status-im-auto commented
## 48% of end-end tests have passed
```
Total executed tests: 33
Failed tests: 17
Passed tests: 16
```
```
IDs of failed tests: 702733,702958,703194,702859,702855,702732,702782,702894,702783,702807,702845,702957,702731,702839,702808,703086,702838 
```
<h3>Failed tests (17)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&PR_ID=16169&TR_CASE_IDS=702733,702958,703194,702859,702855,702732,702782,702894,702783,702807,702845,702957,702731,702839,702808,703086,702838">Rerun failed tests</a></li><br/><h4>Class TestGroupChatMultipleDeviceMergedNewUI:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3164495">test_group_chat_pin_messages</a>, id: 702732 </b></td></tr><tr><td>

```
Test is not run, e2e blocker  
```

<b>[[reason: [NOTRUN] Pin feature is in development]]</b><br/><br/></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3164503">test_group_chat_join_send_text_messages_push</a>, id: 702807 </b></td></tr><tr><td><p><blockquote><div>Device 2: Find `Text` by `xpath`: `//*[starts-with(@text,'Hey, admin!')]/ancestor::android.view.ViewGroup[@content-desc='chat-item']//*[@content-desc='message-status']/android.widget.TextView` </div><div>Device 2: `Text` is `Sent` </div></blockquote></p>

```
critical/chats/test_group_chat.py:224: in test_group_chat_join_send_text_messages_push
    self.chats[1].chat_element_by_text(message_to_admin).wait_for_status_to_be('Delivered', timeout=120)
../views/chat_view.py:228: in wait_for_status_to_be
    raise TimeoutException("Message status was not changed to %s, it's %s" % (expected_status, current_status))
 Message status was not changed to Delivered, it's Sent
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/5e683346e32042d3bf0d98859ee57c03?auth=6340e6fd4bcbeaae67b7bd4fd87378db#122">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/befff0c63bd44731a1eafbd959885153?auth=0eef4477e53824df73b6482e97be5af6#68">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 3:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/da76840ead504ade84df95b1018e769d?auth=94f141a885eee7a61c0bc6c279209d86#67">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3164504">test_group_chat_offline_pn</a>, id: 702808 </b></td></tr><tr><td><p><blockquote><div>Device 3: Looking for a message by text: message from old member </div><div>Device 3: Looking for a message by text: message from new member </div></blockquote></p>

```
None; 
 RemoteDisconnected
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/5e683346e32042d3bf0d98859ee57c03?auth=6340e6fd4bcbeaae67b7bd4fd87378db#134">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/befff0c63bd44731a1eafbd959885153?auth=0eef4477e53824df73b6482e97be5af6#93">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 3:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/da76840ead504ade84df95b1018e769d?auth=94f141a885eee7a61c0bc6c279209d86#72">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestOneToOneChatMultipleSharedDevicesNewUi:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3164496">test_1_1_chat_text_message_delete_push_disappear</a>, id: 702733 </b></td></tr><tr><td><p><blockquote><div>Device 2: Find `Text` by `xpath`: `//*[starts-with(@text,'smth I should edit')]/ancestor::android.view.ViewGroup[@content-desc='chat-item']` </div><div>Device 2: Tap on found: Text </div></blockquote></p>

```
critical/chats/test_1_1_public_chats.py:1158: in test_1_1_chat_text_message_delete_push_disappear
    self.chat_2.chat_element_by_text(message_after_edit_1_1).wait_for_status_to_be("Delivered")
../views/chat_view.py:228: in wait_for_status_to_be
    raise TimeoutException("Message status was not changed to %s, it's %s" % (expected_status, current_status))
 Message status was not changed to Delivered, it's Sending
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/9dd3c377183e46afbfac64f2a38d2504?auth=6f31eb677c2aa9afe48076383672d6c0#263">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/f6cd49970adc4f818b67f6fce8812ce6?auth=d752e0ebbc78837f47ac88bbbcfc2abc#195">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3164516">test_1_1_chat_edit_message</a>, id: 702855 </b></td></tr><tr><td><p><blockquote><div>Device 2: Find `Text` by `xpath`: `//*[starts-with(@text,'Message before edit 1-1')]/ancestor::android.view.ViewGroup[@content-desc='chat-item']` </div><div>Device 2: Tap on found: Text </div></blockquote></p>

```
critical/chats/test_1_1_public_chats.py:1142: in test_1_1_chat_edit_message
    self.chat_2.chat_element_by_text(message_before_edit_1_1).wait_for_status_to_be("Delivered")
../views/chat_view.py:228: in wait_for_status_to_be
    raise TimeoutException("Message status was not changed to %s, it's %s" % (expected_status, current_status))
 Message status was not changed to Delivered, it's Sending 
```

<b>[[Message is being in status 'Sending' for a long time: https://github.com/status-im/status-mobile/issues/15385]]</b><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/9dd3c377183e46afbfac64f2a38d2504?auth=6f31eb677c2aa9afe48076383672d6c0#248">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/f6cd49970adc4f818b67f6fce8812ce6?auth=d752e0ebbc78837f47ac88bbbcfc2abc#171">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3164499">test_1_1_chat_emoji_send_reply_and_open_link</a>, id: 702782 </b></td></tr><tr><td><p><blockquote><div>Device 1: Tap on found: SendMessageButton </div><div>Device 2: Looking for a message by text: Test with link: https://status.im/ here should be nothing unusual. </div></blockquote></p>

```
critical/chats/test_1_1_public_chats.py:919: in test_1_1_chat_emoji_send_reply_and_open_link
    self.chat_2.chat_element_by_text(url_message).wait_for_element(20)
../views/base_element.py:117: in wait_for_element
    raise TimeoutException(
 Device `2`: `ChatElementByText` by` xpath`: `//*[starts-with(@text,'Test wi [...]

2023-06-10 07:20 UTC, ibrkhalil commented
> Hey @ibrkhalil, could you rebase this PR, please? Thanks

Done, Thank you

2023-06-12 08:02 UTC, VladimrLitvinenko commented
hi @ibrkhalil PR is tested and ready to be merged. Thank you!

2023-06-12 08:14 UTC, merged