[16153] Remove scrolling to first message(s)
status-im/status-react pull request #16172
Opened 2023-06-03 13:13 UTC by ibrkhalil

fixes #16153
status: ready

@alwx Can you please elaborate why we needed this piece of code?

2023-06-03 13:19 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 10de3c97 | [#1](https://ci.status.im/job/status-mobile/job/prs/job/android-e2e/job/PR-16172/1/) | 2023-06-03 13:19:40 | ~6 min | `android-e2e` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230603-131324-10de3c-pr16172-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-230603-131324-10de3c-pr16172-x86.apk)|

2023-06-05 09:19 UTC, alwx commented
The reason why it was added is literally written in the FIXME message you're deleting 😂
I will take a look later but by fixing it this way you're literally going to introduce another issue, that's not the way to go.

2023-06-05 09:20 UTC, alwx requested changes
The reason why it was added is literally written in the FIXME message you're deleting :D
I will take a look later but by fixing it this way you're literally going to introduce another issue, that's not the way to go.

2023-06-05 09:21 UTC, ibrkhalil commented
> The reason why it was added is literally written in the FIXME message you're deleting :D
> 
> I will take a look later but by fixing it this way you're literally going to introduce another issue, that's not the way to go.

The FIXME didn't actually explain the issue, Happy to look for another solution.

But please, Explain why we needed it.

2023-06-10 07:32 UTC, closed without merging