[16092] Prevent orientation changing on chat screen and community overview
status-im/status-react pull request #16173
Opened 2023-06-04 06:58 UTC by ibrkhalil

fixes #16092 

### Summary

status: ready

2023-06-04 07:04 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 4e119e13 | [#1](https://ci.status.im/job/status-mobile/job/prs/job/android-e2e/job/PR-16173/1/) | 2023-06-04 07:04:11 | ~5 min | `android-e2e` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-230604-065844-4e119e-pr16173-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-230604-065844-4e119e-pr16173-x86.apk)|

2023-06-04 16:44 UTC, J-Son89 approved these changes

2023-06-04 18:54 UTC, flexsurfer requested changes
im not sure i understand these changes looks like not related to the issue, on the video orientation doesn't change

2023-06-04 18:54 UTC, flexsurfer requested changes
im not sure i understand these changes looks like not related to the issue, on the video orientation doesn't change

2023-06-05 08:42 UTC, ibrkhalil commented
> im not sure i understand these changes looks like not related to the issue, on the video orientation doesn't change

It did change without these changes, Tested on my Google pixel 7A
I think QA enabled auto rotation from the status bar in order to change the orientation

2023-06-05 09:10 UTC, flexsurfer commented
> It did change without these changes

OS layout changed, but not the app, app is still in portrait, so I'm wondering how these changes fix anything, like even in theory, why only these two screens?

2023-06-05 09:19 UTC, ibrkhalil commented
> > It did change without these changes
> 
> 
> 
> OS layout changed, but not the app, app is still in portrait, so I'm wondering how these changes fix anything, like even in theory, why only these two screens?

Invoking the rotation broke the UI, Layout shouldn't change when user rotates the device.

Why these two screens because I was able to reproduce the same issue on these two.

2023-06-05 09:27 UTC, flexsurfer commented
> Why these two screens because I was able to reproduce the same issue on these two.

but do we know a reason? how these screens are different?

2023-06-05 10:33 UTC, ibrkhalil commented
> > Why these two screens because I was able to reproduce the same issue on these two.
> 
> but do we know a reason? how these screens are different?

I'll investigate more and find out why switching to landscape worked on these two screens.

2023-06-10 14:16 UTC, ibrkhalil commented
```clj
    {:name      :chat
     :options   {:insets     {:top? true}
                 :popGesture false}
     :component chat/chat}
```
This is how we store configuration for chat view in `status-im2.navigation.screens`


Some view like share shell have a different config, They have an additional `:options` key in their map that has extra config but also it has the orientation locking option

```clj
    {:name      :share-shell
     :options   options/transparent-screen-options
     :component share/view}
```
->
```clj
(def transparent-screen-options
  (merge
   {:modalPresentationStyle :overCurrentContext
    :layout                 {:componentBackgroundColor :transparent
                             :orientation              ["portrait"]
                             :backgroundColor          :transparent}}
   (if platform/android?
     {:statusBar {:backgroundColor :transparent
                  :style           :light
                  :drawBehind      true}}
     {:statusBar {:style :light}})))
```
So because we hardcoded orientation here, It will never switch to landscape mode, Even if the device had it enabled in the Android's quick settings, Or iOS' control center. Because it's handled by this package `react-native-orientation-locker`

Same is with onboarding screens
```clj
    {:name      :new-to-status
     :options   {:layout options/onboarding-layout}
     :component new-to-status/new-to-status}
```
->
```clj
(def onboarding-layout
  {:componentBackgroundColor colors/neutral-80-opa-80-blur
   :orientation              ["portrait"]
   :backgroundColor          colors/neutral-80-opa-80-blur})
```

But the weird thing that's confusing and is bad for maintaining such functionality is that it's inconsistent.
If you looked at
```clj
    {:name      :intro
     :component intro/view}
```
You won't find any configuration regarding orientation and would think that it should work in portrait and landscape, But the problem is the adding of the orientation key happens on the usage level here `status-im2.navigation.roots/roots`
```clj
(defn roots
  []
  (merge (old-roots)

         {:intro
          {:root
           {:stack {:id       :intro
                    :children [{:component {:name    :intro
                                            :id      :intro
                                            :options (options/default-root nil colors/neutral-100)}}]}}}
          :shell-stack
          {:root
           {:stack {:id       :shell-stack
                    :children [{:component {:name    :shell-stack
                                            :id      :shell-stack
                                            :options (options/default-root
                                                      (if (colors/dark?) :light :dark))}}]}}}
          :profiles
          {:root
           {:stack {:id       :profiles
                    :children [{:component {:name    :profiles
                                            :id      :profiles
                                            :options (options/default-root)}}]}}}

          :enable-notifications
          {:root {:stack {:children [{:component {:name    :enable-notifications
                                                  :id      :enable-notifications
                                                  :options (options/default-root)}}]}}}

          :welcome
          {:root {:stack {:children [{:component {:name    :welcome
                                                  :id      :welcome
                                                  :options (options/default-root)}}]}}}
          :syncing-results
          {:root {:stack {:children [{:component {:name    :syncing-results
                                                  :id      :syncing-results
                                                  :options (options/default-root)}}]}}}}))
```
If you looked at the first key `:into` you'd find that it's using this variable for its configuration options `options/default-root` which has the orientation config
```clj
(defn default-root
  [& [status-bar-theme background-color]]
  (merge (statusbar-and-navbar-root status-bar-theme)
         {:topBar {:visible false}
          :layout {:componentBackgroundColor (or background-color
                                                 (colors/theme-colors colors/white colors/neutral-100))
                   :orientation              ["portrait"]
                   :backgroundColor          (or background-color
                                                 (colors/theme-colors colors/white
                                                                      colors/neutral-100))}}))
```
And the confusion that happened during the PR review happened because the way we set the orientation is not consistent in the codebase. So I'll think of a way to make it easier to maintain and extend.

2023-06-10 14:21 UTC, ibrkhalil commented
We didn't have such a problem with :start-a-new-chat because any view that uses the bottom sheet isn't rotatable.
And also, Thanks to this investigation I was able to reproduce the bug on the discover communities screen.

2023-06-12 14:27 UTC, ilmotta commented
I'm still confused by the original issue and this PR's fix @ibrkhalil. Oh, and thanks for the explanation in https://github.com/status-im/status-mobile/pull/16173#issuecomment-1585683969, quite helpful.

-----

Going on a tangent and putting my user's hat for a moment, I don't really understand why we are designing a mobile app that doesn't minimally work with landscape mode. I know this is not going to change anymore, but I'm sharing my opinion anyway. IMO supporting portrait & landscape since the beginning leads to a better designed product, similar to how designing a truly responsive website from the beginning is better (instead of an after thought that requires tons of rewrites). When done right, the technical dev effort is essentially the same.

2023-06-12 14:34 UTC, ilmotta approved these changes
Approving since I don't have anything to add and locking on portrait seems reasonable.

2023-06-18 11:19 UTC, ibrkhalil commented
@flexsurfer Kindly take a look when you have time

2023-06-19 08:20 UTC, flexsurfer commented on src/status_im2/navigation/screens.cljs
> +                 :layout     {:orientation ["portrait"]}}
does that mean when we use options, they are overriding and not merged? can we find proof from the RNN library?

2023-06-19 08:20 UTC, flexsurfer commented on src/status_im2/navigation/screens.cljs
> +     :options   {:layout {:orientation ["portrait"]}}}
i'm not sure why its needed here, because we didn't have options here before, so default options should worked here

2023-06-23 10:49 UTC, ibrkhalil commented
Fixed in https://github.com/status-im/status-mobile/pull/16370

2023-06-23 10:49 UTC, closed without merging