[wip] draft
status-im/status-react pull request #17049
Opened 2023-08-18 05:40 UTC by OmarBasem

2023-08-18 05:42 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | ad57ad69 | [#1](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-17049/1/) | 2023-08-18 05:42:51 | ~2 min | `tests` | [:page_facing_up:`log`](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-17049/1/consoleText) |

2023-08-18 09:07 UTC, smohamedjavid approved these changes
LGTM 👍

2023-08-18 09:07 UTC, smohamedjavid commented on src/status_im2/contexts/quo_preview/wallet/network_link.cljs
> +
Extra line

2023-08-18 14:10 UTC, J-Son89 commented on src/quo2/components/wallet/network_link/view.cljs
> +  (let [image-component (if (and platform/android? preview?) rn/image fast-image/fast-image)
hmm I'm not sure if this is supposed to be an image - is it more of an svg type component? 🤔 
did you check the expected behaviour with the designers ?

Also I think the colors are not quite fixed but more of a linear gradient that depends on some configurations

2023-08-18 14:11 UTC, J-Son89 requested changes
check my comment about the approach - I think it should be svg type component? 🤔

2023-08-20 16:51 UTC, vkjr requested changes
Agree with @J-Son89, that clarifications from designer team are required

2023-08-21 07:09 UTC, OmarBasem commented
@J-Son89 @vkjr fixed it 👍

2023-08-21 12:30 UTC, J-Son89 approved these changes
looks great, nice @OmarBasem! :)

2023-08-22 04:52 UTC, OmarBasem commented
@Francesca-G design review please :)

2023-08-22 07:39 UTC, Francesca-G approved these changes
Looks good ✨

Adding required follow up due to minor details:
- the x2 style is shorter than design (see screenshot)
- the circles look slightly smaller

<img width="400" alt="Screenshot 2023-08-22 alle 09 33 55" src="https://github.com/status-im/status-mobile/assets/122543089/8ddc8833-eb6a-40a0-a907-5bd73472ced4">

Design on the left, implementation on the right

2023-08-22 08:06 UTC, OmarBasem commented
@vkjr re-review please

2023-08-22 17:58 UTC, vkjr approved these changes

2023-08-22 18:00 UTC, vkjr commented
@OmarBasem, thanks!

2023-08-23 08:53 UTC, merged

2023-09-18 10:59 UTC, churik commented
@OmarBasem  
 did you create an issue follow-up based on the design review (or maybe fixed this in Pr and didn't mention)?

Based on https://github.com/status-im/status-mobile/blob/develop/doc/pipeline_process.md > Design review, all follow-up issues have to be created when PR is merged and linked to the original PR.

2023-09-25 03:49 UTC, OmarBasem commented
@churik yes there is a follow up https://github.com/status-im/status-mobile/issues/17088

2023-09-25 13:26 UTC, churik commented
Oh, sorry, my bad!