Adjusting topbar animation in chat to match design
status-im/status-react pull request #17582
Opened 2023-10-07 05:26 UTC by ibrkhalil

*otherwise*

fixes #17509 

### Summary

Fixes issue described [here](https://github.com/status-im/status-mobile/issues/17509)

status: ready

2023-10-07 05:32 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | a776b31f | [#1](https://ci.status.im/job/status-mobile/job/prs/job/android/job/PR-17582/1/) | 2023-10-07 05:32:18 | ~5 min | `android` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-231007-052634-a776b3-pr17582-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-231007-052634-a776b3-pr17582-universal.apk)|

2023-10-08 15:24 UTC, ibrkhalil commented
Awaiting for design response to open a PR about this.

2023-10-09 04:03 UTC, ibrkhalil commented
Also, I noticed bad UX because of a (vibrating effect).
When there's no more messages at the end.
Should we disable scrolling down until there's actual content?https://github.com/status-im/status-mobile/assets/33176106/224ed8dc-4f0b-49d9-b2f7-5adae3a6a28a

2023-10-10 07:41 UTC, ibrkhalil commented
Got an okay from design [here](https://discord.com/channels/624634427930312714/928625369542713396/1160961848770830417)

2023-10-10 09:00 UTC, ajayesivan approved these changes
Those numbers look like magic to me. If you could add a brief explanation to assist with future changes, that would be nice.

2023-10-10 13:00 UTC, alwx approved these changes

2023-10-10 18:32 UTC, status-im-auto commented
## 72% of end-end tests have passed
```
Total executed tests: 43
Failed tests: 12
Passed tests: 31
```
```
IDs of failed tests: 702809,703194,702859,702732,702840,703495,702948,702786,702844,702731,702808,702845 
```
<h3>Failed tests (12)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&PR_ID=17582&TR_CASE_IDS=702809,703194,702859,702732,702840,703495,702948,702786,702844,702731,702808,702845">Rerun failed tests</a></li><br/><h4>Class TestOneToOneChatMultipleSharedDevicesNewUi:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3253025">test_1_1_chat_pin_messages</a>, id: 702731 </b></td></tr><tr><td>

```
Test is not run, e2e blocker  
```

<b>[[reason: [NOTRUN] Pin feature is in development]]</b><br/><br/></td></tr></tbody></table><h4>Class TestCommunityMultipleDeviceMergedTwo:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3253036">test_community_markdown_support</a>, id: 702809 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_public_chat_browsing.py:780: in prepare_devices
    self.chat_1.send_message('hey')
../views/chat_view.py:995: in send_message
    self.chat_message_input.wait_for_element(wait_chat_input_sec)
../views/base_element.py:121: in wait_for_element
    raise TimeoutException(
 Device `1`: `ChatMessageInput` by` accessibility id`: `chat-message-input` is not found on the screen after wait_for_element
```

<br/><br/></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3253054">test_community_hashtag_links_to_community_channels</a>, id: 702948 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_public_chat_browsing.py:780: in prepare_devices
    self.chat_1.send_message('hey')
../views/chat_view.py:995: in send_message
    self.chat_message_input.wait_for_element(wait_chat_input_sec)
../views/base_element.py:121: in wait_for_element
    raise TimeoutException(
 Device `1`: `ChatMessageInput` by` accessibility id`: `chat-message-input` is not found on the screen after wait_for_element
```

<br/><br/></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3253033">test_community_mentions_push_notification</a>, id: 702786 </b></td></tr><tr><td><p><blockquote><div>Device 1: ChatMessageInput element not found </div><div>Device 1: Sending message 'hey' </div></blockquote></p>

```
Test setup failed: critical/chats/test_public_chat_browsing.py:780: in prepare_devices
    self.chat_1.send_message('hey')
../views/chat_view.py:995: in send_message
    self.chat_message_input.wait_for_element(wait_chat_input_sec)
../views/base_element.py:121: in wait_for_element
    raise TimeoutException(
 Device `1`: `ChatMessageInput` by` accessibility id`: `chat-message-input` is not found on the screen after wait_for_element
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/783212b199b948929f1df76772fa6ac4?auth=ba03cfd55603ba10e6f2021e5ffbdff3">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/0eba76247013474b93da567d1254383f?auth=89b84c1f23205b86f083500d866eb78e">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3253044">test_community_leave</a>, id: 702845 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_public_chat_browsing.py:780: in prepare_devices
    self.chat_1.send_message('hey')
../views/chat_view.py:995: in send_message
    self.chat_message_input.wait_for_element(wait_chat_input_sec)
../views/base_element.py:121: in wait_for_element
    raise TimeoutException(
 Device `1`: `ChatMessageInput` by` accessibility id`: `chat-message-input` is not found on the screen after wait_for_element
```

<br/><br/></td></tr></tbody></table><h4>Class TestGroupChatMultipleDeviceMergedNewUI:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3253026">test_group_chat_pin_messages</a>, id: 702732 </b></td></tr><tr><td>

```
Test is not run, e2e blocker  
```

<b>[[reason: [NOTRUN] Pin feature is in development]]</b><br/><br/></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3253064">test_group_chat_mute_chat</a>, id: 703495 </b></td></tr><tr><td><p><blockquote><div>Device 2: Click until `ChatMessageInput` by `accessibility id`: `chat-message-input` will be presented </div><div>Device 2: Looking for a message by text: Chat is unmuted now </div></blockquote></p>

```
critical/chats/test_group_chat.py:473: in test_group_chat_mute_chat
    self.errors.verify_no_errors()
base_test_case.py:191: in verify_no_errors
    pytest.fail('\n '.join([self.errors.pop(0) for _ in range(len(self.errors))]))
 New messages counter near chats tab button is 1 after unmute, but should be 2
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/1cd5eee5d1f44247bdfd360b0191ef6a?auth=ff57d1470d9a1913cc80cfba190261bc#358">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/344cf0988344465b9fbdbcffd78c7422?auth=0c5549fb0d36808b46c81ea5669262f4#236">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 3:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/53160732f14a481095c51525b4c9ca96?auth=f7252b71d5dec84380df1333628fca7c#217">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3253035">test_group_chat_offline_pn</a>, id: 702808 </b></td></tr><tr><td><p><blockquote><div>Device 3: Looking for a message by text: message from old member </div><div>Device 3: Looking for a message by text: message from new member </div></blockquote></p>

```
critical/chats/test_group_chat.py:309: in test_group_chat_offline_pn
    self.errors.verify_no_errors()
base_test_case.py:191: in verify_no_errors
    pytest.fail('\n '.join([self.errors.pop(0) for _ in range(len(self.errors))]))
 Messages PN was not fetched from offline 
```

<b>[[Data delivery issue]]</b><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/1cd5eee5d1f44247bdfd360b0191ef6a?auth=ff57d1470d9a1913cc80cfba190261bc#306">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/344cf0988344465b9fbdbcffd78c7422?auth=0c5549fb0d36808b46c81ea5669262f4#211">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 3:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/53160732f14a481095c51525b4c9ca96?auth=f7252b71d5dec84380df1333628fca7c#180">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gi [...]

2023-10-13 09:26 UTC, status-im-auto commented
## 86% of end-end tests have passed
```
Total executed tests: 43
Failed tests: 6
Passed tests: 37
```
```
IDs of failed tests: 702786,702731,702808,702732,703503,703495 
```
<h3>Failed tests (6)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&PR_ID=17582&TR_CASE_IDS=702786,702731,702808,702732,703503,703495">Rerun failed tests</a></li><br/><h4>Class TestCommunityMultipleDeviceMergedTwo:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3255401">test_community_mentions_push_notification</a>, id: 702786 </b></td></tr><tr><td><p><blockquote><div>Device 2: Getting PN by 'user_2' </div><div>Device 2: Looking for a message by text: user_2 </div></blockquote></p>

```
critical/chats/test_public_chat_browsing.py:874: in test_community_mentions_push_notification
    self.errors.verify_no_errors()
base_test_case.py:191: in verify_no_errors
    pytest.fail('\n '.join([self.errors.pop(0) for _ in range(len(self.errors))]))
 Can not edit a message with a mention
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/c58189898eb543699700aef6fb3bdbb6?auth=25f843553930108cd4a7fdaca7ee4652#131">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/b36555520b3b497ca49eccc6a793d556?auth=a9a715b4b44764afaaa7ba4d620cd240#101">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestOneToOneChatMultipleSharedDevicesNewUi:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3255393">test_1_1_chat_pin_messages</a>, id: 702731 </b></td></tr><tr><td>

```
Test is not run, e2e blocker  
```

<b>[[reason: [NOTRUN] Pin feature is in development]]</b><br/><br/></td></tr></tbody></table><h4>Class TestCommunityOneDeviceMerged:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3255434">test_community_discovery</a>, id: 703503 </b></td></tr><tr><td><p><blockquote><div>Device 1: Find `Button` by `accessibility id`: `communities-home-discover-card` </div><div>Device 1: Tap on found: Button </div></blockquote></p>

```
critical/chats/test_public_chat_browsing.py:40: in test_community_discovery
    self.home.community_card_item.wait_for_visibility_of_element(30)
../views/base_element.py:139: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 1: BaseElement by accessibility id:`community-card-item` is not found on the screen after wait_for_visibility_of_element
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/05c75e50afa94f689208c320973fbedc?auth=22559d286405f0659c0f2b10ad2f17ac#55">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestGroupChatMultipleDeviceMergedNewUI:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3255403">test_group_chat_offline_pn</a>, id: 702808 </b></td></tr><tr><td><p><blockquote><div>Device 3: Looking for a message by text: message from old member </div><div>Device 3: Looking for a message by text: message from new member </div></blockquote></p>

```
critical/chats/test_group_chat.py:309: in test_group_chat_offline_pn
    self.errors.verify_no_errors()
base_test_case.py:191: in verify_no_errors
    pytest.fail('\n '.join([self.errors.pop(0) for _ in range(len(self.errors))]))
 Messages PN was not fetched from offline 
```

<b>[[Data delivery issue]]</b><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/8a455f1b1576471b97318aac1e680ab1?auth=5c67f358bc411a2b821ad2a226e675fc#307">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/e51b91ce798e4666b5800d82c384cdae?auth=f7b5cc44e69e4bf318b74ac3ecbe4b9b#212">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 3:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/b7dd221abd3847e99abb484661233797?auth=ac2e4439dd49e96965416aaa64edb736#183">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3255394">test_group_chat_pin_messages</a>, id: 702732 </b></td></tr><tr><td>

```
Test is not run, e2e blocker  
```

<b>[[reason: [NOTRUN] Pin feature is in development]]</b><br/><br/></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3255432">test_group_chat_mute_chat</a>, id: 703495 </b></td></tr><tr><td><p><blockquote><div>Device 2: Click until `ChatMessageInput` by `accessibility id`: `chat-message-input` will be presented </div><div>Device 2: Looking for a message by text: Chat is unmuted now </div></blockquote></p>

```
critical/chats/test_group_chat.py:473: in test_group_chat_mute_chat
    self.errors.verify_no_errors()
base_test_case.py:191: in verify_no_errors
    pytest.fail('\n '.join([self.errors.pop(0) for _ in range(len(self.errors))]))
 New messages counter near chats tab button is 1 after unmute, but should be 2
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/8a455f1b1576471b97318aac1e680ab1?auth=5c67f358bc411a2b821ad2a226e675fc#359">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/e51b91ce798e4666b5800d82c384cdae?auth=f7b5cc44e69e4bf318b74ac3ecbe4b9b#237">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 3:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/b7dd221abd3847e99abb484661233797?auth=ac2e4439dd49e96965416aaa64edb736#220">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table></details><h3>Passed tests (37)</h3><details><summary>Click to expand</summary><br/><br/><h4>Class TestCommunityMultipleDeviceMergedTwo:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3255412">test_community_leave</a>, id: 702845 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/c58189898eb543699700aef6fb3bdbb6?auth=25f843553930108cd4a7fdaca7ee4652#357">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/b36555520b3b497ca49eccc6a793d556?auth=a9a715b4b44764afaaa7ba4d620cd240#298">Steps, video, lo [...]

2023-10-13 16:51 UTC, churik commented
Hello @ibrkhalil !
I would not say that animation completely matches design now, but from my perspective, it became better.
Attaching video for better understanding.

Android nightly:

https://github.com/status-im/status-mobile/assets/4557972/6c191ae3-f1b5-4a6c-84e9-215a3aafdb4b

Android PR:

https://github.com/status-im/status-mobile/assets/4557972/e6d1f467-0b21-4f71-91b9-792b0b14aa39

Also, there are still some cases when the top bar is cut:

![IMAGE 2023-10-13 18:49:12](https://github.com/status-im/status-mobile/assets/4557972/c3660581-aa2c-4b02-9a93-4b6407233aec)

But at the same time from my POV the amount of edge cases mentioned https://github.com/status-im/status-mobile/issues/17530 and in https://github.com/status-im/status-mobile/issues/17509 is decreased.

So I'd prefer to get another opinion from design POV here, no objections from merging this PR from my side.

2023-10-13 16:53 UTC, churik commented
also @ibrkhalil would you mind to add an explanation to your changes as requested [in](https://github.com/status-im/status-mobile/pull/17582#pullrequestreview-1666962299) ?

2023-10-14 15:41 UTC, ibrkhalil commented
> Hello @ibrkhalil ! I would not say that animation completely matches design now, but from my perspective, it became better. Attaching video for better understanding.
> 
> Android nightly:
> 
>  FILE.2023-10-13.18.47.40.mp4 
> Android PR:
> 
>  FILE.2023-10-13.18.48.39.mp4 
> Also, there are still some cases when the top bar is cut:
> 
> ![IMAGE 2023-10-13 18:49:12](https://user-images.githubusercontent.com/4557972/274968314-c3660581-aa2c-4b02-9a93-4b6407233aec.jpg)
> 
> But at the same time from my POV the amount of edge cases mentioned #17530 and in #17509 is decreased.
> 
> So I'd prefer to get another opinion from a design POV here, no objections to merging this PR from my side.
> 
> cc @Francesca-G



> Those numbers look like magic to me. If you could add a brief explanation to assist with future changes, that would be nice.

I don't think it's optimal to add an explanation to animation values, We're just interpolating on the scroll-y values on a specific threshold. And the threshold is specified based on if it will give us the right animation or not. 

Reanimated docs should explain this in a good way.

2023-10-14 15:43 UTC, ibrkhalil commented
> Got an okay from design [here](https://discord.com/channels/624634427930312714/928625369542713396/1160961848770830417)

The green light from design was here, And I think the topbar being cut was meant for the case where the user's name was not visible at all (Cut in half and therefore not readable), And I don't think that's reproducible anymore.

2023-10-16 06:58 UTC, Francesca-G commented
> So I'd prefer to get another opinion from a design POV here, no objections to merging this PR from my side.
> 
> cc @Francesca-G

@churik The name of the chat should be visible at all times. When there's not enough messages and the big name is still visible, we shouldn't display any name in the top nav but as soon as the bigger name in the chat is hidden we should display the name in the top nav, with a smooth single animation, avoiding weird states where the name in the top bar isn't fully readable, cut off or with low opacity.

<img width="375" alt="Screenshot 2023-10-16 alle 08 55 01" src="https://github.com/status-im/status-mobile/assets/122543089/c4cbbdfd-35ee-4f2b-8c0d-0d317229f5df">

<img width="375" alt="Screenshot 2023-10-16 alle 08 55 35" src="https://github.com/status-im/status-mobile/assets/122543089/070441a9-18f9-4f33-9d5e-6ba931aac516">

2023-10-16 08:25 UTC, ibrkhalil commented
> > So I'd prefer to get another opinion from a design POV here, no objections to merging this PR from my side.
> > cc @Francesca-G
> 
> @churik The name of the chat should be visible at all times. When there's not enough messages and the big name is still visible, we shouldn't display any name in the top nav but as soon as the bigger name in the chat is hidden we should display the name in the top nav, with a smooth single animation, avoiding weird states where the name in the top bar isn't fully readable, cut off or with low opacity.
> 
> <img alt="Screenshot 2023-10-16 alle 08 55 01" width="375" src="https://user-images.githubusercontent.com/122543089/275416533-c4cbbdfd-35ee-4f2b-8c0d-0d317229f5df.png"> <img alt="Screenshot 2023-10-16 alle 08 55 35" width="375" src="https://user-images.githubusercontent.com/122543089/275416663-070441a9-18f9-4f33-9d5e-6ba931aac516.png">

Now I know what to do :)
Thank you so much @churik @Francesca-G

2023-10-18 11:36 UTC, Francesca-G approved these changes
@ibrkhalil nice job ✨

2023-10-18 13:04 UTC, churik commented
@ibrkhalil 
There is a bug on IOS - when you tap in composer on empty chat (just right after adding someone to contacts), one the top is shown, and the next time there is no top bar anymore. Issue is reproducible again after reopening chat view.
Video:

https://github.com/status-im/status-mobile/assets/4557972/55820710-9891-4bec-9323-1729e8286fec

2023-10-18 14:51 UTC, status-im-auto commented
## 88% of end-end tests have passed
```
Total executed tests: 43
Failed tests: 2
Expected to fail tests: 3
Passed tests: 38
Not executed tests: 1
```
```
IDs of not executed tests: 703629 
```
```
IDs of failed tests: 702844,703202 
```
```
IDs of expected to fail tests: 702731,702808,702732 
```
<h3>Not executed tests (1)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&PR_ID=17582&TR_CASE_IDS=703629">Rerun not executed tests</a></li></details><h3>Failed tests (2)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&PR_ID=17582&TR_CASE_IDS=702844,703202">Rerun failed tests</a></li><br/><h4>Class TestCommunityMultipleDeviceMerged:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3258695">test_community_links_with_previews_github_youtube_twitter_gif_send_enable</a>, id: 702844 </b></td></tr><tr><td><p><blockquote><div>Device 2: Wait for text element `EmojisNumber` to be equal to `1` </div><div>Device 2: Find `EmojisNumber` by `xpath`: `//*[starts-with(@text,'https://m.youtube.com/watch?v=Je7yErjEVt4')]/ancestor::android.view.ViewGroup[@content-desc='chat-item']/../..//*[@content-desc='emoji-reaction-4']/android.widget.TextView` </div></blockquote></p>

```
critical/chats/test_public_chat_browsing.py:594: in test_community_links_with_previews_github_youtube_twitter_gif_send_enable
    self.errors.verify_no_errors()
base_test_case.py:191: in verify_no_errors
    pytest.fail('\n '.join([self.errors.pop(0) for _ in range(len(self.errors))]))
 Link message reaction is not shown for the sender
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/5f3ba5440f9a4680bdc96b8892bf899e?auth=7cfaf0077843e303e747335fcd605680#308">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/1cc5d42927ef41bbaa49c9b4b918b48f?auth=0d64aadb1c987f49bc126155aac6616c#301">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestGroupChatMultipleDeviceMergedNewUI:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3258712">test_group_chat_reactions</a>, id: 703202 </b></td></tr><tr><td><p><blockquote><div>Device 1: Wait for text element `EmojisNumber` to be equal to `1` </div><div>Device 1: Find `EmojisNumber` by `xpath`: `//*[starts-with(@text,'This is a test message to check some reactions.')]/ancestor::android.view.ViewGroup[@content-desc='chat-item']/../..//*[@content-desc='emoji-reaction-4']/android.widget.TextView` </div></blockquote></p>

```
critical/chats/test_group_chat.py:120: in test_group_chat_reactions
    message_element.emojis_below_message(emoji="laugh").wait_for_element_text(1)
../views/base_element.py:172: in wait_for_element_text
    element_text = self.find_element().text.strip()
../views/base_element.py:79: in find_element
    raise NoSuchElementException(
 Device 1: EmojisNumber by xpath: `//*[starts-with(@text,'This is a test message to check some reactions.')]/ancestor::android.view.ViewGroup[@content-desc='chat-item']/../..//*[@content-desc='emoji-reaction-4']/android.widget.TextView` is not found on the screen; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/f9f22b5a894245f79dfdce0539f6ade3?auth=bda953e01bba0d49f97cc404ed059b2c#151">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/6dc96ae61b5649b18abcf1e12a5308b8?auth=e84c5c9abb71ffb29428df62ae2844ff#103">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 3:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/d3cd4cc222d443b1b7933b699aa04919?auth=9c22fe80a53a23316e7fa96d6b35b03b#83">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table></details><h3>Expected to fail tests (3)</h3><details><summary>Click to expand</summary><br/><br/><h4>Class TestOneToOneChatMultipleSharedDevicesNewUi:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3258677">test_1_1_chat_pin_messages</a>, id: 702731 </b></td></tr><tr><td>

```
Test is not run, e2e blocker  
```

<b>[[reason: [NOTRUN] Pin feature is in development]]</b><br/><br/></td></tr></tbody></table><h4>Class TestGroupChatMultipleDeviceMergedNewUI:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3258687">test_group_chat_offline_pn</a>, id: 702808 </b></td></tr><tr><td><p><blockquote><div>Device 3: Looking for a message by text: message from old member </div><div>Device 3: Looking for a message by text: message from new member </div></blockquote></p>

```
critical/chats/test_group_chat.py:309: in test_group_chat_offline_pn
    self.errors.verify_no_errors()
base_test_case.py:191: in verify_no_errors
    pytest.fail('\n '.join([self.errors.pop(0) for _ in range(len(self.errors))]))
 Messages PN was not fetched from offline 
```

<b>[[Data delivery issue]]</b><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/f9f22b5a894245f79dfdce0539f6ade3?auth=bda953e01bba0d49f97cc404ed059b2c#224">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/6dc96ae61b5649b18abcf1e12a5308b8?auth=e84c5c9abb71ffb29428df62ae2844ff#183">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 3:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/d3cd4cc222d443b1b7933b699aa04919?auth=9c22fe80a53a23316e7fa96d6b35b03b#159">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3258678">test_group_chat_pin_messages</a>, id: 702732 </b></td></tr><tr><td>

```
Test is not run, e2e blocker  
```

<b>[[reason: [NOTRUN] Pin feature is in development]]</b><br/><br/></td></tr></tbody></table></details><h3>Passed tests (38)</h3><details><summary>Click to expand</summary><br/><br/><h4>Class TestCommunityMultipleDeviceMerged:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3258692">test_community_emoji_send_copy_paste_reply</a>, id: 702840 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul> [...]

2023-10-20 17:51 UTC, ibrkhalil commented
@churik Should be ready to test again, Thank you.

2023-10-23 13:47 UTC, alwx requested changes

2023-10-23 13:47 UTC, alwx commented on src/status_im2/contexts/chat/messages/list/view.cljs
> +                                                 (< 135 (reanimated/get-shared-value scroll-y)))
it's all full of magic numbers 🥲
could you at least move them to the to constants above to make them less random?

2023-10-23 14:16 UTC, ibrkhalil commented on src/status_im2/contexts/chat/messages/list/view.cljs
> +                                                 (< 135 (reanimated/get-shared-value scroll-y)))
Done

2023-10-23 15:31 UTC, churik commented
@ibrkhalil 

### ISSUE 1:  issue from https://github.com/status-im/status-mobile/pull/17582#issuecomment-1768412217 is still reproducible if there are several messages in chat (IPhone 14) 

https://github.com/status-im/status-mobile/assets/4557972/2bab39d2-72c1-4e15-a98e-9e9cb9dd108b

### ISSUE 2:  you can reach a state of broken topbar when you expand / collapse composer on empty chat (Android, Google Pixel 7)

![IMAGE 2023-10-23 17:18:06](https://github.com/status-im/status-mobile/assets/4557972/78a7219b-b9ce-4516-b642-b490bd3d55f8)

Video:

https://github.com/status-im/status-mobile/assets/4557972/ce56306f-b51e-40f5-ae0b-45ba0885dab3

### ISSUE 3: Fast scrolling back and forth leads to an empty topbar (Android, Google Pixel 7)

https://github.com/status-im/status-mobile/assets/4557972/e395afb5-6f46-469d-9b6e-69d6e7060905

2023-10-24 10:37 UTC, ibrkhalil commented
I am going for give this more time to make sure I done it right.

2023-10-29 19:48 UTC, ibrkhalil commented
Need another code review please as I did a lot of changes.

2023-10-30 08:50 UTC, churik commented
I'm not sure how it correlates with https://github.com/status-im/status-mobile/pull/17734

2023-10-30 09:02 UTC, ibrkhalil commented
> I'm not sure how it correlates with #17734

We can merge my PR and then when @alwx creates the abstraction he can rebase and take into consideration the changes made here.

2023-10-30 09:14 UTC, Francesca-G reviewed
The animation when scrolling a chat full of messages looks good, I think we can improve the animation when typing messages for the first time in a new chat.
>

https://github.com/status-im/status-mobile/assets/122543089/41d6c3a8-179b-4a54-aa80-c27769fd7c7d

>
As you can see there's a delay in the animation that causes a couple of weird states, like these two: 
>
>
- Name overlapping with an invisible top bar
>
<img width="375" alt="Screenshot 2023-10-30 alle 10 10 10" src="https://github.com/status-im/status-mobile/assets/122543089/c0ede6f4-5f7a-4422-87b0-075ec45e9a1c">

>
- Duplicate name in the chat view
>
>
<img width="375" alt="Screenshot 2023-10-30 alle 10 10 26" src="https://github.com/status-im/status-mobile/assets/122543089/369dbb8e-0bae-4238-878f-62e2f61f66b6">

2023-10-30 09:36 UTC, ibrkhalil commented
> The animation when scrolling a chat full of messages looks good, I think we can improve the animation when typing messages for the first time in a new chat.
> 
> > 
> 
>  RPReplay_Final1698656958.mp4 
> > 
> 
> As you can see there's a delay in the animation that causes a couple of weird states, like these two:
> 
> > 
> 
> * Name overlapping with an invisible top bar
> 
> > 
> 
> <img alt="Screenshot 2023-10-30 alle 10 10 10" width="375" src="https://user-images.githubusercontent.com/122543089/278996876-c0ede6f4-5f7a-4422-87b0-075ec45e9a1c.png">
> > 
> 
> * Duplicate name in the chat view
> 
> > 
> 
> <img alt="Screenshot 2023-10-30 alle 10 10 26" width="375" src="https://user-images.githubusercontent.com/122543089/278996889-369dbb8e-0bae-4238-878f-62e2f61f66b6.png">

I think on empty chat, I can trigger the blurring asap and animate the name..
investigating

2023-10-30 11:57 UTC, ibrkhalil commented
> The animation when scrolling a chat full of messages looks good, I think we can improve the animation when typing messages for the first time in a new chat.
> 
> > 
> 
>  RPReplay_Final1698656958.mp4 
> > 
> 
> As you can see there's a delay in the animation that causes a couple of weird states, like these two:
> 
> > 
> 
> * Name overlapping with an invisible top bar
> 
> > 
> 
> <img alt="Screenshot 2023-10-30 alle 10 10 10" width="375" src="https://user-images.githubusercontent.com/122543089/278996876-c0ede6f4-5f7a-4422-87b0-075ec45e9a1c.png">
> > 
> 
> * Duplicate name in the chat view
> 
> > 
> 
> <img alt="Screenshot 2023-10-30 alle 10 10 26" width="375" src="https://user-images.githubusercontent.com/122543089/278996889-369dbb8e-0bae-4238-878f-62e2f61f66b6.png">

Ready for another look 😀

2023-10-30 14:00 UTC, ibrkhalil commented
> > The animation when scrolling a chat full of messages looks good, I think we can improve the animation when typing messages for the first time in a new chat.
> 
> > 
> 
> > > 
> 
> > 
> 
> >  RPReplay_Final1698656958.mp4 
> 
> > > 
> 
> > 
> 
> > As you can see there's a delay in the animation that causes a couple of weird states, like these two:
> 
> > 
> 
> > > 
> 
> > 
> 
> > * Name overlapping with an invisible top bar
> 
> > 
> 
> > > 
> 
> > 
> 
> > <img alt="Screenshot 2023-10-30 alle 10 10 10" width="375" src="https://user-images.githubusercontent.com/122543089/278996876-c0ede6f4-5f7a-4422-87b0-075ec45e9a1c.png">
> 
> > > 
> 
> > 
> 
> > * Duplicate name in the chat view
> 
> > 
> 
> > > 
> 
> > 
> 
> > <img alt="Screenshot 2023-10-30 alle 10 10 26" width="375" src="https://user-images.githubusercontent.com/122543089/278996889-369dbb8e-0bae-4238-878f-62e2f61f66b6.png">
> 
> 
> 
> Ready for another look 😀

Please wait on this, As I found a fee other edge cases.

2023-10-31 13:57 UTC, ibrkhalil commented
Ready for another review, please.
CC: @churik @Francesca-G

2023-10-31 16:11 UTC, ibrkhalil commented
> Ready for another review, please.
> 
> CC: @churik @Francesca-G 

Found another edge case 🥹
Going to make this ready tonight though.

2023-10-31 20:36 UTC, alwx approved these changes

2023-10-31 20:58 UTC, ibrkhalil commented
@churik @Francesca-G Let's give testing it a shot please :D

2023-11-01 09:33 UTC, Francesca-G commented
@ibrkhalil it's getting better but we still have some issues:


https://github.com/status-im/status-mobile/assets/122543089/e6fdf928-6b3d-43aa-9019-e3dc4f30a907
>
>

<img width="300" alt="Screenshot 2023-11-01 alle 10 31 13" src="https://github.com/status-im/status-mobile/assets/122543089/0f54b8c6-7ab0-422f-98f8-85e7773d2585">

2023-11-01 09:38 UTC, ibrkhalil commented
> @ibrkhalil it's getting better but we still have some issues:
> 
> 
> 
> 
> 
> https://github.com/status-im/status-mobile/assets/122543089/e6fdf928-6b3d-43aa-9019-e3dc4f30a907
> 
> >
> 
> >
> 
> 
> 
> <img width="300" alt="Screenshot 2023-11-01 alle 10 31 13" src="https://github.com/status-im/status-mobile/assets/122543089/0f54b8c6-7ab0-422f-98f8-85e7773d2585">
> 
> 

Okay, Another edge case of the two names showing at the same time.
What is the issue in the screenshot?

2023-11-01 12:08 UTC, Francesca-G commented
> > @ibrkhalil it's getting better but we still have some issues:
> > 
> >   
> >     
> >     
> > 
> >     RPReplay_Final1698830960.mp4
> >     
> >   
> > 
> >   
> > 
> >   
> > 
> > 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > <img alt="Screenshot 2023-11-01 alle 10 31 13" width="300" src="https://user-images.githubusercontent.com/122543089/279633211-0f54b8c6-7ab0-422f-98f8-85e7773d2585.png">
> 
> Okay, Another edge case of the two names showing at the same time. What is the issue in the screenshot?

The top nav bar is supposed to be there, probably isn't very visible but I have the X button of the top nav overlapping with my avatar :)

2023-11-02 07:57 UTC, ibrkhalil commented
Hey @Francesca-G
Can you please take another look?
Thank you :)

2023-11-02 09:57 UTC, Francesca-G approved these changes

2023-11-02 10:36 UTC, ibrkhalil commented
CC: @status-im/mobile-qa 
Can I get a review please?

2023-11-02 11:06 UTC, churik commented
will take it soon, thank you @ibrkhalil

2023-11-02 14:26 UTC, churik commented
@ibrkhalil really good work, thank you!
I'll launch tests on the final commit and will move it to "Merge" once I review them

2023-11-02 16:42 UTC, status-im-auto commented
## 82% of end-end tests have passed
```
Total executed tests: 45
Failed tests: 5
Expected to fail tests: 3
Passed tests: 37
```
```
IDs of failed tests: 702948,702869,702786,702844,703629 
```
```
IDs of expected to fail tests: 702732,702731,702808 
```
<h3>Failed tests (5)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&PR_ID=17582&TR_CASE_IDS=702948,702869,702786,702844,703629">Rerun failed tests</a></li><br/><h4>Class TestCommunityOneDeviceMerged:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3269951">test_community_undo_delete_message</a>, id: 702869 </b></td></tr><tr><td><p><blockquote><div>Device 1: Tap on found: Button </div><div>Device 1: Find `Button` by `xpath`: `//*[@text="Undo"]` </div></blockquote></p>

```
critical/chats/test_public_chat_browsing.py:108: in test_community_undo_delete_message
    self.channel.element_by_text("Undo").click()
../views/base_element.py:90: in click
    self.find_element().click()
/home/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py:94: in click
    self._execute(Command.CLICK_ELEMENT)
/home/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py:395: in _execute
    return self._parent.execute(command, params)
/home/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:345: in execute
    self.error_handler.check_response(response)
/home/jenkins/.local/lib/python3.10/site-packages/appium/webdriver/errorhandler.py:122: in check_response
    raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))
 The element 'By.xpath: //*[@text="Undo"]' does not exist in DOM anymore; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
E   Stacktrace:
E   io.appium.uiautomator2.common.exceptions.StaleElementReferenceException: The element 'By.xpath: //*[@text="Undo"]' does not exist in DOM anymore
E   	at io.appium.uiautomator2.model.ElementsCache.restore(ElementsCache.java:117)
E   	at io.appium.uiautomator2.model.ElementsCache.get(ElementsCache.java:153)
E   	at io.appium.uiautomator2.handler.Click.safeHandle(Click.java:36)
E   	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:59)
E   	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:277)
E   	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:271)
E   	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)
E   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
E   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
E   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
E   	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
E   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
E   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
E   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
E   	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
E   	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
E   	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
E   	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
E   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
E   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
E   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
E   	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
E   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
E   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
E   	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
E   	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
E   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
E   	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
E   	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
E   	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
E   	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
E   	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
E   	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
E   	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
E   	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
E   	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
E   	at java.lang.Thread.run(Thread.java:919)
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/b35320b967e34ffcb1306e24f9dd001d?auth=c93bbd58c158818afd6c15c85b5fde36#202">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestCommunityMultipleDeviceMerged:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3269944">test_community_links_with_previews_github_youtube_twitter_gif_send_enable</a>, id: 702844 </b></td></tr><tr><td><p><blockquote><div>Device 2: Find `EmojisNumber` by `xpath`: `//*[starts-with(@text,'https://m.youtube.com/watch?v=Je7yErjEVt4')]/ancestor::android.view.ViewGroup[@content-desc='chat-item']/../..//*[@content-desc='emoji-reaction-4']/android.widget.TextView` </div><div>Device 2: Element EmojisNumber text is equal to 1 </div></blockquote></p>

```
critical/chats/test_public_chat_browsing.py:609: in test_community_links_with_previews_github_youtube_twitter_gif_send_enable
    self.errors.verify_no_errors()
base_test_case.py:191: in verify_no_errors
    pytest.fail('\n '.join([self.errors.pop(0) for _ in range(len(self.errors))]))
 No preview image is shown for https://github.com/status-im/status-mobile/pull/11707
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/05f7991787c442409243f162034aec84?auth=6e0f453bc45a9a0159b762acd31c3d8a#303">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/190041714d2e41e1a5334924b773f4b6?auth=d3ca34aa8796f9ae9564b564bc655524#301">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">F [...]

2023-11-02 17:26 UTC, churik commented
Launched tests one more time to be sure that it is really random fails, as I could not find some of them in the other PRs

2023-11-02 18:22 UTC, status-im-auto commented
## 0% of end-end tests have passed
```
Total executed tests: 45
Failed tests: 43
Expected to fail tests: 2
Passed tests: 0
```
```
IDs of failed tests: 702845,702840,702894,703086,702855,702947,702730,702958,702786,702745,702844,702851,703202,702841,703496,702807,702839,702733,702742,702808,702809,702838,702813,702948,702859,703629,702846,703133,702869,702957,702783,702843,702782,702850,702784,703382,703391,703503,703297,702936,703495,702777,703194 
```
```
IDs of expected to fail tests: 702731,702732 
```
<h3>Failed tests (43)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&PR_ID=17582&TR_CASE_IDS=702845,702840,702894,703086,702855,702947,702730,702958,702786,702745,702844,702851,703202,702841,703496,702807,702839,702733,702742,702808,702809,702838,702813,702948,702859,703629,702846,703133,702869,702957,702783,702843,702782,702850,702784,703382,703391,703503,703297,702936,703495,702777,703194">Rerun failed tests</a></li><br/><h4>Class TestCommunityMultipleDeviceMergedTwo:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3270385">test_community_leave</a>, id: 702845 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_public_chat_browsing.py:778: in prepare_devices
    self.drivers, self.loop = create_shared_drivers(2)
base_test_case.py:309: in create_shared_drivers
    drivers = loop.run_until_complete(start_threads(test_suite_data.current_test.name,
/usr/lib/python3.10/asyncio/base_events.py:646: in run_until_complete
    return future.result()
__init__.py:26: in start_threads
    returns[k] = await returns[k]
/usr/lib/python3.10/concurrent/futures/thread.py:58: in run
    result = self.fn(*self.args, **self.kwargs)
/home/jenkins/.local/lib/python3.10/site-packages/appium/webdriver/webdriver.py:257: in __init__
    super().__init__(
/home/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:206: in __init__
    self.start_session(capabilities)
/home/jenkins/.local/lib/python3.10/site-packages/appium/webdriver/webdriver.py:346: in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)
/home/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:345: in execute
    self.error_handler.check_response(response)
/home/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response
    raise exception_class(message, screen, stacktrace)
 Infrastructure Error -- The Sauce VMs failed to start the browser or device.
E   For more info, please check https://docs.saucelabs.com/dev/error-messages
```

<br/><br/></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3270374">test_community_mentions_push_notification</a>, id: 702786 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_public_chat_browsing.py:778: in prepare_devices
    self.drivers, self.loop = create_shared_drivers(2)
base_test_case.py:309: in create_shared_drivers
    drivers = loop.run_until_complete(start_threads(test_suite_data.current_test.name,
/usr/lib/python3.10/asyncio/base_events.py:646: in run_until_complete
    return future.result()
__init__.py:26: in start_threads
    returns[k] = await returns[k]
/usr/lib/python3.10/concurrent/futures/thread.py:58: in run
    result = self.fn(*self.args, **self.kwargs)
/home/jenkins/.local/lib/python3.10/site-packages/appium/webdriver/webdriver.py:257: in __init__
    super().__init__(
/home/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:206: in __init__
    self.start_session(capabilities)
/home/jenkins/.local/lib/python3.10/site-packages/appium/webdriver/webdriver.py:346: in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)
/home/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:345: in execute
    self.error_handler.check_response(response)
/home/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response
    raise exception_class(message, screen, stacktrace)
 Infrastructure Error -- The Sauce VMs failed to start the browser or device.
E   For more info, please check https://docs.saucelabs.com/dev/error-messages
```

<br/><br/></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3270377">test_community_markdown_support</a>, id: 702809 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_public_chat_browsing.py:778: in prepare_devices
    self.drivers, self.loop = create_shared_drivers(2)
base_test_case.py:309: in create_shared_drivers
    drivers = loop.run_until_complete(start_threads(test_suite_data.current_test.name,
/usr/lib/python3.10/asyncio/base_events.py:646: in run_until_complete
    return future.result()
__init__.py:26: in start_threads
    returns[k] = await returns[k]
/usr/lib/python3.10/concurrent/futures/thread.py:58: in run
    result = self.fn(*self.args, **self.kwargs)
/home/jenkins/.local/lib/python3.10/site-packages/appium/webdriver/webdriver.py:257: in __init__
    super().__init__(
/home/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:206: in __init__
    self.start_session(capabilities)
/home/jenkins/.local/lib/python3.10/site-packages/appium/webdriver/webdriver.py:346: in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)
/home/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:345: in execute
    self.error_handler.check_response(response)
/home/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response
    raise exception_class(message, screen, stacktrace)
 Infrastructure Error -- The Sauce VMs failed to start the browser or device.
E   For more info, please check https://docs.saucelabs.com/dev/error-messages
```

<br/><br/></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3270395">test_community_hashtag_links_to_community_channels</a>, id: 702948 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_public_chat_browsing.py:778: in prepare_devices
    self.drivers, self.loop = create_shared_drivers(2)
base_test_case.py:309: in create_shared_drivers
    drivers = loop.run_until_complete(start_threads(test_suite_data.current_test.name,
/usr/lib/python3.10/asyncio/base_events.py:646: in run_until_complete
    return future.result()
__init__.py:26: in start_threads
    returns[k] = await returns[k]
/usr/lib/python3.10/concurrent/futures/thread.py:58: in run
    result = self.fn(*self.args, **self.kwargs)
/home/jenkins/.local/lib/python3.10/site-packages/appium/webdriver/webdriver.py:257: in __init__
    super().__init__(
/home/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:206: in __init__
    self.start_session(capabilities)
/home/jenkins/.local/lib/python3.10/site-packages/appium/webdriver/webdriver.py:346: in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)
/home/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:345: in execute
    self.error_handler.check_response(response)
/home/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py:229: in check_response
    raise exception_class(message, screen, stacktrace)
 Infrastructure Error -- The Sauce VMs failed to start the browser or device.
E   For more info, please check https://docs.saucelabs.com/dev/error-messages
```

<br/><br/></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3270408">test_community_join_when_node_owner_offline</a>, id: 703629 </b></td></tr><tr><t [...]

2023-11-03 10:17 UTC, status-im-auto commented
## 93% of end-end tests have passed
```
Total executed tests: 45
Failed tests: 0
Expected to fail tests: 3
Passed tests: 42
```
```
IDs of expected to fail tests: 702731,702808,702732 
```
<h3>Expected to fail tests (3)</h3><details><summary>Click to expand</summary><br/><br/><h4>Class TestOneToOneChatMultipleSharedDevicesNewUi:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3270680">test_1_1_chat_pin_messages</a>, id: 702731 </b></td></tr><tr><td>

```
Test is not run, e2e blocker  
```

<b>[[reason: [NOTRUN] Pin feature is in development]]</b><br/><br/></td></tr></tbody></table><h4>Class TestGroupChatMultipleDeviceMergedNewUI:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3270691">test_group_chat_offline_pn</a>, id: 702808 </b></td></tr><tr><td><p><blockquote><div>Device 3: Looking for a message by text: message from old member </div><div>Device 3: Looking for a message by text: message from new member </div></blockquote></p>

```
critical/chats/test_group_chat.py:323: in test_group_chat_offline_pn
    self.errors.verify_no_errors()
base_test_case.py:191: in verify_no_errors
    pytest.fail('\n '.join([self.errors.pop(0) for _ in range(len(self.errors))]))
 Messages PN was not fetched from offline 
```

<b>[[Data delivery issue]]</b><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/2e72974096354cf980a2265839f443eb?auth=8cfbe67560fd5f16a59da2cd40dd9045#300">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/ca607d6ffb9b4d03ba2ed40b3f53d8a4?auth=33d03ffee6ef06777927df3b4409a7c7#211">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 3:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/bb05ef7157b945b4bc384726602ce77b?auth=4787e6eb4f49be88914a18563148107e#197">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3270681">test_group_chat_pin_messages</a>, id: 702732 </b></td></tr><tr><td>

```
Test is not run, e2e blocker  
```

<b>[[reason: [NOTRUN] Pin feature is in development]]</b><br/><br/></td></tr></tbody></table></details><h3>Passed tests (42)</h3><details><summary>Click to expand</summary><br/><br/><h4>Class TestActivityMultipleDevicePRTwo:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3270712">test_activity_center_admin_notification_accept_swipe</a>, id: 702958 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/3d1b2f974831491aacfea9f45aab9489?auth=d466efc5a63c9e28813c884916285dbb#167">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/1026a5ea0e344f31982018428424c6af?auth=2daf17ee6fa127c2103c78a59df4c608#112">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3270711">test_activity_center_mentions</a>, id: 702957 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/3d1b2f974831491aacfea9f45aab9489?auth=d466efc5a63c9e28813c884916285dbb#119">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/1026a5ea0e344f31982018428424c6af?auth=2daf17ee6fa127c2103c78a59df4c608#98">Steps, video, logs</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestCommunityMultipleDeviceMerged:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3270696">test_community_emoji_send_copy_paste_reply</a>, id: 702840 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/f02e570bd9da45568e02593e1b2bc679?auth=7cc58358fe40b8d9bd7fcfd2462ce7ca#281">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/4e5e69a9cb694b028ed94714dc49cd1f?auth=edceca43bc63c685a0432fe60051320e#285">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3270707">test_community_contact_block_unblock_offline</a>, id: 702894 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/f02e570bd9da45568e02593e1b2bc679?auth=7cc58358fe40b8d9bd7fcfd2462ce7ca#385">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/4e5e69a9cb694b028ed94714dc49cd1f?auth=edceca43bc63c685a0432fe60051320e#351">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3270713">test_community_mark_all_messages_as_read</a>, id: 703086 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/f02e570bd9da45568e02593e1b2bc679?auth=7cc58358fe40b8d9bd7fcfd2462ce7ca#556">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/4e5e69a9cb694b028ed94714dc49cd1f?auth=edceca43bc63c685a0432fe60051320e#429">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3270699">test_community_links_with_previews_github_youtube_twitter_gif_send_enable</a>, id: 702844 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/f02e570bd9da45568e02593e1b2bc679?auth=7cc58358fe40b8d9bd7fcfd2462ce7ca#303">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/4e5e69a9cb694b028ed94714dc49cd1f?auth=edceca43bc63c685a0432fe60051320e#300">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3270697">test_community_unread_messages_badge</a>, id: 702841 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/f02e570bd9da45568e02593e1b2bc679?auth=7cc58358fe40b8d9bd7fcfd2462ce7ca#348">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/4e5e69a9cb694b028ed94714dc49cd1f?auth=edceca43bc63c685a0432fe60051320e#341">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>6. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3270695">test_community_message_delete</a>, id: 702839 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/f02e570bd9da45568e02593e1b2bc679?auth=7cc58358fe40b8d9bd7fcfd2462ce7ca#190">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/4e5e69a9cb694b028ed94714dc49cd1f?auth=edceca43bc63c685a0432fe60051320e#130">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>7. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3270694">test_community_message_s [...]

2023-11-03 10:18 UTC, pavloburykh commented
@ibrkhalil PR is ready for merge

2023-11-03 12:20 UTC, merged