#1628: Add Testnet warning, so no real ether or SNT is sent to the app
status-im/status-react pull request #1781
Opened 2017-09-07 15:34 UTC by alwx

Fixes #1628

2017-09-07 15:40 UTC, janherich requested changes
Please remove the Podfile.lock from PR

2017-09-07 17:25 UTC, flexsurfer requested changes
please update cocoapods to the latest version

2017-09-08 08:52 UTC, alwx commented
updated

2017-09-08 08:54 UTC, janherich approved these changes

2017-09-08 08:58 UTC, flexsurfer approved these changes

2017-09-10 09:23 UTC, merged