ci: check status-go-version.json in PR
status-im/status-react pull request #17924
Opened 2023-11-16 08:36 UTC by yqrashawn

fixes #17802

### Summary

check status-go-version.json
make sure the below content is correct

``` text
    "owner": "status-im",
    "repo": "status-go",
    "version": "v0.171.11",
```

### Testing notes
dev exp only PR

status: ready

2023-11-16 08:42 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 2b87f888 | [#1](https://ci.status.im/job/status-mobile/job/prs/job/android-e2e/job/PR-17924/1/) | 2023-11-16 08:42:19 | ~5 min | `android-e2e` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-231116-083632-2b87f8-pr17924-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-231116-083632-2b87f8-pr17924-x86.apk)|

2023-11-16 09:55 UTC, jakubgs requested changes
Why are we adding this to GitHub workflows? This repo doesn't use GitHub actions. It uses Jenkins. And shouldn't this be added to the `Makefile`?

2023-11-17 02:37 UTC, yqrashawn commented
> Why are we adding this to GitHub workflows? This repo doesn't use GitHub actions. It uses Jenkins. And shouldn't this be added to the `Makefile`?

We need a way to block PR merge, putting it into `make lint` might cause people to not review the PR since it will be shown as `test` failed.
Should I create a separate Jenkinsfile for this or for lint? What do you recommend? @jakubgs

2023-11-17 17:03 UTC, jakubgs commented
As far as I'm concerned if a required lint step fails the job that runs linting should fail and merging should be blocked.

If we want to move all linting steps to a separate job that can be done, sure. Though at that point I'd probably split linting into separate stages for visibility.

2023-11-20 07:09 UTC, closed without merging