Upgrade clang and patch Glog for fixing iOS builds on MacOS Sonoma, Xcode 15
status-im/status-react pull request #18108
Opened 2023-12-07 07:42 UTC by siddarthkay

fixes #17682 

After upgrading `MacOS` to `Sonoma` and `Xcode` to 15, pod install stage would fail with `clang` errors.
Turns out that `react-native`'s configure `glog` script sets 2 additional flags, `CC` and `CXX` which conflicts with flags already set in `nix` iOS shell.

In this PR we : 
- bump `clang` from `10.0.0` to `15.0.7`
- patch `glog` configure script to avoid setting those flags

This fixes the `iOS` builds.

status: ready

2023-12-07 07:52 UTC, status-im-auto commented
### Jenkins Builds
<details>
<summary>Click to see older builds (10)</summary>

| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 2bd9fca7 | [#1](https://ci.status.im/job/status-mobile/job/prs/job/ios/job/PR-18108/1/) | 2023-12-07 07:52:22 | ~9 min | `ios` | [:iphone:`ipa`](https://i.diawi.com/yJ6iqL) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2FyJ6iqL)|
| :heavy_check_mark: | 2bd9fca7 | [#1](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-18108/1/) | 2023-12-07 07:55:20 | ~12 min | `tests` | [:page_facing_up:`log`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-231207-074300-2bd9fc-pr18108-tests.log) |
| :heavy_check_mark: | 2bd9fca7 | [#1](https://ci.status.im/job/status-mobile/job/prs/job/android-e2e/job/PR-18108/1/) | 2023-12-07 07:55:20 | ~12 min | `android-e2e` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-231207-074300-2bd9fc-pr18108-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-231207-074300-2bd9fc-pr18108-x86.apk)|
| :heavy_check_mark: | 2bd9fca7 | [#1](https://ci.status.im/job/status-mobile/job/prs/job/android/job/PR-18108/1/) | 2023-12-07 07:55:23 | ~12 min | `android` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-231207-074300-2bd9fc-pr18108-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-231207-074300-2bd9fc-pr18108-universal.apk)|
| | | | | | | |
| :heavy_check_mark: | 10c946d1 | [#2](https://ci.status.im/job/status-mobile/job/prs/job/android-e2e/job/PR-18108/2/) | 2023-12-07 09:00:28 | ~6 min | `android-e2e` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-231207-085341-10c946-pr18108-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-231207-085341-10c946-pr18108-x86.apk)|
| :heavy_check_mark: | 10c946d1 | [#2](https://ci.status.im/job/status-mobile/job/prs/job/android/job/PR-18108/2/) | 2023-12-07 09:00:30 | ~6 min | `android` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-231207-085341-10c946-pr18108-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-231207-085341-10c946-pr18108-universal.apk)|
| :heavy_check_mark: | 10c946d1 | [#2](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-18108/2/) | 2023-12-07 09:06:02 | ~12 min | `tests` | [:page_facing_up:`log`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-231207-085341-10c946-pr18108-tests.log) |
| :heavy_check_mark: | 10c946d1 | [#2](https://ci.status.im/job/status-mobile/job/prs/job/ios/job/PR-18108/2/) | 2023-12-07 09:07:43 | ~14 min | `ios` | [:iphone:`ipa`](https://i.diawi.com/cbFhMD) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2FcbFhMD)|
| | | | | | | |
| :heavy_check_mark: | 6644a98d | [#3](https://ci.status.im/job/status-mobile/job/prs/job/android-e2e/job/PR-18108/3/) | 2023-12-07 09:32:36 | ~6 min | `android-e2e` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-231207-092601-6644a9-pr18108-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-231207-092601-6644a9-pr18108-x86.apk)|
| :heavy_check_mark: | 6644a98d | [#3](https://ci.status.im/job/status-mobile/job/prs/job/android/job/PR-18108/3/) | 2023-12-07 09:32:48 | ~6 min | `android` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-231207-092606-6644a9-pr18108-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-231207-092606-6644a9-pr18108-universal.apk)|
</details>

| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | b90c0b1e | [#4](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-18108/4/) | 2023-12-07 09:40:23 | ~3 min | `tests` | [:page_facing_up:`log`](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-18108/4/consoleText) |
| :heavy_check_mark: | b90c0b1e | [#4](https://ci.status.im/job/status-mobile/job/prs/job/android/job/PR-18108/4/) | 2023-12-07 09:43:28 | ~7 min | `android` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-231207-093622-b90c0b-pr18108-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-231207-093622-b90c0b-pr18108-universal.apk)|
| :heavy_check_mark: | b90c0b1e | [#4](https://ci.status.im/job/status-mobile/job/prs/job/android-e2e/job/PR-18108/4/) | 2023-12-07 09:43:31 | ~7 min | `android-e2e` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-231207-093622-b90c0b-pr18108-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-231207-093622-b90c0b-pr18108-x86.apk)|
| :heavy_check_mark: | b90c0b1e | [#4](https://ci.status.im/job/status-mobile/job/prs/job/ios/job/PR-18108/4/) | 2023-12-07 09:44:31 | ~8 min | `ios` | [:iphone:`ipa`](https://i.diawi.com/a2dNs3) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2Fa2dNs3)|
| | | | | | | |
| :heavy_check_mark: | 4afd1047 | [#5](https://ci.status.im/job/status-mobile/job/prs/job/android/job/PR-18108/5/) | 2023-12-07 09:56:21 | ~6 min | `android` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-231207-094945-4afd10-pr18108-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-231207-094945-4afd10-pr18108-universal.apk)|
| :heavy_check_mark: | 4afd1047 | [#5](https://ci.status.im/job/status-mobile/job/prs/job/android-e2e/job/PR-18108/5/) | 2023-12-07 09:58:29 | ~8 min | `android-e2e` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-231207-094942-4afd10-pr18108-x86.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-231207-094942-4afd10-pr18108-x86.apk)|
| :heavy_check_mark: | 4afd1047 | [#5](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-18108/5/) | 2023-12-07 10:01:24 | ~11 min | `tests` | [:page_facing_up:`log`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-231207-094945-4afd10-pr18108-tests.log) |
| :heavy_check_mark: | 4afd1047 | [#5](https://ci.status.im/job/status-mobile/job/prs/job/ios/job/PR-18108/5/) | 2023-12-07 10:04:25 | ~14 min | `ios` | [:iphone:`ipa`](https://i.diawi.com/Poj3t8) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2FPoj3t8)|

2023-12-07 08:04 UTC, flexsurfer commented on nix/shell.nix
> +      ++ lib.optionals   stdenv.isDarwin ([ cocoapods clang_15 tcl ] ++ appleSDKFrameworks)
oh that's how you do that

2023-12-07 08:04 UTC, flexsurfer approved these changes

2023-12-07 08:06 UTC, siddarthkay commented on nix/shell.nix
> +      ++ lib.optionals   stdenv.isDarwin ([ cocoapods clang_15 tcl ] ++ appleSDKFrameworks)
with this we get clang 15.0.7, incase we want 15.0.0 then we will have to write an overlay to override the version :)

2023-12-07 08:31 UTC, jakubgs commented on nix/shell.nix
> +      ++ lib.optionals   stdenv.isDarwin ([ cocoapods clang_15 tcl ] ++ appleSDKFrameworks)
No, that's not how you do that. You should be setting this in `nix/overlay.nix`.

2023-12-07 08:34 UTC, jakubgs commented on nix/deps/nodejs-patched/default.nix
> +             'unset CC'
Are we use `unset CC` is a good idea, seems weird to me.

2023-12-07 08:35 UTC, jakubgs requested changes
What do you men by:

>which conflicts with flags already set in nix iOS shell.

Which flags set in Nix iOS shell?

2023-12-07 08:38 UTC, status-im-auto commented
## 69% of end-end tests have passed
```
Total executed tests: 49
Failed tests: 9
Expected to fail tests: 6
Passed tests: 34
```
```
IDs of failed tests: 702809,702784,702851,702948,702783,703496,702786,702845,703629 
```
```
IDs of expected to fail tests: 702732,702894,703503,702846,702731,702808 
```
<h3>Failed tests (9)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&PR_ID=18108&TR_CASE_IDS=702809,702784,702851,702948,702783,703496,702786,702845,703629">Rerun failed tests</a></li><br/><h4>Class TestOneToOneChatMultipleSharedDevicesNewUiTwo:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3302860">test_1_1_chat_delete_via_long_press_relogin</a>, id: 702784 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_1_1_public_chats.py:548: in prepare_devices
    self.chat_1.send_message('hey')
../views/chat_view.py:1003: in send_message
    self.chat_message_input.wait_for_element(wait_chat_input_sec)
../views/base_element.py:121: in wait_for_element
    raise TimeoutException(
 Device `1`: `ChatMessageInput` by` accessibility id`: `chat-message-input` is not found on the screen after wait_for_element
```

<br/><br/></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3302859">test_1_1_chat_is_shown_message_sent_delivered_from_offline</a>, id: 702783 </b></td></tr><tr><td><p><blockquote><div>Device 1: ChatMessageInput element not found </div><div>Device 1: Sending message 'hey' </div></blockquote></p>

```
Test setup failed: critical/chats/test_1_1_public_chats.py:548: in prepare_devices
    self.chat_1.send_message('hey')
../views/chat_view.py:1003: in send_message
    self.chat_message_input.wait_for_element(wait_chat_input_sec)
../views/base_element.py:121: in wait_for_element
    raise TimeoutException(
 Device `1`: `ChatMessageInput` by` accessibility id`: `chat-message-input` is not found on the screen after wait_for_element 
```

<b>[[Data delivery issue]]</b><br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/4b19b78eaef84c95a550c87345c54aa6?auth=fe324693e318521fa46fa1a04f3a5da7">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/ec83671f574d45598d61feaebeaa6576?auth=86aa04f367ee043a980d5abe6fb514bf">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3302893">test_1_1_chat_mute_chat</a>, id: 703496 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_1_1_public_chats.py:548: in prepare_devices
    self.chat_1.send_message('hey')
../views/chat_view.py:1003: in send_message
    self.chat_message_input.wait_for_element(wait_chat_input_sec)
../views/base_element.py:121: in wait_for_element
    raise TimeoutException(
 Device `1`: `ChatMessageInput` by` accessibility id`: `chat-message-input` is not found on the screen after wait_for_element
```

<br/><br/></td></tr></tbody></table><h4>Class TestCommunityMultipleDeviceMergedTwo:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3302864">test_community_markdown_support</a>, id: 702809 </b></td></tr><tr><td>

```
Test setup failed: ../views/home_view.py:382: in handle_contact_request
    chat_element.accept_contact_request()
../views/home_view.py:150: in accept_contact_request
    self.handle_cr("accept-contact-request")
../views/home_view.py:147: in handle_cr
    ).wait_for_rendering_ended_and_click()
../views/base_element.py:155: in wait_for_rendering_ended_and_click
    self.click()
../views/base_element.py:90: in click
    self.find_element().click()
../views/base_element.py:79: in find_element
    raise NoSuchElementException(
 Device 2: Button by xpath: `//*[contains(@text, 'user_1')]/ancestor::*[@content-desc='activity']/*[@content-desc="accept-contact-request"]` is not found on the screen; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception

During handling of the above exception, another exception occurred:
critical/chats/test_public_chat_browsing.py:822: in prepare_devices
    self.home_2.handle_contact_request(self.username_1)
../views/home_view.py:392: in handle_contact_request
    self.driver.fail("No contact request received from %s" % username)
base_test_case.py:179: in fail
    pytest.fail('Device %s: %s' % (self.number, text))
E   Failed: Device 2: No contact request received from user_1
```

<br/><br/></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3302882">test_community_hashtag_links_to_community_channels</a>, id: 702948 </b></td></tr><tr><td>

```
Test setup failed: ../views/home_view.py:382: in handle_contact_request
    chat_element.accept_contact_request()
../views/home_view.py:150: in accept_contact_request
    self.handle_cr("accept-contact-request")
../views/home_view.py:147: in handle_cr
    ).wait_for_rendering_ended_and_click()
../views/base_element.py:155: in wait_for_rendering_ended_and_click
    self.click()
../views/base_element.py:90: in click
    self.find_element().click()
../views/base_element.py:79: in find_element
    raise NoSuchElementException(
 Device 2: Button by xpath: `//*[contains(@text, 'user_1')]/ancestor::*[@content-desc='activity']/*[@content-desc="accept-contact-request"]` is not found on the screen; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception

During handling of the above exception, another exception occurred:
critical/chats/test_public_chat_browsing.py:822: in prepare_devices
    self.home_2.handle_contact_request(self.username_1)
../views/home_view.py:392: in handle_contact_request
    self.driver.fail("No contact request received from %s" % username)
base_test_case.py:179: in fail
    pytest.fail('Device %s: %s' % (self.number, text))
E   Failed: Device 2: No contact request received from user_1 
```

<b>[[Can't navigate to a channel by hashtag link, https://github.com/status-im/status-mobile/issues/18095]]</b><br/><br/></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3302861">test_community_mentions_push_notification</a>, id: 702786 </b></td></tr><tr><td><p><blockquote><div>Device 2: Tap on found: Button </div><div>Device 2: Attempt 0 is successful clicking close-activity-center </div></blockquote></p>

```
Test setup failed: ../views/home_view.py:382: in handle_contact_request
    chat_element.accept_contact_request()
../views/home_view.py:150: in accept_contact_request
    self.handle_cr("accept-contact-request")
../views/home_view.py:147: in handle_cr
    ).wait_for_rendering_ended_and_click()
../views/base_element.py:155: in wait_for_rendering_ended_and_click
    self.click()
../views/base_element.py:90: in click
    self.find_element().click()
../views/base_element.py:79: in find_element
    raise NoSuchElementException(
 Device 2: Button by xpath: `//*[contains(@text, 'user_1')]/ancestor::*[@content-desc='activity']/*[@content-desc="accept-contact-request"]` is not found on the screen; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception

During handling of the above exception, another exception occurr [...]

2023-12-07 08:54 UTC, siddarthkay commented on nix/shell.nix
> +      ++ lib.optionals   stdenv.isDarwin ([ cocoapods clang_15 tcl ] ++ appleSDKFrameworks)
moved to `nix/overlay.nix`

2023-12-07 08:58 UTC, jakubgs approved these changes
That's better, but I would be worried about weird future failures if we unser `CC`.

2023-12-07 09:07 UTC, mohsen-ghafouri approved these changes
Well done :)

2023-12-07 09:27 UTC, siddarthkay commented
> That's better, but I would be worried about weird future failures if we unser `CC`.

I understand, the new patch makes it more explicit that we're just avoid 2 flags being set by react-native : 
- CC
- CXX
since they interfere with flags already set by nix.

2023-12-07 09:38 UTC, siddarthkay commented
@status-im/mobile-qa : we don't need QA for this since this just fixes build issues for MacOS Sonoma.

2023-12-07 10:06 UTC, merged

2023-12-07 16:40 UTC, shivekkhurana commented
I was facing the glog issue while trying to run `make pod-install`. Now that is gone, but I get another error:

```1250   │
1251   │ The following build commands failed:
1252   │     SwiftCompile normal arm64 Compiling\ Util.swift /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/Util.swift (in target 'Keycard' from project 'Po
       │ ds')
1253   │     SwiftCompile normal arm64 /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/Util.swift (in target 'Keycard' from project 'Pods')
1254   │     SwiftCompile normal arm64 Compiling\ CashApplicationInfo.swift,\ CashCommandSet.swift /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/CashApplic
       │ ationInfo.swift /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/CashCommandSet.swift (in target 'Keycard' from project 'Pods')
1255   │     SwiftCompile normal arm64 /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/CashApplicationInfo.swift (in target 'Keycard' from project 'Pods')
1256   │     SwiftCompile normal arm64 /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/CashCommandSet.swift (in target 'Keycard' from project 'Pods')
1257   │     SwiftCompile normal arm64 Compiling\ MnemonicEnglish.swift,\ Pairing.swift /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/MnemonicEnglish.swift
       │  /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/Pairing.swift (in target 'Keycard' from project 'Pods')
1258   │     SwiftCompile normal arm64 /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/MnemonicEnglish.swift (in target 'Keycard' from project 'Pods')
1259   │     SwiftCompile normal arm64 /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/Pairing.swift (in target 'Keycard' from project 'Pods')
1260   │     SwiftCompile normal arm64 Compiling\ StatusWord.swift /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/StatusWord.swift (in target 'Keycard' from
       │  project 'Pods')
1261   │     SwiftCompile normal arm64 /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/StatusWord.swift (in target 'Keycard' from project 'Pods')
1262   │     SwiftCompile normal arm64 Compiling\ Metadata.swift,\ Mnemonic.swift /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/Metadata.swift /Users/shive
       │ kkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/Mnemonic.swift (in target 'Keycard' from project 'Pods')
1263   │     SwiftCompile normal arm64 /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/Metadata.swift (in target 'Keycard' from project 'Pods')
1264   │     SwiftCompile normal arm64 /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/Mnemonic.swift (in target 'Keycard' from project 'Pods')
1265   │     SwiftCompile normal arm64 Compiling\ ApplicationInfo.swift,\ ApplicationStatus.swift /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/Application
       │ Info.swift /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/ApplicationStatus.swift (in target 'Keycard' from project 'Pods')
1266   │     SwiftCompile normal arm64 /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/ApplicationInfo.swift (in target 'Keycard' from project 'Pods')
1267   │     SwiftCompile normal arm64 /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/ApplicationStatus.swift (in target 'Keycard' from project 'Pods')
1268   │     SwiftCompile normal arm64 Compiling\ CardChannel.swift,\ CardError.swift /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/CardChannel.swift /User
       │ s/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/CardError.swift (in target 'Keycard' from project 'Pods')
1269   │     SwiftCompile normal arm64 /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/CardChannel.swift (in target 'Keycard' from project 'Pods')
1270   │     SwiftCompile normal arm64 /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/CardError.swift (in target 'Keycard' from project 'Pods')
1271   │     SwiftCompile normal arm64 Compiling\ APDUCommand.swift,\ APDUResponse.swift /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/APDUCommand.swift /U
       │ sers/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/APDUResponse.swift (in target 'Keycard' from project 'Pods')
1272   │     SwiftCompile normal arm64 /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/APDUCommand.swift (in target 'Keycard' from project 'Pods')
1273   │     SwiftCompile normal arm64 /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/APDUResponse.swift (in target 'Keycard' from project 'Pods')
1274   │     SwiftCompile normal arm64 Compiling\ RecoverableSignature.swift,\ SCP02.swift /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/RecoverableSignatu
       │ re.swift /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/SCP02.swift (in target 'Keycard' from project 'Pods')
1275   │     SwiftCompile normal arm64 /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/RecoverableSignature.swift (in target 'Keycard' from project 'Pods')
1276   │     SwiftCompile normal arm64 /Users/shivekkhurana/Wip/status-im/status-mobile/ios/Pods/Keycard/Sources/Keycard/SCP02.swift (in target 'Keycard' from project 'Pods')
1277   │     SwiftEmitModule normal arm64 Emitting\ module\ for\ Keycard (in target 'Keycard' from project 'Pods')
1278   │ (26 failures)
1279   │
```

Here's the complete log file. 
[log.txt](https://github.com/status-im/status-mobile/files/13602719/log.txt)

Did anyone else face this issue ?

2023-12-07 16:49 UTC, siddarthkay commented
@flexsurfer : faced this

2023-12-08 05:47 UTC, flexsurfer commented
hey @shivekkhurana glad to see you :) so i don't know what helped but i cleaned entire project,
removed node_modules, removed ios build and pods, run make xcode-clean  , open xcode and from menu clean build folder, and then it worked ;)

2023-12-08 14:37 UTC, shivekkhurana commented
Glad to see you too Andrey 👋👋
I'll try that out.