clean gradle deps before running `make nix-update-gradle` & retry 3 times for pom failures
status-im/status-react pull request #18579
Opened 2024-01-21 06:53 UTC by siddarthkay

## Summary

When `make nix-update-gradle` fails due to whatever reason.
The local folder has incomplete progress in the following files : 

- `nix/deps/gradle/deps.json`
- `nix/deps/gradle/deps.list`
- `nix/deps/gradle/deps.urls`
- `nix/deps/gradle/proj.list`

This PR adds a makefile command to restore the changes made to these file before running `make nix-update-gradle` so that we get consistent results every-time without manually revert changes in those files.

This PR also links to a branch in go-maven-resolver which retries getting pom url incase of failures.
PR in go-maven-resolver -> https://github.com/status-im/go-maven-resolver/pull/7

fixes #18294

## Testing notes 
QA is not required for this PR

status: ready

2024-01-21 06:59 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 6038d95f | [#1](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-18579/1/) | 2024-01-21 06:59:22 | ~5 min | `tests` | [:page_facing_up:`log`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-240121-065339-6038d9-pr18579-tests.log) |

2024-01-29 19:39 UTC, jakubgs requested changes
The `go-maven-resolver` already supports retries.

2024-01-29 19:39 UTC, jakubgs commented on Makefile
> +	@git restore nix/deps/gradle/deps.json nix/deps/gradle/deps.list nix/deps/gradle/deps.urls nix/deps/gradle/proj.list
Seems very niche and not that useful.

2024-01-29 19:39 UTC, jakubgs commented on Makefile
> +	@echo "Running generate.sh script..."
What for?

2024-04-29 12:13 UTC, flexsurfer commented
cc @siddarthkay still relevant?

2024-04-29 13:49 UTC, closed without merging

2024-04-29 13:49 UTC, siddarthkay commented
@flexsurfer : no we can close this.