Sort communities by currently active tab
status-im/status-react pull request #18812
Opened 2024-02-13 21:49 UTC by ibrkhalil

fixes #17337

### Summary

Sorts communities by last-opened-at property, And falls back to joined-at property if last-opened-at doesn't exist.

status: ready

2024-02-13 21:56 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 33ba9ca6 | [#1](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-18812/1/) | 2024-02-13 21:56:04 | ~6 min | `tests` | [:page_facing_up:`log`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-240213-214935-33ba9c-pr18812-tests.log) |

2024-02-14 10:03 UTC, cammellos commented on src/status_im/contexts/communities/home/view.cljs
> +             :data                              (sort-by (fn [{:keys [last-opened-at joined-at]}]
should be done in subscription

2024-02-14 23:58 UTC, ibrkhalil commented on src/status_im/contexts/communities/events.cljs
> +            (assoc community :last-opened-at (max last-opened-at previous-last-opened-at)))
This is a fix to handle a race condition that happens between fetching the last community details and updating the last opened at key when opening a community.

2024-02-15 08:05 UTC, shivekkhurana requested changes

2024-02-15 08:05 UTC, shivekkhurana commented on src/status_im/subs/communities.cljs
> +                                       (sort-by (fn [{:keys [last-opened-at joined-at]}]
This reducer seems to be going out of control. Can you simplify it  ?
```clj
(reduce (fn [acc community]
          (let [joined?      (:joined community)
                community-id (:id community)
                pending?     (boolean (get requests community-id))]
            (cond
              joined?  (update acc :joined conj community)
              pending? (update acc :pending conj community)
              :else    (update acc :opened conj community))))
        {:joined [] :pending [] :opened []}
        (sort-by (fn [{:keys [last-opened-at joined-at]}]
                   (or last-opened-at joined-at))
                 #(compare %2 %1)
                 (vals communities)))
```

I think we can get rid of the reducer completely. Something like this should be doable:

```clj
(->> communities
         vals
         (sort-by ...)
         (group-by ...)
         (merge-with ...))
```
Links to relavent functions:
- https://clojuredocs.org/clojure.core/group-by
- https://clojuredocs.org/clojure.core/merge-with

2024-02-19 18:52 UTC, ibrkhalil commented on src/status_im/subs/communities.cljs
> +                                       (sort-by (fn [{:keys [last-opened-at joined-at]}]
Done, And thank you for your help on this Shivek!

2024-02-20 08:32 UTC, shivekkhurana commented on src/status_im/subs/communities.cljs
> +
A more crisp version:
```clj
(defn- group-communities-by-status
  [requests {:keys [id] :as community}]
  (cond
    (:joined community)         :joined
    (boolean (get requests id)) :pending
    :else                       :opened))
```

2024-02-20 08:41 UTC, shivekkhurana approved these changes
![image](https://github.com/status-im/status-mobile/assets/1925158/1bed9cfb-9afc-405f-8406-0ef2ab40a425)

2024-02-20 10:20 UTC, ibrkhalil commented on src/status_im/subs/communities.cljs
> +
Done

2024-02-20 16:18 UTC, status-im-auto commented
## 0% of end-end tests have passed
```
Total executed tests: 48
Failed tests: 47
Expected to fail tests: 1
Passed tests: 0
```
```
IDs of failed tests: 702809,702782,702733,702784,703194,702859,702777,702732,702813,703133,704613,702957,702851,702840,703495,703086,702948,702894,702745,702783,702850,702742,703297,704615,702869,703496,702936,702855,703202,703391,702786,702839,702947,702838,702844,702846,702843,702807,702731,702808,702730,702845,702775,702958,703629,703382,702841 
```
```
IDs of expected to fail tests: 703503 
```
<h3>Failed tests (47)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&PR_ID=18812&TR_CASE_IDS=702809,702782,702733,702784,703194,702859,702777,702732,702813,703133,704613,702957,702851,702840,703495,703086,702948,702894,702745,702783,702850,702742,703297,704615,702869,703496,702936,702855,703202,703391,702786,702839,702947,702838,702844,702846,702843,702807,702731,702808,702730,702845,702775,702958,703629,703382,702841">Rerun failed tests</a></li><br/><h4>Class TestOneToOneChatMultipleSharedDevicesNewUiTwo:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3458299">test_1_1_chat_delete_via_long_press_relogin</a>, id: 702784 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_1_1_public_chats.py:526: in prepare_devices
    self.drivers, self.loop = create_shared_drivers(2)
base_test_case.py:323: in create_shared_drivers
    raise e
base_test_case.py:316: in create_shared_drivers
    test_suite_data.current_test.testruns[-1].jobs[drivers[i].session_id] = i + 1
 '_asyncio.Future' object has no attribute 'session_id'
```

<br/><br/></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3458298">test_1_1_chat_is_shown_message_sent_delivered_from_offline</a>, id: 702783 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_1_1_public_chats.py:526: in prepare_devices
    self.drivers, self.loop = create_shared_drivers(2)
base_test_case.py:323: in create_shared_drivers
    raise e
base_test_case.py:316: in create_shared_drivers
    test_suite_data.current_test.testruns[-1].jobs[drivers[i].session_id] = i + 1
 '_asyncio.Future' object has no attribute 'session_id'
```

<br/><br/></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3458332">test_1_1_chat_mute_chat</a>, id: 703496 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_1_1_public_chats.py:526: in prepare_devices
    self.drivers, self.loop = create_shared_drivers(2)
base_test_case.py:323: in create_shared_drivers
    raise e
base_test_case.py:316: in create_shared_drivers
    test_suite_data.current_test.testruns[-1].jobs[drivers[i].session_id] = i + 1
 '_asyncio.Future' object has no attribute 'session_id'
```

<br/><br/></td></tr></tbody></table><h4>Class TestDeepLinksOneDevice:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3458335">test_links_open_universal_links_from_chat</a>, id: 704613 </b></td></tr><tr><td>

```
Test setup failed: critical/test_deep_and_universal_links.py:13: in prepare_devices
    self.drivers, self.loop = create_shared_drivers(1)
base_test_case.py:323: in create_shared_drivers
    raise e
base_test_case.py:316: in create_shared_drivers
    test_suite_data.current_test.testruns[-1].jobs[drivers[i].session_id] = i + 1
 '_asyncio.Future' object has no attribute 'session_id'
```

<br/><br/></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3458295">test_links_deep_links</a>, id: 702775 </b></td></tr><tr><td>

```
Test setup failed: critical/test_deep_and_universal_links.py:13: in prepare_devices
    self.drivers, self.loop = create_shared_drivers(1)
base_test_case.py:323: in create_shared_drivers
    raise e
base_test_case.py:316: in create_shared_drivers
    test_suite_data.current_test.testruns[-1].jobs[drivers[i].session_id] = i + 1
 '_asyncio.Future' object has no attribute 'session_id'
```

<br/><br/></td></tr></tbody></table><h4>Class TestCommunityMultipleDeviceMerged:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3458326">test_community_several_images_send_reply</a>, id: 703194 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_public_chat_browsing.py:284: in prepare_devices
    self.drivers, self.loop = create_shared_drivers(2)
base_test_case.py:323: in create_shared_drivers
    raise e
base_test_case.py:316: in create_shared_drivers
    test_suite_data.current_test.testruns[-1].jobs[drivers[i].session_id] = i + 1
 '_asyncio.Future' object has no attribute 'session_id'
```

<br/><br/></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3458316">test_community_one_image_send_reply</a>, id: 702859 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_public_chat_browsing.py:284: in prepare_devices
    self.drivers, self.loop = create_shared_drivers(2)
base_test_case.py:323: in create_shared_drivers
    raise e
base_test_case.py:316: in create_shared_drivers
    test_suite_data.current_test.testruns[-1].jobs[drivers[i].session_id] = i + 1
 '_asyncio.Future' object has no attribute 'session_id'
```

<br/><br/></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3458307">test_community_emoji_send_copy_paste_reply</a>, id: 702840 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_public_chat_browsing.py:284: in prepare_devices
    self.drivers, self.loop = create_shared_drivers(2)
base_test_case.py:323: in create_shared_drivers
    raise e
base_test_case.py:316: in create_shared_drivers
    test_suite_data.current_test.testruns[-1].jobs[drivers[i].session_id] = i + 1
 '_asyncio.Future' object has no attribute 'session_id'
```

<br/><br/></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3458324">test_community_mark_all_messages_as_read</a>, id: 703086 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_public_chat_browsing.py:284: in prepare_devices
    self.drivers, self.loop = create_shared_drivers(2)
base_test_case.py:323: in create_shared_drivers
    raise e
base_test_case.py:316: in create_shared_drivers
    test_suite_data.current_test.testruns[-1].jobs[drivers[i].session_id] = i + 1
 '_asyncio.Future' object has no attribute 'session_id'
```

<br/><br/></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3458318">test_community_contact_block_unblock_offline</a>, id: 702894 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_public_chat_browsing.py:284: in prepare_devices
    self.drivers, self.loop = create_shared_drivers(2)
base_test_case.py:323: in create_shared_drivers
    raise e
base_test_case.py:316: in create_shared_drivers
    test_suite_data.current_test.testruns[-1].jobs[drivers[i].session_id] = i + 1
 '_asyncio.Future' object has no attribute 'session_id'
```

<br/><br/></td></tr><tr><td><b>6. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3458336">test_community_edit_delete_message_when_offline</a>, id: 704615 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_public_chat_browsing.py:284: in prepare_devices
    self.drivers, self.loop = create_shared_drivers(2)
base_test_case.py:323: in create_shared_drivers
    raise e
base_test_case.py:316: in create_shared_drivers
    test_suite_data.current_test.testruns[-1].jobs[drivers[i].session_id] = i + 1
 '_asy [...]

2024-02-21 13:19 UTC, status-im-auto commented
## 88% of end-end tests have passed
```
Total executed tests: 48
Failed tests: 5
Expected to fail tests: 1
Passed tests: 42
```
```
IDs of failed tests: 702809,702948,702786,702845,703629 
```
```
IDs of expected to fail tests: 703503 
```
<h3>Failed tests (5)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&PR_ID=18812&TR_CASE_IDS=702809,702948,702786,702845,703629">Rerun failed tests</a></li><br/><h4>Class TestCommunityMultipleDeviceMergedTwo:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3459735">test_community_markdown_support</a>, id: 702809 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_public_chat_browsing.py:837: in prepare_devices
    self.community_2.join_community()
../views/chat_view.py:444: in join_community
    self.community_status_joined.wait_for_visibility_of_element(60)
../views/base_element.py:139: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 2: Text by accessibility id:`status-tag-positive` is not found on the screen after wait_for_visibility_of_element
```

<br/><br/></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3459753">test_community_hashtag_links_to_community_channels</a>, id: 702948 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_public_chat_browsing.py:837: in prepare_devices
    self.community_2.join_community()
../views/chat_view.py:444: in join_community
    self.community_status_joined.wait_for_visibility_of_element(60)
../views/base_element.py:139: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 2: Text by accessibility id:`status-tag-positive` is not found on the screen after wait_for_visibility_of_element
```

<br/><br/></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3459732">test_community_mentions_push_notification</a>, id: 702786 </b></td></tr><tr><td><p><blockquote><div>Device 2: Find `Button` by `xpath`: `//*[@content-desc='password-input']/../following-sibling::*//*[@text='Join Community']` </div><div>Device 2: Tap on found: Button </div></blockquote></p>

```
Test setup failed: critical/chats/test_public_chat_browsing.py:837: in prepare_devices
    self.community_2.join_community()
../views/chat_view.py:444: in join_community
    self.community_status_joined.wait_for_visibility_of_element(60)
../views/base_element.py:139: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 2: Text by accessibility id:`status-tag-positive` is not found on the screen after wait_for_visibility_of_element
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/1ee05ae05c16475e8cdb08630c03c7ea?auth=8a6f4d3308660e02f8ec526641904d8e">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/6c18c0efcdcb42d7adf1998bd564c2ed?auth=d96c642101991bf1a22c79d875afaeec">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3459743">test_community_leave</a>, id: 702845 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_public_chat_browsing.py:837: in prepare_devices
    self.community_2.join_community()
../views/chat_view.py:444: in join_community
    self.community_status_joined.wait_for_visibility_of_element(60)
../views/base_element.py:139: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 2: Text by accessibility id:`status-tag-positive` is not found on the screen after wait_for_visibility_of_element
```

<br/><br/></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3459766">test_community_join_when_node_owner_offline</a>, id: 703629 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_public_chat_browsing.py:837: in prepare_devices
    self.community_2.join_community()
../views/chat_view.py:444: in join_community
    self.community_status_joined.wait_for_visibility_of_element(60)
../views/base_element.py:139: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 2: Text by accessibility id:`status-tag-positive` is not found on the screen after wait_for_visibility_of_element
```

<br/><br/></td></tr></tbody></table></details><h3>Expected to fail tests (1)</h3><details><summary>Click to expand</summary><br/><br/><h4>Class TestCommunityOneDeviceMerged:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3459765">test_community_discovery</a>, id: 703503 </b></td></tr><tr><td>

```
Test is not run, e2e blocker  
```

<b>[[reason: [NOTRUN] Curated communities not loading, https://github.com/status-im/status-mobile/issues/17852]]</b><br/><br/></td></tr></tbody></table></details><h3>Passed tests (42)</h3><details><summary>Click to expand</summary><br/><br/><h4>Class TestActivityMultipleDevicePRTwo:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3459754">test_activity_center_mentions</a>, id: 702957 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/5612c8a16e744f60a49e74db9a1ef080?auth=1474252ea57764ea92335c5320ab6edb#119">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/95481cb4d41a4febbe969a576d3f5771?auth=09c42c1302fc255fdf9e3bb3f5911d35#103">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3459755">test_activity_center_admin_notification_accept_swipe</a>, id: 702958 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/5612c8a16e744f60a49e74db9a1ef080?auth=1474252ea57764ea92335c5320ab6edb#167">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/95481cb4d41a4febbe969a576d3f5771?auth=09c42c1302fc255fdf9e3bb3f5911d35#119">Steps, video, logs</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestActivityMultipleDevicePR:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3459751">test_navigation_jump_to</a>, id: 702936 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/4b68fbb93be5491790c54a726f36e0a2?auth=4cd126ea0d772d5386ce63d1b4caca02#139">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/dcde920262d94bd182f64245a6bc26ac?auth=4b1fc245c3408a0b61746ee59e9218be#120">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3459752">test_activity_center_reply_read_unread_delete_filter_swipe</a>, id: 702947 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/4b68fbb93be5491790c54a726f36e0a2?auth=4cd126ea0d772d5386ce63d1b4caca02#167">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.co [...]

2024-02-22 11:22 UTC, mariia-skrypnyk commented
**ISSUE 1: Opened tab isn't sorted by the last opened if user opens communities from links in 1 to 1 chat**

**Preconditions:** User B (desktop) created 3 communities with required approve


**Steps:** 

1. Login as user A
2. Add User B to contacts (desktop user)
3. As User B share all 3 communities
4. As User A open links to every community

**Actual result:** Most opened on the bottom

https://github.com/status-im/status-mobile/assets/147824399/59ce3891-e064-4850-96e6-463820439834


**Expected result:** Most opened on top

Devices: iOS/Android

2024-02-22 12:14 UTC, mariia-skrypnyk commented
ISSUE 2: Most recent joined are not on the top

Preconditions: User B (desktop) created 3 communities with required approve

Steps:

1. Login as user A
2. Add User B to contacts (desktop user)
3. As User B share all 3 communities
4. As User A request to join all 3 communities
5. As User B accept request by request from the first request to the last

Actual result:

1) User B accepts requests isn such sequence:
Pink
Greener
Red
2) User B sees such list in his Joined tab:
Pink
Greener
Red

So there is no "Most recent joined are not on the top" logic here

Expected result: Most recent joined on the top

2024-02-24 08:13 UTC, ibrkhalil commented
@mariia-skrypnyk Both issues should be fixed now, Can you please take another look?

2024-02-25 11:10 UTC, status-im-auto commented
## 12% of end-end tests have passed
```
Total executed tests: 48
Failed tests: 41
Expected to fail tests: 1
Passed tests: 6
```
```
IDs of failed tests: 702845,702840,702894,703086,702855,702947,702730,702958,702786,702745,702731,702844,702851,703202,702841,703496,702807,702839,702733,702808,702809,702838,702813,704615,702948,702859,703629,703133,702957,702783,702843,702782,702850,702784,703391,702732,703297,702936,703495,702777,703194 
```
```
IDs of expected to fail tests: 703503 
```
<h3>Failed tests (41)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&PR_ID=18812&TR_CASE_IDS=702845,702840,702894,703086,702855,702947,702730,702958,702786,702745,702731,702844,702851,703202,702841,703496,702807,702839,702733,702808,702809,702838,702813,704615,702948,702859,703629,703133,702957,702783,702843,702782,702850,702784,703391,702732,703297,702936,703495,702777,703194">Rerun failed tests</a></li><br/><h4>Class TestOneToOneChatMultipleSharedDevicesNewUi:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3469217">test_1_1_chat_edit_message</a>, id: 702855 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_1_1_public_chats.py:40: in prepare_devices
    self.home_2.handle_contact_request(self.username_1)
../views/home_view.py:382: in handle_contact_request
    chat_element.accept_contact_request()
../views/home_view.py:150: in accept_contact_request
    self.handle_cr("accept-contact-request")
../views/home_view.py:147: in handle_cr
    ).wait_for_rendering_ended_and_click()
../views/base_element.py:163: in wait_for_rendering_ended_and_click
    self.wait_for_visibility_of_element(20)
../views/base_element.py:147: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 2: Button by xpath:`//*[contains(@text, 'sender')]/ancestor::*[@content-desc='activity']/*[@content-desc="accept-contact-request"]` is not found on the screen after wait_for_visibility_of_element
```

<br/><br/></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3469191">test_1_1_chat_message_reaction</a>, id: 702730 </b></td></tr><tr><td><p><blockquote><div>Device 2: Tap on found: Button </div><div>Device 2: Attempt 0 is successful clicking close-activity-center </div></blockquote></p>

```
Test setup failed: critical/chats/test_1_1_public_chats.py:40: in prepare_devices
    self.home_2.handle_contact_request(self.username_1)
../views/home_view.py:382: in handle_contact_request
    chat_element.accept_contact_request()
../views/home_view.py:150: in accept_contact_request
    self.handle_cr("accept-contact-request")
../views/home_view.py:147: in handle_cr
    ).wait_for_rendering_ended_and_click()
../views/base_element.py:163: in wait_for_rendering_ended_and_click
    self.wait_for_visibility_of_element(20)
../views/base_element.py:147: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 2: Button by xpath:`//*[contains(@text, 'sender')]/ancestor::*[@content-desc='activity']/*[@content-desc="accept-contact-request"]` is not found on the screen after wait_for_visibility_of_element
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/7b4c0dc63cd340089a0cd31ae6b8820d?auth=3192db3fde4ca1612e74cc88b3c8b786">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/62c9c5b104e149e0a11de4dbeb2075ac?auth=861d8610dd1070cfa29e9e8212754796">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3469196">test_1_1_chat_non_latin_messages_stack_update_profile_photo</a>, id: 702745 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_1_1_public_chats.py:40: in prepare_devices
    self.home_2.handle_contact_request(self.username_1)
../views/home_view.py:382: in handle_contact_request
    chat_element.accept_contact_request()
../views/home_view.py:150: in accept_contact_request
    self.handle_cr("accept-contact-request")
../views/home_view.py:147: in handle_cr
    ).wait_for_rendering_ended_and_click()
../views/base_element.py:163: in wait_for_rendering_ended_and_click
    self.wait_for_visibility_of_element(20)
../views/base_element.py:147: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 2: Button by xpath:`//*[contains(@text, 'sender')]/ancestor::*[@content-desc='activity']/*[@content-desc="accept-contact-request"]` is not found on the screen after wait_for_visibility_of_element
```

<br/><br/></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3469192">test_1_1_chat_pin_messages</a>, id: 702731 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_1_1_public_chats.py:40: in prepare_devices
    self.home_2.handle_contact_request(self.username_1)
../views/home_view.py:382: in handle_contact_request
    chat_element.accept_contact_request()
../views/home_view.py:150: in accept_contact_request
    self.handle_cr("accept-contact-request")
../views/home_view.py:147: in handle_cr
    ).wait_for_rendering_ended_and_click()
../views/base_element.py:163: in wait_for_rendering_ended_and_click
    self.wait_for_visibility_of_element(20)
../views/base_element.py:147: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 2: Button by xpath:`//*[contains(@text, 'sender')]/ancestor::*[@content-desc='activity']/*[@content-desc="accept-contact-request"]` is not found on the screen after wait_for_visibility_of_element
```

<br/><br/></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3469194">test_1_1_chat_text_message_delete_push_disappear</a>, id: 702733 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_1_1_public_chats.py:40: in prepare_devices
    self.home_2.handle_contact_request(self.username_1)
../views/home_view.py:382: in handle_contact_request
    chat_element.accept_contact_request()
../views/home_view.py:150: in accept_contact_request
    self.handle_cr("accept-contact-request")
../views/home_view.py:147: in handle_cr
    ).wait_for_rendering_ended_and_click()
../views/base_element.py:163: in wait_for_rendering_ended_and_click
    self.wait_for_visibility_of_element(20)
../views/base_element.py:147: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 2: Button by xpath:`//*[contains(@text, 'sender')]/ancestor::*[@content-desc='activity']/*[@content-desc="accept-contact-request"]` is not found on the screen after wait_for_visibility_of_element
```

<br/><br/></td></tr><tr><td><b>6. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3469206">test_1_1_chat_push_emoji</a>, id: 702813 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_1_1_public_chats.py:40: in prepare_devices
    self.home_2.handle_contact_request(self.username_1)
../views/home_view.py:382: in handle_contact_request
    chat_element.accept_contact_request()
../views/home_view.py:150: in accept_contact_request
    self.handle_cr("accept-contact-request")
../views/home_view.py:147: in handle_cr
    ).wait_for_rendering_ended_and_click()
../views/base_element.py:163: in wait_for_rendering_ended_and_click
    self.wait_for_visibility_of_element(20)
../views/base_element.py:147: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 2: Button by xpath:`//*[contains(@text, 'sender')]/ancestor::*[@content-desc='activity']/*[@content-desc="accept-contact-request"]` is not found on the screen after wait_for_visibilit [...]

2024-02-29 15:17 UTC, status-im-auto commented
## 19% of end-end tests have passed
```
Total executed tests: 48
Failed tests: 38
Expected to fail tests: 1
Passed tests: 9
```
```
IDs of failed tests: 702809,702782,702733,703194,702859,702777,702732,702813,704613,702957,702851,702840,703495,703086,702948,702894,702745,703297,704615,702936,702855,703202,703391,702786,702839,702947,702838,702844,702843,702807,702731,702808,702730,702845,702775,702958,703629,702841 
```
```
IDs of expected to fail tests: 703503 
```
<h3>Failed tests (38)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&PR_ID=18812&TR_CASE_IDS=702809,702782,702733,703194,702859,702777,702732,702813,704613,702957,702851,702840,703495,703086,702948,702894,702745,703297,704615,702936,702855,703202,703391,702786,702839,702947,702838,702844,702843,702807,702731,702808,702730,702845,702775,702958,703629,702841">Rerun failed tests</a></li><br/><h4>Class TestCommunityMultipleDeviceMerged:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3473329">test_community_several_images_send_reply</a>, id: 703194 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_public_chat_browsing.py:296: in prepare_devices
    self.home_2.handle_contact_request(self.username_1)
../views/home_view.py:382: in handle_contact_request
    chat_element.accept_contact_request()
../views/home_view.py:150: in accept_contact_request
    self.handle_cr("accept-contact-request")
../views/home_view.py:147: in handle_cr
    ).wait_for_rendering_ended_and_click()
../views/base_element.py:163: in wait_for_rendering_ended_and_click
    self.wait_for_visibility_of_element(20)
../views/base_element.py:147: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 2: Button by xpath:`//*[contains(@text, 'user_1')]/ancestor::*[@content-desc='activity']/*[@content-desc="accept-contact-request"]` is not found on the screen after wait_for_visibility_of_element
```

<br/><br/></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3473319">test_community_one_image_send_reply</a>, id: 702859 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_public_chat_browsing.py:296: in prepare_devices
    self.home_2.handle_contact_request(self.username_1)
../views/home_view.py:382: in handle_contact_request
    chat_element.accept_contact_request()
../views/home_view.py:150: in accept_contact_request
    self.handle_cr("accept-contact-request")
../views/home_view.py:147: in handle_cr
    ).wait_for_rendering_ended_and_click()
../views/base_element.py:163: in wait_for_rendering_ended_and_click
    self.wait_for_visibility_of_element(20)
../views/base_element.py:147: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 2: Button by xpath:`//*[contains(@text, 'user_1')]/ancestor::*[@content-desc='activity']/*[@content-desc="accept-contact-request"]` is not found on the screen after wait_for_visibility_of_element
```

<br/><br/></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3473310">test_community_emoji_send_copy_paste_reply</a>, id: 702840 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_public_chat_browsing.py:296: in prepare_devices
    self.home_2.handle_contact_request(self.username_1)
../views/home_view.py:382: in handle_contact_request
    chat_element.accept_contact_request()
../views/home_view.py:150: in accept_contact_request
    self.handle_cr("accept-contact-request")
../views/home_view.py:147: in handle_cr
    ).wait_for_rendering_ended_and_click()
../views/base_element.py:163: in wait_for_rendering_ended_and_click
    self.wait_for_visibility_of_element(20)
../views/base_element.py:147: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 2: Button by xpath:`//*[contains(@text, 'user_1')]/ancestor::*[@content-desc='activity']/*[@content-desc="accept-contact-request"]` is not found on the screen after wait_for_visibility_of_element
```

<br/><br/></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3473327">test_community_mark_all_messages_as_read</a>, id: 703086 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_public_chat_browsing.py:296: in prepare_devices
    self.home_2.handle_contact_request(self.username_1)
../views/home_view.py:382: in handle_contact_request
    chat_element.accept_contact_request()
../views/home_view.py:150: in accept_contact_request
    self.handle_cr("accept-contact-request")
../views/home_view.py:147: in handle_cr
    ).wait_for_rendering_ended_and_click()
../views/base_element.py:163: in wait_for_rendering_ended_and_click
    self.wait_for_visibility_of_element(20)
../views/base_element.py:147: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 2: Button by xpath:`//*[contains(@text, 'user_1')]/ancestor::*[@content-desc='activity']/*[@content-desc="accept-contact-request"]` is not found on the screen after wait_for_visibility_of_element
```

<br/><br/></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3473321">test_community_contact_block_unblock_offline</a>, id: 702894 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_public_chat_browsing.py:296: in prepare_devices
    self.home_2.handle_contact_request(self.username_1)
../views/home_view.py:382: in handle_contact_request
    chat_element.accept_contact_request()
../views/home_view.py:150: in accept_contact_request
    self.handle_cr("accept-contact-request")
../views/home_view.py:147: in handle_cr
    ).wait_for_rendering_ended_and_click()
../views/base_element.py:163: in wait_for_rendering_ended_and_click
    self.wait_for_visibility_of_element(20)
../views/base_element.py:147: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 2: Button by xpath:`//*[contains(@text, 'user_1')]/ancestor::*[@content-desc='activity']/*[@content-desc="accept-contact-request"]` is not found on the screen after wait_for_visibility_of_element
```

<br/><br/></td></tr><tr><td><b>6. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3473339">test_community_edit_delete_message_when_offline</a>, id: 704615 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_public_chat_browsing.py:296: in prepare_devices
    self.home_2.handle_contact_request(self.username_1)
../views/home_view.py:382: in handle_contact_request
    chat_element.accept_contact_request()
../views/home_view.py:150: in accept_contact_request
    self.handle_cr("accept-contact-request")
../views/home_view.py:147: in handle_cr
    ).wait_for_rendering_ended_and_click()
../views/base_element.py:163: in wait_for_rendering_ended_and_click
    self.wait_for_visibility_of_element(20)
../views/base_element.py:147: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 2: Button by xpath:`//*[contains(@text, 'user_1')]/ancestor::*[@content-desc='activity']/*[@content-desc="accept-contact-request"]` is not found on the screen after wait_for_visibility_of_element
```

<br/><br/></td></tr><tr><td><b>7. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3473309">test_community_message_delete</a>, id: 702839 </b></td></tr><tr><td>

```
Test setup failed: critical/chats/test_public_chat_browsing.py:296: in prepare_devices
    self.home_2.handle_contact_request(self.username_1)
../views/home_view.py:382: in handle_contact_request
    chat_element.accept_contact_request()
../views/home_view.py:150: in accept_contact_request
    self.handle_cr("accept-contact-request")
../views/home_view.py:147: in handle_cr
    ).wait_for_rendering_ended_and_click()
../views/base_element.py:163: in wait_for_rendering_ended_and_click
    self.wait_for_visibility_of_element(20)
../v [...]

2024-03-04 12:42 UTC, mariia-skrypnyk commented
@ibrkhalil please, do rebase.

2024-03-04 12:43 UTC, ibrkhalil commented
> @ibrkhalil please, do rebase.

Done

2024-03-04 13:41 UTC, mariia-skrypnyk commented
Hi @ibrkhalil !

Issue 2 is fixed!
Issue 1 still have some points:

According to https://github.com/status-im/status-mobile/issues/17337#issuecomment-1851952622 we need such implementation:

1) Opened tab SHOULD show us communities we opened from last opened on top.
Also Opened tab SHOULD include communities that we Joined and NOT Joined too. 
Now we have a case when opened Joined communities are not shown in Opened tab. Please look at the video:

https://github.com/status-im/status-mobile/assets/147824399/649a63db-bbce-4e7a-bd01-98da3db86593
I open joined communities but they are not shown in Opened tab.

2) The second issue also is described in video above: when you open communities from Joined tab they become sorted 
NOT by order of joining but by order of opening in Joined tab. BUT they should be ordered by order of joining:
<img width="521" alt="Screenshot 2024-03-04 at 14 39 26" src="https://github.com/status-im/status-mobile/assets/147824399/8421d4b0-5bbf-44dd-a788-cab81e77d92f">

2024-03-04 13:42 UTC, status-im-auto commented
## 88% of end-end tests have passed
```
Total executed tests: 48
Failed tests: 5
Expected to fail tests: 1
Passed tests: 42
```
```
IDs of failed tests: 702894,702730,702948,702782,702732 
```
```
IDs of expected to fail tests: 703503 
```
<h3>Failed tests (5)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&PR_ID=18812&TR_CASE_IDS=702894,702730,702948,702782,702732">Rerun failed tests</a></li><br/><h4>Class TestGroupChatMultipleDeviceMergedNewUI:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3477265">test_group_chat_pin_messages</a>, id: 702732 </b></td></tr><tr><td><p><blockquote><div>Device 2: Find `Text` by `xpath`: `//*[@content-desc='pinned-messages-menu']//*[starts-with(@text,'Message 4')]/../../*[@content-desc='pinned-by']/android.widget.TextView` </div><div>Device 2: `Text` is `user admin` </div></blockquote></p>

```
critical/chats/test_group_chat.py:404: in test_group_chat_pin_messages
    self.errors.verify_no_errors()
base_test_case.py:191: in verify_no_errors
    pytest.fail('\n '.join([self.errors.pop(0) for _ in range(len(self.errors))]))
 Pinned messages count 2 doesn't match expected 3 for user 2
E    Message 'Message 3' is missed on Pinned messages list for user 2
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/8f986f47fffb47ee999f5066003a5b5c?auth=25e40dccba0764e9e258e18de435f3fc#348">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/83aa0f41ee4f490bbb2ac26764fde788?auth=af07f0724bca32d3bfb093bd74317b54#246">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 3:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/3aa250cc629244ef9fedc7a0f480e57e?auth=23268984172e48fbab925345729442e9#241">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestCommunityMultipleDeviceMerged:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3477292">test_community_contact_block_unblock_offline</a>, id: 702894 </b></td></tr><tr><td><p><blockquote><div>Device 2: Find `Text` by `xpath`: `//*[starts-with(@text,'Hurray! unblocked')]/ancestor::android.view.ViewGroup[@content-desc='chat-item']//*[@content-desc='message-status']/android.widget.TextView` </div><div>Device 2: `Text` is `Sent` </div></blockquote></p>

```
critical/chats/test_public_chat_browsing.py:738: in test_community_contact_block_unblock_offline
    self.errors.verify_no_errors()
base_test_case.py:191: in verify_no_errors
    pytest.fail('\n '.join([self.errors.pop(0) for _ in range(len(self.errors))]))
 Message was not delivered after back up online.
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/dcbf322674144e9fb2f57d485ad01811?auth=563cfd83ab5a5215df7df98eb8ba6f21#399">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/cb773381fe354f00804bf32c5a48c456?auth=575954ec08e1be34ee139f2a6a524b7d#357">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestCommunityMultipleDeviceMergedTwo:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3477295">test_community_hashtag_links_to_community_channels</a>, id: 702948 </b></td></tr><tr><td><p><blockquote><div>Device 2: Click until `ChatMessageInput` by `accessibility id`: `chat-message-input` will be presented </div><div>Device 2: Looking for a message by text: #cats </div></blockquote></p>

```
critical/chats/test_public_chat_browsing.py:1063: in test_community_hashtag_links_to_community_channels
    self.channel_2.chat_element_by_text(message_with_hashtag).click_on_link_inside_message_body()
../views/chat_view.py:193: in click_on_link_inside_message_body
    self.message_body.wait_for_visibility_of_element(30)
../views/base_element.py:147: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 2: Text by xpath:`//android.view.ViewGroup[@content-desc='chat-item']//android.widget.TextView[contains(@text,'#cats')]` is not found on the screen after wait_for_visibility_of_element
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/15ee39782d8d4436a16107e187cf60e8?auth=26fdb9dbb5f731886b5154b20aa64aa7#331">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/829e2fc662e04a5abf8649f113431c18?auth=d06b18ea2ab5a88cc8f8333c9b092919#332">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestOneToOneChatMultipleSharedDevicesNewUi:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3477263">test_1_1_chat_message_reaction</a>, id: 702730 </b></td></tr><tr><td><p><blockquote><div>Device 1: Find `EmojisNumber` by `xpath`: `//*[starts-with(@text,'Message sender')]/ancestor::android.view.ViewGroup[@content-desc='chat-item']/../..//*[@content-desc='emoji-reaction-2']/android.widget.TextView[2]` </div><div>Device 1: Find `EmojisNumber` by `xpath`: `//*[starts-with(@text,'Message sender')]/ancestor::android.view.ViewGroup[@content-desc='chat-item']/../..//*[@content-desc='emoji-reaction-2']/android.widget.TextView[2]` </div></blockquote></p>

```
critical/chats/test_1_1_public_chats.py:73: in test_1_1_chat_message_reaction
    message_sender.emojis_below_message(emoji="thumbs-up").wait_for_element_text(1, 90)
../views/base_element.py:190: in wait_for_element_text
    self.driver.fail(message if message else "`%s` is not equal to expected `%s` in %s sec" % (
base_test_case.py:179: in fail
    pytest.fail('Device %s: %s' % (self.number, text))
 Device 1: `2` is not equal to expected `1` in 90 sec
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/4ab926d5adbc4658b987a78a3e7bb122?auth=70d5cc47dc65412adc6b9225a9b0d8ba#86">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/d77ec0eeec7540a3b70db31d16aa86be?auth=202dd70a2d561f60b7519e6bad43b736#87">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3477271">test_1_1_chat_emoji_send_reply_and_open_link</a>, id: 702782 </b></td></tr><tr><td><p><blockquote><div>Device 1: Tap on found: SendMessageButton </div><div>Device 2: Looking f [...]

2024-03-05 16:17 UTC, ibrkhalil commented
> Hi @ibrkhalil !
> 
> Issue 2 is fixed! Issue 1 still have some points:
> 
> According to [#17337 (comment)](https://github.com/status-im/status-mobile/issues/17337#issuecomment-1851952622) we need such implementation:
> 
> 1. Opened tab SHOULD show us communities we opened from last opened on top.
>    Also Opened tab SHOULD include communities that we Joined and NOT Joined too.
>    Now we have a case when opened Joined communities are not shown in Opened tab. Please look at the video:
> 
> https://github.com/status-im/status-mobile/assets/147824399/649a63db-bbce-4e7a-bd01-98da3db86593 Actual result: I've open joined communities but they are not shown in Opened tab.
> 
> 2. The second issue also is described in video above: when you open communities from Joined tab they become sorted
>    NOT by order of joining but by order of opening in Joined tab. BUT they should be ordered by order of joining:
> 
> <img alt="Screenshot 2024-03-04 at 14 39 26" width="521" src="https://private-user-images.githubusercontent.com/147824399/309773317-8421d4b0-5bbf-44dd-a788-cab81e77d92f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NTU1MTEsIm5iZiI6MTcwOTY1NTIxMSwicGF0aCI6Ii8xNDc4MjQzOTkvMzA5NzczMzE3LTg0MjFkNGIwLTViYmYtNDRkZC1hNzg4LWNhYjgxZTc3ZDkyZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxNjEzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDY2YmJjNGFiMzhlMmQ2NWMyYWQ1MWM1NmY2MzFlOTM4ZGI4NjQzODgwNmQ4MTdiYjljM2JmY2M3MjExODk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6k37K12Ubm_TS9LmHvGDzMWAXaVBeZFLlFmoBQPEPXo">

Should be fixed now.

2024-03-06 08:36 UTC, status-im-auto commented
## 88% of end-end tests have passed
```
Total executed tests: 48
Failed tests: 5
Expected to fail tests: 1
Passed tests: 42
```
```
IDs of failed tests: 702845,702947,702745,702733,704615 
```
```
IDs of expected to fail tests: 703503 
```
<h3>Failed tests (5)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&PR_ID=18812&TR_CASE_IDS=702845,702947,702745,702733,704615">Rerun failed tests</a></li><br/><h4>Class TestCommunityMultipleDeviceMerged:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3480345">test_community_edit_delete_message_when_offline</a>, id: 704615 </b></td></tr><tr><td><p><blockquote><div># STEP: Receiver is checking if initial messages were delivered</div><div>Device 1: Looking for a message by text: message to edit </div></blockquote></p>

```
critical/chats/test_public_chat_browsing.py:782: in test_community_edit_delete_message_when_offline
    self.channel_1.driver.fail("Message '%s' was not received")
base_test_case.py:179: in fail
    pytest.fail('Device %s: %s' % (self.number, text))
 Device 1: Message '%s' was not received
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/8eac9efae4db46e9b75a4078d83e9e5e?auth=7d06d4ce8d45aa43a6cc88e16e6ffa2a#592">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/075c18ff5c3040db873496039c7b379c?auth=5b819f513da4bfa08cf8e27a6a36b289#466">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestCommunityMultipleDeviceMergedTwo:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3480320">test_community_leave</a>, id: 702845 </b></td></tr><tr><td><p><blockquote><div>Device 2: Find `Button` by `xpath`: `//*[@text="Leave community"]` </div><div>Device 2: Tap on found: Button </div></blockquote></p>

```
critical/chats/test_public_chat_browsing.py:993: in test_community_leave
    self.errors.verify_no_errors()
base_test_case.py:191: in verify_no_errors
    pytest.fail('\n '.join([self.errors.pop(0) for _ in range(len(self.errors))]))
 Community is still shown in the list after leave
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/dd314f3f5792496ba96fc6593e832d8b?auth=0e6c979be65d78a32f33e61cab7f5ad3#328">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/697464a6ff15434688e8376248c0f30d?auth=3a04990f5733f0bd1c9ecacc74e7cfcd#301">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestActivityMultipleDevicePR:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3480329">test_activity_center_reply_read_unread_delete_filter_swipe</a>, id: 702947 </b></td></tr><tr><td><p><blockquote><div>Device 2: Tap on found: SendMessageButton </div><div># STEP: Checking unread indicators</div></blockquote></p>

```
activity_center/test_activity_center.py:308: in test_activity_center_reply_read_unread_delete_filter_swipe
    self.home_1.notifications_unread_badge.wait_for_visibility_of_element(120)
../views/base_element.py:147: in wait_for_visibility_of_element
    raise TimeoutException(
 Device 1: BaseElement by accessibility id:`activity-center-unread-count` is not found on the screen after wait_for_visibility_of_element
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/7c7fb09eaa67459ca3c40677d9013afd?auth=285c4c17d2adb6ce473d3af5214be9ef#167">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/65561357f38645e7a73087ebf4aa2f81?auth=38a646e0ca3832f78cde6e1738a3c2f9#125">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestOneToOneChatMultipleSharedDevicesNewUi:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3480303">test_1_1_chat_non_latin_messages_stack_update_profile_photo</a>, id: 702745 </b></td></tr><tr><td><p><blockquote><div>Device 2: Find `MemberPhoto` by `xpath`: `//*[starts-with(@text,'profile_photo')]/ancestor::android.view.ViewGroup[@content-desc='chat-item']//*[@content-desc='user-avatar']` </div><div>Device 2: Image differs from template to 4.144358915441177 percents </div></blockquote></p>

```
critical/chats/test_1_1_public_chats.py:312: in test_1_1_chat_non_latin_messages_stack_update_profile_photo
    self.errors.verify_no_errors()
base_test_case.py:191: in verify_no_errors
    pytest.fail('\n '.join([self.errors.pop(0) for _ in range(len(self.errors))]))
 Message with text '®	æ ç ♥' was not received
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/ea699b72ec7941cb8c4eacee42005c4e?auth=2222bd0f328fbcfc676a7a46964fe7d9#348">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/a8ca9e0276e24b13a8a65868d52e7361?auth=94eee45d74638696c0f6ae9527834d06#209">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3480301">test_1_1_chat_text_message_delete_push_disappear</a>, id: 702733 </b></td></tr><tr><td><p><blockquote><div>Device 2: Tap on found: Button </div><div>Device 1: Getting PN by 'DELETE ME' </div></blockquote></p>

```
critical/chats/test_1_1_public_chats.py:516: in test_1_1_chat_text_message_delete_push_disappear
    self.errors.verify_no_errors()
base_test_case.py:191: in verify_no_errors
    pytest.fail('\n '.join([self.errors.pop(0) for _ in range(len(self.errors))]))
 Message status was not changed to 'Delivered' after 60 s
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/ea699b72ec7941cb8c4eacee42005c4e?auth=2222bd0f328fbcfc676a7a46964fe7d9#556">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/a8ca9e0276e24b13a8a65868d52e7361?auth=94eee45d74638696c0f6ae9527834d06#401">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table></details><h3>Expected to fail tests (1)</h3><details><summary>Click to expand</summary><br/><br/><h4>Class TestCommunityOneDeviceMerged:</h4><table style="widt [...]

2024-03-06 10:51 UTC, mariia-skrypnyk commented
Hi @ibrkhalil !

Thanks for such a long sorting journey!
Now all sorting requirements are covered and PR can be merged!
Great job!
Failed e2e are not related to your fixes.

2024-03-06 11:13 UTC, merged