Use placeholder value if no wallet name is supplied
status-im/status-react pull request #18882
Opened 2024-02-17 18:17 UTC by ibrkhalil

fixes #18877

### Summary

Uses the placeholder value of wallet account number if the user didn't supply a wallet account name.

status: ready

2024-02-17 18:23 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | aefb0338 | [#1](https://ci.status.im/job/status-mobile/job/prs/job/ios/job/PR-18882/1/) | 2024-02-17 18:23:53 | ~6 min | `ios` | [:iphone:`ipa`](https://i.diawi.com/QaiSTF) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2FQaiSTF)|

2024-02-17 18:43 UTC, mohsen-ghafouri approved these changes

2024-02-18 18:39 UTC, J-Son89 requested changes

2024-02-18 18:39 UTC, J-Son89 commented on src/status_im/contexts/wallet/create_account/view.cljs
> +                                               :account-name (if (string/blank? @account-name)
Hey @ibrkhalil, I don't think we want this change. The real issue is that the slider button doesn't allow to disable and enable again. I have to create an issue for this and that is how we will handle it/ perhaps some design input. In future I think it's best to reach out and discuss things like this to save yourself the effort 
:)

2024-02-18 18:46 UTC, ibrkhalil commented on src/status_im/contexts/wallet/create_account/view.cljs
> +                                               :account-name (if (string/blank? @account-name)
No worries, It was a really simple solution so it didn't take much time
I'll mention @Francesca-G so that we could get design input here.

2024-02-19 09:41 UTC, J-Son89 commented
@ibrkhalil - should we close this pr to save other devs reviewing etc, since we won't be using this approach 👍 
better for us to get input design in the comms channel rather than in a pr this way imo.

2024-02-19 09:42 UTC, ibrkhalil commented
> @ibrkhalil - should we close this pr to save other devs reviewing etc, since we won't be using this approach 👍 better for us to get input design in the comms channel rather than in a pr this way imo.

You're totally right, Thanks Jamie!

2024-02-19 09:42 UTC, closed without merging