Fix #1886
status-im/status-react pull request #1894
Opened 2017-09-19 15:06 UTC by janherich

There were multiple problems with previous approach of always
expecting explicit "sent" signal from async handler, otherwise
displaying the `/send` message as pending, the most serious
problem was that the command handler is only called once during
send time, and it's problematic to depend on the result of that
on the recepient side, which could be for example offline.

The safer approach is to always display `/send` command as
successful (normal display) and only show errors when explicitly
signalised through the async command handler.

This should fix the most urgent problem for now.

Another issue which is not yet solved is that command handler is
called only after preview was already requested, that should clearly
happen in opposite order, also message, should be commited for further
processing/persisting only after handler returns success code, either
synchronously, or asynchronously but as logic input/sent logic is very
entangled and complicated, I decided to hold off with that now and
rather implement it as a part of the #1710 PR.

[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)
fixes #886

### Steps to test:
- Open Status
- Open 1-1 chat and send transaction
- Check the messages on the sender/receiver side

[comment]: # (PRs will only be accepted if squashed into single commit.)
status: ready

2017-09-19 15:13 UTC, rasom approved these changes

2017-09-20 07:08 UTC, annadanchenko commented
on sender side: for removed transaction there is message “transaction failed”, for successful transaction - no messages. 
On recipient side: no message for both successful and removed transaction. Expect to get “failed transaction” for both sides. 

Happens in 1-1 and in group chat, checked Android and iOS

2017-09-20 13:01 UTC, yenda commented
can you fix your indentation please it makes too much noise in the diff

```
  (add-hook 'clojure-mode-hook
            (lambda ()
              (put-clojure-indent 'letsubs 1)
              (put-clojure-indent 'create-class 0)
              (put-clojure-indent 'register-handler-db 0)
              (put-clojure-indent 'register-handler-fx 0)
              (put-clojure-indent 'register-handler 0)
              (put-clojure-indent 'reg-fx 0)
              (put-clojure-indent 'reg-sub 1)
              (put-clojure-indent 'allowed-keys 0)
              (put-clojure-indent 'start 0)
              (put-clojure-indent 'list-item 0)
              (put-clojure-indent 'setTimeout 0)))
```

2017-09-20 13:01 UTC, yenda requested changes

2017-09-20 13:01 UTC, yenda commented on src/status_im/chat/events/commands.cljs
> +  :execute-command-immediately
fix indent please

2017-09-20 15:14 UTC, yenda approved these changes

2017-09-20 18:08 UTC, annadanchenko commented
On new build with re-worked send there is new issue: 
Send transaction from group chat is shown in 1-1 chat for sender.

Steps:
sender: https://app.testfairy.com/projects/4803622-status/builds/6595741/sessions/14/?accessToken=46EwNfzql/Pskd/TkwkyBiOa31c
recipient: https://app.testfairy.com/projects/4803590-status/builds/6595818/sessions/7/?accessToken=7PUecCwg5oewqKAZ9aidk/OmndM

- Open status
- Create 1-1 chat with contact B and group chat with contact B as a member
- in group chat send to B 0.1 ETH. Check if you see send message in chat, currently it's not shown
- as B: check that send message is in group chat (it's there)
- open 1-1 chat with B as a sender: send message is there (should be in group chat)

2017-09-21 11:08 UTC, merged