All addresses text is not updated when changing accounts
status-im/status-react pull request #19379
Opened 2024-03-23 12:07 UTC by ibrkhalil

fixes #19374 

### Summary

Fixes an issue with the text that indicated the number of selected addresses in Edit shared addresses screen and Request to join screen

status: ready

2024-03-23 12:13 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 851e31cf | [#1](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-19379/1/) | 2024-03-23 12:13:37 | ~5 min | `tests` | [:page_facing_up:`log`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-240323-120737-851e31-pr19379-tests.log) |

2024-03-25 09:48 UTC, seanstrom approved these changes
Nice stuff! ✅

2024-03-25 10:03 UTC, flexsurfer requested changes

2024-03-25 10:03 UTC, flexsurfer commented on src/status_im/contexts/communities/actions/accounts_selection/view.cljs
> +        addresses-shared-text (condp = revealed-accounts-count
it's better to implement it similar to 
```clojure
"community-members": {
        "one": "{{count}} member",
        "other": "{{count}} members"
    },
    ```

2024-03-25 10:13 UTC, jo-mut approved these changes

2024-03-25 10:40 UTC, ibrkhalil commented on src/status_im/contexts/communities/actions/accounts_selection/view.cljs
> +        addresses-shared-text (condp = revealed-accounts-count
Done

2024-03-25 11:46 UTC, flexsurfer approved these changes

2024-03-25 15:38 UTC, status-im-auto commented
## 94% of end-end tests have passed
```
Total executed tests: 48
Failed tests: 2
Expected to fail tests: 1
Passed tests: 45
```
```
IDs of failed tests: 703629,702730 
```
```
IDs of expected to fail tests: 703503 
```
<h3>Failed tests (2)</h3><details><summary>Click to expand</summary><br/><li><a href="https://ci.status.im/job/status-mobile/job/e2e/job/status-app-prs-rerun/parambuild/?BRANCH_NAME=develop&PR_ID=19379&TR_CASE_IDS=703629,702730">Rerun failed tests</a></li><br/><h4>Class TestCommunityMultipleDeviceMergedTwo:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3510241">test_community_join_when_node_owner_offline</a>, id: 703629 </b></td></tr><tr><td><p><blockquote><div>Device 2: Looking for community: 'open community' </div><div>Device 2: Click until `Text` by `accessibility id`: `community-description-text` will be presented </div></blockquote></p>

```
critical/chats/test_public_chat_browsing.py:1180: in test_community_join_when_node_owner_offline
    self.errors.verify_no_errors()
base_test_case.py:190: in verify_no_errors
    pytest.fail('\n '.join([self.errors.pop(0) for _ in range(len(self.errors))]))
 Text "You joined “closed community”" in shown toast element doesn't match expected "You joined “open community”"
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/aaacf8d44ed6418b93b577e67dbfc949?auth=23ad368275a5bacfb005ada336c41d18#555">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/213ba8978317446aad8c016fd13d3969?auth=735254d39cb11de18a04bb170cdca27c#517">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestOneToOneChatMultipleSharedDevicesNewUi:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3510196">test_1_1_chat_message_reaction</a>, id: 702730 </b></td></tr><tr><td><p><blockquote><div>Device 1: Find `EmojisNumber` by `xpath`: `//*[starts-with(@text,'Message sender')]/ancestor::android.view.ViewGroup[@content-desc='chat-item']/../..//*[@content-desc='emoji-reaction-2']/android.widget.TextView[2]` </div><div>Device 1: Find `EmojisNumber` by `xpath`: `//*[starts-with(@text,'Message sender')]/ancestor::android.view.ViewGroup[@content-desc='chat-item']/../..//*[@content-desc='emoji-reaction-2']/android.widget.TextView[2]` </div></blockquote></p>

```
critical/chats/test_1_1_public_chats.py:73: in test_1_1_chat_message_reaction
    message_sender.emojis_below_message(emoji="thumbs-up").wait_for_element_text(1, 90)
../views/base_element.py:190: in wait_for_element_text
    self.driver.fail(message if message else "`%s` is not equal to expected `%s` in %s sec" % (
base_test_case.py:178: in fail
    pytest.fail('Device %s: %s' % (self.number, text))
 Device 1: `2` is not equal to expected `1` in 90 sec
```

<br/><br/><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/b229aacfe68544c5834093b8fedda7f5?auth=a01c4ff7e69b99990b1c865bc3ead1da#98">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/7362e73cb37d4b1881da93f50f76cb80?auth=6ae50199468b645066eb04f9d114fb92#87">Steps, video, logs</a></li><li><a href="https://media.giphy.com/media/9M5jK4GXmD5o1irGrF/giphy.gif">Failure screenshot</a></li></ul></p></ul></p></td></tr></tbody></table></details><h3>Expected to fail tests (1)</h3><details><summary>Click to expand</summary><br/><br/><h4>Class TestCommunityOneDeviceMerged:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3510240">test_community_discovery</a>, id: 703503 </b></td></tr><tr><td>

```
Test is not run, e2e blocker  
```

<b>[[reason: [NOTRUN] Curated communities not loading, https://github.com/status-im/status-mobile/issues/17852]]</b><br/><br/></td></tr></tbody></table></details><h3>Passed tests (45)</h3><details><summary>Click to expand</summary><br/><br/><h4>Class TestActivityMultipleDevicePRTwo:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3510230">test_activity_center_admin_notification_accept_swipe</a>, id: 702958 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/b2c84242f29543fc83c5362bc3aed0cc?auth=db404b076632e3bcaad25607122f1324#178">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/300c841e55544263b63b4061381b6293?auth=c664d713ab24214ae9059c983bead2ce#119">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3510229">test_activity_center_mentions</a>, id: 702957 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/b2c84242f29543fc83c5362bc3aed0cc?auth=db404b076632e3bcaad25607122f1324#130">Steps, video, logs</a></li></ul></p><p>Device 2:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/300c841e55544263b63b4061381b6293?auth=c664d713ab24214ae9059c983bead2ce#103">Steps, video, logs</a></li></ul></p></ul></p></td></tr></tbody></table><h4>Class TestCommunityOneDeviceMerged:</h4><table style="width: 100%"><colgroup><col span="1" style="width: 20%;"><col span="1" style="width: 80%;"></colgroup><tbody><tr></tr><tr><td><b>1. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3510200">test_community_copy_and_paste_message_in_chat_input</a>, id: 702742 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/9fb56902733d423fb8ecd527bc7bb96f?auth=57efc0ff5b8272d133b87f33f94c063c#79">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>2. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3510236">test_community_mute_community_and_channel</a>, id: 703382 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/9fb56902733d423fb8ecd527bc7bb96f?auth=57efc0ff5b8272d133b87f33f94c063c#127">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>3. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3510224">test_community_undo_delete_message</a>, id: 702869 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/9fb56902733d423fb8ecd527bc7bb96f?auth=57efc0ff5b8272d133b87f33f94c063c#108">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>4. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3510219">test_community_navigate_to_channel_when_relaunch</a>, id: 702846 </b></td></tr><tr><td><ins>Device sessions</ins><p><ul><p>Device 1:<ul><li><a href="https://eu-central-1.saucelabs.com/jobs/9fb56902733d423fb8ecd527bc7bb96f?auth=57efc0ff5b8272d133b87f33f94c063c#55">Steps, video, logs</a></li></ul></p></ul></p></td></tr><tr><td><b>5. <a href="https://ethstatus.testrail.net/index.php?/tests/view/3510232">test_restore_multiaccount_with_waku_backup_remove_switch</a>, id: 703133 </b></td></tr><tr> [...]

2024-03-25 16:51 UTC, qoqobolo commented
Thanks a lot for the fix @ibrkhalil, PR can be merged.

2024-03-25 20:14 UTC, merged