Disabling Testnet alert banner
status-im/status-react pull request #19762
Opened 2024-04-23 10:07 UTC by alwx

fixes https://github.com/status-im/status-mobile/issues/19506 by disabling the testnet alert banner and replacing it with a simple toast that is shown when the user is logged in. 
also adds a comment why it's done for the future

#### Platforms

- Android
- iOS

#### Areas that maybe impacted

##### Functional

- 1-1 chats
- public chats
- group chats
- wallet / transactions
- dapps / app browsing
- account recovery
- new account
- user profile updates
- networks
- mailservers
- fleet
- bootnodes

status: ready

2024-04-23 10:12 UTC, status-im-auto commented
### Jenkins Builds
<details>
<summary>Click to see older builds (2)</summary>

| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | e8f98e76aa352965d3ec989e637a5c9b94471871 | [#1](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-19762/1/) | 2024-04-23 10:12:33 | ~4 min | `tests` | [:page_facing_up:`log`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-240423-100801-e8f98e76aa352965d3ec989e637a5c9b94471871-pr19762-tests.log) |
| :heavy_check_mark: | e8f98e76aa352965d3ec989e637a5c9b94471871 | [#1](https://ci.status.im/job/status-mobile/job/prs/job/android/job/PR-19762/1/) | 2024-04-23 10:16:12 | ~8 min | `android` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-240423-100801-e8f98e76aa352965d3ec989e637a5c9b94471871-pr19762-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-240423-100801-e8f98e76aa352965d3ec989e637a5c9b94471871-pr19762-universal.apk)|
</details>

| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 3ab012fe5104ac373c1d1597cbe82c6cd50b03f0 | [#3](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-19762/3/) | 2024-04-23 10:21:38 | ~3 min | `tests` | [:page_facing_up:`log`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-240423-101739-3ab012fe5104ac373c1d1597cbe82c6cd50b03f0-pr19762-tests.log) |
| :heavy_check_mark: | 3ab012fe5104ac373c1d1597cbe82c6cd50b03f0 | [#3](https://ci.status.im/job/status-mobile/job/prs/job/android-e2e/job/PR-19762/3/) | 2024-04-23 10:24:45 | ~7 min | `android-e2e` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-240423-101736-3ab012fe5104ac373c1d1597cbe82c6cd50b03f0-pr19762-x86_64.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-240423-101736-3ab012fe5104ac373c1d1597cbe82c6cd50b03f0-pr19762-x86_64.apk)|
| :heavy_check_mark: | 3ab012fe5104ac373c1d1597cbe82c6cd50b03f0 | [#3](https://ci.status.im/job/status-mobile/job/prs/job/ios/job/PR-19762/3/) | 2024-04-23 10:26:13 | ~8 min | `ios` | [:iphone:`ipa`](https://i.diawi.com/frSFWd) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2FfrSFWd)|
| :heavy_check_mark: | 3ab012fe5104ac373c1d1597cbe82c6cd50b03f0 | [#3](https://ci.status.im/job/status-mobile/job/prs/job/android/job/PR-19762/3/) | 2024-04-23 10:26:41 | ~9 min | `android` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-240423-101736-3ab012fe5104ac373c1d1597cbe82c6cd50b03f0-pr19762-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-240423-101736-3ab012fe5104ac373c1d1597cbe82c6cd50b03f0-pr19762-universal.apk)|
| | | | | | | |
| :heavy_check_mark: | fddaf797916ab617299ce04225434d6ff9015014 | [#4](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-19762/4/) | 2024-04-23 13:10:31 | ~6 min | `tests` | [:page_facing_up:`log`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-240423-130345-fddaf797916ab617299ce04225434d6ff9015014-pr19762-tests.log) |
| :heavy_check_mark: | fddaf797916ab617299ce04225434d6ff9015014 | [#4](https://ci.status.im/job/status-mobile/job/prs/job/ios/job/PR-19762/4/) | 2024-04-23 13:14:05 | ~10 min | `ios` | [:iphone:`ipa`](https://i.diawi.com/WmZLzy) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fi.diawi.com%2FWmZLzy)|
| :heavy_check_mark: | fddaf797916ab617299ce04225434d6ff9015014 | [#4](https://ci.status.im/job/status-mobile/job/prs/job/android-e2e/job/PR-19762/4/) | 2024-04-23 13:15:56 | ~12 min | `android-e2e` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-240423-130341-fddaf797916ab617299ce04225434d6ff9015014-pr19762-x86_64.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-240423-130341-fddaf797916ab617299ce04225434d6ff9015014-pr19762-x86_64.apk)|
| :heavy_check_mark: | fddaf797916ab617299ce04225434d6ff9015014 | [#4](https://ci.status.im/job/status-mobile/job/prs/job/android/job/PR-19762/4/) | 2024-04-23 13:16:18 | ~12 min | `android` | [:robot:`apk`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-240423-130341-fddaf797916ab617299ce04225434d6ff9015014-pr19762-universal.apk) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A1&chl=https%3A%2F%2Fstatus-im-mobile-prs.ams3.cdn.digitaloceanspaces.com%2FStatusIm-Mobile-240423-130341-fddaf797916ab617299ce04225434d6ff9015014-pr19762-universal.apk)|

2024-04-23 10:19 UTC, J-Son89 commented
Did we agree to this? 🤔

Can you include a video/ screenshots of how it looks?

2024-04-23 10:20 UTC, J-Son89 commented
At least just do this for the screens where its breaking- wallet looked fine imo

2024-04-23 10:29 UTC, Parveshdhull commented on src/status_im/contexts/profile/login/events.cljs
> +
empty line

2024-04-23 10:29 UTC, Parveshdhull approved these changes

2024-04-23 10:32 UTC, Parveshdhull commented
@alwx please remove fixes from PR description as this will close the issue.
Also please remove your assignment so that it can be picked by someone.

2024-04-23 10:41 UTC, flexsurfer approved these changes

2024-04-23 21:32 UTC, J-Son89 requested changes
let's align on this before merging, should we really remove for all screens? 
There's some minor issues for our developer experience but does that justify this? 

Does this make things better/worse for QA etc?

2024-04-24 07:26 UTC, alwx commented
@J-Son89 we can't easily show it only in Wallet because that banner is a part of a global alert mechanism implemented in `status-im.common.alert-banner` and shown on top of everything in `home-stack` which means everything in `communities`, `chats`, `browser` and `wallet` gets affected. 
Showing it only in the Wallet means implementing a new mechanism for that purpose, which we can do if we want, but this PR is meant to simply roll back changes that were made in the Testnet banner introduction PR just because it caused a lot of problems.

2024-04-24 08:52 UTC, mariia-skrypnyk commented
Hi @J-Son89 @Parveshdhull @alwx !
https://github.com/status-im/status-mobile/pull/19773 it's not the only issue that tracks banner issues.
E.g. we have `Change Password` added and there are also banner issues there. So @clauxx also need to spend time on fixing them in case banner will be present. 
You can find examples here: https://github.com/status-im/status-mobile/pull/19474#issuecomment-2056687509

Yes, Testnet banner gives great visibility but it also raise issues and extra time.

2024-04-24 09:09 UTC, Parveshdhull commented
Thank you @alwx  and @mariia-skrypnyk for your feedback and thank you @J-Son89 for raising the point that this needs to be discussed properly before moving forward.

>  It caused a lot of problems

I would say this is a little over-exaggeration. If we see issues reported in https://github.com/status-im/status-mobile/issues/19506 they were minor styling issues and [needed](https://github.com/status-im/status-mobile/pull/19773) two lines of fix `(- height alert-banners-top-margin)` and `footer-container-padding`.
For debug issues with inspector and pref monitor are nothing new, overlays like the bottom sheet also have the same behavior. Still, I disabled banners for debug builds.

> Yes, the Testnet banner gives great visibility but it also raises issues and extra time for this fix.

This is expected. Whenever we build something new, issues are expected and need to be properly tested and fixed. As the alert banner's [implementation](https://github.com/status-im/status-mobile/pull/19011) was sandboxed it missed proper testing phase and now as this is [enabled](https://github.com/status-im/status-mobile/pull/19348) issues are visible. (In idle case these issues should be [caught/reported](https://github.com/status-im/status-mobile/pull/19011#issuecomment-1985303381) in either of these PRs).

If there are any issues related to alert banner please do report, so we can fix them. As issues mentioned in https://github.com/status-im/status-mobile/issues/19506 are fixed in https://github.com/status-im/status-mobile/pull/19773.

I don't think issues are any problem, they are minor styling issues and can be fixed quickly. The main question should be do we want this feature or not and discuss it with the design team? As far as I remember, we only implemented this functionality because the design team was very keen on this and little persisting.

2024-04-24 09:12 UTC, Parveshdhull commented
> So @clauxx also need to spend time on fixing them in case banner will be present.

@clauxx please let me know if you need any help. Also if issue is only after enabling alert banner, please feel free to log it separately, I can checkout later.
From quick look it seems issue might be in line `keyboardVerticalOffset (- (safe-area/get-bottom))}`

2024-04-24 09:24 UTC, yevh-berdnyk commented
Hi, I just want to add one more detail from the perspective of e2e tests. This banner presence makes some elements on some screens to be hidden so we need to scroll for them and so it makes the tests a little bit longer. Especially having the issue with SauceLabs emulators that the resolution is a way smaller than a usual modern phone, we need to scroll even more often. Of corse it's not a critical issue but I think it can also be pointed here

2024-04-24 09:26 UTC, Parveshdhull commented
Thank you @yevh-berdnyk, I can disable alert banner for e2e builds, will that be ok?

2024-04-24 09:29 UTC, Parveshdhull commented
> Thank you @yevh-berdnyk, I can disable alert banner for e2e builds, will that be ok?

[done](https://github.com/status-im/status-mobile/pull/19773)

2024-04-24 09:29 UTC, yevh-berdnyk commented
> Thank you @yevh-berdnyk, I can disable alert banner for e2e builds, will that be ok?

That will be definitely cool!

2024-04-24 09:30 UTC, Parveshdhull commented
> That will be definitely cool!

[done](https://github.com/status-im/status-mobile/pull/19773)

2024-04-24 13:36 UTC, smohamedjavid commented
I agree with @Parveshdhull to hide it only on the debug builds as hiding the banner completely is not a good idea for the end user (There is a feature planned to disable testnet by tapping on the banner). If this [PR](https://github.com/status-im/status-mobile/pull/19773) fixes those issues and we are all in agreement, can we close this PR?

2024-04-25 08:08 UTC, alwx commented
I don't understand why @Parveshdhull decided to work on this despite the discussions we've had. But whatever, I'm closing this then.

2024-04-25 08:08 UTC, closed without merging