fix: white panel when the bottom sheet is launched
status-im/status-react pull request #20167
Opened 2024-05-24 08:31 UTC by jo-mut

fixes #https://github.com/status-im/status-mobile/issues/20114

### Summary

The white panel appears when the user initiates any action that launches the bottom sheet. The function that applies the navbar background color is called even before the bottom sheet is launched and it has not been supplied with the value of the background color and of the applied theme hence the reason for the white panel this is however fixed in this pr 

https://github.com/status-im/status-mobile/assets/28704507/e34cbbec-6693-4d47-a6d5-6479adec675d

status: ready

2024-05-24 08:36 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 21a6301a874a78b9ee5136ec26cdcadc79b516b9 | [#1](https://ci.status.im/job/status-mobile/job/prs/job/tests/job/PR-20167/1/) | 2024-05-24 08:36:26 | ~4 min | `tests` | [:page_facing_up:`log`](https://status-im-mobile-prs.ams3.cdn.digitaloceanspaces.com/StatusIm-Mobile-240524-083219-21a6301a874a78b9ee5136ec26cdcadc79b516b9-pr20167-tests.log) |

2024-05-24 08:38 UTC, flexsurfer commented on src/status_im/navigation/effects.cljs
> +   (let [theme         (:theme opts)
thank you @jo-mut i've looked into show-overlay usages and I didn't find where we have :theme in opts, so probably it's better to remove it from code

2024-05-24 08:42 UTC, flexsurfer requested changes
it seems like `(:theme opts)` here  `(options/statusbar-and-navbar-options (:theme opts) nil nil)` is always `nil` this should be fixed I guess

2024-05-24 08:48 UTC, flexsurfer commented
this should move `(options/statusbar-and-navbar-options nil rnn-status-bar nav-bar-color)` from ` :show-toasts` to `show-overlay` and I think theme should go as a separate parameter not in options
```clojure
(rf/reg-fx :show-toasts
 (fn [[view-id theme]]
   (let [[rnn-status-bar nav-bar-color] (get-status-nav-color view-id theme)]
     (show-overlay "toasts"
                   (assoc (options/statusbar-and-navbar-options nil rnn-status-bar nav-bar-color)
```

2024-05-24 12:40 UTC, jo-mut commented
https://github.com/status-im/status-mobile/assets/28704507/5ea3d0b3-4160-4d5f-9198-d379ef0e2d34

2024-05-24 14:50 UTC, flexsurfer commented on src/status_im/navigation/effects.cljs
> +   (let [theme (rf/sub [:theme])]
it's illegal, `(rf/sub [:theme])` can't be used here , subscription can be used only in views, so you have to pass theme as parameter

2024-05-27 09:06 UTC, flexsurfer requested changes
still not fixed properly

2024-05-27 09:10 UTC, jo-mut commented
@flexsurfer I had missed your comment above am fixing that now

2024-05-27 09:26 UTC, flexsurfer commented on src/status_im/navigation/effects.cljs
> -                          {:interceptTouchOutside false})))))
also this should keep `{:interceptTouchOutside false}` here

2024-05-31 09:31 UTC, jo-mut commented
this is fixed here https://github.com/status-im/status-mobile/pull/20258#event-12987872516.

2024-05-31 09:31 UTC, closed without merging