[bug] fix 2003 unsigned transaction count upon expiration
status-im/status-react pull request #2017
Opened 2017-10-05 12:41 UTC by yenda

fixing #2003

![screenshot_1507207147](https://user-images.githubusercontent.com/1181225/31227711-28bc3ba8-a9db-11e7-89d0-7eb76f422621.png)

### Summary:

Fix color of transaction count and refresh when transactions expire

this fixed involved changing the swiper so that a function can be passed as title instead of a string.
this allows developpers to pass custom elements as titles and still use style and variables that are computed when tab is built

### Steps to test:
- Open Status
- Send a transaction but sign later
- Go to unsigned tab and wait 5 min for the transaction to expire
- Count and transaction should have disappeared

[comment]: # (PRs will only be accepted if squashed into single commit.)
status: ready

2017-10-05 12:54 UTC, jeluard requested changes

2017-10-05 12:54 UTC, jeluard commented on src/status_im/components/styles.cljs
> +(def color-gray10 "#9BA3A8")
Will it ever stop ?? ;)

2017-10-05 12:54 UTC, jeluard commented on src/status_im/components/tabs/views.cljs
> +             :or {title-fn react/text}}]
Smart!

2017-10-05 12:54 UTC, jeluard commented on src/status_im/components/tabs/views.cljs
> +       (title-fn {:uppercase? (and text-only? (get-in platform/platform-specific [:uppercase?]))
Not exactly the same here as `uppercase?` as no general meaning, only for text-only component.
Probably harmless.

2017-10-05 12:54 UTC, jeluard commented on src/status_im/ui/screens/wallet/transactions/views.cljs
> +     (when (pos? @unsigned-transactions-count)
`@` coud be called only once

2017-10-05 12:54 UTC, jeluard commented on src/status_im/ui/screens/wallet/transactions/views.cljs
> +(defn unsigned-transactions-title [{:keys [uppercase? style]} title]
I don't think `uppercase?` and `style` should be managed by wrapping component as those are specific to this particular implementation.
If the idea was to share behavior between default `title-fn` and this one I'd rather we use functions and duplicate the definition of properties.

2017-10-05 13:06 UTC, flexsurfer commented on src/status_im/components/styles.cljs
> +(def color-gray10 "#9BA3A8")
Designers never slip!

2017-10-05 13:33 UTC, flexsurfer commented on src/status_im/ui/screens/wallet/transactions/views.cljs
> +  (let [unsigned-transactions-count (re-frame/subscribe [:wallet.transactions/unsigned-transactions-count])]
better to use `defview`, and don't use re-frame/subscribe at all

2017-10-05 13:33 UTC, flexsurfer approved these changes

2017-10-06 09:36 UTC, jeluard approved these changes

2017-10-06 13:35 UTC, merged