[BUG #2025] Ensure QR code data is properly parsed
status-im/status-react pull request #2036
Opened 2017-10-06 12:44 UTC by jeluard

fixes #2025

### Summary:
Properly parse and generate data embedded in QR code

### Steps to test:
- Open Status
- Navigate wallet / request
- QR code should be readable by others wallet (status included)
- Navigate wallet / send
- Recipient should be correctly read  from QR code generated by other wallet (status included)

status: ready

2017-10-06 13:06 UTC, yenda requested changes
Nice only minor details

2017-10-06 13:06 UTC, yenda commented on src/status_im/ui/screens/profile/qr_code/views.cljs
> +         [qr-code {:value (eip67/generate-uri (get contact qr-source) (if amount? {:value  amount}))
when

2017-10-06 13:06 UTC, yenda commented on src/status_im/ui/screens/qr_scanner/events.cljs
> +    (dispatch [handler context (:address (eip67/parse-uri data))])))
re-frame/dispatch

2017-10-06 13:06 UTC, yenda commented on src/status_im/ui/screens/qr_scanner/views.cljs
> +                                           (act/back #(dispatch [:navigate-back])))}]]))
action

2017-10-06 13:06 UTC, yenda commented on src/status_im/ui/screens/qr_scanner/views.cljs
> +     [camera/camera {:onBarCodeRead #(dispatch [:set-qr-code identifier (camera/get-qr-code-data %)])
re-frame/dispatch

2017-10-06 13:09 UTC, flexsurfer commented on src/status_im/ui/screens/wallet/send/events.cljs
>  (ns status-im.ui.screens.wallet.send.events
fengshui? :)

2017-10-06 13:12 UTC, flexsurfer commented
@jeluard but what about generating qr? to properly parse we need properly generate first

2017-10-06 13:16 UTC, jeluard commented on src/status_im/ui/screens/wallet/send/events.cljs
>  (ns status-im.ui.screens.wallet.send.events
Weird

2017-10-06 13:17 UTC, jeluard commented
@flexsurfer Right I missed this one!

2017-10-06 13:41 UTC, jeluard commented
@yenda @flexsurfer Pushed changes according to your coments.

2017-10-06 13:51 UTC, yenda commented
good point but one could argue that since it is the ethereum standard it will already work with other wallets QR code (Walleth comes to mind for instance) So this could be merged and the write part done in another PR

2017-10-06 13:51 UTC, yenda approved these changes

2017-10-06 13:59 UTC, flexsurfer commented
@jeluard it's better to implement it completely because now amount always 0, qr should be regenerated when amount input is changing

2017-10-06 14:11 UTC, flexsurfer approved these changes

2017-10-10 08:04 UTC, asemiankevich commented
Severla issues found during testing :
- can't scan QR code which is generated on iOS (either with Wallet scanner or QR Code reader app)
- I receive `error Address is invalid` when I scan code generated on Android by wallet scanner opened on iOS

As improvement  to be implemented: adding the faulty address in the alert so user can understand what actually was scanned and why it is wrong

2017-10-10 10:47 UTC, rasom commented
is this PR in progress? @jeluard please resolve conflicts

2017-10-12 10:46 UTC, asemiankevich commented
Keep receiving error

![image](https://user-images.githubusercontent.com/28752642/31492438-a6cbc248-af53-11e7-8d1b-65aed363ccbe.png)

2017-10-12 15:00 UTC, jeluard commented
This QR code is generated using latest status:

![capture du 2017-10-12 16-42-52](https://user-images.githubusercontent.com/359723/31502978-b795934a-af6e-11e7-8c6f-541ad08611f9.png)

I can read this fine on Android.

2017-10-13 11:01 UTC, merged