Show warning when app is syncing
status-im/status-react pull request #2145
Opened 2017-10-13 16:15 UTC by yenda

### Summary:

![screenshot_1507911282](https://user-images.githubusercontent.com/1181225/31555751-8cfe88d8-b042-11e7-8fe6-417b18c575b7.png)

2017-10-13 16:24 UTC, jeluard requested changes

2017-10-13 16:24 UTC, jeluard commented on src/status_im/ui/screens/wallet/views.cljs
> +(defn wallet-syncing [error-container-style error-message-style]
Code duplication with method above. This could be refactored to extract only differences.

2017-10-13 16:24 UTC, jeluard commented on src/status_im/ui/screens/wallet/styles.cljs
> +(def warning-exclamation
Please refactor so that there is no duplication.

2017-10-16 10:25 UTC, flexsurfer approved these changes

2017-10-18 00:17 UTC, closed without merging