Display time in transaction history list
status-im/status-react pull request #2169
Opened 2017-10-16 14:16 UTC by janherich

Also make `[list/item-content]` element more modular and reusable
as it was necessary to accomplish the task.

fixes #2131 

### Steps to test:
- Check transaction history screen (also unsigned transactions screen)

status: ready

2017-10-16 14:19 UTC, flexsurfer requested changes

2017-10-16 14:19 UTC, flexsurfer commented on src/status_im/ui/screens/wallet/transactions/styles.cljs
> +(def amount-time
use `defstyles` macro

2017-10-16 14:32 UTC, flexsurfer commented on src/status_im/ui/screens/wallet/transactions/styles.cljs
> +(defstyle amount-time
`defstyle` is used for platform differences, 
```
(defstyle amount-time
 {:flex-direction  :row
  :justify-content :space-between
  :ios {:padding-top 13}
  :android {:padding-top 14}})
```
you don't need it for tx-amount and tx-time

2017-10-16 14:39 UTC, flexsurfer commented
@janherich please make changes for `amount-time` and squash commits

2017-10-16 14:52 UTC, janherich commented
@flexsurfer done

2017-10-16 14:53 UTC, flexsurfer approved these changes

2017-10-16 15:05 UTC, jeluard approved these changes

2017-10-16 17:39 UTC, annadanchenko commented
on iOS with 24-hour format (so it shows 19:34 for evening) I see transaction time shown as 07:34. Would expect that it will be shown or in 24 hour format (preferably as it’s shown in such format on Details screen) or that am/pm will be added to the time

2017-10-17 09:19 UTC, annadanchenko commented
next build: 
changed time to 20:11 on my iOS device before installing the build (to see 24 hour format) - on Unsigned it shows 20:11 but on History it’s still 11:11. Would expect for both lists to show the time set on device. TF session https://app.testfairy.com/projects/4803590-status/builds/6879469/sessions/2/?accessToken=td2R8L9zp2A7XJRftgRZApkrUOU

2017-10-17 14:08 UTC, janherich commented
@annadanchenko All the remaining issues are solved in the branch

2017-10-17 16:59 UTC, rasom commented on src/status_im/components/list/views.cljs
> +  [rn/text {:style lst/secondary-text :ellipsize-mode "middle" :number-of-lines 1} secondary])
not a big deal but we could use `:middle` here

2017-10-17 17:00 UTC, rasom commented on src/status_im/ui/screens/wallet/transactions/styles.cljs
> +         {:color styles/color-black
alignment

2017-10-17 17:01 UTC, rasom commented on src/status_im/ui/screens/wallet/transactions/views.cljs
> +         [react/text {:style transactions.styles/tx-amount
alignment in map

2017-10-18 08:20 UTC, annadanchenko commented
long amount is shown with … in the middle but it’s expected to get “…” at the end of a sum, e.g. : `1234567.09876... ETH`. Now it’s `1234...876 ETH`

2017-10-18 15:31 UTC, merged