Fixes #2332 Updates Spanish translations
status-im/status-react pull request #2355
Opened 2017-11-02 22:53 UTC by alan-andrade

Fixes #2332

I'm a native Spanish speaker and I updated strings so they have a friendlier tone.

I saw this at devcon3, fantastic update !

2017-11-05 18:24 UTC, alan-andrade commented
@LaloGarza Corregí el typo de unirse. Las otras dos recomendaciones no supe como arreglarlas ya que son lineas que ya no existen en el archivo de ingles 🤔 . Las especificaciones del ticket indican que deben ser identicas y despues de actualizar el de español, esas lineas ya no estan.


Gracias por el reveiw ❤️

2017-11-06 23:15 UTC, LaloGarza requested changes
Hola, por favor revisa mis comentarios en las líneas, ya casi está lista tu traducción 👍🏼

2017-11-07 01:14 UTC, alan-andrade commented
Hola @LaloGarza ,

Se actualizo el texto restante. En algunas instancias me parecio mejor usar "nuevo _algo_" en lugar de "_algo_ nuevo". Que te parece ?

2017-11-07 14:00 UTC, LaloGarza commented on src/status_im/translations/es.cljs
> +   :faucet-error                          "Error solicitando fuente"
"de la fuente"

2017-11-07 14:35 UTC, LaloGarza commented on src/status_im/translations/es.cljs
> +   :testfairy-message                     "Estás usando una aplicación instalada desde una versión nocturna. Por motivos de testeo esta versión incluye grabación de la sesión si se usa conexión wifi,
hay que traducir tambien la palabra nightly que esta casi al final del enunciado.

2017-11-07 14:43 UTC, LaloGarza commented
Hola @alan-andrade me parece bien usar "nuevo algo".
Agregue dos comentarios en lineas para actualizar, ya solo esas correcciones y queda listo.

2017-11-07 18:00 UTC, alan-andrade commented
@LaloGarza Gracias por el review. Que tal ahora ?

2017-11-07 18:11 UTC, LaloGarza approved these changes
Quedó lista tu traducción ✅ bien hecho Alan.

2017-11-08 08:02 UTC, rasom approved these changes

2017-11-08 08:06 UTC, andytudhope commented on src/status_im/translations/es.cljs
> +   :browsing-browse                       "@navegar"
please change this back to @browse as it is just a formalism our team have decided on.

2017-11-08 08:07 UTC, andytudhope commented
One last comment from me @alan-andrade - please just change the browse command back to @browse as this is a formalism the team maintains across all translations. Then rasom will merge and we can confirm your bounty.

2017-11-08 18:00 UTC, alan-andrade commented
@andytudhope  I updated the string so we keep using "@browse". 

Thanks ! 🍻

2017-11-09 06:43 UTC, merged

2017-11-09 13:23 UTC, andytudhope commented
@alan-andrade will you please log in to openbounty.status.im and update your payment details (i.e. stick in an Ethereum address that you own, ideally using MetaMask) so that we confirm the bounty you have earned for this?

2017-11-09 18:01 UTC, alan-andrade commented
@andytudhope all setup. Thanks !