Fixes #2333 Adds Russian translations
status-im/status-react pull request #2356
Opened 2017-11-03 03:41 UTC by dega1989

Fixes #2333

Making it more native for Russian speaking persons!

2017-11-03 08:39 UTC, annadanchenko requested changes
"Извените" is not correct. Please, re-check spelling and grammar

2017-11-03 15:15 UTC, rasom commented on src/status_im/translations/ru.cljs
> +   :close-app-content                     "Приложение будет остановленно и закрыто. Когда вы его снова откроете, булкт использована выбранная сеть"
`булкт`

2017-11-03 15:35 UTC, dega1989 reviewed
Changed "Извените" for "Извините".
str №114

2017-11-03 15:53 UTC, annadanchenko commented
@dega1989 please re-check spelling and grammar for all of your translations. There are too many typos, I can't list them all

2017-11-03 16:51 UTC, dega1989 commented
Update ru.cljs
Str №18, 87, 114, 155, 158, 174, 209, 271, 275, 280, 284, 284, 290, 300, 319, 325, 326, 327, 360, 361, 363.

2017-11-03 17:09 UTC, annadanchenko commented
Typos still survived after the spell check. For example "Количестро", "Сслылка". I didn't run the full check as it looks like what this PR is about - translate it in a nice way, so Russian-speaking audience can enjoy the app in Russian.

2017-11-05 16:09 UTC, dega1989 reviewed
Check This one!

2017-11-07 10:52 UTC, rasom commented
closing this PR because https://github.com/status-im/status-react/pull/2361 was already merged

2017-11-07 10:52 UTC, closed without merging