Update ru.cljs
status-im/status-react pull request #2361
Opened 2017-11-03 12:48 UTC by pkazo

Due to lack of context I have problems with translation of faucet-success & faucet-error. Would be great if someone could help.

[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

addresses #...

### Summary:

[comment]: # (Summarise the problem and how the pull request solves it)
...

### Steps to test:
- Open Status
- ...
- Step 3, etc.

[comment]: # (PRs will only be accepted if squashed into single commit.)

status: ready

*or*

status: wip

2017-11-03 13:51 UTC, annadanchenko commented
Hey @pkazo if you want to participate in bounty for solving #2333 then make sure that you 
1. Have logged to https://openbounty.status.im/ and set your Ethereum address in Payment details
2. Have changed the PR description, so it contains exact phrase like `Fixes #2333`

2017-11-03 15:45 UTC, annadanchenko requested changes

2017-11-03 15:45 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :photos-access-error                   "Чтобы предоставить необходимое разрешение для фото, пожалуйста, перейдите в настройки системы и убедитесь, что выбрано Статус > Камера."
There are "Статус > Камера." in both strings but it's wrong, English file contains
   :camera-access-error                  ...  Status > Camera is selected."
   :photos-access-error                  ... Status > Photos is selected."

2017-11-03 18:13 UTC, pkazo commented on src/status_im/translations/ru.cljs
> +   :photos-access-error                   "Чтобы предоставить необходимое разрешение для фото, пожалуйста, перейдите в настройки системы и убедитесь, что выбрано Статус > Камера."
on it. Sorry 👍

2017-11-06 07:10 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :photos-access-error                   "Чтобы предоставить необходимое разрешение для фото, пожалуйста, перейдите в настройки системы и убедитесь, что выбрано Статус > Фото."
1. Application name “Status” should not be translated. Please, re-check in the all other translations.
2. On iOS setting is called "Фотографии" not "Фото"

2017-11-06 07:11 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :status-prompt                         "Укажите свой статус. Использование #хэштеги поможет другим узнать о вас и рассказать о том, что у вас на уме"
хэштеги  -> хэштегов

2017-11-06 07:12 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :browsing-browse                       "@просматривать"
Do not translate @browse if it contains "@". This is the name of the command and should  be in English

2017-11-06 07:16 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :shake-your-phone                      "Найдена ошибка или есть предложение? Просто ~встряхните~ свой телефон!"
встряхните -> потрясите

2017-11-06 07:17 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
>     :intro-message1                        "Добро пожаловать в Статус\nНажмите на это сообщение, чтобы установить пароль и начать!"
Please, change app name to English here too

2017-11-06 07:17 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :move-to-internal-failure-message      "Нам нужно переместить некоторые важные файлы из внешнего хранилище во внутреннее. Для этого нам нужно ваше разрешение. В следующих версиях мы не будем испол
хранилище -> хранилища

2017-11-06 07:20 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :debug-enabled                         "Запущен сервер отладки! Теперь вы можете выполнить * status-dev-cli scan *, чтобы найдите сервер с вашего компьютера в той же сети."
чтобы найдите -> чтобы найти

2017-11-06 07:21 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :phone-e164                            "Международная 1"
Международная - > Международный
(it's about phone number formats, format is "he" in Russian, so Международный)

2017-11-06 07:24 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :phone-significant                     "Значительное"
Значительное  -> Простой

2017-11-06 07:25 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :no-statuses-found                     "Статусы не обнаружены"
here it's not an app name, so ok to keep in Russian

2017-11-06 07:26 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :no-statuses-discovered-body           "Когда кто-то отправляет\nстатус, вы увидите его здесь."
отправляет -> создаст

2017-11-06 07:27 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :delete-contact-confirmation           "тот контакт будет удален из ваших контактов"
тот -> этот

2017-11-06 07:30 UTC, rasom commented on src/status_im/translations/ru.cljs
> +   :edit-network-warning                  "Будьте осторожны, редактирование сетевых данных может отключить эту сеть для вас"
```
Будьте осторожны, изменение настроек сети может сделать её недоступной
```
something like this

2017-11-06 07:30 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :location                              "Местоположения"
Местоположения -> Местоположение

2017-11-06 07:33 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :sign-in-to-status                     "Войти в Статус"
Статус  -> Status

2017-11-06 07:35 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :transaction                           "Сделка"
Сделка  -> Транзакция

2017-11-06 07:42 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :nonce                                 "Нонс"
Let's keep it in English "Nonce"

2017-11-06 07:47 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :cost-fee                              "Стоимость/Комиссионные"
Стоимость/Комиссия

2017-11-06 07:48 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :open-on-etherscan                     "Открыть ссылку Etherscan.io"
"Открыть ссылку Etherscan.io" -> "Открыть ссылку на Etherscan.io"

2017-11-06 07:51 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :testfairy-message                     "Вы используете приложение, установленное из ночной сборки. Для целей тестирования эта сборка включает в себя запись сеанса, если используется соединение Wi-
сохраняется -> сохраняются
журналы -> логи

2017-11-06 07:58 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :here-is-your-signing-phrase           "Вот ваша фраза подписи. Вы будете использовать ее для подтверждения своих транзакций. *Запишите ее и храните в безопасности!*"
Вы будете использовать ее для подтверждения своих транзакций. -> Вы будете использовать ее для проверки достоверности своих транзакций.

2017-11-06 08:02 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :transactions-delete-content           "Транзакция будет удалена из списка «Без Подписей»"
«Без Подписей» -> 'Неподписанные'

2017-11-06 08:02 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :transactions-unsigned                 "Без Подписей"
Без Подписей -> Неподписанные

2017-11-06 08:03 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :transaction-moved-text                "Трансакция будет находится в списке «Без Подписей» в течение 5 минут"
Трансакция -> Трансакция

2017-11-06 08:05 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :sign-later-text                       "Проверить историю транзакций, чтобы подписать эту транзакцию"
Проверить историю транзакций -> Откройте историю транзакций

2017-11-06 09:01 UTC, pkazo commented on src/status_im/translations/ru.cljs
> +   :sign-later-text                       "Проверить историю транзакций, чтобы подписать эту транзакцию"
Should I use "Трансакция" or "транзакций".  "с" or "з" ? I got confused to be honest. 
Thank you :)

2017-11-06 11:00 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :send-transaction                      "Отправить трансакцию"
My apologies, I've also made a typo in the last review comments. It should be транзакция (with "з" ) everywhere.

2017-11-06 11:10 UTC, pkazo commented on src/status_im/translations/ru.cljs
> +   :send-transaction                      "Отправить трансакцию"
Thank you for clarification. :)
 I fixed those

2017-11-06 11:44 UTC, annadanchenko approved these changes

2017-11-06 11:48 UTC, annadanchenko requested changes
Транзакция будет находится в списке 'Неподписанные' в течение 5 минут -> что будет делать? будет находиться, right?

2017-11-06 11:49 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :transaction-description               "Пожалуйста, подождите как минимум 12 подтверждений, чтобы убедиться, что транзакцию обработана безопасно"
транзакцию -> транзакция

2017-11-06 11:50 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :view-transaction-details              "Посмотреть детали транзакций"
транзакций -> транзакции

2017-11-06 11:52 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :validation-amount-is-too-precise      "Сумма слишком точная. Наименьшая единица вы можете отправить это 1 Wei (1x10^-18 ETH)"
Наименьшая единица вы можете -> Наименьшая сумма, которую вы можете ..

2017-11-06 11:53 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :transaction-description               "Пожалуйста, подождите как минимум 12 подтверждений, чтобы убедиться, что транзакцию обработана безопасно"
что транзакцию обработана -> что транзакция обработана

2017-11-06 13:19 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :transaction-moved-text                "Транзакция будет находится в списке 'Неподписанные' в течение 5 минут"
Транзакция будет находится в списке 'Неподписанные' в течение 5 минут -> что будет делать? будет находиться, need "ь" right?

2017-11-06 13:21 UTC, annadanchenko approved these changes

2017-11-06 13:32 UTC, rasom commented on src/status_im/translations/ru.cljs
> +   :confirmations-helper-text             "Пожалуйста, подождите как минимум 12 подтверждений, чтобы убедиться, что транзакция обработана безопасно"
Пожалуйста, дождитесь как минимум 12-ти подтверждений, чтобы убедиться, что транзакция обработана безопасно

2017-11-06 13:35 UTC, anna08test commented on src/status_im/translations/ru.cljs
> +   :dropped-pin                           "Dropped pin"
Выбранное местоположение

2017-11-06 13:36 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :dropped-pin                           "Dropped pin"
Выбранное местоположение

2017-11-06 13:46 UTC, annadanchenko commented on src/status_im/translations/ru.cljs
> +   :validation-amount-is-too-precise      "Сумма слишком точная. Наименьшая сумма, которую вы можете отправить это 1 Wei (1x10^-18 ETH)"
Сумма слишком точная. -> Слишком много чисел после запятой. Наименьшая сумма, которую вы можете отправить это 1 Wei (1x10^-18 ETH)

2017-11-06 13:49 UTC, annadanchenko commented
That's it @pkazo  :) Please, address the last 3 comments, so we can approve and merge

2017-11-06 14:13 UTC, rasom approved these changes

2017-11-06 14:13 UTC, merged

2017-11-06 14:49 UTC, pkazo commented
Thank you guys :)

2017-11-06 19:12 UTC, pkazo commented
@rasom I would like to ask question about "Activity" feed in the Status app, earlier today I was mentioned in Activity feed, now I am not there. Is something wrong? Just curious :D

2017-11-07 07:27 UTC, annadanchenko commented
@pkazo after PR is merged claims are not shown on Activity feed anymore (will fix it in the future). You can see status of the claim in the issue #2333 on status-open-bounty comment, it mentions
```
Status: pending maintainer confirmation
Winner: pkazo
```
So, now it's in waiting state for the Status owner to confirm your claim. After this SNT will be sent.

2017-11-07 09:27 UTC, pkazo commented
@annadanchenko I am nooby sorry :D Thank you for clarification :)

2017-11-07 13:23 UTC, pkazo commented
@annadanchenko Sorry to bother again. However, its says that it was Paid to: dega1989 [#2333](https://github.com/status-im/status-react/issues/2333) . Most interesting part that in https://openbounty.status.im/app it says that I have been paid. I have not received anything. Confusing.