Translate App Strings to German #2330
status-im/status-react pull request #2364
Opened 2017-11-03 15:49 UTC by fkbenjamin

Issue #2330 - Mirrored the English File and translated all Strings to German

[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

If you submit PR for issue with bounty then write here Fixes #NN where NN is issue number

*otherwise*

addresses #...

### Summary:

[comment]: # (Summarise the problem and how the pull request solves it)
...

### Steps to test:
- Open Status
- ...
- Step 3, etc.

[comment]: # (PRs will only be accepted if squashed into single commit.)

status: ready

*or*

status: wip

2017-11-06 18:34 UTC, themue requested changes
Tough work, awesome. Thanks. Only missing one text (`:status-sending`), some typos, and some changes. In case of different opinions lets discuss it, you can DM me in German in our Slack as @themue.

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :node-unavailable                      "Keine laufende Ethereum Node"
Better "Kein laufender Ethereum-Knoten".

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :faucet-success                        "Faucet Anfrage wurde empfangen"
Hmm, would like to discuss if "Faucet-Anfrage" is better. Nut yet sure.

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   ;;messages
Missing `:status-sending`.

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :status-seen-by-everyone               "Gesehen von allen"
Would prefer variant 1: "Von allen gesehen". Or maybe "Von jedem gesehen".

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :status-delivered                      "Ausgeliefert"
Also hier I like variant 1 "Zugestellt" more. "Ausgeliefert" sounds more like helplessness. 😄

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :datetime-ago-format                   "{{number}} {{time-intervals}} {{ago}}"
`{{ago}}` has to be in the front. While in English it may be "5 hours ago" it's "vor 5 Stunden" in German.

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :start-conversation                    "Beginne eine Konversation"
Better "Beginne ein Gespräch".

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :mainnet-text                          "Du befindest dich auf dem Hauptnetzwerk. Echter ETH wird gesendet"
Better "Mainnet" than "Hauptnetzwerk", it's a fixed term. And "Echte ETH werden gesendet".

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :here-is-your-passphrase               "Hier ist deine Passphrase, *Notiere sie dir und bewahre sie sicher auf!* Du wirst sie brauchen, um deinen Account wiederherzustellen."
Interpunction is correct. Better may be "... Passphrase. \*Notiere ... auf!\* Du ...". Same above, a period behind "Passphrase".

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :here-is-your-signing-phrase           "Hier ist deine Signaturphrase. Du wirst sie benutzen, um deine Trtansaktionen zu verifizieren. *Notiere sie dir und bewahre sie sicher auf!*"
Please keep the term "Signing Phrase".

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :phone-number-required                 "Tippe hier, um deine Telefonnummer zu validieren und ich finde deine Freunde."
"... und ich werde deine Freunde finden." sounds more natural.

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :shake-your-phone                      "Du hast einen Bug gefunden oder hast einen Verbesserungsvorschlag? ~Schütelle~ einfach dein Handy!"
Typo, "Schüttle".

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :intro-status                          "Chatte mit mir, um deinen Account aufzusetzen und deine Einstellungen zu ändern."
"..., um deinen Account einzurichten ..."

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :move-to-internal-failure-message      "Wir müssen ein paar wichtige Dateien vom externen zum internen Speicher verschieben. Dafür brauchen wir deine Erlaubnis. In zukünftigen Versionen werden wir
In German I would say "... keinen externen Speicher mehr verwenden.".

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :debug-enabled                         "Debug-Server wurde eingeführt! Du kannst jetzt *status-dev-cli scan* ausführen, um den Server von deinem Computer im selben Netzwerk zu finden."
Better "Der Debug-Server wurde gestartet!".

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
>     :new-public-group-chat                 "Öffentlichem Gruppenchat beitreten"
Even if identifier contains a group chat the original message more is like "Öffentlichem Chat beitreten".

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :recent                                "Kürzliche Status"
Ah, nice one. 👏  Most create wrong plural of "Status". 👍

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :no-statuses-found                     "Kein Status gefunden"
"Keine Status gefunden".

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
>     :no-statuses-discovered                "Kein Status gefunden"
"Keine Status gefunden".

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :chat-settings                         "Chat Einstellungen"
"Chat-Einstellungen".

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :dropped-pin                           "Pin abgesetzt"
Better "Pin gesetzt".

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :removed-from-chat                     "hat dich aus den Gruppenchat entfernt"
"... aus dem Gruppenchat ...".

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :address-explication                   "Dein öffentlicher Schlüssel wird verwendet, um deine Adresse auf Ethereum zu generieren und besteht aus einer Folge von Zahlen und Buchstaben. Du findest ih
Better "leicht" instead of "einfach".

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :create-new-account                    "Neuen Account erstellen"
Better "Neues Konto erstellen".

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :amount                                "Menge"
"Betrag" matches better to a currency.

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :got-it                                "Verstanden"
Here "erhalten" is better in the sense of receiving the amount.

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :testfairy-message                     "Du verwendest eine App Version, die aus einem Nightly Build stammt. Zu Testzwecken verwendet diese Version Session-Aufzeichnung, solange eine Wlan-Verbindun
- "Zu Testzwecken zeichnet diese Versions Sitzungsdaten auf, solange eine WLAN-Verbindung genutzt wird."
- "... gespeichert werden (als Video oder Logs) und ..." (added a space).
- "... aus einem Nightly Build installiert wurde."

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :wallet-settings                       "Wallet Einstellungen"
With a dash, "Wallet-Einstellungen".

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :wallet-insufficient-funds             "Ungenügende Mittel"
"Unzureichendes Kapital".

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :transaction-failed                    "Transaktion fehlgeschlafen"
Typo, "fehlgeschlagen".

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :transactions-filter-title             "Filter Verlauf"
"Filterverlauf".

2017-11-06 18:34 UTC, themue commented on src/status_im/translations/de.cljs
> +   :connecting-requires-login             "Das Verbinden mit einem anderen Netzwerk erfordert, eingeloggt zu sein"
Better and more simple "... erfordert eine Anmeldung".

2017-11-06 19:58 UTC, fkbenjamin commented
Thanks for the review! I will fix the changes tomorrow! Sadly I am only in the Riot Chat Room. Slack is closed. Are you there as well to discuss some minor different opinions?

2017-11-06 20:19 UTC, themue commented
Sure, we also can talk on Riot. Here you also find me as @themue.

2017-11-07 13:08 UTC, fkbenjamin commented on src/status_im/translations/de.cljs
> +   :status-delivered                      "Ausgeliefert"
You're totally right 😄

2017-11-07 20:10 UTC, themue approved these changes
Awesome work, thanks.

LGTM

2017-11-08 10:04 UTC, merged