Fixes #2332 : Translate App Strings to Spanish by merlox
status-im/status-react pull request #2365
Opened 2017-11-03 19:07 UTC by merlox

Fixes #2332

This is the translation to spanish. I've changed the first line from:
```
(ns status-im.translations.en)
```
To:
```
(ns status-im.translations.es)
```

2017-11-04 04:01 UTC, adnx2h commented
mainnet and testnet should be translated as well

2017-11-04 04:39 UTC, LaloGarza commented
There’s some translations that are not correct, for example line 105, it should be: Nuevo chat grupal.
And line 137 the word Unirse is misspelled.
![57bda6f0-ee4a-41c8-804a-18b1e4b02e8c](https://user-images.githubusercontent.com/33364523/32402373-3b836db6-c0f0-11e7-9f23-029c99bce516.png)

2017-11-05 21:06 UTC, weisk requested changes
revisiones

2017-11-05 21:06 UTC, weisk commented on src/status_im/translations/es.cljs
> +   :status-failed                         "Fallído"
va sin acento

2017-11-05 21:06 UTC, weisk commented on src/status_im/translations/es.cljs
> +                                               "código. Por favor danos ese código para confirmar tu número de teléfono")
"con una confirmacion código" no tiene sentido. Mejor poner "con un código de confirmacion". El salto de línea da igual que lo pongas con unas palabras más o menos de margen.

2017-11-05 21:06 UTC, weisk commented on src/status_im/translations/es.cljs
> +   :debug-enabled                         "¡El servidor de depuración ha sido activado! Ahora puedes ejecutar *status-dev-cli scan* para encontrar el servidor en tu ordenador desde la misma red."
"en la misma red"

2017-11-05 21:06 UTC, weisk commented on src/status_im/translations/es.cljs
> +   :phone-significant                     "Significante"
Significativo

2017-11-05 21:06 UTC, weisk commented on src/status_im/translations/es.cljs
> +   :web-view-error                        "oops, error"
una tontería, pero creo que en español es mejor "ups"

2017-11-14 14:18 UTC, yenda commented
@merlox can this PR be closed ? It only removes 2 empty lines in the translation file ?

2017-11-23 11:46 UTC, oskarth commented
Closing this PR as it doesn't include any translations. Feel free to open another PR if you feel like this is an error.

2017-11-23 11:46 UTC, closed without merging