[FIX #2118] ui: store search-key under [:toolbar-search :show]
status-im/status-react pull request #2585
Opened 2017-12-02 19:44 UTC by siphiuel

Chat list used to store booleans under [:toolbar-search :show] which is
different from other views and caused the toolbar to appear in Chats if search was used in Discover or Contacts. With this change search key (= :chat-list) is stored under the above path.

2017-12-06 07:39 UTC, jeluard approved these changes

2017-12-06 13:28 UTC, oskarth commented
Same comment as https://github.com/status-im/status-react/pull/2584#issuecomment-349638166 - sorry to be a stickler but it really makes it easier (and quicker!) for devs and QA to review, test and merge your changes.

2017-12-06 14:14 UTC, oskarth approved these changes

2017-12-14 10:40 UTC, rasom commented on src/status_im/ui/screens/chats_list/views.cljs
> -            search?      [:get-in [:toolbar-search :show]]
```
Use of undeclared Var status-im.ui.screens.chats-list.views/search? at line 98 /Users/jenkins/workspace/status-react/parametrized build/src/status_im/ui/screens/chats_list/views.cljs
```
`search?` symbol is used later in this function

2017-12-14 10:42 UTC, rasom requested changes
see comment above

2017-12-14 10:53 UTC, siphiuel commented
Sorry, lame mistake. Fixed.

2017-12-21 08:44 UTC, rasom approved these changes

2017-12-22 10:45 UTC, rasom commented
i've just rebased it onto `develop`

2017-12-22 13:49 UTC, churik commented
Checked:
install:
Chats:
* group chat
* 1-1 chat
* public chat
* search in Discover > Chat screen (adresses to #2118)
* search in Chats > Chat screen
* search in Contacts > Chat screen
Upgrade (IOS only, android is blocked by  #2762)
* data before upgrade is saved
* issue is not reproducible

2017-12-27 07:35 UTC, merged