[FIX #2565] data-store: escape leading tildes in message content
status-im/status-react pull request #2612
Opened 2017-12-05 18:30 UTC by siphiuel

Per Transit [documentation](https://github.com/cognitect/transit-format#special-characters), leading tildes have to be escaped, otherwise they are treated as tagged values.

2017-12-05 18:37 UTC, pablanopete commented
Hi @siphiuel thanks for your contribution! One of our team members will review shortly - in the meantime are you already part of the conversation on our Riot? I'd like to invite you at https://chat.status.im/#/register and ping me @hutch when you join! Thanks.

2017-12-06 07:33 UTC, jeluard requested changes
Please add tests to validate this behavior.

2017-12-06 07:33 UTC, jeluard commented on src/status_im/data_store/realm/messages.cljs
> +           (string/starts-with? content "~"))
Looks like `~` is not the only special character. Also we probably want to do this generically, not only for this particular filed?

2017-12-20 20:29 UTC, siphiuel commented
Hi!

Thank you for reviewing!

Made the following changes:

1. Added tests in `status-im.test.data-store.realm.core` namespace
2. The function that does the escaping (`prepare-for-transit`) is moved to ` status-im.data-store.realm.core` and recursively walks through all string fields in a data structures that is saved to Realm.
3. Additional special characters are taken into account.

I did a force push and some of your comments (the ones regarding items #2 and #3) seem to be gone. Sorry for that.

2017-12-21 07:39 UTC, jeluard commented
Thanks! It's not clear to me if escaped characters will be deserialized correctly. Could we add a round-trip test that would validate the the full serialize / deserialize logic?

2017-12-21 11:01 UTC, siphiuel commented
Hi! There's a round-trip test at line #25:
```
(is (= data (-> prepared-data
                      clj->js
                      internal-convert)))
```
It checks where Clojure data structure survives the conversion in both directions intact. Do you think it is enough?

2017-12-21 11:03 UTC, jeluard commented
Great I missed it!

2017-12-21 11:03 UTC, jeluard approved these changes

2017-12-24 12:02 UTC, rasom commented on src/status_im/data_store/realm/core.cljs
> +    (walk/walk walk-fn identity message)))
We could use `postwalk`, then no need to use recursion inside `walk-fn`. 
Something like
```clojure
(letfn [(walk-fn [e]
            (cond->> e
                     (to-be-escaped? e)
                     (str escape-char)))]
    (walk/postwalk walk-fn message))
```
But this is just a suggestion

2017-12-24 12:03 UTC, rasom commented on src/status_im/data_store/realm/core.cljs
> +                     )
Please fix trailing parenth https://github.com/bbatsov/clojure-style-guide#gather-trailing-parens

2017-12-24 12:04 UTC, rasom commented on src/status_im/data_store/realm/core.cljs
> +                     (first e)
No need to for this check, i mean `(first e)`

2017-12-24 12:05 UTC, rasom commented on src/status_im/data_store/realm/core.cljs
> +                     (contains? #{"~" "^" "`"} (first e))
Please extract this set of with characters which should be escaped to a constant.

2017-12-24 12:06 UTC, rasom commented on src/status_im/data_store/realm/core.cljs
> +              (str "~" e)
Please extract magic value (`"~"`) to constant

2017-12-24 12:08 UTC, rasom commented on src/status_im/data_store/realm/core.cljs
> +            (if (and (string? e)
Also would be great to extract all these predicates to separate function

2017-12-24 12:10 UTC, rasom commented on test/cljs/status_im/test/data_store/realm/core.cljs
> +    (let [data {:to-be-escaped1 "~bad string"
Please align values in maps and `let` forms

2017-12-24 12:11 UTC, rasom commented on test/cljs/status_im/test/data_store/realm/core.cljs
> +          prepare-for-transit #'core/prepare-for-transit
What is the reason for not using `core/prepare-for-transit` directly?

2017-12-24 12:11 UTC, rasom requested changes
See comments above

2017-12-24 20:20 UTC, siphiuel commented
Hi, thanks for reviewing!

Made the requested changes, details below:

1. walk->postwalk: agree, looks simpler.
2. Trailing parens: removed.
3. Extra check for (first e): removed.
4. Extracted special char values to constants, created a predicate fn.
5. Not sure if I got the alignment properly in the test fn.
6. Referring to private functions by vars: in Clojure private ns functions can be referred to from outside via vars, but it seems that in Clojurescript there is no such restriction?

2017-12-25 07:54 UTC, rasom commented
> Referring to private functions by vars: in Clojure private ns functions can only be referred to from outside via vars, but it seems that in Clojurescript there is no such restriction?

I just haven't noticed that function is "private". Yeah it doesn't work in cljs and tbh i see no reason for using `defn-`, but that's not a big problem. 

> Not sure if I got the alignment properly in the test fn.

We usually align let-binding values, so it should look like 
```clojure
(let [data          {:to-be-escaped1 "~bad string"
                     :to-be-escaped2 "^another bad string"
                     :to-be-escaped3 "`and another bad string"
                     :no-escaping    "no escaping"
                     :vector-content ["a" "b" "c"]}
      prepared-data (core/prepare-for-transit data)]
  ...)
```
not 
```clojure
(let [data {:to-be-escaped1 "~bad string"
            :to-be-escaped2 "^another bad string"
            :to-be-escaped3 "`and another bad string"
            :no-escaping    "no escaping"
            :vector-content ["a" "b" "c"]}
      prepared-data (core/prepare-for-transit data)]
  ...)
```

2017-12-25 11:51 UTC, siphiuel commented
Got it, made the changes.

2017-12-25 11:52 UTC, siphiuel commented
I can squash if there are no other changes to be done.

2017-12-25 11:53 UTC, rasom approved these changes

2017-12-25 11:54 UTC, rasom commented
@siphiuel, yes please squash commits

2017-12-25 12:07 UTC, siphiuel commented
Done.

2017-12-25 14:19 UTC, merged