Update swedish translation
status-im/status-react pull request #2710
Opened 2017-12-13 18:01 UTC by pafcu

Fixes #2335 

### Summary:

[comment]: # (Summarise the problem and how the pull request solves it)
Updates Swedish translation to match the current English one

status: ready

2017-12-13 21:16 UTC, andytudhope commented
I will check this in the morning my time from a coverage perspective. Pinging @oskarth to check the actual content. Thank you for the submission @pafcu - are you part of our https://chat.status.im ? If not, please join in and ping me @cryptowanderer to fall further down the rabbit hole 😉

2017-12-14 09:38 UTC, andytudhope commented
Hey @pafcu. I have tested this and it seems like you have covered all the bases. Now we need @oskarth to check the actual Swedish content. If you add `:sv` to the group of language at line 270 of `i18n.cljs` and run `lein test-cljs` you can satisfy yourself that you translated everything. Please do this when you have a moment and add it to this PR?

2017-12-14 19:46 UTC, pafcu commented
I tried running the test, but even without modifications it seems to fail.

Log: [error.txt](https://github.com/status-im/status-react/files/1560508/error.txt)

2017-12-18 08:25 UTC, pafcu commented
Should I file a separate issue for the failing tests?

2017-12-18 08:40 UTC, andytudhope commented
No need @pafcu - no tests are failing on `develop` (though there are some issues with re-frisk) and no tests fail on your branch when I run them, so I suspect it is something you did wrong 😉 Oskar will review sometime this week, just not very high priority and he is a busy guy. He will ping you here when it is done.

2017-12-21 20:24 UTC, oskarth requested changes
Tack för ditt bidrag! Mesta ser bra ut, gav lite kommentarer.

2017-12-21 20:24 UTC, oskarth commented on src/status_im/translations/sv.cljs
>     :notifications-title                   "Aviseringar och ljud"
Notiser och ljud kanske? Se t. ex https://support.apple.com/sv-se/HT201925

2017-12-21 20:24 UTC, oskarth commented on src/status_im/translations/sv.cljs
> +   :faucet-success                        "Kranbegäran mottagen"
Kranbegäran känns lite för försvenskat, vad tror du om att kalla det för Faucet? Det är vad heter också. Samma nedan.

2017-12-21 20:24 UTC, oskarth commented on src/status_im/translations/sv.cljs
> +   :testnet-text                          "Du är på {{testnet}} Testnet. Sänd inte äkta ETH eller SNT till din address"
Istället för äkta, riktiga kanske? Äkta känns mer som "authentic". Samma nedan isåfall.

2017-12-21 20:24 UTC, oskarth commented on src/status_im/translations/sv.cljs
> +   :here-is-your-signing-phrase           "Här är din underskriftsfras. Du kommer att använde den för att verifiera dina transaktioner. *Skriv ner det här och förvara det säkert!*"
"Skriv ner den och förvara den säkert!"?

2017-12-21 20:24 UTC, oskarth commented on src/status_im/translations/sv.cljs
> +   :mute-notifications                    "Tysta anmälningar"
notiser?

2017-12-21 20:24 UTC, oskarth commented on src/status_im/translations/sv.cljs
> +   :search-results                        "Sök resultat"
Sökresultat

2017-12-21 20:24 UTC, oskarth commented on src/status_im/translations/sv.cljs
> +   :address-explication                   "Din offentliga nykel används för att generera din address på Ethereum och är en serie siffror och bokstäver. Du kan hitta den lätt i din profil"
Du kan lätt hitta den i din profil

2017-12-21 20:24 UTC, oskarth commented on src/status_im/translations/sv.cljs
> +   :unsigned-transaction-expired          "Ounderskriven transaktion förföll"
Ej underskriven

2017-12-21 20:24 UTC, oskarth commented on src/status_im/translations/sv.cljs
> +   :confirmations-helper-text             "Var god och vänta på åtminståne 12 bekräftelser för att försäkra dig att transaktionen behandlas säkert"
...på minst...

...försäkra dig om att transaktionen...

2017-12-21 20:24 UTC, oskarth commented on src/status_im/translations/sv.cljs
> +   :testfairy-message                     "Du använder en app som installerats från en nattlig version. För att underlätta testning spelar denna version in sessionen om wifi används. All interaktion
WiFi

utvecklare

2017-12-21 20:24 UTC, oskarth commented on src/status_im/translations/sv.cljs
> +   :signing-phrase-description            "Skriv under transaktionen genom att ge ditt lösenord. Kontrollera att orden ovan motsvarar din hemliga underskriftsfras"
genom att ange ditt

2017-12-21 20:24 UTC, oskarth commented on src/status_im/translations/sv.cljs
> +   :transactions-delete-content           "Transaktionen tas bort från listan 'Ounderskrivna'"
'Ej underskrivna'

2017-12-21 20:24 UTC, oskarth commented on src/status_im/translations/sv.cljs
> +   :transactions-unsigned                 "Ounderskrivna"
Ej underskrivna

2017-12-21 20:24 UTC, oskarth commented on src/status_im/translations/sv.cljs
> +   :transactions-history-empty            "Inga transaktioner in din historik ännu"
i din historik än

2017-12-21 20:24 UTC, oskarth commented on src/status_im/translations/sv.cljs
> +   :transactions-unsigned-empty           "Du har inga ounderskrivna transaktioner"
ej underskrivna

2017-12-21 20:24 UTC, oskarth commented on src/status_im/translations/sv.cljs
> +   :transaction-description               "Var god och vänta på åtminståne 12 bekräftelser för att försäkra dig att transaktionen behandlas säkert"
på minst 12

2017-12-21 20:24 UTC, oskarth commented on src/status_im/translations/sv.cljs
> +   :transaction-description               "Var god och vänta på åtminståne 12 bekräftelser för att försäkra dig att transaktionen behandlas säkert"
"för att försäkra dig om att transaktionen gått igenom" kanske?

2017-12-21 20:24 UTC, oskarth commented on src/status_im/translations/sv.cljs
> +   :transaction-sent                      "Transaktionen sändes"
skickad

2017-12-21 20:24 UTC, oskarth commented on src/status_im/translations/sv.cljs
> +   :transaction-moved-text                "Transaktionen kvarblir på listan 'Ounderskrivna' de nästa 5 minuterna"
Transaktioner står kvar på listan 'Ej underskrivna' i 5 minuter

2017-12-21 20:24 UTC, oskarth commented on src/status_im/translations/sv.cljs
> +   :not-applicable                        "Inte tillämplig på ounderskrivna transaktioner"
Ej applicerbar på ej underskrivna transaktioner

2017-12-21 20:24 UTC, oskarth commented on src/status_im/translations/sv.cljs
> +   :validation-amount-invalid-number      "Summan är inte ett giltigt tal"
belopp?

2017-12-21 20:24 UTC, oskarth commented on src/status_im/translations/sv.cljs
> +   :validation-amount-is-too-precise      "Summan är för exakt. Den minsta summan du kan skicka är 1 Wei (1x10^-18 ETH)"
för precis

2017-12-23 19:08 UTC, pafcu commented on src/status_im/translations/sv.cljs
>     :notifications-title                   "Aviseringar och ljud"
Men det heter Aviseringar på t.ex. Facebook (https://sv-se.facebook.com/help/327994277286267)

2017-12-23 19:12 UTC, pafcu commented on src/status_im/translations/sv.cljs
> +   :mute-notifications                    "Tysta anmälningar"
Eller aviseringar. Hursomhelst borde det säkert vara samma som ovan, jo.

2017-12-23 19:21 UTC, pafcu commented on src/status_im/translations/sv.cljs
> +   :not-applicable                        "Inte tillämplig på ounderskrivna transaktioner"
Är du säker gällande "applicerbar"? SAOL känner inte applicerbar (som låter som en anglism), men däremot tillämplig.

2017-12-23 19:41 UTC, pafcu commented
@oskarth Fixed, but feel free to request more changes.

2017-12-24 07:48 UTC, andytudhope commented
Cool, am sure Oskar will review again after Christmas. Please can you add the key `sv` to the `supported-locales` in `i18n.cljs` so that we can be sure we support Swedish fully and that we have full coverage. The function at line 270 should look like this:
```
(def supported-locales (spec/assert ::locales #{:fr
                                                :zh-hans-cn
                                                :zh-hans-sg
                                                :sr-RS_#Cyrl
                                                :zh-hans-tw
                                                :en
                                                :zh
                                                :de
                                                :zh-hans
                                                :lt
                                                :zh-hans-mo
                                                :zh-hans-hk
                                                :sr-RS_#Latn
                                                :sr
                                                :sv}))
```

If you run `lein test-cljs` after that, you will see that all tests pass and that you have indeed covered all the required keys.

2017-12-24 08:04 UTC, pafcu commented
@andytudhope I now added `:sv` but as I stated earlier, I can't actually test it, since `lein test-cljs` fails for me in any case.

2017-12-24 10:24 UTC, andytudhope commented
Yeah, but that's something wrong in your environment worth looking into 😉 You will need to include that key as I have indicated in order for this PR to be merged. 
Are you sure that you did a successful `npm install` after cloning `status-react`? This part of your error message:
```
Caused by: clojure.lang.ExceptionInfo: node_modules/web3/dist/web3.min.js (No such file or directory) at line 44 src/status_im/utils/js_resources.cljs {:file "src/status_im/utils/js_resources.cljs", :line 44, :column 16, :tag :cljs/analysis-error}
```
suggests that you did not.

2017-12-24 12:40 UTC, pafcu commented
@andytudhope Thanks. I (wrongly) assumed that `lein` takes care of all dependencies, but apparently there is another, parallel dependency manager. In any case `npm install` fixed the problem and the test finishes without errors.

2017-12-25 10:40 UTC, oskarth commented on src/status_im/translations/sv.cljs
>     :notifications-title                   "Aviseringar och ljud"
Aha intressant, kan köra på Aviseringar då

2017-12-25 10:40 UTC, oskarth commented on src/status_im/translations/sv.cljs
> +   :mute-notifications                    "Tysta anmälningar"
Aviseringar funkar

2017-12-25 10:41 UTC, oskarth approved these changes

2017-12-25 10:43 UTC, oskarth commented on src/status_im/translations/sv.cljs
> +   :not-applicable                        "Inte tillämplig på ounderskrivna transaktioner"
http://www.saob.se/artikel/?unik=A_1959-0100.RadQ&pz=5 men Otillämplig funkar också

2017-12-25 10:43 UTC, oskarth commented
Tack @pafcu!

2017-12-26 16:26 UTC, merged