[Fix #2613] Long username is not cut with ...
status-im/status-react pull request #2724
Opened 2017-12-15 09:57 UTC by foopang

Fix #2613 

status: ready

2017-12-15 10:12 UTC, andytudhope commented
Wow, that was quick @foopang! @rasom could you review here, or get a QA team member to check?

2017-12-15 11:20 UTC, yenda requested changes

2017-12-15 11:20 UTC, yenda commented on src/status_im/ui/screens/discover/components/views.cljs
> +            [status-im.utils.utils :refer [truncate-str]]))
please use :as instead of refer

2017-12-15 11:20 UTC, yenda commented on src/status_im/ui/screens/discover/components/views.cljs
> +           (cond-> (display-name me? account-name contact-name name whisper-id)
if display-name is used only in these 2 places then this logic should be in display-name as well instead of duplicated

2017-12-15 12:18 UTC, foopang commented
Updated. Thanks!

2017-12-15 12:39 UTC, yenda approved these changes

2017-12-15 12:47 UTC, rasom commented on src/status_im/ui/screens/discover/components/views.cljs
> +           (display-name {:me? me?
please, align map values

2017-12-15 13:19 UTC, foopang commented
Fixed now.

2017-12-18 08:37 UTC, goranjovic approved these changes

2017-12-18 17:16 UTC, oskarth commented
@foopang Please rebase on our `develop` branch as we've recently upgraded React Native and build is failing (dependencies different).

2017-12-19 01:00 UTC, foopang commented
@oskarth rebased, but then somehow I can no longer connect to figwheel for interactive development after firing up `(cljs-repl)` in `lein repl`. Also am getting errors below by issuing the command `./re-natal enable-source-maps`.

```
➜  status-react git:(fix/issue-2613) ✗ ./re-natal enable-source-maps
Patching file node_modules/metro-bundler/src/Server/index.js to serve *.map files.
fs.js:642
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'node_modules/metro-bundler/src/Server/index.js'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.readFileSync (fs.js:510:33)
    at readFile (/home/pang/dev/status-react/node_modules/re-natal/re-natal.coffee:160:6)
    at edit (/home/pang/dev/status-react/node_modules/re-natal/re-natal.coffee:166:5)
    at patchReactNativePackager (/home/pang/dev/status-react/node_modules/re-natal/re-natal.coffee:396:3)
    at Command.<anonymous> (/home/pang/dev/status-react/node_modules/re-natal/re-natal.coffee:972:3)
    at Command.listener (/home/pang/dev/status-react/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/home/pang/dev/status-react/node_modules/commander/index.js:653:12)
    at Command.parse (/home/pang/dev/status-react/node_modules/commander/index.js:475:21)
    at Object.<anonymous> (/home/pang/dev/status-react/node_modules/re-natal/re-natal.coffee:1005:7)
    at Object.<anonymous> (/home/pang/dev/status-react/node_modules/re-natal/re-natal.coffee:7:1)
    at Module._compile (module.js:570:32)
    at Object.loadFile (/home/pang/dev/status-react/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
    at Module.load (/home/pang/dev/status-react/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pang/dev/status-react/node_modules/re-natal/index.js:4:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
```

----

node v6.12.2
npm 3.10.10
Leiningen 2.7.1 on Java 1.8.0_144 OpenJDK 64-Bit Server VM

2017-12-19 12:42 UTC, Serhy commented
@foopang thanks for rebase! Build succeeded now.
For the above error you have for `./re-natal enable-source-maps` - could you open a separate issue please?

2017-12-19 13:20 UTC, churik commented
new comment in #2613

2017-12-20 11:20 UTC, Serhy commented
@foopang, please check new comment in #2613

2017-12-21 13:36 UTC, Serhy commented
Yes! That looks great now!
Long usernames on Android, iOS on the small and large screens doesn't move Chat button now on Discover neither on Popular hasthag -> ALL, Recent hashtag -> ALL pages.

2017-12-21 15:25 UTC, andytudhope commented
@foopang could you please just squash the commits here and then I will rebase and merge and confirm your payout 😉

2017-12-21 15:51 UTC, foopang commented
@andytudhope squash done, thanks!

2017-12-21 19:56 UTC, merged