[FIX #2620] Refactored double dispatch into single event-fx
status-im/status-react pull request #2741
Opened 2017-12-16 08:51 UTC by nrakochy

Fixes [#2620](https://github.com/status-im/status-react/issues/2620)

### Summary:
Refactored do event on the discovery tab into single event-fx to fix navigation routing. 

The 2nd call on the double-dispatch was failing to properly populate the `:navigate-to` event, which in turn was causing the back button to refer to the previous nav state instead of the newly updated.

status: ready

2017-12-19 15:59 UTC, janherich requested changes

2017-12-19 15:59 UTC, janherich commented on src/status_im/ui/screens/discover/events.cljs
> +                 [:navigate-to view-id]]}))
Can you please refactor the code to not use `:dispatch-n`, but functional composition instead?
```clj
(handlers/register-handler-db
  :show-discovery
  (fn [db [_ tags view-id]]
    (-> db
        (assoc :discover-search-tags tags)
        (navigation/navigate-to view-id))))
```
With `navigation` ns (`status-im.ui.screens.navigation`) required of course. 
The reason is that we are trying to move from imperative, side-effecty code
to something more functional, see the rationale - https://github.com/status-im/ideas/issues/31 (Point 3.)

2017-12-19 16:02 UTC, janherich commented on src/status_im/ui/screens/discover/events.cljs
> +            [status-im.utils.handlers :refer [register-handler register-handler-fx get-hashtags]]
How is that you `:refer` `register-handler-fx` and then use the `handlers/register-handler-fx` ?
In general we are trying to move from `:refer`-ing anything to always explicitly aliasing with `:as`

2017-12-20 16:24 UTC, nrakochy commented
I refactored and rebased this commit. It looks like I also needed to add a nav flag to the component. I think it is in working order.

2017-12-20 16:27 UTC, janherich approved these changes

2017-12-27 21:52 UTC, oskarth commented on src/status_im/ui/screens/discover/views.cljs
> +        tags (map :name popular-tags)]
align

2017-12-27 21:52 UTC, oskarth approved these changes
Just minor formatting

2017-12-28 16:02 UTC, merged