[Fix #2683] Do not run sync state loop on upstream RPC networks
status-im/status-react pull request #2799
Opened 2017-12-22 16:39 UTC by foopang

fixes #2683 

status: ready

2017-12-25 07:59 UTC, flexsurfer requested changes
thanks for contribution @foopang , just little comments

2017-12-25 07:59 UTC, flexsurfer commented on src/status_im/protocol/handlers.cljs
> +            [status-im.ui.screens.network-settings.events :refer [network-with-upstream-rpc?]]))
better to move this function to utils, and use `:as utils` instead `:refer`

2017-12-25 07:59 UTC, flexsurfer commented on src/status_im/protocol/handlers.cljs
> +    (when-not (or sync-listening-started (network-with-upstream-rpc? networks network))
`when-not` with `or` is difficult to read could you please change it on `when`

2017-12-25 15:13 UTC, foopang commented
@flexsurfer  Updated. Thanks for your review. I don't know whether if there is an appropriate namespace already in existence that I could use for the util function `network-with-upstream-rpc?`. So I created a new namespace called `status-im.protocol.utils` for it, hope this makes sense to you.

2017-12-26 16:23 UTC, flexsurfer commented
thanks @foopang , sorry haven't said , please move this function to `status-im.utils.ethereum.core`, sorry for confusion

2017-12-26 23:08 UTC, foopang commented
@flexsurfer updated.

2017-12-27 06:36 UTC, flexsurfer approved these changes

2017-12-27 06:40 UTC, merged