Removed NOTIFICATIONS_WIP_ENABLED flag
status-im/status-react pull request #2846
Opened 2017-12-29 02:13 UTC by taylorjdawson

Fixes #2813

### Summary:
Removed NOTIFICATIONS_WIP_ENABLED flag while keeping behavior for flag ON.

status: ready

2017-12-29 08:18 UTC, flexsurfer requested changes

2017-12-29 08:18 UTC, flexsurfer commented on src/status_im/ios/core.cljs
>             (notifications/request-permissions)
indentation

2017-12-29 08:18 UTC, flexsurfer commented on src/status_im/android/core.cljs
>             (notifications/on-refresh-fcm-token)
indentation

2017-12-29 08:18 UTC, flexsurfer commented on src/status_im/utils/notifications.cljs
>                     (log/debug "get-fcm-token: " x)
indentation

2017-12-29 17:34 UTC, taylorjdawson commented
Alrighty fixed the indentation, thanks!

2018-01-02 08:10 UTC, flexsurfer approved these changes

2018-01-02 11:18 UTC, oskarth approved these changes

2018-01-04 12:36 UTC, asemiankevich commented
I have tested this with 2 builds. I built it with flag = 1 in Jenkins and flag = 0 . I am able to receive PNs in both cases so I assume there is no more impact from the mentioned flag. However the flag is still visible in Jenkins build configuration which is not in scope of this PR (as I got from @oskarth ) and this setting will be removed in one of future PRs. 


Branch: taylorjdawson:feature/remove-notifications-wip-enabled-#2813
Android: https://i.diawi.com/t1QD5d
iOS: https://i.diawi.com/s8vWvD

@taylorjdawson I believe you need to resolve some conflicts before the PR is merged

2018-01-04 12:48 UTC, andytudhope commented
Yeah @taylorjdawson - please just rebase onto latest develop to solve these conflicts and then we will merge and award here 👍

2018-01-04 12:50 UTC, oskarth commented
>  However the flag is still visible in Jenkins build configuration which is not in scope of this P

Reminder: Remove from Jenkins as this PR is merged (after conflicts solved)

2018-01-05 06:55 UTC, merged