Addresses the ClassNotFoundException issue
status-im/status-react pull request #3101
Opened 2018-01-21 05:00 UTC by mehrdadrafiee

fixes the `ClassNotFoundException` issue explained here: https://github.com/bhauman/lein-figwheel/issues/612

### Summary:
Running `brew cask install java` command installs the [latest JDK](https://wiki.status.im/Building_Status#Requirements) as one of the requirements, which results in installing Java 9. As explained [here](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j?answertab=votes#tab-top): 
>Java 9 introduces the concepts of modules, and by default the `java.se` aggregate module is available on the class path (or rather, module path). As the name implies, the `java.se` aggregate module does not include the Java EE APIs that have been traditionally bundled with Java 6/7/8.
The JAXB APIs are considered to be Java EE APIs, and therefore are no longer contained on the default class path in Java SE 9. These Java EE APIs that were provided in JDK 6/7/8 are still in the JDK, but they just aren't on the class path by default. The extra Java EE APIs are provided in the following modules:

```
java.activation
java.corba
java.transaction
java.xml.bind  << This one contains the JAXB APIs
java.xml.ws
java.xml.ws.annotation
```
Adding `:jvm-opts ["--add-modules" "java.xml.bind"]` to the `project.clj` file would make JAXB APIs available at runtime and solve the issue.

status: ready

2018-01-21 05:02 UTC, mehrdadrafiee commented
test

2018-01-22 19:42 UTC, rasom requested changes
Hey @mehrdadrafiee, thanks for contribution!

tbh, i'm not sure that we want to break Java 8 support
https://github.com/bhauman/lein-figwheel/issues/612#issuecomment-352363961

seems that upgrading to the latest version of clojurescript (`1.9.946`) should help, because it contains fix for this issue
https://github.com/clojure/clojurescript/commit/544c1b77d76d48f234cdb03746ea993158c46aff

so better to try newer clojurescript

2018-01-22 19:46 UTC, rasom commented
hm, maybe i'm wrong, this commit was added to master but `1.9.946` is older. Anyway better to find the way to make it work with java 8

2018-02-05 06:29 UTC, oskarth commented
Closing PR due to inactivity. Feel free to reopen PR if you feel like this was in error.

2018-02-05 06:29 UTC, closed without merging