Refactor timestamp
status-im/status-react pull request #3385
Opened 2018-02-20 15:15 UTC by voxlet

[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

Fixes #3304

### Summary:

[comment]: # (Summarise the problem and how the pull request solves it)

- rename utils.datetime/now-ms to timestamp
- replace protocol.web3.utils/timestamp with utils.datetime/timestamp
- replace cljs-time with inst-ms in timestamp

### Review notes

Getting the current timestamp seemed to be a common enough use case, so I kept the utils.datetime version (as it is higher up the hierarchy as a util namespace) instead of replacing all calls of now-ms/timestamp with `(inst-ms (js/Date.))`.

For the name change from `now-ms` to `timestamp`:
- `timestamp` feels more descriptive of intent
- we can visualize impacted call sites in diff

### Steps to test:

Interleave quick calls to the old and new implementations, and check the results monotonically increase. This is crude, but should be good enough to prove there is no behavior change between the two.

In REPL:
```
(do
    (defn old-timestamp []
      (cljs-time.coerce/to-long (cljs-time.core/now)))

    ;; interleave calls eagerly with reduce
    (->> (reduce
           (fn [z _]
             (into z [(old-timestamp) (status-im.utils.datetime/timestamp)]))
           [] (range 100000))
         (apply <=)))
=> true
```

status: ready

2018-02-21 07:18 UTC, jeluard approved these changes

2018-02-22 05:58 UTC, voxlet commented
Rebased to develop.
Also noticed there was another timestamp function in utils.random, so I replaced these as well.

2018-02-22 07:17 UTC, jeluard commented
@yenda @janherich What do you think?

2018-02-24 23:54 UTC, status-open-bounty commented
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xa1caf6e51346aa04e4ca353c4f6a3b884ca5e8cdfe9fc5952262074d74864243](https://etherscan.io/tx/0xa1caf6e51346aa04e4ca353c4f6a3b884ca5e8cdfe9fc5952262074d74864243)

2018-03-02 07:49 UTC, flexsurfer requested changes

2018-03-02 07:49 UTC, flexsurfer commented on src/status_im/chat/handlers.cljs
> +                   :timestamp   (datetime/timestamp)}]
please use `(:now cofx)` here

2018-03-02 07:49 UTC, flexsurfer commented on src/status_im/chat/handlers.cljs
> +     :timestamp   (datetime/timestamp)
please pass `now` from outside the function , take it from `cofx`

2018-03-02 07:49 UTC, flexsurfer commented on src/status_im/data_store/realm/browser.cljs
> +    [status-im.utils.datetime :refer [timestamp]])
please use `:as` instead `:refer`

2018-03-02 07:49 UTC, flexsurfer commented on src/status_im/data_store/realm/chats.cljs
> +            [status-im.utils.datetime :refer [timestamp]]
please use :as instead :refer

2018-03-02 07:49 UTC, flexsurfer commented on src/status_im/data_store/realm/chats.cljs
> +            [status-im.utils.datetime :refer [timestamp]]
or looks like it's not used here, so remove please

2018-03-02 07:49 UTC, flexsurfer commented on src/status_im/data_store/realm/browser.cljs
> +    [status-im.utils.datetime :refer [timestamp]])
or looks like it's not used here, so remove please

2018-03-02 07:49 UTC, flexsurfer commented on src/status_im/data_store/realm/contact_groups.cljs
> +            [status-im.utils.datetime :refer [timestamp]])
not used, remove please

2018-03-02 07:49 UTC, flexsurfer commented on src/status_im/ui/screens/group/events.cljs
> +                     :timestamp   (datetime/timestamp)
please use `(:now cofx)` here

2018-03-02 07:49 UTC, flexsurfer commented on src/status_im/utils/gfycat/core.cljs
> +            [status-im.utils.datetime :refer [timestamp]]))
please use `:as` instead `:refer`

2018-03-02 12:23 UTC, voxlet commented
@flexsurfer Thank you for the feedback, fixed

2018-03-02 12:26 UTC, jeluard commented
@voxlet Please sqush your commits too! Thanks

2018-03-04 12:18 UTC, voxlet commented
@jeluard Done! Should I be squashing on every fix, while in review? (I think I remember reading something in the wiki instructing not to)

2018-03-04 14:34 UTC, flexsurfer approved these changes

2018-03-05 05:15 UTC, flexsurfer commented
@voxlet could you please resolve conflicts. thanks

2018-03-05 05:20 UTC, yenda commented
@flexaurfer I think it can wait it will probably not be tested before the end of the off-site and there might be more conflicts then

2018-03-07 12:59 UTC, voxlet commented
Thanks, went ahead and resolved. Will gladly fix again when needed.

2018-03-14 15:24 UTC, asemiankevich commented
@voxlet can you please rebase once more ?

2018-03-15 11:25 UTC, lukaszfryc commented
Looks good to me!

I tested different types of chats (including notifications) and wallet. I didn't notice anything strange.

2018-03-15 11:53 UTC, merged