Support platform specific :uppercase as a text prop
status-im/status-react pull request #3437
Opened 2018-02-25 10:47 UTC by dongwoo-kim

Fixes #3379 

### Summary:
- Remove all of the conditional code using platform specific `:uppercase`.
- Support this feature inside of the `text` component so that it can be used like this.
```clj
[text {:uppercase? true} "Text"]  ;; for Android
[text {:force-uppercase? true} "Text"] ;; for both ios and Android
```

status: ready

2018-02-25 20:02 UTC, jeluard approved these changes

2018-02-25 20:02 UTC, jeluard commented on src/status_im/ui/screens/discover/styles.cljs
>  ;; NOTE(oskarth): Hacky use of defstyle to get
Can you remove this comment too?

2018-02-25 20:02 UTC, jeluard commented on src/status_im/ui/screens/discover/styles.cljs
>  ;; NOTE(goranjovic): Another hacky use of defstyle to get
Same here

2018-02-26 01:12 UTC, dongwoo-kim commented
@jeluard Applied and squashed!

2018-02-26 08:31 UTC, flexsurfer commented
hey @dongwoo-kim thanks for the contribution, looks like some changes not related to this PR, could you please rebase onto latest develop?

2018-02-26 11:51 UTC, dongwoo-kim commented
@flexsurfer Thanks, I've just done it.

2018-02-26 12:30 UTC, flexsurfer commented
@dongwoo-kim  thanks, you need to delete `platform-specific` from ios/platform and android/platform

2018-02-27 12:15 UTC, janherich commented
Great work @dongwoo-kim ! Can you please rebase on current develop, so we can move this to QA ?

2018-02-27 13:27 UTC, dongwoo-kim commented
@flexsurfer @janherich deleted remaining `:uppercase`, rebased on develop, and changed some additional code.

2018-02-28 10:23 UTC, flexsurfer approved these changes

2018-02-28 10:23 UTC, flexsurfer commented
thanks @dongwoo-kim looks good!

2018-02-28 10:45 UTC, alwx requested changes

2018-02-28 10:45 UTC, alwx commented on src/status_im/ui/components/react.cljs
> +            ts))))))
I think that the readability is an issue here. And there are plenty of ways of improving it. For instance, you can easily move the `map` to a separate function, and replace all this `let` with something really simple, like this:
```
(->> (conj ts t)
     (transform-to-upper-case opts)
     (concat [text-class (add-font-style :style opts)])
     (vec))
```

2018-03-01 07:03 UTC, jeluard commented
@dongwoo-kim Have you noticed @alwx comment? If you could give it a try that would be awesome!

2018-03-01 09:21 UTC, flexsurfer commented
@dongwoo-kim  please check, there are new `:uppercase?` usage added, should be reworked too, thanks

2018-03-03 15:05 UTC, dongwoo-kim commented
@jeluard @alwx Applied your feedback. Please check if it looks OK.
@flexsurfer Fixed two more `platform/android?` usages.

2018-03-12 13:57 UTC, alwx approved these changes

2018-03-12 13:58 UTC, alwx commented
Awesome, @dongwoo-kim. Thank you!

2018-03-13 15:33 UTC, jeluard commented
@dongwoo-kim Could your rebase your PR?

2018-03-14 14:21 UTC, dongwoo-kim commented
@alwx You're welcome. Thanks for your feedback.
@jeluard Sure, it's done.

2018-03-15 09:46 UTC, lukaszfryc commented
I have smoke tested Android and iOS apps and they both look fine!

2018-03-15 09:51 UTC, flexsurfer commented
@dongwoo-kim sorry, could you rebase one more time, and please check if there new usages of uppercase appeared, thanks

2018-03-15 14:19 UTC, dongwoo-kim commented
@flexsurfer No problem. Changed one more usage of uppercase.

2018-03-15 14:22 UTC, merged

2018-03-15 14:42 UTC, flexsurfer commented
thanks @dongwoo-kim amazing work