Feature/Introduced onboarding sign in
status-im/status-react pull request #3470
Opened 2018-02-28 11:16 UTC by flexsurfer

fixes #3326

2018-02-28 11:26 UTC, goranjovic approved these changes

2018-02-28 11:38 UTC, janherich commented
@flexsurfer  After this PR is merged, will it mean that console chat is not shown at all, meaning the one can't issue `/faucet` command ? That's big bummer for anyone developing wallet/send-command functionality, I think it's crucial that we will still have the option to easily get testnet ETH for testing.

2018-02-28 11:49 UTC, goranjovic commented
@flexsurfer @janherich I thought it will be shown if you set Dev mode somewhere, no?

2018-02-28 12:17 UTC, janherich commented
@flexsurfer @goranjovic I'm concerned about this:
https://github.com/status-im/status-react/pull/3470/files#diff-50b2d2f85046da6681844adb5e140a06R61

2018-02-28 12:51 UTC, flexsurfer commented
yes @janherich you're right, i'll uncomment this after PR will be tested, because i want to merge this PR, but dev option in the profile will be implemented only in next PR

2018-02-28 13:27 UTC, jeluard requested changes
Impressive work ! 

Not a big fan of the various `:set-in`
.
Also feels like some of the styles could be merged and have some more common parts?

2018-02-28 13:27 UTC, jeluard commented on src/status_im/chat/events.cljs
> +     :dispatch-n [[:add-contacts [console/contact]]]
Why not `dispatch` ?

2018-02-28 13:27 UTC, jeluard commented on src/status_im/chat/events.cljs
> +     :save-all-contacts [console/contact]}))
Alignment?

2018-02-28 13:27 UTC, jeluard commented on src/status_im/chat/events/console.cljs
> +  (:require [status-im.constants :as const]
`constants` ?

2018-02-28 13:27 UTC, jeluard commented on src/status_im/chat/subs.cljs
> +                        (and (:is-active chat) (not= const/console-chat-id (:chat-id chat))))
Extract function for better lisibility?

2018-02-28 13:27 UTC, jeluard commented on src/status_im/ui/components/colors.cljs
> +(defn alpha [hex opacity]
Nice!

2018-02-28 13:27 UTC, jeluard commented on src/status_im/ui/components/common/common.cljs
> +            [status-im.ui.components.icons.vector-icons :as icons]
`vector-icons` ?

2018-02-28 13:27 UTC, jeluard commented on src/status_im/ui/components/common/common.cljs
> +(defn bottom-button [{:keys [label disabled? on-press forward?]}]
There is `bottom-buttons` and `button` ns already. Are those different?

2018-02-28 13:27 UTC, jeluard commented on src/status_im/ui/components/common/styles.cljs
> +  {:ios     {:shadowColor   colors/black
No camel case?

2018-02-28 13:27 UTC, jeluard commented on src/status_im/ui/components/text_input/view.cljs
> +(defn text-input-with-label [{:keys [label error style height] :as props}]
Do we still use this?

2018-02-28 13:27 UTC, jeluard commented on src/status_im/ui/components/toolbar/view.cljs
> -  ([{:keys [background-color style flat? title-centered?]}
No more centering?

2018-02-28 13:27 UTC, jeluard commented on src/status_im/ui/components/tooltip/styles.cljs
> +   :border-radius      8})
It's defined in `styles`

2018-02-28 13:27 UTC, jeluard commented on src/status_im/ui/screens/accounts/create/styles.cljs
> +   :background-color colors/white})
Alignment

2018-02-28 13:27 UTC, jeluard commented on src/status_im/ui/screens/accounts/create/views.cljs
> +            password-confirm [:get-in [:accounts/create :password-confirm]]]
Can't be simplified? Like a single sub?

2018-02-28 13:27 UTC, jeluard commented on src/status_im/ui/screens/accounts/create/views.cljs
> +        [react/view {:style styles/logo-container}
Would read better with sub-components

2018-02-28 13:27 UTC, jeluard commented on src/status_im/ui/screens/accounts/events.cljs
> +    {:db (update db :accounts/create assoc :step :account-creating :error nil)
Alignment

2018-02-28 13:27 UTC, jeluard commented on src/status_im/ui/screens/accounts/events.cljs
> +    (-> {:db (assoc-in db [:accounts/create :show-welcome?] true)
Alignment

2018-02-28 13:27 UTC, jeluard commented on src/status_im/ui/screens/accounts/login/views.cljs
> +                 :numberOfLines 1}
No kebab case?

2018-02-28 13:27 UTC, jeluard commented on src/status_im/ui/screens/accounts/login/views.cljs
> +                                (re-frame/dispatch [:set-in [:accounts/login :error] ""]))
Can't be a dedicated handler for both info?

2018-02-28 13:27 UTC, jeluard commented on src/status_im/ui/screens/accounts/styles.cljs
> +   :color          common/color-black})
`colors/black`

2018-02-28 13:27 UTC, jeluard commented on src/status_im/ui/screens/intro/styles.cljs
> +   :ios         {:line-height 28
Alignment

2018-02-28 13:27 UTC, jeluard commented on src/status_im/ui/screens/intro/styles.cljs
> +   :android     {:font-size 24
Alignment

2018-02-28 13:27 UTC, jeluard commented on src/status_im/ui/screens/usage_data/styles.cljs
> +   :ios         {:line-height 28
Alignment

2018-02-28 13:27 UTC, jeluard commented on src/status_im/ui/screens/usage_data/styles.cljs
> +   :android     {:font-size 24
Alignment

2018-02-28 13:27 UTC, jeluard commented on src/status_im/ui/screens/wallet/transactions/views.cljs
> +    [react/view {:style {:flex 1 :background-color :white}}
Extract as style?

2018-02-28 19:13 UTC, yevh-berdnyk commented
Android: https://i.diawi.com/aFtrrf
iOS: https://i.diawi.com/qY18Ca

Keyboard expanded after running the app on iPhone covering OK button on the warning alert
![img_ba5cddfed2b3-1](https://user-images.githubusercontent.com/29711298/36807072-9d05288c-1cca-11e8-8c12-a983085ca2c9.jpeg)

Recovering account: **Passphrase** instead of **Enter your seed phrase**, typo **wrords**
<img width="764" alt="screen shot 2018-02-28 at 9 03 56 pm" src="https://user-images.githubusercontent.com/29711298/36807377-7a699eec-1ccb-11e8-98a6-17d2e794ad82.png">

**Password confirmation doesn’t match password** instead of **Passwords don't match** when creating account
<img width="783" alt="screen shot 2018-02-28 at 9 08 17 pm" src="https://user-images.githubusercontent.com/29711298/36807481-cde84104-1ccb-11e8-88c3-0cc8d9b79cc2.png">

No **learn more** on Help improve Status view
<img width="765" alt="screen shot 2018-02-28 at 9 11 07 pm" src="https://user-images.githubusercontent.com/29711298/36807674-2f3ddd6a-1ccc-11e8-9f1b-8c6822e6bc92.png">

2018-03-01 05:48 UTC, flexsurfer commented
@jeluard  thanks, done!

2018-03-01 05:49 UTC, flexsurfer commented
@yevh-berdnyk 
alert - fixed
typo - fixed
learn more - will be implemented later
all text will be revisited
thanks

2018-03-01 07:24 UTC, jeluard approved these changes

2018-03-01 08:55 UTC, janherich approved these changes

2018-03-01 09:16 UTC, merged