[Fix #3394] Add accessibility labels for Wallet screens
status-im/status-react pull request #3517
Opened 2018-03-04 03:32 UTC by foopang

### Summary:

Add accessibility labels for Wallet screens

status: wip

2018-03-12 11:15 UTC, lukaszfryc commented
@jeluard could you quickly check if the code looks right? Also, see related pull requests #3528 #3529

2018-03-12 12:56 UTC, jeluard requested changes

2018-03-12 12:56 UTC, jeluard commented on src/status_im/ui/components/toolbar/view.cljs
> +                     (dissoc props :style :handler :disabled? :uppercase?))
Is this only for `accessibility-label`?

2018-03-12 12:56 UTC, jeluard commented on src/status_im/ui/screens/wallet/transactions/views.cljs
> +  ([label value extra-value & [value-accessibility-label extra-value-accessibility-label]]
I'd rather have a single label base and have both labels derive from it.

2018-03-12 12:58 UTC, jeluard commented
@lukaszfryc Looks mostly good!
Is there some structure / logic in those labels? Are reusable components being labeled with some pattern?

2018-03-12 13:13 UTC, lukaszfryc commented
@jeluard I want to use `-button` suffix for clickable elements like `send-transaction-button`. Similar `-text` for text,`-input` for input fields. See more in #3394.

Reusable components like list items should follow the same pattern (for instance `transaction-history-item`). It maybe helpful if we include index of item (`transaction-history-item-1`) but it's not necessary.

2018-03-12 15:01 UTC, yevh-berdnyk commented
Send transaction -> Choose recipient -> Recent recipients: contact-name-text label is not added
<img width="795" alt="screen shot 2018-03-12 at 3 00 55 pm" src="https://user-images.githubusercontent.com/29711298/37290658-83c85200-2615-11e8-837b-30e9dd01e5e9.png">

Send transaction. Recipient was chosen: recipient-name-text label is added to recipient item instead of the name text
<img width="744" alt="screen shot 2018-03-12 at 4 54 51 pm" src="https://user-images.githubusercontent.com/29711298/37290933-32bfa3b2-2616-11e8-83cf-51366589a2cd.png">

The same on New transaction view:
<img width="833" alt="screen shot 2018-03-12 at 4 07 35 pm" src="https://user-images.githubusercontent.com/29711298/37290953-4302b8a4-2616-11e8-9a04-edc76c9faf03.png">

Transaction amount and currency texts have no labels on both transaction list and transaction details
<img width="753" alt="screen shot 2018-03-12 at 4 31 33 pm" src="https://user-images.githubusercontent.com/29711298/37291183-caa37aa0-2616-11e8-8947-da8cd310be59.png">
<img width="760" alt="screen shot 2018-03-12 at 4 36 59 pm" src="https://user-images.githubusercontent.com/29711298/37291188-cb6d12e8-2616-11e8-8410-2613a595fe43.png">
<img width="746" alt="screen shot 2018-03-12 at 4 43 29 pm" src="https://user-images.githubusercontent.com/29711298/37291190-ccb740ba-2616-11e8-8814-97326d0af796.png">

After recovering account when sender or recipient name is not displayed for transaction sender-name-text label is pinned to sender address text
<img width="751" alt="screen shot 2018-03-12 at 4 39 32 pm" src="https://user-images.githubusercontent.com/29711298/37291234-e8be13ba-2616-11e8-9417-8228d53441cc.png">

2018-03-13 02:11 UTC, foopang commented
@yevh-berdnyk Thanks for checking! It's mostly fixed now. but **Transaction amount and currency texts have no labels on both transaction list and transaction details** this is not true because those labels were added to child `TextView`, if you expand the parent `TextView`, you will find accessibility labels for child `TextView`.

![screenshot from 2018 03 13 08 46 36](https://user-images.githubusercontent.com/4666757/37318634-87ea57b6-26a6-11e8-97b3-25b023e1adf6.png)


@jeluard I've updated for `details-list-row`, second and third function arguments can now pass a vector of props data with value or simple text value.

2018-03-13 08:43 UTC, jeluard commented
@yevh-berdnyk What is the tool you are using?

2018-03-13 08:50 UTC, lukaszfryc commented
@jeluard it's most probably the Appium Inspector or just Appium Driver itself.

2018-03-15 12:22 UTC, jeluard commented
@foopang Please rebase!

2018-03-15 12:22 UTC, jeluard approved these changes

2018-03-15 12:46 UTC, foopang commented
@jeluard rebased.

2018-03-15 12:48 UTC, yevh-berdnyk commented
@jeluard , @lukaszfryc yes, I used Appium inspector

2018-03-15 12:59 UTC, merged

2018-03-15 12:59 UTC, jeluard commented
@foopang Thanks!