[WIP #3575] Create clj script
status-im/status-react pull request #3608
Opened 2018-03-17 01:29 UTC by foopang

### Summary:
Fix #3575
Create clj script with the following commands:

**Start figwheel + CLJS REPL**
`clj -R:repl build.clj figwheel [build-ids]`

`[build-ids]` arg is optional, a comma-sparated list of build ids, i.e. `android,ios`

**Start figwheel + nREPL**
`clj -R:repl build.clj figwheel [build-ids] [port-number]`

`[port-number]` to provide that for nREPL so that you can connect to nREPL from your editor.

**Compile CLJS**
`clj build.clj compile [env] [build-id] [type]`
`[env]` is required, `[build-id]` and `[type]` args are optional, if `[build-id]` is omitted, this command will compile all builds from the specified `[env]`. `[type]` is the build type - value could be `once` or `watch`, default to `once` if not explicitly set.

I don't know why compile optimizations is not working right now, so compiling for `:prod` is broken at the moment. Will see how to fix it.

**Run tests**
`clj -R:test build.clj test [build-id]`
`[build-id]` arg is required - value could be `test`, `protocol` or `env-dev-utils`. It will compile then run the tests once.

status: wip

2018-03-19 09:40 UTC, dmitryn commented
@foopang thanks for contribution!
I'm having error while starting figwheel for android (don't have this on ios though):
```
[12:19:04] status-react git:(f792ad42*) $ clj -R:repl build.clj figwheel android
readline: ~/.inputrc: line 19: -o: unknown variable name
readline: ~/.inputrc: line 19: -o: unknown variable name
Figwheel: Starting server at http://0.0.0.0:3449
Figwheel: Watching build - android
Compiling "target/android/app.js" from ["react-native/src" "src" "env/dev"]...
Failed to compile "target/android/app.js" in 56.272 seconds.
----  Exception    ----



----  Exception Stack Trace  ----

java.lang.NullPointerException: null
 at java.util.regex.Matcher.getTextLength (Matcher.java:1283)
    java.util.regex.Matcher.reset (Matcher.java:309)
    java.util.regex.Matcher.<init> (Matcher.java:229)
    java.util.regex.Pattern.matcher (Pattern.java:1093)
    clojure.core$re_matcher.invokeStatic (core.clj:4796)
    clojure.core$re_matches.invokeStatic (core.clj:4826)
    clojure.core$re_matches.invoke (core.clj:4826)
    cljs.util$compiled_by_version.invokeStatic (util.cljc:42)
    cljs.util$compiled_by_version.invoke (util.cljc:39)
    cljs.closure$compile_from_jar.invokeStatic (closure.clj:586)
    cljs.closure$compile_from_jar.invoke (closure.clj:579)
    cljs.closure$eval6976$fn__6977.invoke (closure.clj:619)
    cljs.closure$eval6906$fn__6907$G__6895__6914.invoke (closure.clj:493)
    cljs.closure$compile_sources$iter__7094__7098$fn__7099.invoke (closure.clj:954)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:49)
    clojure.lang.Cons.next (Cons.java:39)
    clojure.lang.RT.next (RT.java:706)
    clojure.core$next__5108.invokeStatic (core.clj:64)
    clojure.core$dorun.invokeStatic (core.clj:3134)
    clojure.core$doall.invokeStatic (core.clj:3140)
    clojure.core$doall.invoke (core.clj:3140)
    cljs.closure$compile_sources.invokeStatic (closure.clj:950)
    cljs.closure$compile_sources.invoke (closure.clj:939)
    cljs.closure$build.invokeStatic (closure.clj:2596)
    cljs.closure$build.invoke (closure.clj:2507)
    cljs.build.api$build.invokeStatic (api.clj:205)
    cljs.build.api$build.invoke (api.clj:189)
    figwheel_sidecar.components.cljs_autobuild$cljs_build.invokeStatic (cljs_autobuild.clj:28)
    figwheel_sidecar.components.cljs_autobuild$cljs_build.invoke (cljs_autobuild.clj:27)
    figwheel_sidecar.build_middleware.injection$hook$fn__29642.invoke (injection.clj:197)
    figwheel_sidecar.components.cljs_autobuild$notify_command_hook$fn__29962.invoke (cljs_autobuild.clj:68)
    figwheel_sidecar.components.cljs_autobuild$figwheel_start_and_end_messages$fn__29954.invoke (cljs_autobuild.clj:48)
    figwheel_sidecar.components.cljs_autobuild$catch_print_hook$fn__29994.invoke (cljs_autobuild.clj:185)
    figwheel_sidecar.components.cljs_autobuild$open_urls_hook$fn__29986.invoke (cljs_autobuild.clj:141)
    figwheel_sidecar.build_middleware.stamp_and_clean$hook$fn__29939.invoke (stamp_and_clean.clj:66)
    figwheel_sidecar.components.cljs_autobuild$color_output$fn__29966.invoke (cljs_autobuild.clj:79)
    figwheel_sidecar.components.cljs_autobuild.CLJSAutobuild.start (cljs_autobuild.clj:255)
    com.stuartsierra.component$eval28127$fn__28128$G__28117__28130.invoke (component.cljc:5)
    com.stuartsierra.component$eval28127$fn__28128$G__28116__28133.invoke (component.cljc:5)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.lang.Var.applyTo (Var.java:702)
    clojure.core$apply.invokeStatic (core.clj:659)
    clojure.core$apply.invoke (core.clj:652)
    com.stuartsierra.component$try_action.invokeStatic (component.cljc:117)
    com.stuartsierra.component$try_action.invoke (component.cljc:116)
    com.stuartsierra.component$update_system$fn__28186.invoke (component.cljc:139)
    clojure.lang.ArraySeq.reduce (ArraySeq.java:114)
    clojure.core$reduce.invokeStatic (core.clj:6747)
    clojure.core$reduce.invoke (core.clj:6730)
    com.stuartsierra.component$update_system.invokeStatic (component.cljc:135)
    com.stuartsierra.component$update_system.doInvoke (component.cljc:129)
    clojure.lang.RestFn.invoke (RestFn.java:445)
    com.stuartsierra.component$start_system.invokeStatic (component.cljc:163)
    com.stuartsierra.component$start_system.invoke (component.cljc:155)
    com.stuartsierra.component$start_system.invokeStatic (component.cljc:161)
    com.stuartsierra.component$start_system.invoke (component.cljc:155)
    com.stuartsierra.component.SystemMap.start (component.cljc:178)
    com.stuartsierra.component$eval28127$fn__28128$G__28117__28130.invoke (component.cljc:5)
    com.stuartsierra.component$eval28127$fn__28128$G__28116__28133.invoke (component.cljc:5)
    clojure.lang.Atom.swap (Atom.java:37)
    clojure.core$swap_BANG_.invokeStatic (core.clj:2344)
    clojure.core$swap_BANG_.invoke (core.clj:2337)
    figwheel_sidecar.system.FigwheelSystem.start (system.clj:119)
    com.stuartsierra.component$eval28127$fn__28128$G__28117__28130.invoke (component.cljc:5)
    com.stuartsierra.component$eval28127$fn__28128$G__28116__28133.invoke (component.cljc:5)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.lang.Var.applyTo (Var.java:702)
    clojure.core$apply.invokeStatic (core.clj:659)
    clojure.core$apply.invoke (core.clj:652)
    com.stuartsierra.component$try_action.invokeStatic (component.cljc:117)
    com.stuartsierra.component$try_action.invoke (component.cljc:116)
    com.stuartsierra.component$update_system$fn__28186.invoke (component.cljc:139)
    clojure.lang.ArraySeq.reduce (ArraySeq.java:109)
    clojure.core$reduce.invokeStatic (core.clj:6747)
    clojure.core$reduce.invoke (core.clj:6730)
    com.stuartsierra.component$update_system.invokeStatic (component.cljc:135)
    com.stuartsierra.component$update_system.doInvoke (component.cljc:129)
    clojure.lang.RestFn.invoke (RestFn.java:445)
    com.stuartsierra.component$start_system.invokeStatic (component.cljc:163)
    com.stuartsierra.component$start_system.invoke (component.cljc:155)
    com.stuartsierra.component$start_system.invokeStatic (component.cljc:161)
    com.stuartsierra.component$start_system.invoke (component.cljc:155)
    com.stuartsierra.component.SystemMap.start (component.cljc:178)
    figwheel_sidecar.system$start_figwheel_system$fn__30291.invoke (system.clj:668)
    figwheel_sidecar.system$dispatch_system_component_errors.invokeStatic (system.clj:654)
    figwheel_sidecar.system$dispatch_system_component_errors.invoke (system.clj:652)
    figwheel_sidecar.system$start_figwheel_system.invokeStatic (system.clj:668)
    figwheel_sidecar.system$start_figwheel_system.invoke (system.clj:666)
    figwheel_sidecar.system$start_figwheel_BANG__STAR_.invokeStatic (system.clj:703)
    figwheel_sidecar.system$start_figwheel_BANG__STAR_.invoke (system.clj:689)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.core$apply.invokeStatic (core.clj:657)
    clojure.core$apply.invoke (core.clj:652)
    figwheel_sidecar.system$start_figwheel_BANG_.invokeStatic (system.clj:747)
    figwheel_sidecar.system$start_figwheel_BANG_.doInvoke (system.clj:705)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:657)
    clojure.core$apply.invoke (core.clj:652)
    figwheel_sidecar.repl_api$start_figwheel_BANG_$fn__30308.invoke (repl_api.clj:29)
    clojure.lang.AFn.applyToHelper (AFn.java:154)
    clojure.lang.AFn.applyTo (AFn.java:144)
    clojure.lang.Var.alterRoot (Var.java:305)
    clojure.core$alter_var_root.invokeStatic (core.clj:5450)
    clojure.core$alter_var_root.doInvoke (core.clj:5445)
    clojure.lang.RestFn.invoke (RestFn.java:425)
    figwheel_sidecar.repl_api$start_figwheel_BANG_.invokeStatic (repl_api.clj:29)
    figwheel_sidecar.repl_api$start_figwheel_BANG_.doInvoke (repl_api.clj:26)
    clojure.lang.RestFn.invo [...]

2018-03-19 09:45 UTC, dmitryn commented
@foopang also, it would be helpful to have sort of help:
`clj build.clj help` to show all available arguments and options.

2018-03-19 09:46 UTC, dmitryn requested changes
Please add `help` command to show available commands and options.

2018-03-19 12:59 UTC, foopang commented
@dmitryn Thanks for checking! I don't have such error as you described. May I look inside your `~/.inputrc` file to see if it may have caused the error.

2018-03-20 13:49 UTC, jeluard commented
@foopang Great work! `clojurescript` will have a new release early next week (if all goes well). Let's wait for it and integrate all the nice new features?

In the meantime WDYT about #3398 ?
Ultimately I'd like to replace `re-natal` with this library that would be called directly from the `clj` script, making changes only when relevant.

2018-03-20 13:58 UTC, dmitryn commented
@foopang i've commented line in inputrc causing "unknown variable" warning (last line), here is my inputrc:
```
$ cat ~/.inputrc
"\e[1~": beginning-of-line
"\e[4~": end-of-line
"\e[5~": history-search-backward
"\e[6~": history-search-forward
"\e[3~": delete-char
"\e[2~": quoted-insert
"\e[5C": forward-word
"\e[5D": backward-word
"\e\e[C": forward-word
"\e\e[D": backward-word

set completion-ignore-case on
set expand-tilde on
set convert-meta off
set input-meta on
set output-meta on
set show-all-if-ambiguous on
set visible-stats on
# set -o vi
```

And i'm still having NPE while running `clj -R:repl build.clj figwheel android`

2018-03-20 14:35 UTC, dmitryn commented
@foopang i've just got same NPE error with `lein figwheel-repl android` so it's not related to using `build.clj` script, please ignore it.

2018-03-20 14:40 UTC, foopang commented
@jeluard Interesting! I will see how best to implement re-natal features in the CLJ script.

@dmitryn Thanks for clarifying! I have no idea what may have caused that error though, sorry.

2018-03-20 14:43 UTC, jeluard commented
@foopang Cool! Please make that a separate ns, or better a separate lib so that it can be improved and reused by the community!

2018-03-26 13:28 UTC, jeluard commented
@foopang ClojureScript `1.10.238` has now been [released](https://clojurescript.org/news/2018-03-26-release). Maybe we could give it a try?

2018-03-27 01:31 UTC, foopang commented
@dmitryn @jeluard Updated with `help` command. And bumped ClojureScript version to `1.10.238`. Let me know if it is fine now.

2018-03-27 06:29 UTC, jeluard commented
@foopang Great thansk! No particular issue with latest ClojureScript?

2018-03-27 11:20 UTC, foopang commented
@jeluard No particular issue with latest ClojureScript AFAIK.

2018-03-27 13:17 UTC, dmitryn approved these changes
Have tried all the commands, don't see any issues.

2018-03-27 13:19 UTC, merged