Align toolbar titles to the left for network & offline-messaging screens
status-im/status-react pull request #3800
Opened 2018-04-09 02:45 UTC by criwo

Fixes #3748 

### Summary:

Toolbar titles have been aligned to the left for network & offline-messaging screens

### Steps to test:
- Open Status
- Go to profile
- Advanced -> settings && Advanced -> Offline messages
- Check titles alignment

status: ready

2018-04-09 06:42 UTC, jeluard requested changes
@criwo Thanks for contributing! Actually all headers should have title aligned left on android. So this should be done directly in `toolbar` component. Sorry for not being clear enough!

2018-04-09 09:06 UTC, criwo commented
@jeluard Oh, that makes it easier! I'll make the change in a moment

2018-04-09 09:37 UTC, jeluard approved these changes

2018-04-09 22:14 UTC, rasom approved these changes

2018-04-10 13:09 UTC, lukaszfryc commented
I've noticed slightly different margin between header and first item in Home vs Profile:

**Home**
<img src="https://user-images.githubusercontent.com/7532782/38558526-b352b3ea-3cd0-11e8-961a-e1b47a672fd1.png" width="300">

**Profile**
<img src="https://user-images.githubusercontent.com/7532782/38558585-e224e8b4-3cd0-11e8-8e2a-0b7bef668a26.png" width="300">


@denis-sharypin? Shouldn't be unified? I like the Home margin better (has more space).

2018-04-10 16:22 UTC, denis-sharypin commented
This margin should be 12 px if we are mesauring from circle. In profile setting looks like it's smaller.
<img width="700" alt="screenshot 2018-04-10 18 22 03" src="https://user-images.githubusercontent.com/6559881/38569647-1b0dcc5c-3cec-11e8-8589-7e8da815be8c.png">

2018-04-10 16:26 UTC, lukaszfryc commented
And the icon should have 12px margin:
<img src="https://user-images.githubusercontent.com/7532782/38569815-9c3c9c5e-3cec-11e8-95cc-ef495e393bb9.png" width="300">

@criwo could you check both margins?

2018-04-11 06:59 UTC, criwo commented
Sure :+1: I'll check it tonight

2018-04-12 23:19 UTC, ghikio commented
@jeluard I've been trying to figure out where are that space between header and items defined, but I'm afraid I can't find a way to modify it. Could you give me a hand with this?

2018-04-13 06:31 UTC, jeluard commented
@nocriw When I don't know what introduces incorrect styling I usually use this [tool](https://github.com/facebook/react-devtools). Pretty easy to find the root cause and make dynamic changes then.

2018-04-18 11:11 UTC, nocriw commented
Thanks, amazing tool! :)

@denis-sharypin @lukaszfryc It looks like the top margin for the button is actually 12px
![image](https://user-images.githubusercontent.com/20615416/38928501-5521126e-4309-11e8-8275-11b912282227.png)

2018-04-18 14:54 UTC, lukaszfryc commented
@denis-sharypin wdyt?

2018-04-18 15:05 UTC, denis-sharypin commented
Good then

2018-04-19 06:37 UTC, nocriw commented
Should be merged then?

2018-04-19 07:19 UTC, lukaszfryc commented
I think so. @jeluard?

2018-04-19 07:21 UTC, jeluard commented on src/status_im/ui/screens/network_settings/views.cljs
> +     [toolbar/simple-toolbar (i18n/label :t/network-settings)]
Why this change?

2018-04-19 07:22 UTC, jeluard commented
@nocriw Sure! Do you mind rolling back the two noop changes you introduced related to line breaks? Sorry I missed that somehow!

2018-04-19 08:23 UTC, ghikio commented
@jeluard should be okay now! That was a mistake of a newbie fighting with git :)

2018-04-19 08:36 UTC, merged