[#3852] Back button from new chat goes to home screen
status-im/status-react pull request #3859
Opened 2018-04-13 01:27 UTC by kwingram25

Fixes #3852 

### Summary:
- Extends replace-view to allow popping multiple views
- Newly created chat can navigate back to home screen immediately 

### Steps to test:
- Open Status
- Log in, create new chat from home screen
- Tap back button
- View should navigate to home screen instead of "New" options menu

Status: Ready

2018-04-13 06:13 UTC, jeluard commented
@kwingram25 Please resolve conflicts

2018-04-13 06:18 UTC, jeluard submitted a review, later dismissed

2018-04-13 06:18 UTC, jeluard commented on src/status_im/ui/screens/navigation.cljs
> +(defn replace-views [view-id depth {:keys [db]}]
Can you add some doc for the method? Also why `views` ?

2018-04-13 06:18 UTC, jeluard commented on src/status_im/ui/screens/navigation.cljs
> +  (loop [stack' stack n times]
I'd rather have `new-stack` than `stack`

2018-04-13 06:18 UTC, jeluard commented on src/status_im/ui/screens/navigation.cljs
> +  (loop [stack' stack n times]
Also could be worth moving to `utils` and have a test.
Or might be worth considering `subvec` or `subseq`.

2018-04-13 06:18 UTC, jeluard commented on src/status_im/chat/events.cljs
> +                       (navigation/replace-views :chat 2)
Add a comment describing `2`

2018-04-13 06:19 UTC, jeluard commented
@kwingram25 Please resolve conflicts

2018-04-13 06:45 UTC, cammellos commented on src/status_im/ui/screens/navigation.cljs
> +  (loop [stack' stack n times]
Looks like `stack` is a list, 

so to `pop` twice you can just use `drop`:

`(drop 2 l)` should be the same as `(pop (pop l))`

2018-04-13 08:26 UTC, rasom commented on src/status_im/ui/screens/navigation.cljs
> +  (let [depth  (if n n 1)
`(or n 1)`

2018-04-13 08:27 UTC, rasom commented on src/status_im/ui/screens/navigation.cljs
> +    (if (= n 0)
`(zero? n)`

2018-04-13 09:35 UTC, flexsurfer commented
thanks for contribution @kwingram25 , but i think this may be to complicated, lets just `:navigate-to-clean :home` on chat's back button

2018-04-13 09:35 UTC, flexsurfer requested changes
..

2018-04-13 22:00 UTC, kwingram25 commented
Ah good call

2018-04-16 15:47 UTC, denis-sharypin commented
Please don't merge it. The scope and requirements are no clear yet

2018-04-24 06:13 UTC, flexsurfer commented
@denis-sharypin any updates?

2018-04-24 08:20 UTC, denis-sharypin commented
@flexsurfer The confirmed scope is here:
https://github.com/status-im/status-react/issues/3852#issuecomment-383832720

2018-04-30 07:15 UTC, flexsurfer commented
@kwingram25 could you take a look? #3852 (comment)

2018-05-02 18:03 UTC, yenda commented
Hey @kwingram25 ! Thanks for all your recent contribution to the project, awesome work ! Do you mind looking at this one again ? Scope as been refined and the PR has some conflicts. Thanks!

2018-05-03 07:05 UTC, flexsurfer commented on src/status_im/ui/screens/profile/user/views.cljs
> +   [toolbar/nav-back-close-app]
why do we need this?

2018-05-03 07:06 UTC, flexsurfer requested changes

2018-05-03 07:06 UTC, flexsurfer commented on src/status_im/ui/screens/wallet/views.cljs
> +   [toolbar/nav-back-close-app {:color :white}]
why do we need this?

2018-05-03 07:07 UTC, flexsurfer commented on src/status_im/ui/screens/profile/user/views.cljs
> +   [toolbar/nav-back-close-app]
ok i understand, they meant only physical back button on android devices , we don't need to show back button in toolbar

2018-05-03 07:09 UTC, kwingram25 commented on src/status_im/ui/screens/profile/user/views.cljs
> +   [toolbar/nav-back-close-app]
Other than that I didn't see what changes were requested? It already went to home screen from any chat window

2018-05-03 07:11 UTC, flexsurfer commented on src/status_im/ui/screens/profile/user/views.cljs
> +   [toolbar/nav-back-close-app]
https://github.com/status-im/status-react/blob/develop/src/status_im/android/core.cljs#L21

2018-05-03 07:12 UTC, flexsurfer commented on src/status_im/ui/screens/profile/user/views.cljs
> +   [toolbar/nav-back-close-app]
https://github.com/status-im/status-react/blob/develop/src/status_im/android/core.cljs#L29

2018-05-03 07:13 UTC, flexsurfer commented on src/status_im/ui/screens/profile/user/views.cljs
> +   [toolbar/nav-back-close-app]
@kwingram25 so it shold work, we don't need changes for this requirements, could you please revert `nav-back-close-app`, thanks, sorry for the confusion

2018-05-03 07:18 UTC, flexsurfer commented on src/status_im/ui/screens/profile/user/views.cljs
> +   [toolbar/nav-back-close-app]
ok it will not work, we need to add exit app case

2018-05-08 07:00 UTC, rasom commented
@flexsurfer @jeluard can you guys check this PR again?

2018-05-08 07:14 UTC, flexsurfer approved these changes

2018-05-08 07:14 UTC, flexsurfer commented on src/status_im/android/core.cljs
> +                           (some #(= view-id %) [:home :wallet :my-profile])
it could be just `(#{:home :wallet :my-profile} view-id)`

2018-05-09 04:37 UTC, rasom approved these changes

2018-05-09 09:59 UTC, merged

2018-05-09 10:00 UTC, rasom commented
Thanks for contribution @kwingram25 !