[#3825] Retain chat input text on blur
status-im/status-react pull request #3860
Opened 2018-04-13 02:00 UTC by kwingram25

Fixes #3825 

### Summary:
No longer clears inputted chat text when focus lost

### Steps to test:
- Open Status
- Open chat, type in input field
- Tap elsewhere
- Text should stay in input

Status: Ready

2018-04-13 06:12 UTC, jeluard commented
@kwingram25  Please resolve conflicts

2018-04-13 06:12 UTC, jeluard approved these changes

2018-04-13 08:25 UTC, rasom commented on src/status_im/chat/views/input/input.cljs
> -                                  :on-change-text      #(do (re-frame/dispatch [:set-chat-seq-arg-input-text %])
let's not touch this line

2018-04-13 08:25 UTC, rasom commented on src/status_im/chat/views/input/input.cljs
> -  (letsubs [input-text     [:chat :input-text]
and this

2018-04-13 09:31 UTC, flexsurfer approved these changes

2018-04-24 06:14 UTC, flexsurfer commented
hey @kwingram25 can't see any changes, can we close this PR?

2018-04-24 07:41 UTC, flexsurfer requested changes
no changes in this PR

2018-04-24 07:44 UTC, kwingram25 commented
Looks like I also fixed it in #3662 which was merged

2018-04-30 07:15 UTC, closed without merging