Allow address copying in the QR code viewer screen
status-im/status-react pull request #3957
Opened 2018-04-22 02:13 UTC by go1t

fixes #3616 

### Summary:

Allows long tap to copy the wallet address from the qr code viewer screen. This is done by adding `selectable` to the text. 

The highlight box will also show when the long press is performed (and go away when anywhere else is touched).
...

status: ready

2018-04-23 16:54 UTC, pablanopete commented
@go1t Thanks for joining! Would love to learn more about your journey into Status Open bounty, mind sending me a DM when you get a chance on https://chat.status.im !

2018-04-23 22:47 UTC, go1t commented
@pablanopete DM'ed!

2018-04-26 06:37 UTC, flexsurfer commented
thanks for contribution @go1t , have you seen this https://github.com/status-im/status-react/pull/3646#issuecomment-375335646 ?

2018-04-26 21:27 UTC, go1t commented
@flexsurfer yep I have seen that. Unfortunately <Text> component cant do the highlight that would persist after long tap is released, so I had to use a bit of a state here to get that highlight to show up. But yeah it should be working

2018-04-27 13:21 UTC, jeluard requested changes

2018-04-27 13:21 UTC, jeluard commented on src/status_im/ui/components/highlight.cljs
> +    [react/touchable-without-feedback {:on-press   #(reset! highlighting false)}
Extra space?

2018-04-27 13:21 UTC, jeluard commented on src/status_im/ui/components/highlight.cljs
> +     [react/view {:flex 1}
We have `components/flex` for this.

2018-04-27 13:21 UTC, jeluard commented on src/status_im/ui/screens/profile/contact/styles.cljs
> +  {:background-color styles/color-light-blue-transparent})
Please use `colors` ns.

2018-04-27 13:21 UTC, jeluard commented on src/status_im/ui/screens/profile/contact/views.cljs
> +                  :on-long-press         #(reset! highlight-address true)}
`highlight-address?` maybe?

2018-04-27 13:21 UTC, jeluard commented on src/status_im/ui/components/qr_code_viewer/styles.cljs
> +  {:background-color styles/color-light-blue-transparent})
Please use `colors` ns

2018-04-27 13:21 UTC, jeluard commented on src/status_im/ui/screens/profile/user/views.cljs
> +     (highlight/highlight-provider (fn [highlight-address]
Why not regular reagent component usage?

2018-04-27 13:21 UTC, jeluard commented on src/status_im/ui/components/highlight.cljs
> +      (render-fn highlighting)]]))
Can't this be a regular reagent component composition?

2018-04-27 13:22 UTC, jeluard commented
@go1t Thanks for the contribution! I added some comments.
It looks to me the highlight part could be simplified using plain reagent component?

2018-04-28 22:54 UTC, go1t commented
@jeluard Thanks for the review!

Before the latest commit it was using the plain reagent component (see here: https://github.com/status-im/status-react/pull/3957/files/f83415f0e698ec804d5ec4a909dd74b35e09b136). As you can see I had to copy and paste the atom and touchable-highlight with unhighlighting behavior everywhere I need to use it. I thought it would be nicer to abstract that part out and just expose the highlighting state to the outside so that it's easier to add / remove.

Does this justify its existence a little bit, or do you prefer the plain version more?

2018-05-02 06:36 UTC, jeluard commented
@go1t You can create your function that encapsulate those, then use it with reagent square bracket syntax.
Something like `(defn highlight-provider [props children])` then directly use `[highlight-provider {}]`.

As a rule of thumb most components should follow this convention. Probably you can provide the highlight fn part of the props map.

Does that make sense?

2018-05-02 23:08 UTC, go1t commented
Ah I see what you meant now. I wasn't aware that what I was doing was akin to defining a function that returns a component instead of defining a react component (sorry a little new to clojurescript and re-agent hehe). But yeah you are right my intention was to define a component that has render as a prop. I will update the pull request soon!

2018-05-03 06:59 UTC, go1t commented on src/status_im/ui/screens/profile/contact/views.cljs
> +                  :on-long-press         #(reset! highlight-address true)}
sorry why do we need the question mark here?

2018-05-03 07:14 UTC, jeluard commented on src/status_im/ui/screens/profile/contact/views.cljs
> +                  :on-long-press         #(reset! highlight-address true)}
To better reflect that this is a boolean value?

2018-05-03 17:11 UTC, go1t commented on src/status_im/ui/screens/profile/contact/views.cljs
> +                  :on-long-press         #(reset! highlight-address true)}
oh I wasn't aware that it's a naming convention. Fixed

2018-05-03 17:13 UTC, go1t commented on src/status_im/ui/components/highlight.cljs
> +     [react/view {:flex 1}
I can't find it :( I only saw this code being used elsewhere

2018-05-04 06:14 UTC, jeluard commented on src/status_im/ui/components/highlight.cljs
> +     [react/view {:flex 1}
Here it is: https://github.com/status-im/status-react/blob/develop/src/status_im/ui/components/styles.cljs#L58

2018-05-04 09:36 UTC, go1t commented
@jeluard I just force-pushed the same branch so I don't have to open a new pull request. Hopefully that works

2018-05-04 10:26 UTC, goranjovic approved these changes

2018-05-04 10:42 UTC, jeluard commented
@go1t It does! Thanks for the extra effort.

2018-05-04 10:42 UTC, jeluard approved these changes

2018-05-04 10:43 UTC, go1t commented
No problem! Thanks for the review in the previous iteration.

2018-05-04 12:30 UTC, asemiankevich commented
@go1t would you mind please look at the issues outlined:

1. long tap is not working on android, for ex: open status -> go to profile -> tap show my contact code -> long tap it. Please, notice that the code is now hidden a bit under the picture
2. when I log tapped for ex the public key on iOS - tapping outside does nothing, the selection still remains as is

2018-05-04 18:21 UTC, go1t commented
@asemiankevich Absolutely. Sorry I forgot to test on android before.

The 2nd issue is somewhat a behavior that we can't do much about unless we want to complicate things more (e.g. introducing an atom). I think tapping other elements such as the qr code image would make it disappear. I will see what I can do though.

2018-05-05 10:01 UTC, go1t commented
Ugh seems like a multiline TextInput being non-selectable on android is another issue on react-native... :(

Since selectable works fine on android but buggy on iOS, while TextInput works fine on iOS but buggy on android, I think it might make sense to just use both of them (with https://facebook.github.io/react-native/docs/platform-specific-code.html). What do you think? @jeluard @flexsurfer

2018-05-05 12:11 UTC, jeluard commented
@go1t Please go ahead!

2018-05-07 13:03 UTC, jeluard approved these changes

2018-05-09 08:12 UTC, lukaszfryc commented
@go1t it works fine. One small issue that still persist is the following - only on iOS, when qr code is copied the text is still selected:

<img src="https://user-images.githubusercontent.com/7532782/39803148-6c569d42-5370-11e8-81ce-679c3c245698.png" width="200">

Can we deselect it? If not, let's merge.

2018-05-09 08:24 UTC, flexsurfer commented
@go1t could you please squash commits, thanks

2018-05-09 08:28 UTC, go1t commented
@flexsurfer will do!

@lukaszfryc there is no trivial way to deselect it as it's an upstream issue unfortunately and we would like to keep it simple so yeah I think we probably should go forward with this for now.

2018-05-09 08:32 UTC, merged