Show timestamp inside bubble for text messages
status-im/status-react pull request #3970
Opened 2018-04-23 16:49 UTC by cammellos

fixes #3927 

### Summary:

Shows timestamp inside the bubble for text messages, updates also the padding according to designs.
status: ready

2018-04-23 16:55 UTC, jeluard requested changes

2018-04-23 16:55 UTC, jeluard commented on src/status_im/chat/styles/message/message.cljs
> +           :font-size  10
I find using plain merge and when more readable for those cases.

2018-04-23 16:55 UTC, jeluard commented on src/status_im/chat/styles/message/message.cljs
> +          :padding-left    12
You can use `padding-horizontal` here.

2018-04-23 16:55 UTC, jeluard commented on src/status_im/chat/views/message/message.cljs
> +  (str "   " t))
Could you add a comment detailing why this is not done in CSS?

2018-04-24 05:41 UTC, rasom approved these changes

2018-04-24 06:12 UTC, asemiankevich commented
@cammellos does the PR fixes the following:

1. timestamps in bubbles
2. remove avatars
3. correct paddings
4. change messages colors? 

I am sorry if this was not readable in the issue description, me bad :(  Would you mind to check this PR and adjust?

2018-04-24 06:13 UTC, cammellos commented
not all of them, but i can add the missing parts

On Tue, Apr 24, 2018, 7:12 AM asemiankevich <notifications@github.com>
wrote:

> @cammellos <https://github.com/cammellos> does the PR fixes the following:
>
>    1. timestamps in bubbles
>    2. remove avatars
>    3. correct paddings
>    4. change messages colors?
>
> I am sorry if this was not readable in the issue description, me bad :(
> Would you mind to check this PR and adjust?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/status-im/status-react/pull/3970#issuecomment-383815185>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA-EsBN7ptg58KLyYtMkOAVpyCaR89KWks5trsJCgaJpZM4TgQCK>
> .
>

2018-04-24 06:35 UTC, janherich approved these changes

2018-04-24 06:35 UTC, asemiankevich commented
@cammellos thanks!!

2018-04-24 09:11 UTC, denis-sharypin commented
@cammellos Please don't change the color of the sender bubble. Sorry, mockups are misleading in this way.

2018-04-27 14:30 UTC, cammellos commented
@jeluard made the changes, could you have a quick look? thanks

2018-04-27 14:33 UTC, jeluard commented on src/status_im/chat/views/toolbar_content.cljs
> +
Extra lines?

2018-04-27 14:33 UTC, jeluard approved these changes

2018-04-27 14:33 UTC, jeluard commented
@cammellos Thanks!

2018-04-30 09:42 UTC, asemiankevich commented
@cammellos the avatar on the top is not being changed (in chat). However new one is shown on Home tab

![image](https://user-images.githubusercontent.com/28752642/39421802-67a390d8-4c73-11e8-8ee7-60a84101e256.png)

![image](https://user-images.githubusercontent.com/28752642/39421813-73361f9c-4c73-11e8-84e4-b09ce524d58b.png)

Also names of the participants are outside the bubbles but @denis-sharypin said it is okay for now

2018-04-30 10:03 UTC, cammellos commented
@asemiankevich how did you trigger a change in the picture? Just changing the picture on phone B will do?

2018-04-30 10:04 UTC, asemiankevich commented
@cammellos so i created 1x1 chat with default pictures under Ropsten and then i went to devices' profiles and changed default pictures to custom

2018-04-30 11:37 UTC, cammellos commented
@asemiankevich fixed here https://jenkins.status.im/blue/organizations/jenkins/status-react%2Fpull%20requests/detail/PR-3970/13/pipeline 
thanks!

2018-04-30 12:01 UTC, asemiankevich commented
it works now @cammellos thanks!

2018-04-30 12:04 UTC, merged