Sort Assets in alphabetical order on Wallet -> Manage Assets screen [#3926]
status-im/status-react pull request #4022
Opened 2018-04-26 14:41 UTC by psdp

### Summary:

fixes #3926 Sort assets in alphabetical order

status: ready

2018-04-26 14:45 UTC, jeluard requested changes

2018-04-26 14:45 UTC, jeluard commented on src/status_im/utils/ethereum/tokens.cljs
> +       (sort #(compare (.toLowerCase (:name %1)) (.toLowerCase (:name %2))))))
Can you use [lower-case](https://clojuredocs.org/clojure.string/lower-case) ?

2018-04-27 12:58 UTC, flexsurfer requested changes

2018-04-27 12:58 UTC, flexsurfer commented on src/status_im/utils/ethereum/tokens.cljs
> +  (:require [clojure.string :refer [lower-case]]))
please use `:as string` instead `:refer`

2018-05-01 14:23 UTC, goranjovic approved these changes

2018-05-01 14:23 UTC, goranjovic commented
@flexsurfer @jeluard Could you re-review? Looks updated now

2018-05-01 15:29 UTC, flexsurfer approved these changes

2018-05-02 05:46 UTC, jeluard approved these changes

2018-05-02 12:56 UTC, merged