#3939 & #3940: Wallet signing phrase and welcome screens
status-im/status-react pull request #4058
Opened 2018-04-30 09:18 UTC by alwx

Fixes two issues:

#3939: Introducing wallet / welcome screen
#3940: Introducing wallet / signing phrase

2018-04-30 09:24 UTC, flexsurfer requested changes

2018-04-30 09:24 UTC, flexsurfer commented on src/status_im/data_store/realm/schemas/base/v1/account.cljs
> +             :properties {:address               :string
v1 in the release already

2018-05-09 05:54 UTC, rasom commented
@alwx any updates on this PR?

2018-05-09 06:28 UTC, alwx commented
@rasom coming today

2018-05-09 06:38 UTC, alwx commented
Somebody made tons of indentation changes, thus this branch required rebasing. I rebased it and fixed all issues mentioned here before. 
Can be checked now.

2018-05-09 06:38 UTC, rasom commented
> Somebody 
yeah, that was me

2018-05-09 06:39 UTC, rasom commented
there are also formatting errors
https://jenkins.status.im/blue/organizations/jenkins/status-react%2Fpull%20requests/detail/PR-4058/8/pipeline

2018-05-09 06:57 UTC, flexsurfer approved these changes

2018-05-09 07:06 UTC, rasom approved these changes

2018-05-09 07:10 UTC, alwx commented
Fixed.

2018-05-09 07:13 UTC, cammellos commented
@alwx I had encountered some problems when changing schema version on develop as this code https://github.com/status-im/status-react/blob/3b8e2b7f75796813b5dea988597b3bc211f114f5/src/status_im/data_store/realm/core.cljs#L66 is triggered everytime I log in and out, resetting the database. Could you check if you have the same issue? (log in/log out, or restart the app, you loose all the chats). If so we probably want to remove that check with the PR.

2018-05-09 07:16 UTC, flexsurfer commented
@janherich please take a look at the comment above

2018-05-09 07:43 UTC, janherich commented on ios/StatusIm.xcodeproj/project.pbxproj
> +		};
Why are changes in this file necessary for this PR ?

2018-05-09 07:50 UTC, janherich commented
@flexsurfer @cammellos @alwx Yes, we should remove that check and include it conditionally whenever some future release will contain incompatible changes.
In my opinion, it should be done via flag and it should be simple check if schema version (`realm-version file-name encryption-key`) is different (`=`) from provided schema version `and` it's not `-1` (value for fresh install without any previous schema installed), if both conditions are false and flag is set, we just show the popup and delete the schema, if not, normal flow (migration to latest version) will proceed.
In case of any incompatible release in the future, it will be just matter turning the flag on (default will be false).
I can open PR with that logic, in the meantime you should remove that strange version check in any PR which increases the schema version.

2018-05-09 08:26 UTC, alwx commented
@janherich project.pbxproj changes have been removed

2018-05-09 08:31 UTC, alwx commented
@janherich @cammellos if I got it right, the problem should be solved by this commit (also included to this PR):
https://github.com/status-im/status-react/pull/4058/commits/4764313e35e9d3bed5a517b6d086d39fa3c82d33

2018-05-09 08:44 UTC, janherich approved these changes

2018-05-09 08:46 UTC, cammellos approved these changes

2018-05-09 09:02 UTC, cammellos commented
@alwx code style check failed https://jenkins.status.im/blue/organizations/jenkins/status-react%2Fpull%20requests/detail/PR-4058/12/pipeline

2018-05-10 01:44 UTC, yevh-berdnyk commented
Android: https://i.diawi.com/qpU67y
iOS: https://i.diawi.com/1Kq1EJ

Found issues
**Transaction phrase is changed after recovering an account in both cases if wallet was set up or it was not**
Reproduction:
- On device 1 create new account
- Navigate to Wallet and remember a transaction phrase
- Setup your wallet (you can skip this step and just remember the phrase)
- On device 2 recover created account
- Click Wallet
- Click Send Transaction
- Select a recipient and input some amount
- Click Sign transaction
- Transaction phrase is changed

2018-05-10 07:52 UTC, alwx commented
This issue is not related to onboarding flow

2018-05-10 11:11 UTC, yevh-berdnyk commented
@alwx you right, I've checked on develop and wallet phrase is changed after recovering account.
I'll create a separate issue for it

2018-05-10 12:43 UTC, goranjovic commented
@alwx I see two commits in the PR. Is this intentional or do you want to squash them before merge?

2018-05-10 15:10 UTC, flexsurfer commented
@alwx could you resolve conflicts and squash commits please

2018-05-11 04:25 UTC, merged