bug #3877 - no longer possible to sign messages with empty password
status-im/status-react pull request #4086
Opened 2018-05-02 13:16 UTC by goranjovic

fixes #3877 

### Summary:

This PR clears the password when signing is cancelled. Also, Sign button is now disabled when 
password is empty (tapping it does nothing as opposed to giving "Wrong password" which was previously the case).

### Steps to test:
See #3877 

status: ready

2018-05-02 13:17 UTC, janherich approved these changes

2018-05-02 13:18 UTC, jeluard approved these changes
Do we allow empty password during account creation?

2018-05-02 13:20 UTC, flexsurfer requested changes

2018-05-02 13:20 UTC, flexsurfer commented on src/status_im/ui/screens/wallet/send/events.cljs
> +    (merge {:db (-> db  (update-in [:wallet :send-transaction] merge clear-send-properties)
maybe better to add `:password` to `clear-send-properties` ?

2018-05-02 13:20 UTC, flexsurfer commented on src/status_im/ui/screens/wallet/send/events.cljs
> +    {:db (-> db (update-in [:wallet :send-transaction] assoc
why don't just add `:password nil` to `assoc`?

2018-05-02 13:42 UTC, goranjovic commented
@flexsurfer Gotcha

@jeluard  No

2018-05-02 13:43 UTC, flexsurfer approved these changes

2018-05-03 20:42 UTC, yenda approved these changes

2018-05-03 20:42 UTC, merged