[#4075] Clear invalid contact code error message when returning to "Start new chat"
status-im/status-react pull request #4143
Opened 2018-05-08 06:23 UTC by psdp

fixes #4075

### Summary:

Clear the input field value so that it won't display invalid contact code error message when returning to the "Start new chat"

status: ready

2018-05-08 06:50 UTC, flexsurfer requested changes
hey @psdp thanks, but we use common approach for this, please create `navigation.cljs` and use `defmethod navigation/preload-data!`

2018-05-08 07:33 UTC, psdp commented
@flexsurfer fixed :)

2018-05-08 07:36 UTC, flexsurfer approved these changes

2018-05-10 10:56 UTC, goranjovic approved these changes

2018-05-11 09:44 UTC, Serhy commented
Builds Android: https://i.diawi.com/jM3uBG and  iOS: https://i.diawi.com/AUyHLf tested - looks good!

2018-05-11 09:54 UTC, merged