set defaultAccount when getting web3
status-im/status-react pull request #4151
Opened 2018-05-08 10:37 UTC by yenda

status: ready

2018-05-08 10:40 UTC, janherich approved these changes

2018-05-08 10:42 UTC, flexsurfer approved these changes

2018-05-08 11:14 UTC, rasom requested changes

2018-05-08 11:14 UTC, rasom commented on src/status_im/protocol/handlers.cljs
> +      (set! (.-defaultAccount (.-eth web3)) (ethereum/normalized-address (get-in coeffects [:db :account/account :address])))
80 chars limit :)

2018-05-08 12:18 UTC, yenda commented on src/status_im/protocol/handlers.cljs
> +      (set! (.-defaultAccount (.-eth web3)) (ethereum/normalized-address (get-in coeffects [:db :account/account :address])))
fixed

2018-05-08 12:24 UTC, rasom approved these changes

2018-05-11 12:47 UTC, asemiankevich commented
@yenda returns `undefined` , same as in develop

2018-05-11 13:10 UTC, merged