[FIX] Make unread badge touchable (aka fat finger fix)
status-im/status-react pull request #4242
Opened 2018-05-13 16:47 UTC by yenda

Unread message badge is not touchable which reduces the surface area
that can be used to go back from a chat when user has unread messages

This gives user the impression that he needs to tap many times to go
back and that the UI lags because a smaller area is touchable when
users have unread messages

![screenshot from 2018-05-13 18-38-36](https://user-images.githubusercontent.com/1181225/39969567-04f763c2-56de-11e8-8e3d-982d240679f1.png)
![screenshot from 2018-05-13 18-39-20](https://user-images.githubusercontent.com/1181225/39969568-0512955c-56de-11e8-8e1a-554031f8fea3.png)
![screenshot from 2018-05-13 18-39-31](https://user-images.githubusercontent.com/1181225/39969569-052c538e-56de-11e8-9073-1dc4ccd1d731.png)
![screenshot from 2018-05-13 18-44-50](https://user-images.githubusercontent.com/1181225/39969570-0547ad78-56de-11e8-8d6d-250b881679b9.png)

status: ready

2018-05-13 17:00 UTC, rasom commented
apk uploaded to https://i.diawi.com/9B2oGP for branch PR-4242

2018-05-13 17:08 UTC, rasom commented
ipa uploaded to https://i.diawi.com/yh4XdW for branch PR-4242

2018-05-14 04:43 UTC, rasom commented
@yenda why 3 commits here?

2018-05-14 04:45 UTC, rasom requested changes
please rebase it onto develop

2018-05-14 04:45 UTC, rasom commented on src/status_im/ui/components/toolbar/styles.cljs
> +(defnstyle nav-item-button [unread-messages?]
can be just `defn` btw

2018-05-14 18:38 UTC, yenda commented
@rasom there was 3 commits because I was making a special build for Chad to test performance issues. I still need to fix dapps screen there is a misalignement now I will update this PR later

2018-05-14 18:39 UTC, yenda commented
@jeluard I add you to the review because you are the last one who touched these components, I was wondering if you have an opinion on a better way to do this

2018-05-14 18:50 UTC, rasom commented
apk uploaded to https://i.diawi.com/WJ8RoW for branch PR-4242

2018-05-14 18:58 UTC, rasom commented
ipa uploaded to https://i.diawi.com/FmV7R3 for branch PR-4242

2018-05-15 06:15 UTC, jeluard reviewed
Looks fine to me!
Just make sure you address both comments (Roman's and mine)

2018-05-15 06:15 UTC, jeluard commented on src/status_im/ui/components/toolbar/styles.cljs
> +  {:padding-horizontal 3
Please align values

2018-05-16 01:24 UTC, rasom commented
apk uploaded to https://i.diawi.com/3ahmva for branch PR-4242

<blockquote><div><strong><a href="https://i.diawi.com/3ahmva">Install - Diawi - Development and In-house Apps Wireless Installation</a></strong></div></blockquote>

2018-05-16 01:33 UTC, rasom commented
ipa uploaded to https://i.diawi.com/SeaZ9T for branch PR-4242

2018-05-16 06:42 UTC, denis-sharypin approved these changes

2018-05-16 23:27 UTC, rasom commented
apk uploaded to https://i.diawi.com/CiZyap for branch PR-4242

2018-05-16 23:34 UTC, rasom commented
ipa uploaded to https://i.diawi.com/MH2Kz6 for branch PR-4242

2018-05-16 23:44 UTC, yenda commented
@rasom is it ok now ?
@denis-sharypin are the design ok ? I updated the screenshot, I realigned the dapp icon it was a bit off to the top even on current release

2018-05-17 07:13 UTC, denis-sharypin commented
@yenda everything is okay! Thanks, Eric

2018-05-17 07:28 UTC, jeluard approved these changes

2018-05-17 07:28 UTC, jeluard commented
@rasom Can you review again?

2018-05-17 09:34 UTC, rasom commented
apk uploaded to https://i.diawi.com/BWdNmX for branch PR-4242

2018-05-17 09:42 UTC, rasom commented
ipa uploaded to https://i.diawi.com/Nmny2Y for branch PR-4242

2018-05-18 10:02 UTC, rasom approved these changes

2018-05-18 14:30 UTC, asemiankevich commented
LGTM, however the improvement is hardly visible on iOS

2018-05-18 14:41 UTC, yenda commented
@asemiankevich do you mean the tap area is still small or it was already including the unread messages badge ?

2018-05-18 14:53 UTC, asemiankevich commented
@yenda well i think the problem here is that the badge is small itself)

2018-05-18 15:18 UTC, merged