Feature/build_no with push
status-im/status-react pull request #4540
Opened 2018-05-30 13:58 UTC by jakubgs

Since the tagging behavior is a bit flaky after discussing this with Igor we've decided all builds should be tagged. Now if you rung `build_no.sh` with `--increment` it fetches, tags, and pushes, all in one.

2018-05-30 14:00 UTC, mandrigin commented on Jenkinsfile.upload_release_android
> +            usernamevariable: 'git_user',
why different case here?

2018-05-30 14:00 UTC, mandrigin commented on Jenkinsfile.upload_release_ios
> +            usernamevariable: 'git_user',
why different case here?

2018-05-30 14:00 UTC, mandrigin requested changes
a few small questions

2018-05-30 14:18 UTC, rasom commented
apk uploaded to https://i.diawi.com/jvsHny for branch PR-4540

2018-05-30 14:25 UTC, rasom commented
ipa uploaded to https://i.diawi.com/6zWYgb for branch PR-4540

2018-05-30 15:45 UTC, jakubgs commented on Jenkinsfile.upload_release_android
> +            usernamevariable: 'git_user',
I must have fat-fingered `gu` in vim. Fixed.

2018-05-30 15:45 UTC, jakubgs commented on Jenkinsfile.upload_release_ios
> +            usernamevariable: 'git_user',
Well spotted.

2018-05-30 15:58 UTC, rasom commented
apk uploaded to https://i.diawi.com/c8PDko for branch PR-4540

2018-05-30 16:01 UTC, mandrigin approved these changes
Nice!

2018-05-30 16:05 UTC, rasom commented
ipa uploaded to https://i.diawi.com/CbjeLk for branch PR-4540

2018-05-30 16:58 UTC, mandrigin commented
merging because it is trivial

2018-05-30 17:36 UTC, rasom commented
apk uploaded to https://i.diawi.com/wG9ZNp for branch PR-4540

2018-05-30 17:43 UTC, rasom commented
ipa uploaded to https://i.diawi.com/C5dfvo for branch PR-4540

2018-06-09 04:13 UTC, rasom approved these changes

2018-06-12 08:08 UTC, merged