Add border to profile picture & style chat icon
status-im/status-react pull request #4634
Opened 2018-06-05 08:51 UTC by cammellos

Fixes #4419 

### Summary:

* Added a transparent border to profile images
* Allowed multiple colors in chat-icons
* Changed `identicon` to display smaller icons

### Review notes (optional):

I have consolidated most of the logic for creating pictures in a single place  `status-im.chat.views.photos`.

The method for adding a border is to superimpose a `div` with a invisible border, of all the method considered that is the simplest, afaics.

### Testing notes:

* Previously generated images will not change.
* I have tried to find all the profile pics in the app, but without a comprehensive list I might have missed some.

status: ready

2018-06-05 08:55 UTC, goranjovic approved these changes

2018-06-05 08:55 UTC, goranjovic commented on src/status_im/ui/components/styles.cljs
> +  (rand-nth chat-colors))
Maybe better place this in `status-im.ui.components.colors`

2018-06-05 09:38 UTC, jeluard requested changes

2018-06-05 09:38 UTC, jeluard commented on src/status_im/chat/styles/photos.cljs
> +(def border-color "#ccd3d6")
Is that a new color? Can it be deifined in `colors` ns?

2018-06-05 09:38 UTC, jeluard commented on src/status_im/chat/views/photos.cljs
> +            :size style/default-size})))
Not aligned :)

2018-06-05 09:38 UTC, jeluard commented on src/status_im/ui/components/chat_icon/styles.cljs
> +  {:color       color-white
Can use colors ns

2018-06-05 09:38 UTC, jeluard commented on src/status_im/ui/components/styles.cljs
> +(def chat-colors ["#fa6565"
Does it make sense to have those in colors ns?

2018-06-05 10:18 UTC, cammellos commented
@jeluard updated!

2018-06-05 10:21 UTC, jeluard approved these changes

2018-06-05 11:39 UTC, cammellos commented
Looking at the failed e2e tests, I pushed a change to re-introduce `:chat-id` label, might ask you to restart them if not automatic.

2018-06-07 08:57 UTC, lukaszfryc commented
@cammellos all looks good. One small thing - maybe you could check if the character is really centered inside the avatar. If it is, please merge.

<img src="https://user-images.githubusercontent.com/7532782/41089039-38699f24-6a41-11e8-8d59-e3e4dd21e5a4.png" width="200">

2018-06-07 11:26 UTC, cammellos commented
@lukaszfryc as far as I can see from the code, it should be center aligned, `justify-content :center`

2018-06-07 11:50 UTC, merged