WIP add contact functionality
status-im/status-react pull request #4714
Opened 2018-06-12 09:04 UTC by rcullito

fix for #4276

2018-06-12 09:15 UTC, vitvly approved these changes

2018-06-12 09:24 UTC, maxhora approved these changes

2018-06-12 10:13 UTC, vkjr approved these changes

2018-06-12 10:25 UTC, rcullito commented
### Testing instructions

1. after clicking on "add to contacts", the copy will disappear. 
2. the main change here is that the `pending?` flag on the contact itself is set to false. Right now desktop is just displaying the list of chats and (as far as I'm aware) there is no visible contact list, so `1.` is the main visual change that can be observed during testing.

2018-06-12 14:41 UTC, asemiankevich commented
well, i can confirm that I can click this `add to contacts` button and it disappears. All known issues remain same:
1. Can't receive messages sent from desktop to mobile (talked to Max about it, need to figure out what should be done there)
2. Contact name is not updated when adding mobile to friends on desktop
3. Chats are overlapping
4. The whole UI is still laggy and amateurish
5. When  i click the button - contact is added to the left panel

If this is the only change (click the button and see it is not shown) - then we can merge it. 

We need to revisit this later when regression comes or any new design is done, so chats are more stable along with contacts to make any meaningful conclusion.

2018-06-12 19:19 UTC, asemiankevich commented
Agreed with @rcullito to open separate issue for realm storing . Moving this to merge as is.

2018-06-12 19:35 UTC, rcullito commented
Thanks for looking into it @asemiankevich. Yes no statements of app-wide greatness bundled with this one lol :) Just hoping to get in a lot of minor, small improvements to address these issues so that a less buggy version emerges onto develop for other feature branches to pick up. 

Will tackle realm storage as a next step so that this persists on app refresh!

2018-06-12 19:55 UTC, cammellos requested changes
Just looking at this,

I think we removed `add-pending-contact` event handler, the desktop version might have some outdated code & not have been updated accordingly, unfortunately I think that might be the case for quite a few parts of the codebase.

You can re-use some of the events in the namespace `status-im.ui.screen.contacts.events` , depending on what you would like to do (there's a version that open a chat as well I believe).

Also at the moment we exchange keys through the contact request, and we start sending profile information to the contact, so there's some additional logic involved when adding a contact, if you re-use one of the handlers it should be taken care of (that's why you probably are not getting updates from contacts).

Maybe is worth if you ask to review someone from the mobile team when sending PR (as well feel free to ping us in slack), as we can help you out with some issues like this that might be a bit counter-intuitive.

2018-06-12 20:27 UTC, rcullito commented
@cammellos great, thanks for that extra info! Yes, as you said, our branch is in a state where the view is dispatching an event that is then missing from the list of registered handlers. 

It sounds like this removal was intentional though? I'll consult `status-im.ui.screen.contacts.events` for the full suite of updates necessary beyond just setting a contact's `pending?` flag to false. 

As you brought up in Slack, I would be quite open to a discussion  about how to keep `desktop` up to date against develop despite the difference in codebases. 

Much appreciated on the review! 🙏

2018-06-13 08:54 UTC, cammellos commented
@rcullito yes, the removal was intentional, we don't have a distinction between how we handle a `pending` contact or not at the UI layer, same event, the underlying layer handles whether is should respond or send a new contact request.

2018-06-14 07:49 UTC, asemiankevich commented
@rcullito please close this branch without merging as agreed

2018-06-14 08:01 UTC, closed without merging