Allow to connect to any node for dev mode [#4817]
status-im/status-react pull request #5175
Opened 2018-07-15 14:05 UTC by flexsurfer

fixes #4817, #5170, #4935, #4676, #4354, #3981

2018-07-16 06:24 UTC, cammellos requested changes
looks good to me, please add tests whenever adding/changing new functionalities (`update-transaction`, `chain-id->chain-keyword` could be tested, but there are no existing tests for them, but we have some for `save` and/or `new-network`)

2018-07-16 06:24 UTC, cammellos commented on src/status_im/models/network.cljs
> +(defn- new-network [{:keys [random-id] :as cofx} network-name upstream-url type network-id]
Could you extend https://github.com/status-im/status-react/blob/11bb0097879dc8fd992f0ada5f0da651ba1f1e77/test/cljs/status_im/test/models/network.cljs#L31 to take into consideration the new functionality? (uses  `networkId` parsed if it's an integer)
or otherwise you can test the same from the `save` method

2018-07-16 06:29 UTC, jeluard approved these changes

2018-07-16 13:19 UTC, flexsurfer commented
@cammellos done!

2018-07-16 13:21 UTC, cammellos approved these changes
@flexsurfer nice!

2018-07-17 13:30 UTC, lukaszfryc commented
@flexsurfer 6 bugs in a single PR, https://www.youtube.com/watch?v=1qlzLS4xyjw :) 

Works good, I used Kovan network (42) in Infura to test custom id. I also added a Ropsten network with manually specifying network id (3). I did not see any issues with messaging, transactions or overall connectivity. 

But, nothing has changed in regards to https://github.com/status-im/status-react/issues/4935. The "Ethereum node started incorrectly" appears every time I log in when provided network (or network id) was incorrect. Can we show it once and then revert back to Mainnet? We could state it in the dialog by saying "Ethereum node was started with incorrect configuration. Application will be stopped to recover and will connect to Mainnet upon next login."

2018-07-17 13:31 UTC, lukaszfryc commented
Alternatively, let's do it in a separate PR.

2018-07-17 13:32 UTC, lukaszfryc commented
Also, could you add "Allow to specify Network ID for custom network" or something similar to Changelog?

2018-07-17 13:40 UTC, flexsurfer commented
thanks @lukaszfryc your comment made me laugh :) i'll take a look at #4935 one more time and make changes to changelog

2018-07-18 12:26 UTC, lukaszfryc commented
OK. I'll move it to Contributor column for now.

2018-07-19 08:11 UTC, lukaszfryc commented
@flexsurfer let me know how it goes. We can always resolve #4935 in a separate PR I think

2018-07-19 08:58 UTC, flexsurfer commented
@lukaszfryc yeah, let's merge this one, i'll look at 4935 separately

2018-07-19 09:09 UTC, merged