Update CHANGELOG.md
status-im/status-react pull request #5225
Opened 2018-07-18 15:43 UTC by rachelhamlin

### Summary:

More updates from https://github.com/status-im/status-react/compare/release/0.9.22...develop

Fixed blinging token transaction in history
Fixed showing correct fiat value in /send and /request messages
Automatically convert recovery phrase to lowercase during account recovery
Fixed unread messages counter
Fixed incoming message timestamp

2018-07-18 16:12 UTC, jeluard approved these changes

2018-07-18 16:41 UTC, flexsurfer approved these changes

2018-07-19 07:58 UTC, lukaszfryc requested changes
@rachelhamlin can you mention deep links and the fact we removed Mixpanel?

You can use "Added" and "Changed" sections to include
- Added deep links
- Removed Mixpanel

2018-07-19 09:13 UTC, lukaszfryc approved these changes

2018-07-19 09:16 UTC, merged