bug #4952 - moved the wrong password tooltip a bit up to make the fie…
status-im/status-react pull request #5322
Opened 2018-07-27 12:42 UTC by goranjovic

fixes #4952 

### Summary:

The "Wrong password" tooltip was blocking access to the password field, making it unfocusable if the user ever loses focus on it. This PR fixes the immediate issue by moving the tooltip just a little bit up.

### Steps to test:
see #4952 

status: ready

2018-07-27 12:43 UTC, goranjovic commented
![screenshot-2018-07-27_14 31 11 506](https://user-images.githubusercontent.com/711764/43321195-631c99ec-91ab-11e8-95ba-e32e6632aa5b.png)

2018-07-27 12:43 UTC, jeluard approved these changes

2018-07-27 12:43 UTC, jeluard commented on src/status_im/ui/screens/wallet/send/views.cljs
> +         [tooltip/tooltip (i18n/label :t/wrong-password) {:bottom-value -20}])]]]))
Could this be defined in `styles`?

2018-07-27 12:45 UTC, flexsurfer commented
@goranjovic something wrong, this tooltip should be under the whole panel, looks like it has been moved to another container

2018-07-27 13:28 UTC, goranjovic commented
@flexsurfer It didn't really make sense, because even before this change it was hiding the text a little bit.

You mean like this?

![screenshot-2018-07-27_14 31 11 506](https://user-images.githubusercontent.com/711764/43323343-aa6fd60a-91b1-11e8-915b-27914ec26907.png)

2018-07-28 09:38 UTC, flexsurfer commented
@goranjovic yes you can find it in zepplin https://zpl.io/bL4KqX7
![image](https://user-images.githubusercontent.com/11790366/43355329-164639d0-9263-11e8-91f1-ba611b1a39a5.png)

2018-07-30 07:07 UTC, denis-sharypin requested changes
@goranjovic  thanks! Please, follow @flexsurfer  example above. Also, the style of the tooltip should be a bit different. In the tooltip that we use during the onboarding, it has a red background. Can we use it here as well?

2018-07-30 14:05 UTC, goranjovic commented
@denis-sharypin @flexsurfer updated:

![screenshot-2018-07-30_16 01 48 78](https://user-images.githubusercontent.com/711764/43402140-4d38b9da-9412-11e8-8df2-97546b5c943f.png)

2018-07-30 14:14 UTC, flexsurfer approved these changes

2018-07-31 09:08 UTC, denis-sharypin approved these changes

2018-07-31 15:01 UTC, asemiankevich commented
https://github.com/status-im/status-react/issues/4952 and https://github.com/status-im/status-react/issues/4835 are fixed here. Also UI looks good!
![image](https://user-images.githubusercontent.com/28752642/43467798-34602720-94eb-11e8-8ac5-4eac80d972cc.png)

![image](https://user-images.githubusercontent.com/28752642/43467892-6c43b454-94eb-11e8-8c06-cfb4f500e539.png)

2018-07-31 15:09 UTC, merged