Update desktop dependencies
status-im/status-react pull request #5454
Opened 2018-08-10 15:42 UTC by dmitryn

### Summary:

Update desktop dependencies introduced by https://github.com/status-im/status-react/pull/4997

status: ready

2018-08-10 21:36 UTC, maxhora requested changes
just referencing `react-native-firebase` for Desktop allows to pass JS package bundling step, but on runtime app fails on startup with error:
```
Debug: ubuntu-server err:  "RNFirebase core module was not found natively on Android, ensure you have correctly added the RNFirebase and Firebase gradle dependencies to your `android/app/build.gradle` file.\r\n\r\n See http://invertase.link/android for the android setup guide."

Debug: ubuntu-server err:  "Module AppRegistry is not a registered callable module (calling runApplication)"
```
This happens, because `react-native-firebase` module doesn't support Desktop platform. As quick workaround, possibly, will work adding of conditional check that `react-native-firebase` module related source code is executing on Mobile platform currently.

2018-08-10 23:50 UTC, MaxRis commented
Have pushed commit which fixes desktop builds by dirty workaround to frame notifications related code with `when-not platform/desktop?` condition.

2018-08-11 11:47 UTC, yenda commented
What would be a more long term fix @MaxRis ?

2018-08-11 12:04 UTC, MaxRis commented
@yenda 
Probably, more long term workaround can be moving of `utils.notifications` namespace under `mobile` namespace and redefining of `utils.notifications` under `desktop` namespace. (similar like we do with `js-dependencies`)

For Desktop we currently also working on desktop notifications feature ( in-progress PR is there https://github.com/status-im/status-react/pull/5330 ), but I'm not sure what common implementation details are in both cases. On desktop we have defined our own `react-native-desktop-notifications` react-native native module to handle notifications background logic.

2018-08-11 23:26 UTC, yenda commented
@MaxRis if you are satisfied with the fix can you remove your change request and squash your commit so that we can merge ?

2018-08-11 23:29 UTC, yenda commented on src/status_im/utils/notifications.cljs
> +  ;(def firebase "")
comment can be removed

2018-08-11 23:30 UTC, yenda approved these changes

2018-08-12 09:09 UTC, MaxRis commented on src/status_im/utils/notifications.cljs
> +  ;(def firebase "")
@yenda oh, overlooked it, thanks!

2018-08-12 09:22 UTC, maxhora approved these changes

2018-08-12 09:23 UTC, maxhora commented
@yenda done! thank you

2018-08-12 20:20 UTC, merged