set `FLEET` in env variable
status-im/status-react pull request #5503
Opened 2018-08-14 17:09 UTC by adambabik

Allow to specify a fleet in the `env` file and use it in the configuration.

Todo:
- [ ] figure out which envs should use `env.staging` instead of `eth.beta`.

Closes #5213

2018-08-14 17:10 UTC, adambabik commented
@mandrigin which `.env` file is used by the CI job trigged by this PR?

2018-08-14 17:20 UTC, adambabik commented
`eth.staging` mail servers:
1. `enode://69f72baa7f1722d111a8c9c68c39a31430e9d567695f6108f31ccb6cd8f0adff4991e7fdca8fa770e75bc8a511a87d24690cbc80e008175f40c157d6f6788d48@206.189.240.16:30504`,
2. `enode://e4fc10c1f65c8aed83ac26bc1bfb21a45cc1a8550a58077c8d2de2a0e0cd18e40fd40f7e6f7d02dc6cd06982b014ce88d6e468725ffe2c138e958788d0002a7f@35.239.193.41:30504`

2018-08-14 19:57 UTC, mandrigin commented
@adambabik just `.env`

2018-08-14 19:58 UTC, mandrigin approved these changes
LGTM!

2018-08-15 08:33 UTC, pedropombeiro approved these changes
LGTM

2018-08-15 09:39 UTC, mandrigin commented
@adambabik maybe later you can make a separate PR for `eth.staging` builds that won't be merged? Just for tests?
After that, you can create one more .env and I can add another nightly or release job to build an app for eth.staging

2018-08-15 09:40 UTC, mandrigin commented
@adambabik afaik, staging mailservers are in `src/status_im/constants.cljs`

2018-08-15 10:23 UTC, adambabik commented
@mandrigin I think we can use a parametrized build in Jenkins if one needs to test against the `eth.staging`. I already changed the job. My question is if that job is reliable.

2018-08-15 10:32 UTC, adambabik commented
@mandrigin I don't see these mail servers in that file. There are different. I would need some help with someone familiar with Clojure to change that, pretty much the task is to remove Mail Servers per network as they all are the same now and instead we should have Mail Servers per fleet.

2018-08-15 22:50 UTC, adambabik commented
There is some issue with a parametrized build (https://ci.status.im/job/status-react/job/parametrized_build/761/console) but this Android version should work on "eth.staging": https://i.diawi.com/MeGGkw

2018-08-16 07:41 UTC, PombeirP commented on modules/react-native-status/android/src/main/java/im/status/ethereum/module/StatusModule.java
> +               JSONObject clusterConfig = (JSONObject) customConfig.get("ClusterConfig");
Missing one space in indentation

2018-08-16 07:42 UTC, mandrigin commented
@adambabik 
> There is some issue with a parametrized build (https://ci.status.im/job/status-react/job/parametrized_build/761/console)

rebasing to the latest `develop` should fix it

2018-08-16 07:50 UTC, adambabik commented
I merged develop and pulled with rebase which was a mistake... I will squash it before merging to develop so all should be fine. I don't want to force push as multiple people committed already.

2018-08-16 11:49 UTC, adambabik commented
It's ready to be tested. I build it with `eth.staging` fleet as well: https://ci.status.im/job/status-react/job/parametrized_build/763/

2018-08-20 09:46 UTC, mandrigin commented
@yenda @adambabik I'll take over this one if you don't mind :-)

2018-08-20 16:23 UTC, annadanchenko commented
Issue 1. beta fleet nodes are used instead of staging, e.g. `436cc6f674928fdc9a9f7990f2944002b685d1c37f025c1be425185b5b1f0900feaf1ccc2a6130268f9901be4a7d252f37302c8335a2c1a62736e9232691cc3a` is used 

TF session: https://app.testfairy.com/projects/4803622-status/builds/8563803/sessions/4398968123/?accessToken=LDKbiNAO2RRireCbgKrcwPugxeg
Build: https://jenkins.status.im/job/status-react/job/parametrized_build/770/ 

Issue 2 (not sure it's expected): Mailservers list is empty 
![screenshot_20180820-172836](https://user-images.githubusercontent.com/6584810/44352997-0b8b3900-a4a6-11e8-94b6-ba0e83da1bae.png)


<blockquote><div><strong><a href="https://app.testfairy.com/projects/4803622-status/builds/8563803/sessions/4398968123/?accessToken=LDKbiNAO2RRireCbgKrcwPugxeg">TestFairy: Status 0.9.26 (6461) @2018</a></strong></div></blockquote>
<blockquote><img src="/static/b2f7dc7b/favicon.ico" width="48" align="right"><div><strong><a href="https://jenkins.status.im/job/status-react/job/parametrized_build/770/">status-react » parametrized_build #770 [Jenkins]</a></strong></div></blockquote>

2018-08-21 10:26 UTC, yenda requested changes

2018-08-21 10:26 UTC, yenda commented on src/status_im/constants.cljs
> +        (assoc :rinkeby nodes-for-fleet))))
This is equivalent to

```
(let [nodes-for-fleet (get default-wnodes-without-custom config/fleet)]
  {:custom nodes-for-fleet
   :testnet nodes-for-fleet
   :mainnet nodes-for-fleet
   :rinkeby nodes-for-fleet})
```

2018-08-21 10:28 UTC, yenda approved these changes

2018-08-21 10:37 UTC, mandrigin commented on src/status_im/constants.cljs
> +        (assoc :rinkeby nodes-for-fleet))))
yeah, I overcomplicated it 😆

2018-08-21 10:40 UTC, mandrigin commented on src/status_im/constants.cljs
> +        (assoc :rinkeby nodes-for-fleet))))
fixed

2018-08-22 08:19 UTC, annadanchenko commented
with https://ci.status.im/job/status-react/job/nightly_staging_fleet/5/console build can connect to staging fleet (see mailserver and bootnode from staging nodes), no mailserver from beta fleet. https://app.testfairy.com/projects/4803622-status/builds/8565108/sessions/4399080579/?accessToken=8ZlfCTYroufGrZm9tMa6psSCgjk

2018-08-22 08:22 UTC, merged