Now user profile can be opened from public chat
status-im/status-react pull request #5546
Opened 2018-08-17 11:30 UTC by vkjr

fixes #5184 

### Summary:
Now user profile can be opened from public chat on desktop

### Steps to test:
- Open Status
- go to public chat, like `#status`
- open profile of any user, check that it opens and shows user information

status: ready

2018-08-17 11:37 UTC, goranjovic approved these changes

2018-08-17 12:08 UTC, flexsurfer requested changes

2018-08-17 12:08 UTC, flexsurfer commented on src/status_im/ui/screens/desktop/main/chat/events.cljs
> +  (navigation/navigate-to-cofx :chat-profile nil {:db (assoc db :contacts/identity identity)}))
better to use `merge-fx`

2018-08-17 12:49 UTC, vitvly approved these changes

2018-08-17 15:45 UTC, maxhora approved these changes

2018-08-19 09:22 UTC, vkjr commented
@flexsurfer, thanks, fixed.

2018-08-19 09:44 UTC, flexsurfer approved these changes

2018-08-20 07:26 UTC, churik commented
@vkjr 
this PR cannot be built.
https://ci.status.im/job/status-react/job/pull%20requests/view/change-requests/job/PR-5546/3/console

```
Aug 20, 2018 8:15:05 AM com.google.javascript.jscomp.LoggerErrorManager printSummary
WARNING: 1 error(s), 0 warning(s)
ERROR: JSC_MISSING_PROVIDE_ERROR. required "screens.desktop.main.chat.events" namespace never provided at /Users/jenkins/workspace/react_pull_requests_PR-5546-FSANQVJBHVI4YTKWLTQJXCXBJYV25KZ63DQY7NFLW522YRJHNZJQ/target/desktop-prod/status_im/ui/screens/desktop/main/chat/views.js line 21 : 0
[31mCompiling ["index.desktop.js"] failed.
```

2018-08-21 14:39 UTC, churik commented
1. Cannot navigate to user profile when there are several messages in a row (should be last in chat)
Steps:
- join to any chat where several last messages are sent in a row from one user (21/08/18 it is `#tery` and `status-desktop`)
- click on user pic to navigate to user profile

* Expected: *
navigated to user profile

* Actual: *
cannot navigate when clicking on user picture
<img width="568" alt="dfsfd" src="https://user-images.githubusercontent.com/4557972/44408409-fdeab780-a568-11e8-8980-f0cceecb4fed.png">

* Video: * http://take.ms/I0jFN
* Log: * [StatusIm.txt](https://github.com/status-im/status-react/files/2306728/StatusIm.txt)

2018-08-21 19:23 UTC, vkjr commented
@churik, thanks for finding. Strange bug, not always reproducible with steps you described, but quite often, investigating...

2018-08-22 06:50 UTC, vkjr commented
@churik, I investigated a bit and suspect that problem is not on clojure side, probably something in react-native-desktop. I would suggest to merge this PR and create separate issue for a problem. Because functionality is quite demanded and issue itself is not that critical.
What do you think?

2018-08-22 07:10 UTC, churik commented
Yes, OK. Can you create separate issue on react-native side and link it to PR or how we can track the progress?

2018-08-22 08:04 UTC, churik commented
@vkjr I retest it one more time and noticed one more strange behavior - when you scroll through history sometimes navigating just stop working and I faced two times after constant switching that app stops responding.
So it works +/- stable only for messages from today and when they are not sent in row from one user.

Video: http://take.ms/SDHC4
Log: [StatusIm.txt](https://github.com/status-im/status-react/files/2309370/StatusIm.txt)

@chadyj is it acceptable?

2018-08-22 09:00 UTC, vkjr commented
@churik, unfortunately I can't create react-native issue for now, because I don't know exact reason and don't have minimal example to reproduce it. I can create status-react issue and work on it and add react-native-desktop issue if will figure out it.

2018-08-22 09:03 UTC, vkjr commented
But I'm pretty sure that problem is not in the clojurescript code that is going to be commited in this PR. So if we commit it in 'develop', fixing react-native-desktop side can automatically fix the issue, so we will have functionality fully available.

2018-08-22 11:32 UTC, chadyj commented
If it's a regression in the PR, let's fix before merging.

If not, lets merge and create a new issue.

2018-08-22 12:21 UTC, churik commented
Reported in https://github.com/status-im/status-react/issues/5597

2018-08-22 16:02 UTC, merged