Feature/remove old flags
status-im/status-react pull request #5675
Opened 2018-08-28 15:53 UTC by yenda

Removed: add-custom-mailservers-enabled?, universal-links-enabled?, offline-inbox-enabled?
Enabled on all builds and could be removed: SPAM_BUTTON_DETECTION_ENABLED
Doesn't exist as a flag but is still in build configs: USE_SYM_KEY

TODO: clean up env files from dead flags

Not sure we need QA on that one ?

2018-08-28 17:17 UTC, dmitryn approved these changes

2018-08-28 18:08 UTC, rasom approved these changes

2018-08-29 08:26 UTC, annadanchenko approved these changes

2018-08-29 08:29 UTC, mandrigin requested changes
Should we remove these flags from .env files as well? Otherwise, it’ll be confusing.

2018-08-29 14:02 UTC, yenda commented
@mandrigin I removed them as well it was in the todo just wanted to make sure everybody agrees with the removed flags.

2018-08-29 14:28 UTC, mandrigin approved these changes
:+1:

2018-08-29 14:30 UTC, merged