WIP: HTTP debug bridge
status-im/status-react pull request #5680
Opened 2018-08-28 19:42 UTC by alwx

Work in progress

(re-)Introduces the debug bridge for Status. Also uses the new and updated version of `react-native-http-bridge`, the work for it was done here: https://github.com/alwx/react-native-http-bridge

2018-08-29 14:28 UTC, yenda commented
@alwx The branch needs to be rebased, also it seems the http-server is always startedm shouldn't it be a developer option only ?

2018-08-31 08:20 UTC, flexsurfer requested changes

2018-08-31 08:20 UTC, flexsurfer commented on src/status_im/debug/events.cljs
> +(ns status-im.debug.events
I'm not sure why debug? maybe something like `dev-server` ?

2018-08-31 08:20 UTC, flexsurfer commented on src/status_im/debug/events.cljs
> + :http-server/start-if-needed
`(data-store.accounts/get-by-address` looks weird in `fx` usually, we pass all data from event, you can get account from cofx and pass it here instead address

2018-08-31 08:20 UTC, flexsurfer commented on src/status_im/debug/events.cljs
> +(defmethod process-request! [:DELETE "network" nil]
why not move multimethods in model?

2018-08-31 08:20 UTC, flexsurfer commented on src/status_im/init/core.cljs
> +
extra line

2018-09-03 15:54 UTC, alwx commented
@flexsurfer the PR was updated

2018-09-04 10:32 UTC, flexsurfer approved these changes

2018-09-04 13:02 UTC, jeluard approved these changes

2018-09-05 13:02 UTC, merged