[TESTS] Create e2e tests for `privacy links` and `network switch`
status-im/status-react pull request #5767
Opened 2018-09-05 20:19 UTC by hetvart

[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

### Summary:
PR covers e2e tests described in [the issue](https://github.com/status-im/status-react/issues/5724).
Added tests:
- privacy policy is accessible (testrail id is 4769)
- can switch network (testrail id is 690)

[comment]: # (Summarise the problem and how the pull request solves it)

### Review notes:
New view added:
_about_view.py_ describing the view Profile -> About

**NOTE:** When verifying privacy policy link we ensure that Privacy Policy summary title appears on the page opened in mobile browser (see screen)

<img width="391" alt="privacy_policy_summary" src="https://user-images.githubusercontent.com/15172961/45118153-46f15d00-b160-11e8-96dd-d5cb3de33a18.png">

### Steps to test:
#### 1. Privacy policy is accessible

|   | Step                                                                                          | Expected result                                                                                   |
|---|-----------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------|
| 1 | Open status and check Privacy policy is visible on signup                                     | The privacy policy is visible on signup                                                           |
| 2 | Click the privacy policy link                                                                 | Tapping privacy link opens in a browser (link >> https://www.iubenda.com/privacy-policy/45710059) |
| 3 | Open status - create account - log out - other accounts. Check Privacy is visible on recovery | Privacy is visible on recovery                                                                    |
| 4 | Click the privacy policy link                                                                 | Tapping privacy link opens in a browser (link >> https://www.iubenda.com/privacy-policy/45710059) |
| 5 | Open status - tap profile -> about. Check Privacy visible on the profile tab                  | Privacy visible on the profile tab                                                                |
| 6 | Tap the privacy policy item                                                                   | Tapping privacy link opens in a browser (link >> https://www.iubenda.com/privacy-policy/45710059) |

#### 2. Can switch network

|   | Step                                                                           | Expected result                                      |
|---|--------------------------------------------------------------------------------|------------------------------------------------------|
| 1 | Go to Profile, enable dev mode and switch network to Mainnet with Upstream RPC | app warns that restart is needed                     |
| 2 | agree to restart and login                                                     | go to Profile screen and verify the selected network |

status: ready

2018-09-06 07:11 UTC, antdanchenko requested changes

2018-09-06 07:11 UTC, antdanchenko commented on test/appium/tests/base_test_case.py
> +        desired_caps['platformVersion'] = '8.0'
please remove the change, we do not expect to migrate on 8.0 version in scope of this PR

2018-09-06 07:11 UTC, antdanchenko commented on test/appium/tests/test_general_verifications.py
> +            self.errors.append(f'{no_link_open_error_msg} Sign in view!')
please add `self.verify_no_errors()` in the end of each test, if there is at least one `errors.append`
Without the method the test will always pass :)

2018-09-06 07:19 UTC, antdanchenko commented on test/appium/views/about_view.py
> +            '//android.view.ViewGroup[@content-desc="privacy-policy"]/android.view.ViewGroup')
please, use more general xpath for all added elements
e.g. //*[@content-desc="privacy-policy"]

2018-09-06 08:55 UTC, yevh-berdnyk commented on test/appium/tests/atomic/account_management/test_profile.py
> +        self.home_view = signin_view.create_user()
We don't need to create a class instance attribute here

2018-09-06 08:55 UTC, yevh-berdnyk commented on test/appium/views/profile_view.py
> +            '//android.view.ViewGroup[@content-desc="about-button"]/android.view.ViewGroup')
It's better to use accessibility ids where it's possible, here it's 'about-button'

2018-09-09 07:48 UTC, hetvart commented
@antdanchenko @yevh-berdnyk 
went through PR and made changes according to your comments.
Please review.

2018-09-10 14:30 UTC, yevh-berdnyk approved these changes

2018-09-12 09:12 UTC, antdanchenko approved these changes

2018-09-14 10:28 UTC, antdanchenko commented
@hetvart please rebase the PR on `status-im/develop` in order to fix the issue with `This commit cannot be built`

2018-09-18 17:38 UTC, siphiuel commented
@hetvart Can you please GPG-sign your commits as well?

2018-10-02 13:20 UTC, merged