Introduced upgraded status js api according latest web3 opt-in api
status-im/status-react pull request #6058
Opened 2018-09-28 13:47 UTC by flexsurfer

According to the latest web3 opt-in EIP we inject read-only ethereum provider, we can expand this provider with status api, so there is no need in messages anymore

Before
```JavaScript
window.addEventListener('statusapi', function (event) {
    console.log(event.detail.permissions) //=> ["CONTACT_CODE"] if allowed 
    console.log(event.detail.data["CONTACT_CODE"]) //=> "0x0012300..123" if allowed
});
// request status API
window.postMessage({ type: 'STATUS_API_REQUEST', permissions: ["CONTACT_CODE"] }, '*');
```

After
```JavaScript
ethereum.status.getContactCode().then(data => {console.log('Contact code:', data)});
```

2018-09-28 13:52 UTC, yenda requested changes
the animation can show with a delay. we should never have to use dispatch and dispatch later in effects

https://github.com/status-im/status-react/pull/5824/files#diff-eeb5b0806bc1baaec4e6d3739c4a3681R17

2018-09-28 14:08 UTC, yenda commented on resources/js/web3_init.js
> +        } else if (data.type === "web3-send-async-callback") {
why can't everything be handled as an api response ?

2018-09-28 14:12 UTC, flexsurfer commented
@yenda what is wrong with dispatching event?

2018-10-01 08:57 UTC, flexsurfer commented
@yenda moved `dispatch` to UI

2018-10-01 15:48 UTC, yenda approved these changes

2018-10-01 16:22 UTC, jeluard approved these changes

2018-10-02 09:51 UTC, flexsurfer commented on src/status_im/ui/screens/browser/permissions/views.cljs
> +#_{:component-will-update (fn [this [_ _ {:keys [requested-permission]}]]
@yenda do we need this?

2018-10-02 09:56 UTC, goranjovic approved these changes

2018-10-02 10:32 UTC, goranjovic commented
@flexsurfer are there intentionally two commits?

2018-10-02 10:36 UTC, flexsurfer commented
@goranjovic yes, one from Eric

2018-10-02 16:28 UTC, Serhy commented
Looks good to me!

2018-10-02 20:13 UTC, merged