[#5979]: Add ENS names to profile screen
status-im/status-react pull request #6071
Opened 2018-10-01 08:30 UTC by alwx

Fixes #5979

2018-10-01 08:34 UTC, goranjovic approved these changes

2018-10-01 08:35 UTC, jeluard approved these changes

2018-10-01 09:03 UTC, janherich approved these changes

2018-10-01 09:25 UTC, yenda requested changes

2018-10-01 09:25 UTC, yenda commented on src/status_im/ui/screens/profile/events.cljs
> + :profile/open-ens-names-in-browser
please use a name that reflects what happened in the UI not what is going to happen

2018-10-01 09:25 UTC, yenda commented on src/status_im/ui/screens/profile/events.cljs
> +(handlers/register-handler-fx
please move this to status-im.events

2018-10-01 10:08 UTC, alwx commented on src/status_im/ui/screens/profile/events.cljs
> +(handlers/register-handler-fx
why? what's the point?

2018-10-01 10:55 UTC, yenda commented on src/status_im/events.cljs
> + :profile/open-ens-names-in-browser
:profile.ui/ens-names-button-pressed

2018-10-01 11:30 UTC, yenda approved these changes

2018-10-01 12:11 UTC, asemiankevich commented
I am curious if we want to introduce new screen leading to dead url (statusnames.eth seems to be down) . So question is: do we want to merge it as is or wait for the url up and runnung? 

cc @rachelhamlin @bgits

2018-10-01 13:22 UTC, asemiankevich commented
i talked to @jeluard and the decision was made to wait for merge until the URL is up and running

2018-10-01 13:24 UTC, rachelhamlin commented
I like that decision!

2018-10-01 15:18 UTC, alwx commented
Ok. Yes, let's just wait.

2018-10-02 13:47 UTC, vkjr approved these changes

2018-10-09 15:14 UTC, jeluard commented
@alwx Please update the ENS name to `names.statusnet.eth`  (and rebase :))

2018-10-11 06:53 UTC, merged