[TESTS] Adapt normal txs tests to work with both Ropsten and Rinkeby test networks
status-im/status-react pull request #6363
Opened 2018-10-17 13:38 UTC by hetvart

## Summary:
Due to a recent issue with Constantinople Ropsten hard fork update some normal txs tests were failing.
This PR proposes a fix which enables integration with Rinkeby in case of Ropsten unavailability.

### Review notes:
- made network api object to work with Rinkeby
- implemented rinkeby faucet depending under which network you run tests (i.e. --network flag)
- fixture for defining under which network you run directly in test

Default network is still unchanged. 
If we face the issue in future the only thing we will need to do is to change the network to Rinkeby and those 3 tests will run against Rinkeby. 

As for now on, it tested and works on both Ropsten and Rinkeby.

2018-10-17 19:34 UTC, yevh-berdnyk approved these changes

2018-10-18 13:31 UTC, antdanchenko requested changes
Please, redesign the PR in the way when `request.config.getoption('network')` defines which network should be set in tests so tests marked with `switch_network` will run on the chosen network

2018-10-19 13:14 UTC, antdanchenko commented
@hetvart great, thanks for the PR, but let's merge the PR after the release

2018-11-19 14:04 UTC, antdanchenko approved these changes

2018-12-10 14:16 UTC, closed without merging