[#5179] show fiat value in transaction details
status-im/status-react pull request #6371
Opened 2018-10-17 21:40 UTC by peskymerryherald

Fixes #5179

### Summary:

This patch uses the user current currency to show the value of a transaction in that currency. Transaction cost/fee is also shown in this format.

![ss](https://user-images.githubusercontent.com/44213672/47117397-841f3380-d264-11e8-9352-b4a503277fc9.jpg)

### Review notes:

I decided to show these amounts by appending the symbol name. I did not find any way to render currency based on locale. If there is a method to render currency based on the locale that supports crypto too, then I should use that method. If not, this implementation is good enough for now, IMHO.

#### Platforms
- Android
- iOS

#### Areas that maybe impacted
**Functional**
- 1-1 chats
- wallet / transactions

### Steps to test:
- Open Status
- Send or receive a transaction
- Open Transaction Details from Wallet

status: ready

2018-10-18 00:49 UTC, yenda requested changes
Thank you for your contribution, looks good but please move the logic out of the view into subscriptions. I know there is some bits of logic sometimes in our view but this is bad examples and will be refactored in the future.

2018-10-18 00:49 UTC, yenda commented on src/status_im/ui/screens/wallet/transactions/views.cljs
> +      (pretty-print-fiat transaction currency prices)]
the logic should be moved in the `:wallet.transactions/transaction-details` subscription

2018-10-18 08:30 UTC, peskymerryherald commented
@yenda Makes sense. Sorry I'm a total newbie with *re-frame* 😅. I think that now is more clear. Let me know.

2018-10-18 09:10 UTC, yenda approved these changes

2018-10-18 11:56 UTC, peskymerryherald commented
☝️ Fixed conflicts with 24068fe

2018-10-18 23:22 UTC, janherich approved these changes

2018-10-19 04:58 UTC, rasom approved these changes

2018-10-19 08:22 UTC, goranjovic approved these changes

2018-10-25 12:57 UTC, asemiankevich commented
@peskymerryherald sorry for delay - could you please rebase your branch?

2018-10-25 22:18 UTC, peskymerryherald commented
@asemiankevich np, done 👍

2018-10-27 08:53 UTC, asemiankevich commented
@peskymerryherald i noticed an error when i open transaction from transaction history

![image](https://user-images.githubusercontent.com/28752642/47601834-b0624f00-d9de-11e8-9265-351741d18ce1.png)

STEPS:
- open status
- switch to ropsten
- open test dapp and claim test eth
- wait for a while for funds to arrive
- go to transaction history and open transaction to see its details

This is not happening in develop so I assume it is in this branch, would you mind to take a look?

2018-11-13 13:23 UTC, lukaszfryc commented
@peskymerryherald any update on this PR?

2018-12-04 13:37 UTC, closed without merging