Added Kickback
status-im/status-react pull request #6397
Opened 2018-10-18 16:52 UTC by jeluard

fixes #6374

### Summary:

Added Kickback

status: wip

2018-10-18 23:12 UTC, yenda requested changes
you didn't add the image

2018-10-19 07:40 UTC, jeluard commented
@yenda Please re review

2018-10-19 07:42 UTC, alwx approved these changes

2018-10-19 07:43 UTC, flexsurfer approved these changes

2018-10-19 08:07 UTC, yenda approved these changes

2018-10-19 09:04 UTC, asemiankevich commented
looks good.

1. Kickback is added in social networks section
2. I can sign txn to this dapp
3. I can proceed to send a txn to the dapp

2018-10-19 09:07 UTC, merged