[desktop] Add search feature for chat list
status-im/status-react pull request #6401
Opened 2018-10-19 01:56 UTC by yenda

### Summary:

Add search feature for chat list

#### Platforms (optional)
- macOS
- Linux

### Steps to test:
- Open an account that has a lot of chats
- On top of chat list type something in the search field
- Only chats that match the search should be displayed

status: ready

2018-10-19 07:31 UTC, janherich requested changes

2018-10-19 07:31 UTC, janherich commented on src/status_im/ui/screens/desktop/main/tabs/home/views.cljs
> +      #_[react/view {:style {:flex 1}}]
Please remove commented out/debug code

2018-10-19 07:31 UTC, janherich commented on src/status_im/ui/screens/desktop/main/tabs/home/views.cljs
> +                  search-filter-ref   (atom nil)
Why do we keep reference to the search filter react component ? I see it's passed to the `search-input` but it's not used there at all, if that's the case and I didn't miss something, please remove it.

2018-10-19 11:34 UTC, janherich approved these changes

2018-10-19 13:53 UTC, chadyj commented
@yenda Can you please add some screenshots for @EugeOrtiz @denis-sharypin @errorists?

Also, designers, how about ideas for this feature on mobile?

2018-10-19 14:55 UTC, dmitryn approved these changes

2018-10-19 14:55 UTC, dmitryn commented on src/status_im/ui/screens/desktop/main/tabs/home/views.cljs
> +                                      :margin 2
align map values

2018-10-19 14:55 UTC, dmitryn commented on src/status_im/ui/screens/desktop/main/tabs/home/views.cljs
> +                                      :align-content :center}
do we have agreement to move stylings to styles.cljs or not? just checking our styleguide

2018-10-20 08:25 UTC, chadyj commented
Designers + @yenda, we can probably merge this and do a separate issue for design tweaks and mobile. We also need to consider message search and whether this is per-chat, or global.  WDYT?

2018-10-22 10:05 UTC, vitvly approved these changes

2018-10-22 10:06 UTC, vitvly approved these changes

2018-10-23 13:34 UTC, churik commented
Tested on Mac OSx and Linux. Searched for 1-1 for users with default and custom usernames, public and group chats.
Mobile builds are not affected (tested on IOS).
Waiting for e2e tests to send it to `Merge` if no regression found.

2018-10-23 15:28 UTC, merged