Support of java 8+ versions
status-im/status-react pull request #6470
Opened 2018-10-22 23:57 UTC by MaxRis

Running `lein` build commands with openjdk `10.0.2` installed failures with output similar to:
```
Exception in thread "main" java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter, compiling:(org/httpkit/server.clj:1:1)
...
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter
``` 

Upgrading to http-kit/http-kit  of version "2.3.0" resolves above issue

2018-10-23 05:37 UTC, rasom approved these changes

2018-10-23 05:48 UTC, jeluard requested changes
Do we need this dependency at all? It's probably coming from transitive dependency.
Also project.clj should always be updated alongside deps.edn.

2018-10-23 09:32 UTC, jeluard commented
@MaxRis Where is this dep coming from? Do we use it? My guess is that it should be removed

2018-10-23 11:15 UTC, MaxRis commented
@jeluard seems like `figwheel-sidecar-0.5.16` has dependency on it:

```
<dependency>
      <groupId>http-kit</groupId>
      <artifactId>http-kit</artifactId>
      <version>2.2.0</version>
    </dependency>
```
I guess, need to check for the newer version of `figwheel-sidecar`

2018-10-25 19:57 UTC, MaxRis commented
@jeluard updating of figwheel-sidecar to 0.5.17 helped to resolve the issue, thanks

2018-11-01 08:22 UTC, maxhora commented
@jeluard could you please take a look again, thanks

2018-11-27 10:39 UTC, closed without merging