Feature/update links
status-im/status-react pull request #6742
Opened 2018-11-15 14:37 UTC by andytudhope

Fixes #6740

### Summary:

The link to the FAQs in the app is broken. I did a find + replace for all the links I could get, but still haven't been able to find the guilty culprit. Maybe someone better at Clojure could help a brother out. 

#### Platforms (optional)
- Android
- iOS
- macOS
- Linux
- Windows

#### Areas that maybe impacted (optional)
**Functional**
- account recovery
- new account
- user profile updates
- networks
- mailservers
- fleet
- bootnodes

### Steps to test:
- Open Status
- Check that the link under Profile > Need Help? > Frequently Asked Questions points to the right place, which is here: https://status.im/docs/FAQs.html

status: WIP

2018-11-15 14:39 UTC, chadyj approved these changes
Thanks for the quick update!

2018-11-15 14:47 UTC, lukaszfryc commented
@andytudhope does it all work or you still need some clojure help?

2018-11-15 14:49 UTC, andytudhope commented
Long story short: I had a nightmare trying to sync my fork to latest develop, got into merge conflict hell, and ended up deleting it all and starting fresh, so I am not running this locally right now and don't have 30mins to build it all - was hoping someone else could test if they're already set up... Sorry!

2018-11-15 14:51 UTC, lukaszfryc commented
Ok, so let's wait for jenkins to check it. After that we will merge

2018-11-15 14:51 UTC, lukaszfryc approved these changes

2018-11-15 15:26 UTC, lukaszfryc requested changes

2018-11-15 15:26 UTC, lukaszfryc commented on src/status_im/ui/screens/help_center/views.cljs
> +                                        :action-fn           #(.openURL react/linking "https://status.im/FAQs.html")}]
@andytudhope should be `https://status.im/docs/FAQs.html`

2018-11-15 18:05 UTC, flexsurfer approved these changes

2018-11-16 08:30 UTC, lukaszfryc approved these changes

2018-11-16 08:30 UTC, lukaszfryc commented
@andytudhope works fine. Please merge :)

2018-11-16 09:01 UTC, cammellos commented
@andytudhope could you squash the commits please?

2018-11-16 09:18 UTC, merged