[#6786] restyle main wallet screen
status-im/status-react pull request #6797
Opened 2018-11-20 11:50 UTC by bhauman

fixes #6786  Wallet main screen re-style for new wallet flow

### Summary:

This re-styles the wallet main screen according to for `main-01` in the following figma https://www.figma.com/file/SIeZPHvrX7KUwEBW8VQct8C5/WIP_New-send-transaction.

### Testing notes:

Check that the screens match the figma and that they function as intended.

### Steps to test:
- Open Status
- Navigate to wallet
- compare the screen to `main-01` on the figma linked above

Thanks!

status: ready

2018-11-20 11:52 UTC, bhauman commented
Android screen shot:
![android_screen](https://user-images.githubusercontent.com/2624/48771905-b91e0c00-ec90-11e8-9e07-9e0251d1bce1.gif)

IOS Screen Shot:
![simulator screen shot - iphone 7 - 2018-11-19 at 21 57 09](https://user-images.githubusercontent.com/2624/48771933-cf2bcc80-ec90-11e8-9a11-f556410390ca.png)

2018-11-20 13:56 UTC, chadyj commented
ping @denis-sharypin!

2018-11-20 16:30 UTC, goranjovic approved these changes

2018-11-22 07:36 UTC, asemiankevich commented
@flexsurfer @yenda please add your reviews asap

2018-11-22 07:40 UTC, asemiankevich commented
@errorists sorry for so many pings, i am forced to ask you while Denis is out. Would you mind to check this real quick too? Thanks!

2018-11-22 07:51 UTC, asemiankevich commented
@antdanchenko @yevh-berdnyk @hetvart:
- `Receive transaction` is replaced with `Deposit`
- `Send transaction` is replaced with `Send`

please update tests.

2018-11-22 08:14 UTC, hetvart commented
> @antdanchenko @yevh-berdnyk @hetvart:
> 
> * `Receive transaction` is replaced with `Deposit`
> * `Send transaction` is replaced with `Send`
> 
> please update tests.

I've just downloaded the e2e `*.apk` and tried to run tests with the buttons from `develop` branch and it works as expected. We used `accessibility_id` for these locators so no need to change them. (https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-181121-165435-955356-e2e.apk)

Thanks to update us!

2018-11-22 08:32 UTC, yenda requested changes

2018-11-22 08:32 UTC, yenda commented on src/status_im/ui/screens/wallet/main/styles.cljs
> +   :color         "#939ba1"
colors/gray

2018-11-22 08:36 UTC, asemiankevich commented
screens look good

![image](https://user-images.githubusercontent.com/28752642/48889942-7c951080-ee48-11e8-81a1-fb8f325ad61a.png)

![image](https://user-images.githubusercontent.com/28752642/48889948-8159c480-ee48-11e8-9e2a-7a10b2cb899c.png)

2018-11-22 14:35 UTC, yenda approved these changes

2018-11-22 14:41 UTC, bhauman commented
@asemiankevich is this all set to go?

2018-11-22 14:42 UTC, asemiankevich commented
yess)

2018-11-22 17:27 UTC, merged

2019-02-13 05:54 UTC, oskarth commented
@goranjovic why did we rename 'Receive' to 'Deposit'?