[WIP] [TESTS] Block PR
status-im/status-react pull request #6869
Opened 2018-11-24 16:19 UTC by yevh-berdnyk

status: wip

2018-11-26 10:44 UTC, hetvart approved these changes

2018-11-26 11:02 UTC, Serhy approved these changes

2018-12-18 15:00 UTC, antdanchenko requested changes
we should use https://developer.github.com/v3/checks/runs/ instead of changing status of a commit

2018-12-19 13:22 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 95594f75 | [#2](https://ci.status.im/job/status-react/job/prs/job/android/job/PR-6869/2/) | 1:22:05 PM | ~14 min | `android` | [:package: package](https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-181219-130742-95594f-pr.apk) |

2018-12-24 12:24 UTC, antdanchenko approved these changes

2018-12-24 14:02 UTC, closed without merging