bug #5975 - navigating back to chat after /send command with onboarding
status-im/status-react pull request #6878
Opened 2018-11-26 12:22 UTC by goranjovic

fixes #5975

### Summary:

Navigates back to chat after /send command is done, even when the flow is intercepted by wallet onboarding. This bug fix also unblocks e2e tests.

### Testing notes (optional):

The previous attempt to quickfix this (PR #6113) introduced a regression (#6283). Please check for both problems in this PR.

### Steps to test:
see #5975 and #6283

status: ready

2018-11-26 12:22 UTC, ghost commented
<!--prchecklist--> 
### Pull Request Checklist
- [x] Have you updated the documentation, if impacted (e.g. [docs.status.im](https://docs.status.im/docs/build_status.html))?

2018-11-26 13:46 UTC, bhauman approved these changes

2018-11-27 08:42 UTC, rasom commented on src/status_im/ui/screens/wallet/send/events.cljs
> +(fx/defn navigate-after-transaction [{:keys [db] :as cofx} send-command? chat-id]
`send-command?` is not used here

2018-11-27 08:44 UTC, rasom commented on src/status_im/ui/screens/wallet/send/events.cljs
> + (fn [cofx [_ send-command? chat-id]]
what is the point of adding this parameter if it is not used in `navigate-after-transaction`?

2018-11-27 08:45 UTC, rasom requested changes
see comments above

2018-11-27 13:42 UTC, goranjovic commented
Pushed a wrong commit, just a moment.

2018-12-06 19:23 UTC, asemiankevich commented
@goranjovic any news about this one?

2018-12-07 08:16 UTC, goranjovic commented
will be changed completely in redesigned screens, no point fixing it now

2018-12-07 08:16 UTC, closed without merging