[#7262] Remove shortcut creation when following universal links insid…
status-im/status-react pull request #7572
Opened 2019-02-25 10:35 UTC by flexsurfer

fixes #7262

2019-02-25 10:50 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | d83f0683 | [#1](https://ci.status.im/job/status-react/job/prs/job/ios-e2e/job/PR-7572/1/) | 2019-02-25 10:50:22 | ~14 min | `ios-e2e` | [:package: pkg](https://status-im.ams3.digitaloceanspaces.com/StatusIm-190225-103545-d83f06-e2e.app.zip) |

2019-02-26 10:02 UTC, yenda requested changes

2019-02-26 10:02 UTC, yenda commented on src/status_im/browser/core.cljs
> +        (fx/merge cofx {})
seems like this does nothing? so you could replace the `if` by a `when-not` and remove that line

2019-02-26 11:59 UTC, goranjovic requested changes

2019-02-26 11:59 UTC, goranjovic commented on src/status_im/utils/universal_links/core.cljs
> +   (re-matches #"(^status-im://)[\x00-\x7F]+$" url)))
let's put those regex literals into constants.
also, can we have some unit tests for regexes?

2019-02-26 13:51 UTC, dmitryn approved these changes
lgtm, except points already mentioned by other reviewers

2019-02-26 15:26 UTC, flexsurfer commented
@yenda @goranjovic thanks, made changes!

2019-02-27 08:56 UTC, yenda approved these changes

2019-02-27 09:42 UTC, goranjovic approved these changes

2019-02-27 09:42 UTC, goranjovic commented
@flexsurfer did you push the changes? I still see the same thing

2019-02-27 16:01 UTC, flexsurfer commented
@goranjovic yes, i did, don't know what can be the reason, i can see changes

2019-03-01 13:47 UTC, churik commented
Checked on IOS and Android: no shortcuts are created when following universal links on public and 1-1 chats in Status.
As a regression checked Mac OS build, and following universal links from browsers on IOS and Android.
Waiting for e2e results.

2019-03-01 16:01 UTC, merged