TtT chat flow
status-im/status-react pull request #7616
Opened 2019-02-28 09:42 UTC by siphiuel

2019-02-28 09:43 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | 28e64200 | [#1](https://ci.status.im/job/status-react/job/prs/job/linux/job/PR-7616/1/) | 2019-02-28 09:43:25 | ~18 sec | `linux` | [:page_facing_up: log](https://ci.status.im/job/status-react/job/prs/job/linux/job/PR-7616/1/consoleText) |

2019-02-28 09:43 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | 28e64200 | [#1](https://ci.status.im/job/status-react/job/prs/job/linux/job/PR-7616/1/) | 2019-02-28 09:43:25 | ~18 sec | `linux` | [:page_facing_up: log](https://ci.status.im/job/status-react/job/prs/job/linux/job/PR-7616/1/consoleText) |
| :x: | 28e64200 | [#1](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-7616/1/) | 2019-02-28 09:43:25 | ~23 sec | `android-e2e` | [:page_facing_up: log](https://ci.status.im/job/status-react/job/prs/job/android-e2e/job/PR-7616/1/consoleText) |

2019-04-17 07:33 UTC, oskarth commented
@siphiuel might be a good idea to ask for reviewers a la https://github.com/status-im/status-react/blob/develop/doc/decisions/0011-tweak-pr-process.md

2019-04-17 07:38 UTC, oskarth requested changes
Didn't review the code, just the ARD. It'd be a good idea to put the code changes under a flag so this PR can be merged sooner rather than later, right now it's been open for a long time.

2019-04-17 07:38 UTC, oskarth commented on doc/decisions/0012-tribute-to-talk.md
> +Origin TtT design did not take into account future migration problems. E.g., how would users with a TtT v1 compliant client communicated with users having a TtT v2 setting?
> account future migration problems.

If I'm understanding it correctly, is this suggesting contracts can't be upgradable? That seems off to me

Asked @richard-ramos as review, apologize in advance if it's wrong person (forgot who wrote TTT contract)

2019-04-17 07:38 UTC, oskarth commented on doc/decisions/0012-tribute-to-talk.md
> +Instead of storing tribute information on-chain, opt for storing all TtT-related data on IPFS, and store content hashes on-chain instead. This will allow for simpler versioning in the future.
If we are using IPFS (similar to some other parts of UI), why is there talk about Swarm feeds (really cool, but not quite production-ready/dependable yet)

2019-04-17 07:38 UTC, oskarth commented on doc/decisions/0012-tribute-to-talk.md
> +# 0012. Tribute-to-Talk
Kudos for writing ARD with PR

2019-04-17 07:38 UTC, oskarth commented on doc/decisions/0012-tribute-to-talk.md
> +proposed
How will this be accepted? Is the plan to bring it up in a core dev call?

2019-04-17 08:12 UTC, yenda commented
@oskarth it's a draft not a PR, we frequently merge small PRs from it in develop, this is what we use to build and test the big picture

2019-04-17 09:01 UTC, oskarth commented
Alright fair enough, the questions in ARD are still relevant though. When is that planned to be merged and communicated?

2019-04-17 09:34 UTC, yenda commented
@oskarth good idea to talk about it during dev call. Regarding progress I'm almost done replacing the contract and ipfs by swarm, so I have hstrong hopes the whole thing will be done development wise by Friday.

2019-04-17 10:05 UTC, oskarth commented
To be clear, the concern here is more on (seemingly?) relying on a piece of technology that is is still immature. What happens if it stops working? Returns stale reads?

2019-04-17 10:13 UTC, yenda commented
@oskarth for different failures:
- data loss: the feed will be checked every time the user logs in and re-uploaded if it is missing
- stale read: as long as we are using a gateway I don't think this can happen?
- gateway down: same as ipfs, spam filter is down while gateway is down

2019-04-23 12:26 UTC, yenda commented on src/status_im/ui/screens/chat/views.cljs
>          ;; TODO Fiat value still hardcoded
remove todo

2019-04-24 06:22 UTC, oskarth commented
@yenda @siphiuel Could you explain a bit more on what the purpose of this branch (draft) is? How long is it expected to be kept open? We want to finish up TTT and move to other prios as soon as possible.

2019-04-24 11:19 UTC, yenda commented
@oskarth the purpose of this branch is to allow us to test all the code related to tribute to talk. It will probably be closed by the end of the week once the last PR for ttt will be submitted for review. Here is what this branch currently contain that will be in separately reviewed and tested PRs:
- tribute to talk settings #8022 
- fix token transactions #8024 
- fix on-error dispatch in transactions #8021 
- move block contact to separate namespace to avoid circular dependencies (to be created)
- move ttt document to separate PR to allow more focus debate (to be created)
What will be left of this PR after all of the above are merged in develop is going to be the final ttt-chat-flow PR.

2019-04-29 15:05 UTC, yenda commented
Update:

I created 4 ttt related issues to fix before release https://github.com/status-im/status-react/issues?q=is%3Aissue+is%3Aopen+label%3Atribute-to-talk

@siphiuel has fixed 2 of them already, the one left are related to how we handle the ugprade to a new version of tribute to talk. The contarct features a way to stop it and we need to ship from the beginning a version of ttt that is aware of that and is deactivated when the contract is stopped with the appropriate UX. We will polish this UX and related issue and submit them as bounties

2019-05-01 20:26 UTC, yenda commented
;; account x, valid manifest
satoshi document engage inflict goddess auction rule unfair bid next buddy shy
0x0446e3ea8d84a3783acaefc75502d60f3d5657718c071a72f2cbee7999b1fb8efa2edc41f9d7521a4deb7dc38e7f1bd16d65f55eba450b5ced2c075381324af309

;; account y, valid manifest
plastic prevent toddler soon tuna old door gown slab blood agree pigeon
0x0434b6a979e7e1c7d826bb89f4941b67e7b95f094bb83d8789874dfe52cb00fa866de9bb77d07faab97dd4f1945c608aef6938b7b4d1fdd9af5dd43135f0077a7c

Create new account A
Open new chat with account B on mainnet

![Screenshot_1556737719](https://user-images.githubusercontent.com/1181225/57040545-064ed280-6c60-11e9-9adb-02b7140df11f.png)

Switch to Ropsten
Open chat with account B

![Screenshot_1556737932](https://user-images.githubusercontent.com/1181225/57040552-0c44b380-6c60-11e9-96c7-7106684ff9f5.png)

Click on pay to chat -> insufficient funds

![Screenshot_1556737992](https://user-images.githubusercontent.com/1181225/57040557-123a9480-6c60-11e9-9a64-90446bc2f803.png)

Get some eth and snt
Pay the tribute to B

![Screenshot_1556741771](https://user-images.githubusercontent.com/1181225/57040573-2088b080-6c60-11e9-8875-4950bc711746.png)
![Screenshot_1556741820](https://user-images.githubusercontent.com/1181225/57040580-28485500-6c60-11e9-940d-67c0c93816c4.png)

2019-05-01 20:28 UTC, yenda commented
@churik @errorists see comment above for testing done for tribute payment flow on android

@siphiuel will open a new PR that will fix 2 open bugs, squash all current commits and include testing of tribute payment reception on iphone

2019-05-02 12:59 UTC, errorists commented
first of all, thanks for all the work guys! 👏 

_random comment:_ bolded text on Android is not using Inter UI, have no clue what happened, should I open an issue? 😢 

_and another random comment:_ can we do something about the blurriness of user identicons? can't we request a larger version?

now TtT, I'll test it tomorrow and update this post as I go on but looking at the screenshots:

- [ ] Are you friends? message bubble has wrong left margin, should be the same as regular message

- [ ] Pay to Chat message has a chin, meaning the bottom padding is too large or more likely the text button too much of a height. Let's try to have a 12px distance between the text object and bottom.

- [ ] I've noticed the personalised message and the pay to chat bubble share the same width. It would be nicer if the width of each bubble was calculated individually.

2019-05-03 16:24 UTC, yenda approved these changes

2019-05-05 17:39 UTC, closed without merging

2019-05-05 17:44 UTC, siphiuel commented
@errorists Thanks for having a look! Fixed the 3 issues you've mentioned. Wrong font/blurriness are still open though. Updated PR is here: https://github.com/status-im/status-react/pull/8129