New extension event to send message from event (currently disabled)
status-im/status-react pull request #7694
Opened 2019-03-06 20:11 UTC by krisc

@jeluard @StatusSceptre this PR is for the bounty #7354 . The original PR on my submission for the bounty wasn't building and sending a new PR made it simpler for me. Sorry for the clutter :P

2019-03-06 20:17 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | 3b0593e5 | [#1](https://ci.status.im/job/status-react/job/prs/job/macos/job/PR-7694/1/) | 2019-03-06 20:17:25 | ~5 min | `macos` | [:page_facing_up: log](https://ci.status.im/job/status-react/job/prs/job/macos/job/PR-7694/1/consoleText) |

2019-03-07 07:37 UTC, jeluard requested changes

2019-03-07 07:37 UTC, jeluard commented on env/dev/env/config.cljs
>  (def figwheel-urls {:android "ws://localhost:3449/figwheel-ws",
Please remove this from the PR

2019-03-08 11:44 UTC, flexsurfer approved these changes

2019-03-11 08:35 UTC, jeluard approved these changes

2019-03-11 08:46 UTC, asemiankevich commented
@krisc could you please provide an extension sample for this ?

2019-03-11 08:49 UTC, jeluard commented
@krisc You will have to rebase too

2019-03-11 19:11 UTC, krisc commented
> @krisc could you please provide an extension sample for this ?

@asemiankevich please see this comment https://github.com/status-im/status-react/pull/7560#issuecomment-468015731

2019-03-11 22:14 UTC, yenda requested changes
For code that can be optionally enabled, we use environment variable. You can create one in `status-im.utils.config` and surround your code in a `when` close using the variable you create

2019-03-12 06:53 UTC, asemiankevich commented
> > @krisc could you please provide an extension sample for this ?
> 
> @asemiankevich please see this comment [#7560 (comment)](https://github.com/status-im/status-react/pull/7560#issuecomment-468015731)

When trying to install this errors are shown and extension could not be installed:
![image](https://user-images.githubusercontent.com/28752642/54180426-a7b17780-44ac-11e9-8013-8067456c1e16.png)

@jeluard @flexsurfer any hint?

2019-03-12 06:57 UTC, jeluard commented
@asemiankevich Yes this is expected, there is nothing to be tested here.
Actually it might make sense to not merge this PR, but still give the bounty. @StatusSceptre WDYT?

2019-03-12 06:59 UTC, asemiankevich commented
> @asemiankevich Yes this is expected, there is nothing to be tested here.
> Actually it might make sense to not merge this PR, but still give the bounty. @StatusSceptre WDYT?

could you please add then this disappointing `skip-manual-qa` label just in case?

2019-03-12 19:39 UTC, krisc commented
> @asemiankevich Yes this is expected, there is nothing to be tested here.
> Actually it might make sense to not merge this PR, but still give the bounty. @StatusSceptre WDYT?

@jeluard  You still think it's not worth merging with the optional enabling as @yenda suggested? In any case, I'll wait on what @StatusSceptre thinks before continuing on.

2019-03-14 22:40 UTC, krisc commented
@StatusSceptre care to comment on this?

2019-03-15 06:23 UTC, StatusSceptre commented
@jeluard @yenda are we decided that we do not merge this, but still payout the bounty? Am going to go ahead and do that as it is just for 80 DAI.

2019-03-15 07:19 UTC, jeluard commented
@StatusSceptre Exactly!

2019-03-18 07:40 UTC, closed without merging