Added dBay in one commit
status-im/status-react pull request #7706
Opened 2019-03-09 17:45 UTC by LuisEGV

Added image, changed resource.cljs and default_dapps.cljs

[comment]: # (Please replace ... with your information. Remove < and >)
[comment]: # (To auto-close issue on merge, please insert the related issue number after # i.e fixes #566)

If you submit PR for issue with bounty then write here Fixes #NN where NN is issue number

*otherwise*

fixes #...

### Summary:

[comment]: # (Summarise the problem and how the pull request solves it)
...

### Review notes (optional):

### Testing notes (optional):

#### Platforms (optional)
- Android
- iOS
- macOS
- Linux
- Windows

#### Areas that maybe impacted (optional)
**Functional**
- 1-1 chats
- public chats
- group chats
- wallet / transactions
- dapps / app browsing
- account recovery
- new account
- user profile updates
- networks
- mailservers
- fleet
- bootnodes

**Non-functional**
- battery performance
- CPU performance / speed of the app
- network consumption

### Steps to test:
- Open Status
- ...
- Step 3, etc.

status: ready

2019-03-09 17:47 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | a763df37 | [#1](https://ci.status.im/job/status-react/job/prs/job/macos/job/PR-7706/1/) | 2019-03-09 17:47:13 | ~1 min | `macos` | [:page_facing_up: log](https://ci.status.im/job/status-react/job/prs/job/macos/job/PR-7706/1/consoleText) |

2019-03-11 08:32 UTC, jeluard requested changes

2019-03-11 08:32 UTC, jeluard commented on src/status_im/ui/screens/browser/default_dapps.cljs
> +             :dapp-url    "https://www.dbay.ai/"
Please align key and values or the build fails.

2019-03-18 07:36 UTC, jeluard commented
@LuisEGV Could you update the map alignment?

2019-04-22 15:17 UTC, flexsurfer commented
@rachelhamlin should we close this? cc @andytudhope

2019-04-23 08:48 UTC, andytudhope commented
Added in this commit https://github.com/status-im/discover-dapps/commit/c8ed9d99114dd7f533f3d72247c829f112bbaeba

2019-04-23 08:48 UTC, closed without merging