[feature] implement erc20 get-transaction for SNT and STT
status-im/status-react pull request #7901
Opened 2019-04-03 22:49 UTC by yenda

- change `ethereum/get-transaction` to use call-private-rpc instead
of web3 object
- implement a version for erc20 tokens SNT and STT that provides enriches
result of get-transaction with `:recipient` and `:snt-amount`

@flexsurfer why was the decode function converting big int to number? Isn't there a risk of loosing precision?

2019-04-03 22:54 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | 76c19733 | [#1](https://ci.status.im/job/status-react/job/prs/job/macos/job/PR-7901/1/) | 2019-04-03 22:54:26 | ~4 min | `macos` | [:page_facing_up: log](https://ci.status.im/job/status-react/job/prs/job/macos/job/PR-7901/1/consoleText) |

2019-04-04 07:27 UTC, flexsurfer commented on src/status_im/utils/ethereum/abi_spec.cljs
> +    (dependencies/Web3.prototype.toBigNumber (str "0x" x) 16)))
`.toBigNumber` has only one parameter, so 16 is just confusing and better to remove it
how does it work without `.toNumber`?

2019-04-04 07:27 UTC, flexsurfer commented on src/status_im/utils/ethereum/core.cljs
> +#_(defn get-transaction [web3 number cb]
remove?

2019-04-04 07:29 UTC, flexsurfer approved these changes

2019-04-04 07:30 UTC, flexsurfer commented on src/status_im/utils/ethereum/abi_spec.cljs
> +    (dependencies/Web3.prototype.toBigNumber (str "0x" x) 16)))
`.toBigNumber` has only one parameter, so better to remove 16 to do not confuse

2019-04-19 13:13 UTC, vitvly requested changes

2019-04-19 13:13 UTC, siphiuel commented on src/status_im/utils/ethereum/core.cljs
> +     (if (= "" response)
Can we use string/blank? instead?

2019-04-19 14:54 UTC, vitvly approved these changes

2019-04-22 10:12 UTC, oskarth commented
@yenda what's the state of this PR?

2019-04-22 10:26 UTC, yenda commented
It doesn't need to be tested just e2e tests as there is no changes to previous code

2019-04-23 07:57 UTC, churik commented
@yenda e2e cannot be built:
```
The triggering condition was at timestamp=1556005729: inotify-add-watch(/home/jenkins/workspace/us-react_prs_android-e2e_PR-7551/node_modules/unset-value/node_modules/has-value) -> The user limit on the total number of inotify watches was reached; increase the fs.inotify.max_user_watches sysctl
09:48:54  All requests will continue to fail with this message until you resolve
09:48:54  the underlying problem.  You will find more information on fixing this at
09:48:54  https://facebook.github.io/watchman/docs/troubleshooting.html#poison-inotify-add-watch. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.html.
```
Infrastructure error?

2019-04-23 12:23 UTC, merged