Update partitioned topic derivation algorithm
status-im/status-react pull request #7981
Opened 2019-04-16 08:54 UTC by rasom

2019-04-16 08:58 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :x: | fc59991b | [#1](https://ci.status.im/job/status-react/job/prs/job/macos/job/PR-7981/1/) | 2019-04-16 08:58:15 | ~3 min | `macos` | [:page_facing_up: log](https://ci.status.im/job/status-react/job/prs/job/macos/job/PR-7981/1/consoleText) |

2019-04-16 09:02 UTC, mandrigin requested changes
https://github.com/status-im/specs/pull/3 should be updated with this algorithm cc @adambabik @oskarth

2019-04-16 09:37 UTC, cammellos approved these changes

2019-04-16 09:38 UTC, oskarth commented
Indeed @mandrigin, preferably separate proposal with compatibility and clear upgrade path etc. See previous dev calls for legwork that was identified as needed before putting this in production https://github.com/status-im/pm/issues

2019-04-16 12:14 UTC, rasom commented
@mandrigin @oskarth so what's the plan then? We need to create proposal, discuss it, approve and only then implement, right? 

There is a probability that the whole algorithm (I mean not only topic derivation) will be changed (isn't it?), and on the other hand it might be accepted just as it is in this PR. We are already listening to the topic which we are not going to use, so including this commit to the next release will not make any harm even if we will change the whole thing.

I don't mind to close this PR if we need to wait till discussion will be finished.

2019-04-16 15:48 UTC, adambabik commented
Let's just create another PR to `status-protocol` branch in https://github.com/status-im/specs repo. It should be a self-contained section somewhere below `Topic` header, for example as another header `### Partitioned Topic`.

2019-04-16 16:36 UTC, adambabik commented
Oh and one concern I have is the number of topics an individual would need to subscribe to. For example, if I have `N` private contacts, I need to provide `N` topics to the Whisper filter. Has anyone verified what's the maximum `N` for Whisper?

2019-04-17 05:12 UTC, oskarth commented
What @adambabik said. Spoke with @mandrigin about this, but it should be a separate PR to specs repo with a proposal that takes into account upgradability, etc. It doesn't have to build on the current spec WIP PR, but it can refer to it.

Relevant here would also be to mention:
- bandwidth usage and how it might change with launch and users
- how this would impact trade-off of potentially not having compatibility
- what a 100% or 99.9% compatibilty would look like (multicast vs device abstraction) and what it requires
- entertain option of what keep listening to discovery topic and send less over it through some form of toggle would look like, i.e. 99.9% compatibility case (similar to device sync, but perhaps corner case re recovered account way in future)
- upgrade path, both from old to new as well as from proposal to further (say we change topic partition again in future)
- summary of options with trade-offs
- possibly options for sacrificing compatibility in short term and regaining it later, e.g. with device data sync 
- evaluation should have a big premium/bias towards keeping compatibility, for reasons mentioned in several previous core dev calls

I realize this sounds like a lot, and it'd be easier to just hack it and implement it. But we are trying to create a protocol and spec that exists on its own, and can't be changed ad hoc. This will only increase in importance going forward, especially as we get more clients. By doing this properly now we are changing the culture of what spec changes look like, and ensuring we know how to do it now rather than later. It is similar to Chaos Unicorn Day in that sense. It is cheap to learn this now, expensive to learn it later.

As a role model here I just want to point to @arnetheduck, who has a lot of experience on working on p2p protocols, including getting hundreds of millions of downloads for a compatible reverse-engineered p2p protocol 10 years ago. @cammellos rightfully points out there are some differences in terms of protocol negotiation etc, and this is the kind of consideration we want to see in the spec proposal. Similarly, @mandrigin and others have pointed out that we do have real-world constraints, such as launching an app with non-sucky BW usage, which might lead to different trade-offs. This type of thing can too be reasoned about thoughtfully in a proposal which clearly outlines different options and trade-offs with rationale.

Once that proposal is in a better shape, let's bring it up in Core Dev call.

2019-04-17 06:23 UTC, rasom commented
@adambabik @oskarth @mandrigin ok

2019-04-17 06:23 UTC, closed without merging