Remove LightClient note from PlayStore
status-im/status-react pull request #8242
Opened 2019-05-20 16:56 UTC by Serhy

Fix #7988
- removed the note with Light Client claim in section Beta features
- updated https://chat.status.im/ to https://get.status.im/chat/public/status

2019-05-20 17:12 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 4890652f | [#1](https://ci.status.im/job/status-react/job/prs/job/linux/job/PR-8242/1/) | 2019-05-20 17:12:58 | ~16 min | `linux` | [:package: App](https://status-im-prs.ams3.digitaloceanspaces.com/StatusIm-190520-165641-489065-pr.AppImage) |

2019-05-21 07:13 UTC, mandrigin approved these changes

2019-05-21 07:48 UTC, annadanchenko requested changes
轻客户端—Status实现了Go以太坊的完全运行，并启用了轻客户端和Whisper协议。needs to be removed in fastlane/metadata/android/zh-CN/full_description.txt

2019-05-21 08:09 UTC, Serhy commented
> 轻客户端—Status实现了Go以太坊的完全运行，并启用了轻客户端和Whisper协议。needs to be removed in fastlane/metadata/android/zh-CN/full_description.txt

Thanks @annadanchenko, removed it from zh-CN/full_description.txt

2019-05-21 08:30 UTC, annadanchenko approved these changes

2019-05-21 09:35 UTC, Serhy commented
Failed autotest in the https://github.com/status-im/status-react/pull/8242#issuecomment-494301233 is known https://github.com/status-im/status-react/issues/8157 (looks good after re-run)

2019-05-21 09:39 UTC, merged