Explicitly compare values
status-im/status-react pull request #9132
Opened 2019-10-07 09:29 UTC by churik

Sometimes test `test_mobile_data_usage_settings` failed because of wrong comparison of grabbed attributes.
Replaced with explicit comparison - checked 5 times locally, test is passed.

2019-10-07 09:41 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | b44c7735 | [#1](https://ci.status.im/job/status-react/job/prs/job/ios/job/PR-9132/1/) | 2019-10-07 09:41:01 | ~10 min | `ios` | [:package:`ipa`](https://i.diawi.com/ouosXr) [:calling:](https://chart.apis.google.com/chart?cht=qr&chs=400x400&chld=L%7C%0A0&chl=https%3A%2F%2Fi.diawi.com%2FouosXr)|

2019-10-07 10:33 UTC, Serhy requested changes
Test passed 5 of 5 runs because with "is True"/"is False" it will always pass :)
attribute_value method returns 'true'/'false' as str type. Thus, 
`if "false" is True` ->  `False`
`if "false" is False` ->  `False`
`if "false" == "false"` -> `True`

And that's why `if profile_view.use_mobile_data.attribute_value("checked"):` always return `True`

For our needs here lets make is_checked method inside use_mobile_data/ask_me_when_on_mobile_network elements which will return boolean value

2019-10-08 08:46 UTC, churik commented
@Serhy ready to be reviewed again

2019-10-08 09:15 UTC, Serhy approved these changes

2019-10-08 11:29 UTC, merged